### ISSUE TITLE
Type naming conflicts lead to invalid API specification

### ISSUE THREAD

**Issue by yholkamp** [ory/kratos#1043]
**Describe the bug**

The kratos repository contains multiple objects named `Type` and possibly others as well, in the generated OpenAPI schema, this leads to invalid type specifications.

The Type type is defined here:
https://github.com/ory/kratos/blob/4301ea6191076c4f1a42d70518c8d344ff81281d/.schema/api.swagger.json#L1860-L1864

And is used to both represent:
https://github.com/ory/kratos/blob/4301ea6191076c4f1a42d70518c8d344ff81281d/selfservice/flow/type.go#L8-L11
and
https://github.com/ory/kratos/blob/4301ea6191076c4f1a42d70518c8d344ff81281d/text/type.go#L5-L8

As a result, the Message object now has a type property that may only contain 'browser' or 'public':
https://github.com/ory/kratos/blob/4301ea6191076c4f1a42d70518c8d344ff81281d/.schema/api.swagger.json#L1796-L1812

**Reproducing the bug**

Open the generated schema.

**Expected behavior**

The generated schema distinguishes between models, even if their names are identical. Perhaps the text package Type can be referenced to as TextType or MessageType, allowing API clients to more strictly rely on the schema to determine the valid values.

**Comment by aeneasr** [comment]
Most open api generators support a setting which avoids type duplicates. Which one are you using?

**Comment by yholkamp** [comment]
@aeneasr the issue is actually that this information isn't available to the generator. There is only `Type` type defined in the API spec, while there should be two different `Type` types. Due to that a generator cannot know that the `Message` object's `type` field (info or error) should be different from the type property of the `recoveryFlow` (api or browser).

**Comment by aeneasr** [comment]
We generate specs for all major programming languages, and it has not been an issue so far (unless misconfigured).

> Which one are you using?

Can you please share what generator you are using?

**Comment by yholkamp** [comment]
@aeneasr I'm not using a generator, this is present in https://github.com/ory/kratos/blob/master/.schema/api.swagger.json, which seems to be last generated by you.

**Comment by aeneasr** [comment]
I might have misunderstood, I was under the impression that you are generating code, using the schema, which leads to invalid types due to naming clashes. Sorry for the confusion! :)

You're absolutely correct, the types are overwritten. I'm not sure if there is an option in go-swagger to resolve this. Alternatively, the new pipeline which also generates OpenAPI Spec 3.0 is able to patch the schema, which we could use to solve this (see https://github.com/ory/kratos/pull/1012 )

I'd generally want to avoid following swagger issues in the Go code as we want to stay as idiomatic as possible in the Go code.

**Comment by yholkamp** [comment]
@aeneasr makes sense, I didn't see a clear way to work around this either without bigger changes. Looking at the PR it seems like it might already be resolved:
https://github.com/ory/kratos/blob/9c38e75ab679ad80a7cfe64ee48ea871eed17036/.schema/api.openapi.json#L1186-L1210
shows a different name for the UI type so that already takes care of it. It doesn't seem to enumerate all the available options in the spec yet but that's a minor detail. Thanks for the quick response and your great work!

**Comment by aeneasr** [comment]
Thank you @yholkamp :)
