### ISSUE TITLE
Cann't work with mysql

### ISSUE THREAD

**Issue by artisan-yp** [ory/kratos#1051]
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.5.5-alpha.1

docker pull oryd/kratos:latest-sqlite
docker pull oryd/kratos-selfservice-ui-node:latest
docker-compose -f quickstart.yml -f quickstart-standalone.yml -f quickstart-mysql.yml up --build --force-recreate

I flow https://www.ory.sh/kratos/docs/quickstart this way, with error below:
![image](https://user-images.githubusercontent.com/53302341/107224355-4b698080-6a52-11eb-93ea-1dcf6b6ec6c2.png)

**Comment by artisan-yp** [comment]
mysqld_1                      | 2021-02-08T13:08:58.359383Z 0 [Note] Event Scheduler: Loaded 0 events
kratos-migrate_1              | [POP] 2021/02/08 13:08:58 info - Migrations already up to date, nothing to apply
kratos-migrate_1              | [POP] 2021/02/08 13:08:58 info - 0.0175 seconds
kratos-migrate_1              | Successfully applied SQL migrations!
mysqld_1                      | 2021-02-08T13:08:58.359637Z 0 [Note] mysqld: ready for connections.
mysqld_1                      | Version: '5.7.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysqld_1                      | 2021-02-08T13:08:58.652680Z 2 [Note] Aborted connection 2 to db: 'mysql' user: 'root' host: '172.23.0.5' (Got an error reading communication packets)
kratos_kratos-migrate_1 exited with code 0

**Comment by artisan-yp** [comment]
mysqld_1                      | 2021-02-08T13:14:26.862260Z 5 [Note] Aborted connection 5 to db: 'mysql' user: 'root' host: '172.23.0.5' (Got an error reading communication packets)

**Comment by aeneasr** [comment]
Just wait a bit, MySQL is slow, it will work eventually.

**Comment by vinckr** [comment]
Yes I can confirm! Just reproduced it and got a similar error as you, but then it just went through after a while.

**Comment by artisan-yp** [comment]
> Just wait a bit, MySQL is slow, it will work eventually.

But my MySQL container ip is 172.23.0.4, not 172.23.0.5，and i didn't found any db or table in MySQL.

**Comment by aeneasr** [comment]
You misunderstand the error message:

1. `mysqld_1                      | 2021-02-09T14:03:37.942884Z 3 [Note] Aborted connection 3 to db: 'mysql' user: 'root' host: '172.18.0.5' (Got an error reading communication packets)` is coming from **MySQL**, the IP `172.18.0.5` is the migration container.
2. The error just means that the connection was closed, which happens when migrations execute successfully.

My feeling is that you haven't actually checked if the service is running, but are assuming it doesn't, because of the error log. In fact, your logs show that Kratos boots successfully. So as far as I can tell there is no problem except for the stray log message from MySQL.

**Comment by artisan-yp** [comment]
> You misunderstand the error message:
> 
> 1. `mysqld_1                      | 2021-02-09T14:03:37.942884Z 3 [Note] Aborted connection 3 to db: 'mysql' user: 'root' host: '172.18.0.5' (Got an error reading communication packets)` is coming from **MySQL**, the IP `172.18.0.5` is the migration container.
> 2. The error just means that the connection was closed, which happens when migrations execute successfully.
> 
> My feeling is that you haven't actually checked if the service is running, but are assuming it doesn't, because of the error log. In fact, your logs show that Kratos boots successfully. So as far as I can tell there is no problem except for the stray log message from MySQL.

Thank you for your help😄
