### ISSUE TITLE
login ui returned without flowid 

### ISSUE THREAD

**Issue by williamohara** [ory/kratos#1055]
**Describe the bug**

If an application were to start the browser/settings flow without a session token - the flow redirects the user to the login ui without a flow ID. The absence of a flow id causes an error when hitting .getSelfServiceLoginFlow to get login flow context

**Reproducing the bug**

in a logged out state - hit the /self-service/settings/browser endpoint
it returns the login ui url with no flow id

_Server logs_

time=2021-02-08T20:47:56Z level=info msg=started handling request method=GET name=public#https://auth-dev.subscripify.com/api/ remote=10.240.0.4 request=/self-service/settings/browser
time=2021-02-08T20:47:56Z level=info msg=completed handling request method=GET name=public#https://auth-dev.subscripify.com/api/ remote=10.240.0.4 request=/self-service/settings/browser status=302 text_status=Found took=48.101µs

_Server configuration_

    serve:
      public:
         base_url: https://auth-dev.subscripify.com/api/
        host: ''
        port: 4433
        cors:
         enabled: true
         allowed_origins:
            - https://auth-dev.subscripify.com
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Authorization
            - Cookie
          exposed_headers:
            - Content-Type
            - Set-Cookie
          allow_credentials: true
          options_passthrough: true
          max_age: 0
          debug: true

**Expected behavior**

I would expect the login ui url to return with a flow id

**Environment**

from helm values.yaml
image:
  repository: oryd/kratos
  tag: v0.5.5-alpha.1-sqlite
deployed on aks in a

**Additional context**

implemented workaround to hit /self-service/login/browser when there is a lack of a flow id in the login url.

**Comment by aeneasr** [comment]
Thank you for the report, implementing your workaround is actually the expected course of action. Your app should also be able to handle 410 (gone) and other errors when fetching login flows!

However, this could still be handled better the way you suggest - so keeping this issue open.

**Comment by williamohara** [comment]
Yeah - I re-looked at the sample app you guys have and saw that you had done that in front end- I am actually back and forth on such things. Do it in front end first before making the call to the server or keep logic out of the front end and let the backend manage it. I like to keep my front end as logic free as possible, so I lean this way.

**Comment by aeneasr** [comment]
Hello, this is currently possible for SPA flows. However, there are certain situations where this is required. Unfortunately, due to the way Ory Kratos works with the redirects, I don't think we'll ever be able to remove these IDs completely. Closing :)
