### ISSUE TITLE
Just wait a bit, MySQL is slow, it will work eventually.

### ISSUE THREAD

**Issue by artisan-yp** [ory/kratos#1056]
Just wait a bit, MySQL is slow, it will work eventually.

_Originally posted by @aeneasr in https://github.com/ory/kratos/issues/1051#issuecomment-775188914_

The error:
mysqld_1                      | 2021-02-09T03:02:19.668790Z 4 [Note] Aborted connection 4 to db: 'mysql' user: 'root' host: '172.23.0.5' (Got an error reading communication packets)

But my MySQL container ip is 172.23.0.4, not 172.23.0.5，and i didn't found any db or table in MySQL.

**Comment by artisan-yp** [comment]
![image](https://user-images.githubusercontent.com/53302341/107312857-5a8d1480-6acc-11eb-920d-ca66904cb2a1.png)

# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.23.0.4  netmask 255.255.0.0  broadcast 172.23.255.255
        ether 02:42:ac:17:00:04  txqueuelen 0  (Ethernet)
        RX packets 24666  bytes 12293560 (11.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28025  bytes 9495248 (9.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8  bytes 751 (751.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 751 (751.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by aeneasr** [comment]
Hello, sorry, it looks like closing the issue was a miscommunication. You're still allowed to reply there! I'm closing this here and continuing the conversation there: https://github.com/ory/kratos/issues/1051#issuecomment-775962945
