### ISSUE TITLE
Courier: send plaintext email bodies in "text/plain" body portion

### ISSUE THREAD

**Issue by mbonnell-wish** [ory/kratos#1065]
**Is your feature request related to a problem? Please describe.**

Currently, the HTML versions of emails are sent in the plaintext body. Ideally, we'd send plaintext versions here. 
Additionally, currently emails are stored in the DB in HTML form. Ideally, they'd be stored in plaintext and the templates would be populated at send-time. Especially now that we have the option to run a separate foreground courier worker, if the nodes/configs for the courier and the normal instances were to differ (eg valid SMTP details only supplied on the courier instance), it would be more intuitive for the courier config's templates/template path be authoritative.

**Describe the solution you'd like**

Store emails in the DB in plaintext, send plaintext bodies in the "text/plain" portion of the emails, populate the HTML templates at send time.

**Describe alternatives you've considered**

Alternatively, the plaintext body could be stored alongside the HTML body in the DB, but I think it would be cleaner to just store plaintext and then populate templates with the values retrieved from the DB. 

**Additional context**

I'm happy to work on this, shouldn't be too much work.

**Comment by aeneasr** [comment]
Good idea! I think we should serialise and store the "Template"  structs in the DB and then use that data to populate both text and html versions. Would be great if you could work on this!

**Comment by mattbonnell** [comment]
Sounds like a good approach. To handle template updates, would we just overwrite the templates in DB on startup, if the template path is set in the config and valid templates are found there?

**Comment by aeneasr** [comment]
I am not sure if I understand this part:

> would we just overwrite the templates in DB on startup

Could you elaborate please?

**Comment by mattbonnell** [comment]
Sure. So, in the configuration, we specify the path to a directory containing templates. You mention that we should serialize the templates structs and store them in the DB. My question is, how should we handle updates to the templates? For ex, I make a change to the custom templates pointed to in my config. How/when does this change get applied?

**Comment by aeneasr** [comment]
> You mention that we should serialize the templates structs and store them in the DB. My question is, how should we handle updates to the templates? For ex, I make a change to the custom templates pointed to in my config. How/when does this change get applied?

So the idea is that the model/raw data is serialized, not the template. Template updates would just update the content I think.

https://github.com/ory/kratos/blob/master/courier/template/recovery_invalid.go#L14

**Comment by mbonnell-wish** [comment]
Ah ok, yes I understand. Sounds good. I'm going to prioritize working on some of those 0.6 milestone issues and circle back to this one.

**Comment by aeneasr** [comment]
Awesome!!
