### ISSUE TITLE
Expand password validation error messages to facilitate i18n

### ISSUE THREAD

**Issue by yholkamp** [ory/kratos#1071]
**Is your feature request related to a problem? Please describe.**

When using Kratos in a non-English environment, we have to rely on the message ID plus context in order to translate error messages that are returned by the various flows. We're running in to the fact the [password validation error](https://github.com/ory/kratos/blob/1940a679eb6b695e22cb939fb0d8d85cebb82a1e/text/message_validation.go#L62-L71) message in particular lacks a lot of information and is used for a variety of errors, which are hard to property convey to the end user without knowing what happened. Currently what's available is just the generic id plus a 'reason', which contains an English sentence, with at least these options;

1. The password can not be used because the password is too similar to the user identifier.
2. The password can not be used because password length must be at least 6 characters but only got 4.
3. The password can not be used because the password has been found in at least 5810 data breaches and must no longer be used..

**Describe the solution you'd like**

With the approach to i18n support Kratos has taken, it would be really convenient to split out this particular error message in to multiple separate error messages and populating the 'context' with the necessary variables to allow the messages to be captured. 
For example:
1. `ErrorValidationPasswordPolicySimilarToIdViolation`
2. `ErrorValidationPasswordLengthPolicyViolation`, context: `{required:6, provided:4}`
3. `ErrorValidationPasswordBreachedPolicyViolation`, context: `{count: 5810}`

This will provide these messages with separate message IDs, which combined with the context allows Kratos users to translate these messages accordingly.

**Describe alternatives you've considered**

An alternative solution might be to include i18n support inside Kratos, by providing translation files in a similar manner as the email templates but this does not appear to be the direction Kratos is headed.

**Additional context**
None

**Comment by zepatrik** [comment]
Agree, would you be up for a PR?

**Comment by yholkamp** [comment]
@zepatrik definitely, just to check before I take a look at later, I think I'd update the [`Validate` method](https://github.com/ory/kratos/blob/4a2f41977439354415118df3e37dd0cde8dac1aa/selfservice/strategy/password/validator.go#L144-L183) to return errors.WithStack objects that also contain the context and an error type reference, would that be the appropriate way to tackle this or is there a more Go-like alternative to use?

**Comment by zepatrik** [comment]
I would probably add a specific error type there that holds the context. You can then use `errors.Is` and `errors.As` to do type assertions and get the wrapped error. Like

```go
type ErrIdentifierTooSimilar struct {
    Distance int
}

type ErrTooShort struct {
    RequiredMin, Actual int
}
```

and corresponding `Error() string` functions.

**Comment by aeneasr** [comment]
Hello, yes, this makes sense! The errors @zepatrik describes should be defined here: https://github.com/ory/kratos/blob/4a2f41977439354415118df3e37dd0cde8dac1aa/schema/errors.go

**Comment by aeneasr** [comment]
Marked as stale in error.
