### ISSUE TITLE
Port proxy TLS termination from Hydra to Kratos

### ISSUE THREAD

**Issue by mbonnell-wish** [ory/kratos#1079]
**Is your feature request related to a problem? Please describe.**

Hydra currently supports listing IPs which can handle TLS termination https://www.ory.sh/hydra/docs/production/#tls-termination.

Wanted to get a sense of where this is in Kratos's roadmap.

**Describe the solution you'd like**

https://www.ory.sh/hydra/docs/production/#tls-termination

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by aeneasr** [comment]
We don't have strict TLS enforcment in Ory Kratos so there is currently no need to add this. Once we enforce TLS on incoming requests, it makes sense to add this IMO.

**Comment by mbonnell-wish** [comment]
Sounds good.

**Comment by aeneasr** [comment]
Ok so I will close this as the feature is not needed right now. We can reopen if strict tls enforcement lands
