### ISSUE TITLE
test file have a problem

### ISSUE THREAD

**Issue by CedrusZhao** [ory/kratos#1094]
**Describe the bug**

In the  file `selfservice/strategy/password/login_test.go`.  
``` 
t.Run("case=should pass even without CSRF token/type=api", func(t *testing.T) {
			f := testhelpers.InitializeLoginFlowViaAPI(t, apiClient, publicTS, false)
			c := testhelpers.GetLoginFlowMethodConfig(t, f.Payload, identity.CredentialsTypePassword.String())

			actual, res := testhelpers.LoginMakeRequest(t, true, c, apiClient, testhelpers.EncodeFormAsJSON(t, true, values))
			assert.EqualValues(t, http.StatusBadRequest, res.StatusCode)
			assert.Contains(t, actual, "provided credentials are invalid")
		})
```
this test should pass,so the StatusCode should be 200.But why this is http.StatusBadRequest?

**Comment by aeneasr** [comment]
Can you please link the exact LOC in a github link?

**Comment by CedrusZhao** [comment]
the code is [here](https://github.com/ory/kratos/blob/master/selfservice/strategy/password/login_test.go).

**Comment by zepatrik** [comment]
https://github.com/ory/kratos/blob/dbda88ffe79abd446d100cb0572a61bde0a798c1/selfservice/strategy/password/login_test.go#L177-L184

**Comment by CedrusZhao** [comment]
thank you for teaching me how  to link the exact LOC.
In the line 177, it said the case should pass, so  the code in line 182 should is  `assert.EqualValues(t, http.StatusOK, res.StatusCode) `,but why not?

**Comment by aeneasr** [comment]
The description is not super correct - it passes the CSRF check (because the test is about CSRF) but the username/password combination is still incorrect.

**Comment by CedrusZhao** [comment]
thank you!

**Comment by aeneasr** [comment]
No problem!
