### ISSUE TITLE
Add support for personal access tokens

### ISSUE THREAD

**Issue by davidthor** [ory/kratos#1106]
**Is your feature request related to a problem? Please describe.**

Our customers rely heavily on our CLI to interact with our cloud solution. While sometimes used directly by users, this CLI is more frequently used inside jobs triggered automatically by CI systems (e.g. CircleCI, Github Actions, Jenkins, etc.). Users can often use built-in secret managers to safely provide their username/password into these jobs without risking the credentials being revealed but doing so forces the user to a) store their personal credential in a shared secret manager, and b) update the password value every time they rotate their personal credentials. This can create a risk of exposure for personal, often re-used passwords, and creates credential management complexity.

**Describe the solution you'd like**

I'd like to allow users to create and manage one or more Personal Access Tokens (PATs), that can be used to login to their account and acquire a session. Users would be able to create unique PATs for each of their use cases (e.g. CI jobs triggered by Github Actions) and would be able to use those tokens to login from each of their respective flows. These tokens could be created and rotated separately from personal passwords allowing users to more safely expose them to shared secret managers. It would also decouple the personal password from the PAT usage allowing users to change their own password without impacting other flows. 

**Describe alternatives you've considered**

Haven't considered any others since this is a common utility. Ideally it would behave identically to Github's own usage: https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token

**Additional context**

It's also worth noting that PATs should be exempt from MFA even if MFA is enabled for an associated user. PATs are most frequently used in non-interactive flows (e.g. CI jobs) where MFA is unrealistic. I know Kratos doesn't support this yet, but since it is a high priority issue its worth noting the expected behavior.

_This was created as a result of conversations on https://github.com/ory/kratos/issues/385_

**Comment by ashley-3r** [comment]
Wrong solution you are looking for a Hydra client credential with jwks. Kratos was made for users and not machines. PAT is client credentials with secret token to authenticate.

**Comment by davidthor** [comment]
I thought oauth and Hydra was for 3rd party use-cases whereas this would be a first-party use-case. Assuming that I did use the client credentials grant for that flow, would that mean a PAT is synonymous with a new client secret? How would I associate said secret with the specific user who requested its creation? It basically needs to act as though it is the user who requested it and inherit all the same permissions.

**Comment by zepatrik** [comment]
In my opinion running Hydra and oauth2 is quite overkill and not really meant for first party integrations, so might be something Kratos could offer. As @aeneasr pointed out in #385 this can indeed easily be implemented as an application feature instead, but I see a valid point in having this as a feature of Kratos - or at least this discussion. 
PATs have to be managed, revoked, and ideally checked for validity in a single call to `/sessions/whoami`. All of the permission management has to be taken care of outside of Kratos, as with users.

**Comment by aeneasr** [comment]
So PATs are a user-bound / self-service form of API Keys. I would say that API keys themselves are not within the scope of Ory Kratos but I think we can make an exception for PATs. Maybe PATs are session tokens derived from an active session?

PATs I have seen in the wild:

- keep track of when they were used, where, and by whom
- are revokable at any time
- do not have the full permissions of the user but a subset

Did I leave out anything?

@ashley-3r client credentials are not a mechanism to solve PATs / API Keys!

**Comment by ashley-3r** [comment]
PAT doesn't solve it but if you want keys to authenticate a CI to your backend. Private JWKS is the best way to manage machine clients. Even if hydra gets owned you would only leak the public keys instead of the private keys. PAT is for lightweight CLI where you want to bind user authentication like GitHub tokens and not real machine authentication. I get the need now.

**Comment by aeneasr** [comment]
Right, that makes sense! JWTs with PKI is definitely a one-up to PATs and can be preferred in high-security environments (see e.g. Google Service Accounts). PATs on the other hand are easier to use and there are many ways in which you can secure the PAT storage - e.g. hashing the key in the DB and only comparing the hash, encrypting the value at rest, and so on. It's usually a trade-off and both options are viable depending on context!

**Comment by aeneasr** [comment]
Thank you for the discussion. After some deliberation we have come to the conclusion that this is better left outside of Ory Kratos. Essentialy, a PAT is a K/V which has the PAT value as the key, and the subject id as the value. The subject can be a user, but also something else (service account, ...).

Therefore, we think PATs should be solved in a different project as they are not directly in the domain of Ory Kratos.

**Comment by davidthor** [comment]
So is the suggestion that we should use a 2nd, alternative form of authentication to protect apps/services? Some middleware or gateway rule that would check the kratos session or the PAT?

**Comment by aeneasr** [comment]
Yes that would be the correct approach IMO. PATs can have many shapes and forms (scoped, unscoped, expiring, not expiring, ...) and it would probably need a pretty large module to cover all these use cases in a performant manner. So it's probably easier and faster to just implement a second service (or use e.g. something like Vault although that might not be the best solution here). You can still link the PAT's owners to the Kratos Identity :)

**Comment by fugkco** [comment]
@aeneasr you're absolute right that PATs can have many shapes, but I think one of the big advantages of using the Ory suite is that Ory can implement best practices so that others don't have to have a degree in securing user related resources and other related things. Having personal access tokens as part of Kratos allows for a common interface and good practices that includes all the above shapes. Combining it with Oathkeeper allows for a common interface to ensure that tokens can be least privilege based.

Having said all of that, the biggest issue I see with all Ory users implementing their own system for PATs is the fact that now PATs would potentially live in a separate database, which adds additional security concerns, and a database look up that otherwise can minimized to be with Ory. These PATs are essentially a username and password, and storing them separately from the main user data means that one increases the potential attack surface.

I'd love for this to be re-considered.

**Comment by aeneasr** [comment]
Thank you for bringing this up! We’re planning to introduce a new service for PATs next year :)

**Comment by fugkco** [comment]
That's great to hear! I look forward to it!

**Comment by hoshsadiq** [comment]
@aeneasr is there a place to track it?

**Comment by aeneasr** [comment]
Not yet

**Comment by ysaakpr** [comment]
If PAT is maintained in a separate system how one can can validate it with identity service ??.

What i understand is, PAT is long expiry credentials mapped against an entity, be it user account or service account. And whenever a service receives the token, it has to validate the PAT and retrieve the user associated with PAT and go ahead with access allow/deny logic. Considering that with a dynamic sessions created by a user while logging in, the only difference i can see is that its one time generated, and have long life(most of the time). 

With this understanding if you keep them under a different service, it become complex for the authentication layer in the apps to check the token type by checking some prefix  to validate with PAT service or identity service. which is actually over kill for maintenance and usage.

I still dont understand if user sessions are maintained in Kratos, why PAT(a long lived session identifier) need to be maintained in a separate service.

Am i missing something more than this??

**Comment by hoshsadiq** [comment]
@ysaakpr I totally get where you're coming from, but I think having a PAT as a separate service makes sense. While most applications need some sort of user authentication and session management, not all applications needs PATs. Quite often, companies don't even want you to use their APIs. From that perspective, having it separate allows one to take away the admin burden of functionality that you don't care about.

**Comment by micahlmartin** [comment]
@aeneasr are there any updates on when this might be available for beta testing?

**Comment by quintilation** [comment]
a year later, any update - I too would like to have something like PATs in kratos.
