### ISSUE TITLE
Make csrf_token cookie to follow "session > cookie > domain" configuration for subdomains scenarios

### ISSUE THREAD

**Issue by DavidBM** [ory/kratos#1112]
**Is your feature request related to a problem? Please describe.**

Currently, we are building a multi sub-domain system. The idea is to have kratos.example.com and access.example.com. Where access.example.com is the selfservice ui.

We configured the "session > cookie > domain" in order to set it up to "exmaple.com", so the session cookie will be available for all subdomains. The problem is that the csrf_token cookie doesn't seem to follow the configuration property, so it doesn't work.

**Describe the solution you'd like**

There are two possible solutions:

1. Make the csrf_token to follow the "session > cookie > domain" configuration from the kratos.yml config file
2. Add a configuration like "csrf > cookie > domain" in order to be able to configure the domain of the csrf_token cookie

**Describe alternatives you've considered**

I have read the solution of stream the data from the selfservice UI to kratos in order for both to be under the same subdomain. That is the option we will implement for now, but if this feature is available, we would like to switch back to expose kratos directly, as kratos has many endpoints.

**Additional context**

We are using Rust and building our own self service UI using the generated rust crate from the openapi api definitions.

**Comment by DavidBM** [comment]
Additionally, I would be happy to help in this if I get some guidance.

**Comment by aeneasr** [comment]
The CSRF cookie is only required in the context of Ory Kratos, so there is no need to have it run under a different domain. No-one expect Ory Kratos needs access to the CSRF cookie! The UI receives the CSRF token from Ory Kratos.

**Comment by DavidBM** [comment]
You are very right! I don't know what happened, just tried today and it worked! Thanks!
