### ISSUE TITLE
add messaging for privileged fields login

### ISSUE THREAD

**Issue by williamohara** [ory/kratos#1117]
**Is your feature request related to a problem? Please describe.**

The user may not understand why they need to log in after trying to update a privileged field after  `privileged_session_max_age` 
 expiry. I'd like to present an info message to the user saying something like "This update requires you to re-authenticate"

**Describe the solution you'd like**

Pass a message into the login form indicating why the user needs to authentication - it would be really easy at that point to jus put the message up on the login form page

**Describe alternatives you've considered**

I could put "may require re-authentication" as a note on the settings update page - but that would be wordy and against my minimalist design aesthetic. I like to keep forms as self descriptive as possible

Another way would be to reveal the  privileged_session expiration time in the return for getSelfServiceSettingsFlow and the list if privileged fields and then the front end can decide on showing a message on the page based upon that info - it'd be kinda logic rich to do it that way

**Additional context**

**Comment by zepatrik** [comment]
The idea was to have the UI decide which message to show. But we should have an easy way for the UI to determine that (I don't think there is any yet). Maybe we can include such a message in the form (it will be especially useful to people who just got started). I don't think it is really required though.

**Comment by aeneasr** [comment]
Yeah that makes sense, there should be some type of prompt explaining what is going on! This is a good issue to tackle - if you're up for the challenge I can give some pointers.

**Comment by nanikjava** [comment]
@aeneasr Interested to work on this. Could you kindly give me some pointers on the following

1) Endpoint and flow to test using `curl` eg: `/self-service/XXX` ?
2) Existing test case that can be looked at ?

Thanks.

**Comment by aeneasr** [comment]
Yeah, we don't have a bot for this right now :/

Regarding your question. When a reauth is requested, we add the `?refresh` query parameter:

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/selfservice/flow/login/handler.go#L125-L126

This would allow the addition of a message saying something like "Please confirm this action by verifying that it's you" (or something similar) around here

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/selfservice/flow/login/handler.go#L92

if the login flow is forced

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/selfservice/flow/login/flow.go#L101

An example of such a message is here:

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/selfservice/strategy/link/strategy_verification.go#L174

And finally, this would of course need some tests, in particular below

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/selfservice/flow/login/handler_test.go#L126

and

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/selfservice/flow/login/handler_test.go#L162

and

https://github.com/ory/kratos/blob/c2a1b6df95bcb5dfe2b238be5903f483b9e701b5/test/e2e/cypress/integration/profiles/email/login/success.spec.js#L49

**Comment by nanikjava** [comment]
@aeneasr can you kindly look at the WIP PR to cross-check if this is how you have in mind ?

Used the following `curl` command to test the flow

```
flow=$(curl -s -X GET  \
       -H "Accept: application/json"   \
       http://127.0.0.1:4433/self-service/registration/api  | jq -r '.id' )

curl -s -X POST \
        -H "Content-Type: application/json" \
 -d '{"password_identifier": "idonotexist@google.com", "traits.name.first" : "dummy", "traits.name.last" : "lastname", "traits.email": "idonotexist@google.com", "password": "__JUST_A_PASSWORD__", "method": "password"}'     \
"http://127.0.0.1:4433/self-service/registration?flow=$flow" | jq



flow=$(curl -s -X GET -H "Accept: application/json" \
  "http://127.0.0.1:4433/self-service/login/api" \
| jq -r '.id')



curl -s -X GET -H "Accept: application/json" \
  "http://127.0.0.1:4433//self-service/login/api?flow=$flow&refresh=true"   | jq
```

Let me know what you think.
