### ISSUE TITLE
Support dynamic return_to address on verification flow

### ISSUE THREAD

**Issue by davidthor** [ory/kratos#1123]
**Is your feature request related to a problem? Please describe.**

Most flows support a `return_to` search parameter in the URLs to override default redirect behavior. It seems the verification flow is the one exception where there is no such logic and the user is always routed to the verification UI URL instead. This leaves me with no way for the upstream application to identify itself to the verification URL and allow the user to easily return back to the main application.

**Describe the solution you'd like**

I'd like to be able to provide a custom `return_to` URL (that matches my configured whitelist of course) that the verification flow will route back to upon successful verification. If I route my user to `/self-service/verification/browser?return_to=http://app.domain.com`, I would expect them to be routed back to `http://app.domain.com` after completing the verification flow by navigating to: `/self-service/verification/methods/link?token=<token>`. 

**Describe alternatives you've considered**

Right now I've made this a query string parameter supported by my UI application. I then store the value in the UI application session and trigger the return when the verification flow state is set to `passed_challenge`. 

**Additional context**

My only problem with this flow is that I have to introduce the idea of a session to the UI application code to store this value. If the `return_to` value was in the flow object like described in https://github.com/ory/kratos/issues/1121, I'd be more than happy to instrument this logic in the UI application myself since it's a simple conditional on my verification page.

**Comment by aeneasr** [comment]
Yes that makes sense! Would you be up for a contribution here? :)
