### ISSUE TITLE
Provide a means to specify the `return_to` URL for the post-registration verification flow

### ISSUE THREAD

**Issue by mattbonnell** [ory/kratos#1133]
**Is your feature request related to a problem? Please describe.**

This is an extension of #1123, but it would be nice to be able to provide a means to pass a `return_to` parameter to the post-registration verification flow.

**Describe the solution you'd like**

In our particular use case, using the same `return_to` that we pass to the initial registration flow would work just fine, but a more general solution where we added a separate `after_verification` parameter to flows which trigger a verification email would perhaps be better.

**Describe alternatives you've considered**

I think it would have to be one of those two options, but if anyone has other ideas please share!

**Additional context**

We're using Kratos as our IdP behind Hydra. We currently store OIDC session state in an encrypted/signed session cookie (our way of working around #1121). We generate a state string that we store in the cookie and also pass in the query parameter for any page which uses it, and only accept the cookie if it matches, to prevent CSRFs. Additionally, we enforce email verification for new accounts before we accept the login request, so we need to access this cookie after the user verifies so we can direct them back to our login endpoint and finally accept their login request. Since we can't currently pass a `return_to` URL to this verification, we're forced to bypass our CSRF-check and accept the cookie without the matching query param state string, which is a vulnerability we'd like to eliminate. 

If #1121 were implemented, we probably wouldn't even need to maintain a session. But I think this would still be good to have regardless.

**Comment by aeneasr** [comment]
I guess #1121 is the correct path forward for this?

**Comment by mattbonnell** [comment]
If we were able to access a return_to url from the post-registration verification flow object then yeah that would work. So I suppose it's a combination of #1121 and #1123

**Comment by davidthor** [comment]
My use case is identical as is my work-around. I created #1121 and #1123 for exactly those reasons. Seems like a natural problem when using Kratos and Hydra together.

**Comment by mattbonnell** [comment]
> My use case is identical as is my work-around. I created #1121 and #1123 for exactly those reasons. Seems like a natural problem when using Kratos and Hydra together.

Have you begun working on those yet, @davidthor? I'm looking to resolve this issue in my current sprint so I would be happy to work on some PRs.

**Comment by davidthor** [comment]
> Have you begun working on those yet, @davidthor? I'm looking to resolve this issue in my current sprint so I would be happy to work on some PRs.

I have not. I was planning to this weekend, but happy to have someone jump in earlier.

**Comment by mattbonnell** [comment]
> > Have you begun working on those yet, @davidthor? I'm looking to resolve this issue in my current sprint so I would be happy to work on some PRs.
> 
> 
> 
> I have not. I was planning to this weekend, but happy to have someone jump in earlier.

Cool. I will take a crack at #1121 today.

**Comment by mbonnell-wish** [comment]
@aeneasr do you happen to know if the post-registration verification inherits the registration flow's `RequestURL` currently?

**Comment by aeneasr** [comment]
> @aeneasr do you happen to know what post-registration verification flow's RequestURL gets set to currently? Does it inherit the registration flow's RequestURL? If you're not sure I'll take a look through the code. As mentioned in the issue description, we would still need a means to pass some URL to this flow that we can send the user to after they successfully verify (same use-case as #1123)

Hm not sure, I think it's just the public base url appended with the verification path?
