### ISSUE TITLE
Account Recovery API flow requires CSRF cookie

### ISSUE THREAD

**Issue by zhming-hub** [ory/kratos#1141]
tool: POSTMAN
1. GET http://127.0.0.1:4433/self-service/recovery/api
response: 
{
    "id": "d2fa5fe6-bb5e-4cfe-8ae3-3c4d807859de",
    "type": "api",
    "expires_at": "2021-03-12T05:14:44.337986Z",
    "issued_at": "2021-03-12T04:14:44.337986Z",
    "request_url": "http://127.0.0.1:4433/self-service/recovery/api",
    "messages": null,
    "methods": {
        "link": {
            "method": "link",
            "config": {
                "action": "http://127.0.0.1:4433/self-service/recovery/methods/link?flow=d2fa5fe6-bb5e-4cfe-8ae3-3c4d807859de",
                "method": "POST",
                "fields": [
                    {
                        "name": "csrf_token",
                        "type": "hidden",
                        "required": true,
                        "value": ""
                    },
                    {
                        "name": "email",
                        "type": "email",
                        "required": true
                    }
                ]
            }
        }
    },
    "state": "choose_method"
}
2. POLT http://127.0.0.1:4433/self-service/recovery/methods/link?flow=d2fa5fe6-bb5e-4cfe-8ae3-3c4d807859de
body: 
{
  "email":"zh_ming@aliyun.com"
}
response: 
{
    "error": {
        "code": 400,
        "status": "Bad Request",
        "reason": "CSRF token is missing or invalid.",
        "message": "The request was malformed or contained invalid parameters"
    }
}

Why is that? I wonder

**Comment by zepatrik** [comment]
The problem is that postman is in fact a browser (electron). We block browsers from accessing the API flows. Can you try the same with curl? That should work.

**Comment by zhmingGIT** [comment]
> The problem is that postman is in fact a browser (electron). We block browsers from accessing the API flows. Can you try the same with curl? That should work.

The result is the same @zepatrik

**Comment by zepatrik** [comment]
Ok first of, what is your kratos version and setup?

**Comment by zhmingGIT** [comment]
> Ok first of, what is your kratos version and setup?

1. install: brew install kratos
2. 
kratos version
Version:			v0.5.5-alpha.1
Build Commit:	83aedcb885acb96c5deb39fff675d5f0528af32d
Build Timestamp:	2020-12-09T11:10:11Z

**Comment by Benehiko** [comment]
I could reproduce this error by following [the guide](https://www.ory.sh/kratos/docs/self-service/flows/account-recovery/#recovery-for-api-clients) and [rest api reference](https://www.ory.sh/kratos/docs/reference/api#initialize-recovery-flow-for-api-clients) in the docs. Will investigate it a bit further, for some reason it always expects the csrf. 

*Initialise API Recovery flow*
```
 ~ curl -s -X GET \
  -H "Accept: application/json"  \                      
  http://127.0.0.1:4433/self-service/recovery/api | jq
{
  "id": "b802b7e6-ea4d-49fd-b90f-19323a7333e0",
  "type": "api",
  "expires_at": "2021-03-12T19:32:58.879806705Z",
  "issued_at": "2021-03-12T18:32:58.879806705Z",
  "request_url": "http://127.0.0.1:4433/self-service/recovery/api",
  "messages": null,
  "methods": {
    "link": {
      "method": "link",
      "config": {
        "action": "http://127.0.0.1:4433/self-service/recovery/methods/link?flow=b802b7e6-ea4d-49fd-b90f-19323a7333e0",
        "method": "POST",
        "fields": [
          {
            "name": "csrf_token",
            "type": "hidden",
            "required": true,
            "value": ""
          },
          {
            "name": "email",
            "type": "email",
            "required": true
          }
        ]
      }
    }
  },
  "state": "choose_method"
}
```

*Complete recovery flow*
```
~ curl -s -X POST \
--data '{"email":"alano@ory.sh"}' \
http://127.0.0.1:4433/self-service/recovery/methods/link\?flow\=b802b7e6-ea4d-49fd-b90f-19323a7333e0 | jq
{
  "error": {
    "code": 400,
    "status": "Bad Request",
    "reason": "CSRF token is missing or invalid.",
    "message": "The request was malformed or contained invalid parameters"
  }
}
```

**Comment by aeneasr** [comment]
If you send JSON, you need to set `Content-Type: application/json` and `Accept: application/json`. That should fix it.

**Comment by zhming-hub** [comment]
> If you send JSON, you need to set `Content-Type: application/json` and `Accept: application/json`. That should fix it�.

No, master

**Comment by changev** [comment]
I met the same issue.

**Comment by jay-kanakala** [comment]
I am facing the same issue too... can some one pls tell me how to fix this. I kind of need it urgently, can't wait till next release. If some one can give me any pointers at code level where the issue is, I will try to fix it.

**Comment by jay-kanakala** [comment]
Hey guys, I am also facing the same issue with Verification API flow as well

curl -s -X POST
--data '{"email":"testuser1@gmail.com"}'
http://127.0.0.1:4433/self-service/verification/methods/link?flow=e2e7e1af-4958-4f8d-9693-09dc82bc41be | jq
{
  "error": {
    "code": 400,
    "status": "Bad Request",
    "reason": "CSRF token is missing or invalid.",
    "message": "The request was malformed or contained invalid parameters"
  }
}

**Comment by aeneasr** [comment]
A fix is scheduled for 0.6

**Comment by jay-kanakala** [comment]
Hey man, really appreciate the great work you did. This was really useful to us. But can you pls give me some pointers at code level to disable this CSRF token via API flow... I think I need to do something in strategy_recovery.go file in self service strategy folder. Can you pls tell me what to do here ... like, comment out a piece of code or something like that. I am a JS dev, dont know about Go lang. but I need this urgently. please

**Comment by johanforssell** [comment]
[session/handler.go](https://github.com/ory/kratos/blob/63b269f2c9c921eead62fdd0b14aa95d9190d498/session/handler.go#L52) uses **.ExemptPath()**:
```
func (h *Handler) RegisterPublicRoutes(public *x.RouterPublic) {
	h.r.CSRFHandler().ExemptPath(RouteWhoami)
	h.r.CSRFHandler().ExemptPath(RouteRevoke)
...
```

while [selfservice/flow/recovery/handler.go](https://github.com/ory/kratos/blob/63b269f2c9c921eead62fdd0b14aa95d9190d498/session/handler.go#L52) uses **.IgnorePath()**:
```
func (h *Handler) RegisterPublicRoutes(public *x.RouterPublic) {
	h.d.CSRFHandler().IgnorePath(RouteInitAPIFlow)
...
```

Should it also use **CSRFHandler().ExemptPath()** ?

**Comment by aeneasr** [comment]
That might be the problem - is this still an issue in 0.6?

**Comment by cortopy** [comment]
I'm still experiencing this with `/self-service/recovery/methods/link`. I'm getting

```json
{
    "error": {
        "code": 400,
        "status": "Bad Request",
        "reason": "CSRF token is missing or invalid.",
        "message": "The request was malformed or contained invalid parameters"
    }
}
```

I've found API flow works for `/self-service/recovery` with this payload:

```json
{
    "email": "me@example.com",
    "method": "link"
}
``` 

But since this payload is not documented in the openapi specs I'm not sure if it's the right endpoint to use

**Comment by aeneasr** [comment]
Yup me too - just opened a new issue to track it #1368
