### ISSUE TITLE
Do not Send Verification Emails for OAuth Flows

### ISSUE THREAD

**Issue by borchero** [ory/kratos#1146]
**Is your feature request related to a problem? Please describe.**

When signing up via an OAuth provider and populating the email address field with a *verified* email address, ORY Kratos still sends out a superfluous verification email.

**Describe the solution you'd like**

When using a Jsonnet configuration like the following, no verification email shall be sent to the provided email address:

```jsonnet
local claims = {
  email_verified: false
} + std.extVar('claims');

{
  identity: {
    traits: {
      [if "email" in claims && claims.email_verified then "email" else null]: claims.email,
    },
  }
}
```

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/issues/1057
