### ISSUE TITLE
Implement immutable keyword in JSON Schema for Identity Traits

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#117]
**Is your feature request related to a problem? Please describe.**

At the moment, all data may be changed by the identity or the administrator. Some data however might be considered immutable (like a username for example).

**Describe the solution you'd like**

The Identity Traits JSON Schema should allow a directive such as `immutable` to express a field that can not be changed once set.

**Describe alternatives you've considered**

None

**Additional context**

Assuming a username can be chosen by the user but updated only by the administrator, we would need something like a privileged keyword - which is out of the scope of this issue.

**Comment by candlerb** [comment]
This applies especially to traits which control the authorization of the user, such as "groups".

Ideally traits would be divided into three classes:
* visible to end-user and editable by end-user
* visible to end-user, but only editable by administrator
* invisible to end-user, and only editable by administrator

Idea: the current identity record could be passed to a jsonnet function, which returns the set of visible traits and whether they are editable.

**Comment by aeneasr** [comment]
Yeah that's what I was thinking as well. My idea would be to have traits that are only user-readable expressed in the JSON schema, and then a new identity field called e.g. `meta` which contains meta-information about the user that is not visible to the user.

**Comment by halms** [comment]
I just wanted to understand how this relates to #47.

To my understanding, the use case described in https://github.com/ory/kratos/issues/117#issuecomment-853903941 is covered by #47, which is now closed.

The original use case (immutable identity traits), though, is still something that may be useful in some applications.

**Comment by aeneasr** [comment]
Since we now have public and private metadata, this issue can be marked as closed as immutable traits can now be handled using these two fields!
