### ISSUE TITLE
Password Derived Encrypted User Keys

### ISSUE THREAD

**Issue by jordanisaacs** [ory/kratos#1218]
# Feature

I am building an app that requires data to be encrypted per-user. A common way to do this through reading around online is to do password derived encrypted user keys. However, this requires being hooked into the login/registration/password change process. Thus, I am currently unable to use ory kratos.

# Solution

I noticed there are hooks. Thus I am thinking that a encrypted user key hook could be enabled in the config file. It would work as follows

Registration Hook:
- Hashes the password with a new password_salt (different from the hashed password stored for authentication)
- Generates a cryptographically secure random number (the user key)
- Encrypts (with aes?) a the user key and a key_salt
- Store the password_salt, key_salt, and encrypted key as a hidden user trait _userkey_ (similar to how password's don't show up in the /whoami)

Login Hook:
- After successful authentication and before return to client, hash the password with the stored password_salt
- Decrypts the userkey with the key_salt and the hashed password
- Timestamp signs the decrypted userkey with the age of the session using a server secret
- Returns the timestamp signed userkey (how to return though... json, cookies, ???)

Password Change Hook:
- Do all the necessary things to decrypt the user key
- Re-encrypt the user key with the new password
- Return the new timestamp signed userkey

Logout:
Not sure if there is a way to revoke a userkey though, reliant on the timed signature

# Alternatives

Try to do the encryption client side and send the data as part of the form and a trait but this feels like it would be better done on the kratos server.

**Comment by jordanisaacs** [comment]
As I need this feature, I am willing to do the work to implement it if it is believed to be compatible with the project.

I was reading through the source code and the logic would fit nicely with the password strategies code. I see it as sort of a sub-strategy, because it depends on password authentication. I am not experienced with OIDC/oauth so not sure if there is a token/key that could use to encrypt a user key.

My thought would be to have a flag in the methods->password to enable the generation/storage/distribution of a user key. Something like:
```
methods:
    password:
        enabled: true
        user_key: true
```

**Comment by aeneasr** [comment]
So you would want to use the user key outside of Ory Keto, or do you want to also encrypt data in Ory Keto with the user key?

**Comment by jordanisaacs** [comment]
Sorry for the confusion. I thought it was best to just rewrite the feature request with much better clarification. see #1246
