### ISSUE TITLE
Rethink public fetch request protection

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#122]
**Is your feature request related to a problem? Please describe.**

Right now, several flows work like this:

1. Make an initial request to `GET /<workflow>` using a browser
2. Be redirected to `urls.<workflow>_ui` and append `?request=abcde`
3. At `<workflow>_ui`, make a request to `GET /<workflow>/requests?request=abcde` and use the resulting data to render things.

The issue here is that knowing `abcde` can cause a data leak. Assuming malicious Malice would be able to guess `abcde`, she could extract all of the identity's traits using a profile management request, and other possible form error messages.

This is because we do not require a strong binding between the first request and the third request. In fact, knowing the TOTP `abcde` is enough proof of authorization at the moment.

We could increase authenticity by additionally binding the TOTP to the CSRF Token. That would require Malice to have access to the CSRF Cookie, which she has not. It would render guessing attacks unsuccessful, for example.

Currently, we have two target audiences for the third request:

- Code running on the client (e.g. SPA)
- Code running on a server

For the first group (code on client), this additional safeguard would be no problem as we could easily tell the e.g. XHR request to include the cookie when making the request.

For code running on the server though, is is absolutely not possible as the server (e.g. the "Login UI") does not have access to the CSRF cookie and even if the server had access to that cookie, it wouldn't be able to decode it because it does not know the cookie secret (by design).

**Describe the solution you'd like**

There are two possibilities:

1. Keep the system as is. Guessing the TOTP is very, very, very hard. Even though it would not be required, adding request throttling could further limit the applicability of prediction attacks.
2. Serve `/<workflow>/requests?request=abcde` over both ports: admin and public, with public requiring a CSRF Token and Admin not requiring any token.

**Additional context**

Comments welcome.

**Comment by amahrt** [comment]
I think the 2nd. approach is a bit better; it's less likely that someone get's access to your servers than that someone is guessing that token.

**Comment by aeneasr** [comment]
While I would strongly contest that guessing a UUID right is easier than accessing some server, I too think that the second option is better, as it protects against any CSRF shenanigans.
