### ISSUE TITLE
Receive the verification email every time when I update my password

### ISSUE THREAD

**Issue by cwei-wish** [ory/kratos#1221]
**Describe the bug**

I registered an account but did not verify the email address. I received an verification email every time  I change my password. This seems unexpected.
Is this intentional? Is there a way to stop this?

**Reproducing the bug**

_Server logs_

_Server configuration_

**Expected behavior**
No email should be sent when I just update my password.

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
We should probably check if the email has changed before we send the email! Probably in here or somewhere where this is used https://github.com/ory/kratos/blob/master/selfservice/hook/verification.go#L51

Contributions welcomed!

**Comment by cwei-wish** [comment]
> We should probably check if the email has changed before we send the email! Probably in here or somewhere where this is used https://github.com/ory/kratos/blob/master/selfservice/hook/verification.go#L51
> 
> Contributions welcomed!

Hi @aeneasr thanks for the reply. I am very happy to contribute. But this hook is called after account is created. How could I know whether the email has been changed or not? In other words, how could I get the previous state of VerifiableAddresses

**Comment by aeneasr** [comment]
Good question! 

https://github.com/ory/kratos/blob/master/selfservice/hook/verification.go#L42-L44 is called after the settings were saved, but also (unfortunately) after the identity was already persisted in the store - otherwise we could have looked it up.

One option could also be to add a new field to `VerifiedEmailAddress` which sets wether we've already initiated the sending of the verification email or not. We could check that there and if true skip sending the email.

**Comment by cwei-wish** [comment]
> Good question!
> 
> https://github.com/ory/kratos/blob/master/selfservice/hook/verification.go#L42-L44 is called after the settings were saved, but also (unfortunately) after the identity was already persisted in the store - otherwise we could have looked it up.
> 
> One option could also be to add a new field to `VerifiedEmailAddress` which sets wether we've already initiated the sending of the verification email or not. We could check that there and if true skip sending the email.

Thanks! I made the changes, but it fails many test cases since I added a new field in VerifiableAddress which is part of the identity collection. How can I use openID generator to generate the new schemas and new models in http client? Is there any step I need to follow when I make schema change?
