### ISSUE TITLE
Documentation link leads to 404

### ISSUE THREAD

**Issue by Fabianstelmach** [ory/kratos#1225]
**Describe the bug**

The following docs link leads to a 404:
https://github.com/ory/kratos/blame/master/docs/docs/concepts/index.md#L274

**Reproducing the bug**

1. Go to https://www.ory.sh/kratos/docs/concepts/index/#bring-your-own-identity-models
2. Click the link "JSON Schemas for Identities"
3. The redirect leads to https://www.ory.sh/kratos/docs/concepts/index/identity-data-model, which is 404

**Expected behavior**

I expect the redirect to go to 
https://www.ory.sh/kratos/docs/concepts/identity-data-model
instead of 
https://www.ory.sh/kratos/docs/concepts/index/identity-data-model

**Additional context**

I made an attempt to figure out why this happens. Unfortunately, I am not able to reproduce this bug by running the docs locally.  Locally, the link correctly leads to /kratos/docs/concepts/identity-data-model.

**Comment by vinckr** [comment]
Thanks a lot for catching this! 
I have tested your change locally too and it works fine! 

Do you want to open a PR for this and reap the fame or should I do it :)

**Comment by Fabianstelmach** [comment]
The PR i opened was for another issue. As mentioned before, I do not know how to fix this bug because I can't reproduce it locally. Please go ahead with a new PR if you wish to fix this.

**Comment by nerrixDE** [comment]
Looks like it was fixed for me, this might be closed now
