### ISSUE TITLE
Support for merging/melding of accounts

### ISSUE THREAD

**Issue by mitar** [ory/kratos#1228]
**Is your feature request related to a problem? Please describe.**

This is related to how users might make a mistake and sign-up once using a social account and another time using another social account or username/password. The user ends up with multiple accounts and after they realized that they made a mistake (e.g., content they expect to be under their account is missing) they want a fix.

**Describe the solution you'd like**

It would be great to have a way for user or an admin (after user contacts the admin through user support) could trigger merging/melding of accounts in to a new merged account. After merging is complete, all apps using Kratos should be notified so that they can also internally update any references necessary.

**Describe alternatives you've considered**

This could be done on the app's side but I think it is better if it is done at the authentication server's side and then propagates to the app.

**Comment by aeneasr** [comment]
I think this has to be done on the implementor‘s side. Ory Kratos does not yet support changing credentials but once it does, this could be done with one or two API calls. Building this into Ory Kratos means:

- we need to understand the models
- have strategies for resolving conflicts
- notify systems via hooks
- habe different merge strategies (merge/replace/…)

So I think this won’t be added :/
