### ISSUE TITLE
Support for linking of a social account to an existing account

### ISSUE THREAD

**Issue by mitar** [ory/kratos#1229]
**Is your feature request related to a problem? Please describe.**

This is a variation on #1228: So user signs up with username and password. Later on the user wants also to link a social account to their account so that user can signs in using both means to authenticate.

**Describe the solution you'd like**

It seems there is no way (maybe I missed something) to invoke linking additional social account to an existing account.

**Comment by aeneasr** [comment]
This is implemented - on the settings page
