### ISSUE TITLE
A HTTP hook to be called when user's profile changes

### ISSUE THREAD

**Issue by mitar** [ory/kratos#1230]
**Is your feature request related to a problem? Please describe.**

So if the app which uses Kratos to authenticate stores user's e-mail address into app's own database and uses this e-mail address when user is not around (e.g., to send notifications) it is important to keep e-mail address in sync with what user configures in the profile on Kratos. Currently, it seems there is no way for the app to be informed about a change to the e-mail address in the profile of the user.

**Describe the solution you'd like**

A some way to configure a HTTP hook to be called towards some app's endpoint when profile of any user changes. In this way the change can propagate further to the app proactively.

**Comment by aeneasr** [comment]
#30
