### ISSUE TITLE
Add possiblitiy to create custom hook

### ISSUE THREAD

**Issue by ptitpoulpe** [ory/kratos#1231]
**Is your feature request related to a problem? Please describe.**

I want to add a default role to registered user, having a post hook that could call another api endpoint could help doing that.

**Describe the solution you'd like**

Add a way to have custom hooks, or at least a callApi hook.

**Comment by aeneasr** [comment]
Already tracked as https://github.com/ory/kratos/issues/30 - contribs welcomed
