### ISSUE TITLE
Documentation and examples missing for form fields ordering

### ISSUE THREAD

**Issue by christian-roggia** [ory/kratos#1236]
According to https://github.com/ory/kratos/issues/176 it is possible to define the ordering of form fields but documentation about it seems to be completely missing and so are examples.

I would also like to know whether it is possible to also define the ordering of OIDC fields (e.g. have OIDC buttons before the username / password textboxes).

**Comment by zepatrik** [comment]
You can always reorder stuff in your UI. Better don't rely on Kratos to ensure a certain order, but rather use some mapping to render your UI according to your UX decisions. See also #1196

**Comment by aeneasr** [comment]
We've improved the ordering in the Ory Kratos 0.6 branch but it is not possible to really customize it. As @zepatrik said this will be probably the burden of the UI implementation :)

**Comment by aeneasr** [comment]
But yeah we need docs for that!
