### ISSUE TITLE
Master branch bug

### ISSUE THREAD

**Issue by Highter87** [ory/kratos#1237]
Master branch. Please test new registration via email. I got error
![image](https://user-images.githubusercontent.com/17083227/114988585-2c96c880-9e9f-11eb-9864-4ff3f0ff52cc.png)

![image](https://user-images.githubusercontent.com/17083227/114988658-3f110200-9e9f-11eb-97f3-06671aa8c9fd.png)

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/issues/647
