### ISSUE TITLE
Document OIDC auth flow

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#124]
**Is your feature request related to a problem? Please describe.**

This documents how the OpenID Connect (and OAuth2) strategy work.

**Describe the solution you'd like**

1. Document that POST data (e.g. `traits.foo=bar`) overrides data from oidc provider (using `ory\.sh/kratos.mappings.identities.traits.#.path`) when signing up.
3. Document the overall flow using [mermaid graph](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVEQ7XG5pbml0W09uIHNvbWUgd2Vic2l0ZSBvciBhcHAgZS5nLiBrcmF0b3MuY29tXVxuaW5pdFJbR0VUIGtyYXRvcy5jb20vYXV0aC9icm93c2VyL3JlZ2lzdHJhdGlvbl1cbmluaXRMW0dFVCBrcmF0b3MuY29tL2F1dGgvYnJvd3Nlci9sb2dpbl1cbnVpTFtzaG93IGxvZ2luIHVpXVxudWlSW3Nob3cgcmVnaXN0cmF0aW9uIHVpXVxuYXV0aHVbUE9TVCBrcmF0b3MuY29tL2F1dGgvYnJvd3Nlci9tZXRob2RzL29pZGMvYXV0aC9yZXF1ZXN0LTEyMzRdXG5zdWNjZXNzTFtsb2dnZWQgaW4hXVxuYXV0aFRbJ0F1dGhvcml6ZSBhcHBsaWNhdGlvbicgVHdpdHRlciBVSV1cbmNiUltFeHRyYWN0IGRhdGEgZnJvbSB0d2l0dGVyIGFuZCBjb3B5IHRvIGlkZW50aXR5XVxuY2JSMltVc2UgZXhpc3RpbmcgZGF0YSB0byBwb3B1bGF0ZSByZWdpc3RyYXRpb24gcmVxdWVzdCBmaWVsZHMsIGVycm9ycyBldGMuXVxuc3VjY2Vzc1JbYWNjb3VudCByZWdpc3RlcmVkIV1cblxuaW5pdC0tPnxDbGljayAnY3JlYXRlIGFjY291bnQnfGluaXRSXG5pbml0LS0-fENsaWNrICdsb2dpbid8aW5pdExcbmluaXRSLS0-fFJlZGlyZWN0IHRvIHVybHMucmVnaXN0cmF0aW9uX3VpfHVpUlxuaW5pdEwtLT58UmVkaXJlY3QgdG8gdXJscy5sb2dpbl91aXx1aUxcblxudWlSLS0-fEZvcm0gUE9TVCB3aXRoIHByb3ZpZGVyPXR3aXR0ZXJ8YXV0aHVcbnVpTC0tPnxGb3JtIFBPU1Qgd2l0aCBwcm92aWRlcj10d2l0dGVyfGF1dGh1XG5hdXRodS0tPnxSZWRpcmVjdCB0byBUd2l0dGVyfGF1dGhUXG5hdXRoVC0tPnxUd2l0dGVyIHJlZGlyZWN0cyB0byBPQXV0aDIgQ2FsbGJhY2sgVVJMIHxjYltHRVQga3JhdG9zLmNvbS9hdXRoL2Jyb3dzZXIvbWV0aG9kcy9vaWRjL2NhbGxiYWNrL3R3aXR0ZXI_Y29kZT0uLi5dXG5jYi0tPnxhY2NvdW50IGV4aXN0cyBhbmQgcGVyZm9ybWluZyBsb2dpbnxzdWNjZXNzTFxuY2ItLT58YWNjb3VudCBleGlzdHMgYnV0IGV4cGVjdGVkIHJlZ2lzdHJhdGlvbnxpbml0TFxuY2ItLT58YWNjb3VudCBkb2VzIG5vdCBleGlzdCBidXQgZXhwZWN0ZWQgbG9naW58aW5pdFJcbmNiLS0-fGFjY291bnQgZG9lcyBub3QgZXhpc3QgYW5kIHBlcmZvcm1pbmcgcmVnaXN0cmF0aW9ufGNiUlxuY2JSLS0-fGlkZW50aXR5IGRhdGEgaXMgdmFsaWR8c3VjY2Vzc1JcbmNiUi0tPnxpZGVudGl0eSBkYXRhIGRvZXMgbm90IHZhbGlkYXRlLCBlLmcuIG1pc3NpbmcgZmlyc3QgbmFtZXxjYlIyXG5jYlIyLS0-fHJlZGlyZWN0IHRvIHVybHMucmVnaXN0cmF0aW9uX3VpIHdpdGggcmVxdWVzdC0xMjM0fHVpUlxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0)

**Comment by gperdomor** [comment]
How this flow works? Kratos standalone or should be configured with Hydra?

**Comment by aeneasr** [comment]
This will be working with ORY Hydra and GitHub, Google, and so on. Still needs a lot of docs though!

**Comment by gperdomor** [comment]
In my job, we provide a SAAS platform and we want to expand our API to 3rd party clients, so we want to rewrite some things, one of them, the User related API, Initially I wanted to write a User/Identity API (in this case, with Node) and connected with Hydra, until i saw Kratos, what do you recommend us?

**Comment by aeneasr** [comment]
I see, so this issue will document how ORY Kratos can consume e.g. "Sign in with Google". Another issue will be to integrate ORY Hydra natively with ORY Kratos. You can probably work around this interface not existing yet by implementing the login/consent flow in the app that handles the login ui for kratos :)

**Comment by gperdomor** [comment]
Mmmmm yes ... instead of using Node to build some kind of "Kratos", I wanted to try using Kratos + Hydra ... I was thinking that maybe build a REST with a user CRUD and call the Kratos API in second plan to manage the Identities, then try to integrate with Hydra 🤔

**Comment by aeneasr** [comment]
Yeah, that's a good plan :) We don't support Hydra yet in Kratos as downstream (so your usecase), only as upstream (so "log in via X,Y,Z") but this will be solved in a future patch!

**Comment by aeneasr** [comment]
This should be addressed after the switch to JSONNet #380
