### ISSUE TITLE
Support Unix Sockets

### ISSUE THREAD

**Issue by sloonz** [ory/kratos#1249]
AFAICT Kratos can only listen on TCP sockets. Unix sockets have a few advantages over TCP sockets.From least important to more important:

- Minor performance gains
- Convenience for system administrators in some contexts : using `/run/http/kratos.sock` rather than `localhost:31038` is more expressive and less error-prone (for example, when configuring the reverse-proxy). There's no need to keep track of ports assignments (which ports are assigned to which services, which should be open/closed on the firewall…).
- Security benefits : Unix sockets are never reachable from an external machine, so a misconfiguration (listening on 0.0.0.0:8080 instead of localhost:31038) has less of an impact. More importantly, Unix socket are subject to normal Unix permissions ; if a non-privileged user is compromised on the machine, he can access without any trouble to `localhost:31038`, but still be limited by normal filesystem restrictions to access on `/srv/http/kratos.sock`

**Comment by sloonz** [comment]
It’s here in Hydra: https://github.com/ory/hydra/blob/24f91ab7038e4c612db5af86ff0f3ee5eb03c878/cmd/server/handler.go#L284

I think what could be done is extracting a `MakeListener(add string, permission *config.UnixPermission) (l net.Listener, tlsPossible bool, err error)` function and put it into github.com/ory/x. It would require to also move hydra's config.UnixPermission into ory/x.

I can try to do a pull request doing this if you’re okay with that approach.

**Comment by aeneasr** [comment]
SGTM!

**Comment by sloonz** [comment]
First try : 

https://github.com/ory/x/compare/master...sloonz:master
https://github.com/ory/hydra/compare/master...sloonz:master
https://github.com/ory/kratos/compare/master...sloonz:master

How do I proceed from here ? Do we keep discussing this here ? Or do I create an issue (pull request ?) on each project ?

**Comment by aeneasr** [comment]
Oh great! I'll take a look now!

**Comment by aeneasr** [comment]
Yeah I think you can just create the PRs - looks good to me

**Comment by aeneasr** [comment]
merged!

**Comment by sloonz** [comment]
Thanks for taking the time of reviewing merging this !

**Comment by aeneasr** [comment]
Thank you for making it! :)
