### ISSUE TITLE
'Sign in with Github' button disappears after failed email-password sign in attempt

### ISSUE THREAD

**Issue by RomeldaB** [ory/kratos#1281]
Hi! Apologies if this is a known issue but couldn't find anything related to it.

**Describe the bug**

I am building an application that supports both email-password sign in and also sign in with github. Both of them work fine for the moment, however if I try to sign in with an email and e.g a short password, when the form with the error messages is generated, it doesn't have a sign in with github button. A new flow has to be created to make it show up.

**Reproducing the bug**

Go through the tutorial on adding the sign in with Github option after doing the quickstart (https://www.youtube.com/watch?v=Hz_dP5c_qvc&t=213s) then type a@a.com or any email and a short password e.g 123. Upon pressing sign in the error messages show but the login with github button dissappears.

**Expected behavior**

The form that comes with the error messages should also have the 'SIgn in with Github' button.

Thank you!

**Comment by aeneasr** [comment]
I believe the idea here is to have one method which is active - so you choose to sign up with email-password and then you probably retry that. But we could add the SSO button again - this might actually be the case on master!

**Comment by RomeldaB** [comment]
Makes sense. I was just thinking about the case when a user tries to use some weak password, and maybe after some tries, decides to give up and go for the social login which is easier as they just have to click once. Not sure if this is the case on master, I have only tried the quickstart and also in my project using the helm chart of the current latest version (0.9.0) and the issue is still there.

**Comment by aeneasr** [comment]
In that case it probably makes sense to have a "Reset" button or link which resets the form. This could be implemented in the UI using a `<a>` or `<button>` element. For regular flows, I believe the current model is more intuitive for end users because there's only one option to continue with the flow.

Closing as workaround possible / wontfix :)
