### ISSUE TITLE
Reintroduce SQL Migration plans

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#131]
**Is your feature request related to a problem? Please describe.**

With the recent update to gobuffalo/pop, we currently have no way of printing out the planned migrations.

**Describe the solution you'd like**

Migrations should be printed out and user should confirm migrations.

**Additional context**

Upsream: https://github.com/gobuffalo/pop/issues/473

**Comment by aeneasr** [comment]
The issue has been resolved now. This affects the `cmd` module and there the "Migrate" functionality. I've disabled some code there with comments and they should basically be re-added but use the newly merged function from gobufallo/pop

**Comment by phozzy** [comment]
Probably I'm just out of the scope, so sorry...
Did you consider this solution: https://github.com/golang-migrate/migrate ?

**Comment by aeneasr** [comment]
We're using pop now, see the upstream issue (linked in the OP): https://github.com/gobuffalo/pop/issues/473
