### ISSUE TITLE
Forgot username feature

### ISSUE THREAD

**Issue by jess-sheneberger** [ory/kratos#1324]
**Is your feature request related to a problem? Please describe.**
My apps users sign up with a username and also provide an email address. A user could forget their username and need to recover it.

**Describe the solution you'd like**
I want to provide a "forgot username" option that takes the users email address, looks up the username associated with that email address, and sends the user an email with their username. This would be somewhat similar to a recovery flow, except it wouldn't need to email a recovery link, just the username.

I could implement this in Kratos and submit a pull request. Does this make sense to provide in Kratos?

**Describe alternatives you've considered**
I understand many who use Kratos would not need such a feature because, for example, they might use email addresses to login.  But if you use usernames it seems you'd need something similar.

**Comment by aeneasr** [comment]
Hm, good question. I would probably prefer not to implement this.

I think if you remember your email address (which you use to recover your username), why not just use that email to sign in instead of going the extra round trip of sending an email to your email with your username so that you use it to sign in with that instead of the email?

**Comment by nerrixDE** [comment]
I agree with aeneasr here, such a feature would create a tone of new security challenges, complicate Kratos and question the principle of a single identifier (being Email or Phone).
I see the problem the OP has however I see the benefits of such a feature / change in no relation to the heavy consequences, usability and especially security issues it would cause.

**Comment by aeneasr** [comment]
I'm closing this as a wontfix
