### ISSUE TITLE
Feature: websocket for verification flow updates

### ISSUE THREAD

**Issue by jess-sheneberger** [ory/kratos#1325]
**Is your feature request related to a problem? Please describe.**

I want to be able to provide an uninterrupted signup and verification experience, where the user isn't required to switch devices or between app and browser to sign up, verify their email address, and then start working in my app.

Users could sign up in a desktop app, mobile app, or in the browser. User clicks "sign up", enters their email address, and gets a link via email to validate their account. But maybe they signed up via mobile and got the email on their laptop, or maybe they signed up via desktop app and got the email on their mobile. If they click that link, they probably end up in a browser tab, possibly on a different device from where they started. It breaks up the registration experience, and forces the user out of the native app.

**Describe the solution you'd like**

I'd like the user to be able to, for example, register in the desktop app, click the validation link in their mobile, and then be able to return to their desktop app and have it be notified that the validation was completed.  This could be accomplished by upgrading the verification flow request to a websocket connection, so the app can wait to be notified that the state was changed to "passed_challenge".

**Describe alternatives you've considered**

I could write my UI to poll the verification flow for the update to the "passed_challenge" state, but polling usually sucks. It creates unnecessary complication and adds to the workload for the backend service.

Also, a different verification method could be used instead of a link, such as a six-digit code the user could fetch from their email and then enter into the registration UI. So for example the user would register in the desktop app, pull up the email on their phone to find the six-digit code, and then return to the desktop app to enter it, then move on into the app.  But we'd need to generate six-digit codes and store them.  Six digit codes might be less secure than the link generation method Kratos currently uses.

I'd be happy to try implementing the websocket approach if there is a reasonable chance at it being merged. I'm interested to hear if you all think this would be a useful feature.

**Comment by aeneasr** [comment]
> Also, a different verification method could be used instead of a link, such as a six-digit code the user could fetch from their email and then enter into the registration UI. So for example the user would register in the desktop app, pull up the email on their phone to find the six-digit code, and then return to the desktop app to enter it, then move on into the app. But we'd need to generate six-digit codes and store them. Six digit codes might be less secure than the link generation method Kratos currently uses.

We are thinking in that direction to also solve issues around the "email agent previews all the links and invalidates them" https://github.com/ory/kratos/issues/1142

**Comment by aeneasr** [comment]
For websockets - I don't think the use case warrants the complexity of the implementation here :/ While useful, it sounds like it would be difficult to maintain and scale
