### ISSUE TITLE
Login only with verified address

### ISSUE THREAD

**Issue by dadrus** [ory/kratos#1328]
**Describe the bug**

With kratos v0.5.x it was possible to disable login until the account is activated (until the email is verified). This does not work with the current version (v0.6.0-alpha.2) anymore.

**Reproducing the bug**

1. Register the user (since the registration flow does not have the password session hook configured, the user is not logged in). Kratos will send an email with an email verification link.
2. Don't open the link, instead try to login. Kratos will create a session (so the user is logged in)

Here's a stripped down kratos yaml with the most relevant settings, which worked with v0.5.x versions and also with v0.6.0-alpha.2 (but results in a different behavior)

```.yaml
....

selfservice:
  default_browser_return_url: http://127.0.0.1:9090/
  whitelisted_return_urls:
    - http://127.0.0.1:9090

  methods:
    link:
      enabled: true 
    password:
      enabled: true
    profile:
      enabled: true

  flows:
    login:
      ui_url: http://127.0.0.1:9090/identity/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:9090/identity/register
      after:
        default_browser_return_url: http://127.0.0.1:9090/identity/activation_pending

    verification:
      enabled: true
      ui_url: http://127.0.0.1:9090/identity/activate_account
      after:
        default_browser_return_url: http://127.0.0.1:9090/identity/account_activated

....

```

**Expected behavior**

The v0.5.x functionality is preserved, so instead of logging in the user, an error is returned.

**Comment by aeneasr** [comment]
This did not work in Ory Kratos 0.5 either - it's not a regression. Currently, it is not possible to require verification before login in Ory Kratos.

**Comment by dadrus** [comment]
I would not file this issue, if it had not worked previously. Even the [documentation](https://www.ory.sh/kratos/docs/next/guides/account-activation-email-verification/) is talking about account activation. But maybe something else is meant by "account activation" and the behavior, I know from the past was an "unofficial" feature.

**Comment by aeneasr** [comment]
I know that it did not work before - maybe it was something you implemented in your system - because we have tests that check verification. They explicitly check that you can sign in even if you do not have a verified email address. But it doesn't really matter - it's still a feature request :)

**Comment by dadrus** [comment]
Ok. :) How relevant or important do you see this feature request for kratos?
I very appreciate if you could give me some hints where to look in the code as well to add the corresponding behavior. Thank you in advance.

**Comment by aeneasr** [comment]
Yes, that was the original plan for this feature! I think it would make sense to have this here!

**Comment by aeneasr** [comment]
I might change the name of the hook to `require_verification`

**Comment by aeneasr** [comment]
Or `require_verified_address`
