### ISSUE TITLE
bug: Recovery Credentials case sensitive

### ISSUE THREAD

**Issue by vinckr** [ory/kratos#1329]
**Describe the bug**

I try to recover my account, but it only works when i put in the "exact" email I registered with. 
For example I mistakenly registered with "Vincent(ät)ory.sh" and I can only recover the account when I input "Vincent(ät)ory.sh", other capitalizations like "vincent(ät)ory.sh" dont work.

**Reproducing the bug**

I encountered the bug in the Ory console, would have to confirm that it occurs when I run kratos locally too.

**Expected behavior**

I can recover my account with any capitalization, regardless of how i capitalized it when signing up.

**Additional context**

There could be a notice "Needs to be capitalized exactly like when signing up", but its far better UX when you can just spell it however. Usually the capitalization when signing up is a mistake and wont be remembered later on (as in my case).

**Comment by you1996** [comment]
Hi @vinckr... Yes i confirm the bug ...i'll be happy if i could contribute by fixing this 😃 !
