### ISSUE TITLE
Config schema not available for v0.6.0+

### ISSUE THREAD

**Issue by nickdbush** [ory/kratos#1331]
**Describe the bug**

For `v0.5.5-alpha.1` (and prior), the JSON schema for the configuration file was found at https://raw.githubusercontent.com/ory/kratos/v0.5.5-alpha.1/.schema/config.schema.json.

`v0.6.0-alpha.1` and `v0.6.0-alpha.2` do not have the `config.schema.json` file in the `.schema directory. This causes a 404 for the https://raw.githubusercontent.com/ory/kratos/v0.6.0-alpha.2/.schema/config.schema.json resource.

The config schemas for v0.6.0+ are referenced in the [schemastore.org schema](https://raw.githubusercontent.com/ory/kratos/master/.schema/version.schema.json).

This prevents IntelliSense and validation from working in compatible editors for v0.6.0+ configs.

**Reproducing the bug**

1. Open VSCode
2. Create a `kratos.yml` file
3. Observe that IntelliSense works for the `version` key. Set `version: v0.6.0-alpha.2`
4. Observe that IntelliSense fails to find the schema for the rest of the configuration options.

**Expected behaviour**

Autocomplete is populated with available configuration options for v0.6.0+ configs.

**Environment**

- Version: v0.6.0-alpha.2
- Environment: Windows, VScode

**Comment by zepatrik** [comment]
Right, sorry for that. The config schema moved but we forgot to update the release automation.

**Comment by aeneasr** [comment]
@zepatrik could you make a PR for this?
