### ISSUE TITLE
Implement session management endpoints

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#1346]
**Is your feature request related to a problem? Please describe.**

We need a couple of endpoints to allow us to manage an identity's session.

**Describe the solution you'd like**

* [ ] we need a global sessions API that allows us to list all sessions (with pagination!) `GET /sessions` at the admin endpoint.
* [ ] we must be able to get a specific session `GET /sessions/<id>` and also delete/revoke a session `DELETE /sessions/<id>`
* [ ] We should be able to see an identity's sessions (again at the admin endpoint) `GET /identities/<id>/sessions`

**Additional context**

These endpoints are needed to display and manage user sessions in the Ory Console.

**Comment by zepatrik** [comment]
I assume this is already tracked in #655?
