### ISSUE TITLE
Implement Password Strength Meter API

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#136]
**Is your feature request related to a problem? Please describe.**

The API should return a password strength ranging from 0.0 (weak) to 1.0 (strong) to support frontends with displaying a password-strength meter.

**Comment by Firstyear** [comment]
I'd recommend you look at zxcvbn as it also provides good feedback on how users can improve their passwords, and has js, go, rs, py and other implementations for client and server side validation.

**Comment by aeneasr** [comment]
Thanks! That looks pretty good. We're already checking against HIBP to find leaked passwords, but I think preventing certain patterns (aaa) is a good idea also.

**Comment by aeneasr** [comment]
https://github.com/nbutton23/zxcvbn-go

**Comment by evalsocket** [comment]
Anyone working on this ?

**Comment by aeneasr** [comment]
Not right now - we can discuss ideas tomorrow :)

**Comment by evalsocket** [comment]
@aeneasr can we write it as package in ory/x so that hydra can also use this route like health route

**Comment by aeneasr** [comment]
Hydra doesn't need this :)

**Comment by aeneasr** [comment]
I'm closing this because we went another route with password policies. We're using things like Levensthein Distance and HIBP API to find if a password is uncompromised and hard to guess.

**Comment by juliandroid** [comment]
Is it possible ory.sh/kratos/docs/concepts/security/ to be updated, since it references this ticket here?

**Comment by aeneasr** [comment]
Right, we could probably offer a binary API that runs the password validation against e.g. `{ "password": ... }` and returns either ok or the error.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
