### ISSUE TITLE
UiNode has invalid open schema

### ISSUE THREAD

**Issue by cortopy** [ory/kratos#1361]
**Describe the bug**

According to [openapi schema](https://github.com/ory/kratos/blob/867abfc813b08142786f71bfe28e373d4754c959/internal/httpclient/api/openapi.yaml#L3752) `UiNode` has a `messages` property defined as an array. However, this property is `null` when there are no messages

**Reproducing the bug**

1. Start kratos
2. Make a request to `/self-service/registration/api`
3. The UiNode nodes will have `null` messages

**Expected behavior**

Either kratos returns an empty array to comply with the spec, or the field is declared as `nullable` in the spec

**Environment**

- Version: v0.6.3-alpha.1
- Environment: Docker

**Comment by aeneasr** [comment]
Thank yopu for the report!

https://github.com/ory/kratos/pull/1362
