### ISSUE TITLE
corp package likely misplaced in go.mod

### ISSUE THREAD

**Issue by oliverpool** [ory/kratos#1363]
**Description**

I want to version the kratos build along my go project.

**Reproducing the bug**

1. Create a new go module
2. Create a `cmd/kratos/main.go` file, copy the content of the https://github.com/ory/kratos/blob/master/main.go file.
3. Build the kratos binary:
```
go: finding module for package github.com/ory/x/profilex
go: finding module for package github.com/ory/x/dbal
go: finding module for package github.com/ory/kratos/driver
go: finding module for package github.com/ory/kratos/cmd
go: found github.com/ory/kratos/cmd in github.com/ory/kratos v0.6.3-alpha.1
go: found github.com/ory/kratos/driver in github.com/ory/kratos v0.6.3-alpha.1
go: found github.com/ory/x/dbal in github.com/ory/x v0.0.238
go: found github.com/ory/x/profilex in github.com/ory/x v0.0.238
go: github.com/ory/kratos@v0.6.3-alpha.1 requires
	github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Expected behavior**

The build succeeds.

**Environment**

- go version go1.16.4 linux/amd64

**Additional context**

I think the following lines should be removed from `go.mod`

https://github.com/ory/kratos/blob/8ffd8247c9f781cb36ba18daff6510d3fa8e458d/go.mod#L12

https://github.com/ory/kratos/blob/8ffd8247c9f781cb36ba18daff6510d3fa8e458d/go.mod#L71

Since the `corp` package is already in the `github.com/ory/kratos` module, I think there is no need to add a `require` and `replace` directive.

**Comment by aeneasr** [comment]
This is a limitation of go modules right now - what you need to do is to have the SHA tag of e.g. the master branch in the go mod file and then run `go mod tidy`. [See example](https://github.com/ory/cli/blob/master/go.mod#L9)

**Comment by oliverpool** [comment]
Ah ok, I just saw that `github.com/ory/kratos/corp` is a module (since it has a specific `go.mod` file) - I assumed it was a package.

Why is it a module and not a package of `github.com/ory/kratos` ?

**Comment by aeneasr** [comment]
We have another package that has some stuff in it to make it work better with our cloud env, but is too specific to be useful for the OSS. This is the leanest way to achieve that (versus e.g. go plugins, ...)

**Comment by oliverpool** [comment]
Alright, thank you for your quick replies.

Adding the following to my `go.mod` fixed the initial issue:
```
replace github.com/ory/kratos/corp => github.com/ory/kratos/corp v0.0.0-20210518162551-d1b15217867c

replace github.com/ory/kratos-client-go => github.com/ory/kratos-client-go v0.6.3-alpha.1
```

---

However it still doesn't build :
```
go build ./...
# github.com/ory/kratos/persistence/sql
../../go/pkg/mod/github.com/ory/kratos@v0.6.3-alpha.1/persistence/sql/persister.go:154:8: model.Alias undefined (type *pop.Model has no field or method Alias)
```

Since it looks like a lot of headache for a minor gain, I will just download the compiled version :shrug:.

So you can consider this issue as closed (and thanks again for your quick replies!!)

**Comment by aeneasr** [comment]
Yeah you also need to take over the replaces from the go.mod in this project‘s root but I agree - it’s a lot of work to keep all this in sync. Unfortunately go modules and replaces don’t  go well together…

**Comment by oliverpool** [comment]
I just had an idea to refactor the `github.com/ory/kratos/corp` module to fix this issue :

- create a global var in the `corp` package called `DefaultContextualizer` which will be called by every global function
- remove the `go.mod` file to make it a simple package and remove the replace directive.

If you want to customize it for your own "cloud env", you just have to set a custom `corp.DefaultContextualizer` in some `init` function.

If you agree that this is a leaner solution that the current situation, I can craft a PR.

**Comment by aeneasr** [comment]
Good idea! We could also solve this using context in the cmd package! Unfortunately this won’t work for internal/httpclient which is the SDK generated by openapi-generator and needs to match the openapi spec 1:1 while also mirroring the published SDK at kratos-client-go. :/

**Comment by aeneasr** [comment]
I've worked on this as best as possible - most of the replace requirements are dropped now. We still however need one for the kratos-client-go. Due to the structure of ory/cli this can unfortunately not circumvented.

Closing :)

**Comment by oliverpool** [comment]
Thank you for your work on this!
