### ISSUE TITLE
Feat: Hash type detection improvements

### ISSUE THREAD

**Issue by harnash** [ory/kratos#1378]
**Background**

This is the follow-up of the discussions in #1332. As mentioned in that PR it would be nice to not rely on the hash format (prefix/ID etc.) to determine the type of the hash. Since not all hash algorithms uses [Modular Crypt Format](https://cryptopp.com/wiki/Modular_Crypt_Format) or [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) and comparing some arbitrary prefixes is risky and not straightforward it would be nice to have a better solution.

**Proposal**

Ideally it would be to keep the information about the type of the hash in the credentials config. This would cleanup the code and allow some other operations to be done easily on the hashes (statistics, audits, etc.). It would also allow cleaner implementation of some legacy hashers and perhaps help with #605.

**Comment by aeneasr** [comment]
We now support PHC

**Comment by aeneasr** [comment]
Sorry, misread the issue. Still closing though due to lack of (public) interest.
