### ISSUE TITLE
Basic SMTP Connection to MailHog doesn't work

### ISSUE THREAD

**Issue by CMCDragonkai** [ory/kratos#1387]
**Describe the bug**

Described the bug here: https://github.com/ory/kratos/issues/781#issuecomment-851766787

However this is different as the SMTP itself isn't working with no errors.

**Reproducing the bug**

Using:

```
courier:
  smtp:
    connection_uri: smtp://127.0.0.1:1025
```

And running MailHog with:

```
MailHog -smtp-bind-addr 127.0.0.1:1025 -ui-bind-addr 127.0.0.1:8025 -api-bind-addr 127.0.0.1:8025
```

Results in no verification emails being sent and no errors reported either.

However if I use:

```
mailsend \
    -to target@target.com \
    -from me@me.com \
    -port 1025 \
    -smtp 127.0.0.1 \
    -sub test \
    -M "test message"
```

The message appears and I get proper logs on MailHog.

![image](https://user-images.githubusercontent.com/640797/120270033-3dcf5380-c2ec-11eb-9281-08e9c2b5fdc7.png)

The rest of the configuration is the same as the quickstart https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password/kratos.yml

I'm running this on NixOS with the latest version: https://github.com/MrMebelMan/nixpkgs/blob/40d02e732df187c03f6e8956db8f60a66885d89c/pkgs/applications/misc/kratos/default.nix

**Expected behavior**

Expect an email to be received or at the very least some useful logs as to why no email is being sent.

**Comment by aeneasr** [comment]
You’re probably missing the —watch-courier flag or are not running the courier job
