### ISSUE TITLE
DetermineNetwork method always try to migrate DB when booting up

### ISSUE THREAD

**Issue by upgle** [ory/kratos#1399]
**Describe the bug**

I am using a MySQL cluster managed by DBA, and migrating the DB manually.
I've discovered a potential issue in the code that could lead to one unintended DB migration.

I think Kratos and Ory ecosystem should provide an option to turn off this auto migration.

https://github.com/ory/kratos/blob/4e2b1fe7f45e7b54e64c4bcd58f5700dd9b9d214/driver/registry_default.go#L510
https://github.com/ory/kratos/blob/4e2b1fe7f45e7b54e64c4bcd58f5700dd9b9d214/persistence/sql/persister.go#L75

In this code, migration is performed whenever the application determines the network.
If multiple instances are deployed, migration will be attempted on all instances.

```go
func (p *Persister) DetermineNetwork(ctx context.Context) (*networkx.Network, error) {
        // migration is performed here
	if err := p.p.MigrateUp(ctx); err != nil {
		return nil, err
	}
	return p.p.Determine(ctx)
}
```

**Expected behavior**

Provide an option to disable it.

**Comment by aeneasr** [comment]
Thank you for the report! This migrates a table needed by the other schemas but it probably should indeed be manual anyways!

**Comment by upgle** [comment]
@aeneasr 
Thank you for your fast feedback 👍 

I think the kratos-migrate is a good tool to do this job.
https://www.ory.sh/kratos/docs/cli/kratos-migrate/


And if user use the in-memory type, kratos can migrate on every start.
```go
// if dsn is memory we have to run the migrations on every start
if dbal.IsMemorySQLite(m.Config(ctx).DSN()) || m.Config(ctx).DSN() == dbal.SQLiteInMemory || m.Config(ctx).DSN() == dbal.SQLiteSharedInMemory || m.Config(ctx).DSN() == "memory" {
	m.Logger().Infoln("Ory Kratos is running migrations on every startup as DSN is memory. This means your data is lost when Kratos terminates.")
	if err := p.MigrateUp(ctx); err != nil {
		m.Logger().WithError(err).Warnf("Unable to run migrations, retrying.")
		return err
	}
}
```
