### ISSUE TITLE
Method `whoami` is changed to `toSession`?

### ISSUE THREAD

**Issue by hbrls** [ory/kratos#1405]
**Describe the bug**

As far as I can guess from the source code in node_modules, the method `whoami` was change to `toSession`. Where is the open source code of `kratos-client`? Where is the doc or example for the new `toSession` method?

**To Reproduce**

**Expected behavior**

**Environment**

`@ory/kratos-client: 0.6.3-alpha.1`

**Additional context**

**Comment by aeneasr** [comment]
We merged a patch which introduces both session token as well as session cookie capabilities! This will be included in the next release. Thank you for the report :)
