### ISSUE TITLE
Better support for custom provider

### ISSUE THREAD

**Issue by adamkissvcc** [ory/kratos#1410]
**Is your feature request related to a problem? Please describe.**

Currently it's very hard to add a custom provider without forking Kratos. 

**Describe the solution you'd like**

I would like the providers to "register themselves" in an init() function, instead of the current `func (c ConfigurationCollection) Provider`.

in provider_config.go:
```go
var Providers = map[string]func(config *Configuration, public *url.URL)Provider{}

func (c ConfigurationCollection) Provider(id string, public *url.URL) (Provider, error) {
	for _, p := range c.Providers {
		if newProvider, ok := Providers[p.ID]; ok {
			return newProvider(&p, public), nil
		}

		providerNames := make([]string, 0, len(Providers))
		for pName := range Providers {
			providerNames = append(providerNames, pName)
		}

		return nil, errors.Errorf("provider type %s is not supported, supported are: %v", p.Provider, providerNames)
	}

	return nil, errors.WithStack(herodot.ErrNotFound.WithReasonf(`OpenID Connect Provider "%s" is unknown or has not been configured`, id))
}
```

in provider_*.go (eg: provider_slack.go)
```go
func init() {
	Providers["slack"] = NewProviderSlack
}

func NewProviderSlack(
	config *Configuration,
	public *url.URL,
) Provider {
	return &ProviderSlack{
		config: config,
		public: public,
	}
}
```

**Additional context**

This would be one step forward for making kratos more pluggable :) . I would be happy to write up a merge request if you are ok with this approach.

**Comment by aeneasr** [comment]
That makes a lot of sense to me :)

**Comment by nanikjava** [comment]
@aeneasr any pointer to point me in the right direction to work on this ?

**Comment by aeneasr** [comment]
I think the OP has some good context, what help specifically are you looking for?

**Comment by nanikjava** [comment]
> I think the OP has some good context, what help specifically are you looking for?

For a start I think what is the behaviour that is expected from the custom provider in terms of initialisation process.

**Comment by bcordobaq** [comment]
@aeneasr @vinckr Do you have any plans to reconsider this feature? Is there something available?
