### ISSUE TITLE
Separate OpenAPI tags into stable and experimental and rework admin strategy

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#1424]
# Proposal

In order to provide a more stable and better SDK experience, we are looking to refactor the SDK methods.

## Why

Why do we want to make this change?

### OpenAPI Tags

Currently, the SDK is structured into tags `public` and `admin`. This stems from the fact that we have two ports in Ory Kratos - one administrative and one public port.

While serves as a good overview when working with Ory Kratos, it does not express:

- What module the API belongs to (e.g. self-service, identity, ...)
- What maturity the API has (e.g. experimental, alpha, beta, ...)
- What version the API has (e.g. v0alpha0, v1beta0, ...)

#### Solution: Use Tags for Versioning

As a first, we would like to propose that the current `admin` and `public` tags are replaced with a versioned approach indicating the maturity of the API used. For example, `initializeSelfServiceSettingsForBrowsers` would no longer be under the `public` tag but instead under the `v0alpha1` tag:

```patch
 import {
   Configuration,
-  PublicApi
+  V0Alpha1
 } from '@ory/kratos-client';

- const kratos = new PublicApi(new Configuration({ basePath: config.kratos.public }));
+ const kratos = new V0Alpha1(new Configuration({ basePath: config.kratos.public }));
```

This in turn requires creation of two instances if both public and admin SDKs should be available:

```patch
import {
  Configuration,
-  PublicApi
+  V0Alpha1
} from '@ory/kratos-client';

- const kratosPublic = new PublicApi(new Configuration({ basePath: config.kratos.public }));
- const kratosAdmin = new PublicApi(new Configuration({ basePath: config.kratos.admin }));
+ const kratosPublic = new V0Alpha1(new Configuration({ basePath: config.kratos.public }));
+ const kratosAdmin = new V0Alpha1(new Configuration({ basePath: config.kratos.admin }));
```

This *will be confusing* to newcomers as @zepatrik has [pointed out](https://github.com/ory/kratos/issues/1424#issuecomment-861395873). For the SaaS however, this would be straight forward:

```js
import {
  Configuration,
  V0Alpha1
} from '@ory/ory-client';

const ory = new V0Alpha1(new Configuration({ apiToken: '...', basePath: '...' }));
```

### Using the Wrong Endpoint

Some users use the wrong port which leads to 404 errors. There have been several reports related to this and it is also the sentiment in [@zepatrik's comment](https://github.com/ory/kratos/issues/1424#issuecomment-861395873).

#### Solution: Redirects

To avoid accidentally using the wrong port [as pointed out in @zepatrik's comment](https://github.com/ory/kratos/issues/1424#issuecomment-861395873) we could return an error, or even do a redirect, to the correct port if we detect that a public request goes to the admin port or vice versa.

```
GET /identities
Host public.kratos.com

HTTP 307
Location: admin.kratos.com/identities
```

### Ory SaaS

The Ory SaaS does not know different ports for the API capabilities (admin/public) but instead relies on a reverse proxy that differentiates by path:

- `/api/kratos/admin` - admin port
- `/api/kratos/public` - public port

As such, having `public` and `admin` tags does not make sense for the SaaS system. To keep semantic parity between SaaS and open source we want to therefore change the naming.

#### Solution: Prefix Methods

All administrative functions require, in the Ory SaaS, authorization using e.g. an Ory Personal Access Token. In the open source, we do not know what developers use to protect their APIs. As such, we believe that it is ok to have admin and public functions under one common API and differentiate with an `admin` prefix:

```patch
 import { 
- AdminApi, 
+ V0Alpha1,
   Configuration
 } from '@ory/kratos-client';

-const kratos = new AdminApi(new Configuration({ basePath: config.kratos.admin }));
+const kratos = new V0Alpha1(new Configuration({ basePath: config.kratos.admin }));

-kratos.createIdentity({
+kratos.adminCreateIdentity({
   schema_id: 'default',
   traits: { /* ... */ }
 })
```

### Names and Parameters

Parameters, responses, and models have vastly different naming conventions. We would like to propose one common standard to make the SDK use consistent.

For parameters, we often have something like this:

```go
// nolint:deadcode,unused
// swagger:parameters submitSelfServiceVerificationFlow
type submitSelfServiceVerificationFlow struct {
	// The Registration Flow ID
	//
	// The value for this parameter comes from `flow` URL Query parameter sent to your
	// application (e.g. `/registration?flow=abcde`).
	//
	// required: true
	// in: query
	Flow string `json:"flow"`

	// in: body
	Body submitSelfServiceVerificationFlowBody
}

// nolint:deadcode,unused
// swagger:model submitSelfServiceVerificationFlowBody
type submitSelfServiceVerificationFlowBody struct {
	// Method supports `link` only right now.
	//
	// enum:
	// - link
	// required: true
	Method string `json:"method"`

	// Email is the email to which to send the verification message to.
	//
	// required: true
	Email string `json:"email"`
}

// swagger:route POST /self-service/verification public submitSelfServiceVerificationFlow
```

This leads to pretty ugly SDKs:

```go
	flow, _, err = client.PublicApi.
		SubmitSelfServiceVerificationFlowExecute(ory.PublicApiApiSubmitSelfServiceVerificationFlowRequest{}.
			Flow(flow.Id).
			SubmitSelfServiceVerificationFlowBody(
				ory.SubmitSelfServiceVerificationFlowBody{
					Email: email, Method: "link"}))
```

Ideally, we would want something like this:

```go
	flow, _, err = client.PublicApi.
		SubmitSelfServiceVerificationFlow().Body(client.SubmitSelfServiceVerificationFlow{Email: email, Method: "link"})
```

but it does not appear to be possible to do that right now.

#### Solution: Don't Prefix Model/Request Names

We can disable prefixing in the Go generator which would make this a bit easier to read:

```go
	flow, _, err = client.PublicApi.
		SubmitSelfServiceVerificationFlowExecute(ory.SubmitSelfServiceVerificationFlowRequest{}.
			Flow(flow.Id).
			SubmitSelfServiceVerificationFlowBody(
				ory.SubmitSelfServiceVerificationFlowBody{
					Email: email, Method: "link"}))
```

#### Solution: Do not Append Body to Model

We can omit the `Body` in `// swagger:model submitSelfServiceVerificationFlowBody` so it becomes:

```go
	flow, _, err = client.PublicApi.
		SubmitSelfServiceVerificationFlowExecute(ory.SubmitSelfServiceVerificationFlowRequest{}.
			Flow(flow.Id).
			SubmitSelfServiceVerificationFlow(
				ory.SubmitSelfServiceVerificationFlow{
					Email: email, Method: "link"}))
```

### Security Controls

Ory Kratos has several security controls in place:

- Ory Personal Access Tokens (SaaS way of accessing the admin endpoints / usually global)
- Ory Kratos Session Cookie (for self-service)
- Ory Kratos Session Token (for self-service)

These are currently all mixed up.

#### Solution: Differentiate between Permanent and Per-Request

Permanent security credentials (e.g. used to access the admin api) should be global:

```
const kratosAdmin = new V0Alpha1(new Configuration({ basePath: config.kratos.admin, accessToken: 'some-token' }));

kratosAdmin.adminCreateIdentity({
  schema_id: 'default',
  traits: { /* ... */ },
});
```

But per-request credentials (e.g. session cookie / token) should be per request:

```
public getSelfServiceRegistrationFlow(id: string, cookie?: string, options?: any) {}

public getSelfServiceSettingsFlow(id: string, xSessionToken?: string, cookie?: string, options?: any) {}
```

**Comment by zepatrik** [comment]
The separation of public/admin endpoints will still be kept right? So `client.StableApi.AdminCreateIdentity` and `client.StableApi.GetSelfServiceLoginFlow` will be on the same client, but one will error because the endpoint is wrong? I am not sure if that is very intuitive, it feels more like we will get :100: issues regarding mixed up endpoints...
Or how do you want to separate between endpoint privilege with regard to the proposal?

**Comment by aeneasr** [comment]
Yes, but that's the case with the current SDK as well, as described in the issue above

**Comment by aeneasr** [comment]
This will have to be solved another way, for example Ory Kratos detecting if there's an admin API request coming in on public and redirecting to the correct endpoint. This would have to be configurable.

For Ory this is not an issue as we prefix the paths with admin/public and have a swagger spec reflecting that.

**Comment by aeneasr** [comment]
Additionally, the following things should be considered:

**toSession**

This feels very wonky:

```
  kratos.toSession(undefined, req.cookies['ory_kratos_session']).then(({ data: session })
```

I think this was better before:

```
  kratos.whoami(
    req.header("Cookie"),
    req.header("Authorization"),
  )
```

**getSelfServiceSettingsFlow**

Does currently not support session cookies on the public interface

**createSelfServiceLogoutUrlForBrowsers**

This also feels wonky - can't we just forward all the headers?

```
createSelfServiceLogoutUrlForBrowsers(req.cookies['ory_kratos_session']).
```

**Comment by aeneasr** [comment]
Keeping this for backup:




---

**Is your feature request related to a problem? Please describe.**

In order to bring parity into ory and ory kratos and better visibility into what APIs are in what stage we should deprecate the admin / public keywords and instead replace them with e.g. `alpha`, `beta`, and `stable`.

Currently, the usage is as follows:

```go
// public
	conf := kratos.NewConfiguration()
	conf.Servers = kratos.ServerConfigurations{{URL: "https://public.kratos"}}
	conf.HTTPClient = client
	client := kratos.NewAPIClient(conf)

	flow, _, err := client.PublicApi.GetSelfServiceLoginFlow(context.Background()).Id(flowID).Execute()

	// This will error because wrong server url
	// _, _, err := client.AdminApi.CreateIdentity().Execute()

// admin
	conf := kratos.NewConfiguration()
	conf.Servers = kratos.ServerConfigurations{{URL: "https://admin.kratos"}}
	conf.HTTPClient = client
	client := kratos.NewAPIClient(conf)

	_, _, err := client.AdminApi.CreateIdentity().Execute()

	// This will error because wrong server url
	// flow, _, err := client.PublicApi.GetSelfServiceLoginFlow(context.Background()).Id(flowID).Execute()
```

This is analogous to other SDKs. I think that the tags are not really helpful here because we have to create two SDK instances anyways as openapi doesn't support an API with multiple endpoints. So this would make more sense:

```go
// admin
	conf := kratos.NewConfiguration()
	conf.Servers = kratos.ServerConfigurations{{AdminUrl: "https://admin.kratos", PublicUrl: "https://public.kratos"}}
	conf.HTTPClient = client
	client := kratos.NewAPIClient(conf)

	flow, _, err := client.PublicApi.GetSelfServiceLoginFlow(context.Background()).Id(flowID).Execute()
	_, _, err := client.AdminApi.CreateIdentity().Execute()
```

However, that's simply not possible with openapi right now!

**Describe the solution you'd like**

To better indicate which APIs are at what stage I propose to repurpose the tags and also rename some of the methods:


```go
	conf := kratos.NewConfiguration()
	conf.Servers = kratos.ServerConfigurations{{URL: "https://admin.kratos"}}
	conf.HTTPClient = client
	adminClietn := kratos.NewAPIClient(conf)

	_, _, err := client.StableApi.AdminCreateIdentity()
	
	// This will still error because wrong server url but at least now we know what state the API is in.
	flow, _, err := client.AlphaApi.GetSelfServiceLoginFlow(context.Background()).Id(flowID).Execute()
```

**Comment by harnash** [comment]
One thing to consider is the fact that having `admin` and `public` APIs on a separate port makes it pretty trivial to not expose `admin` api externally and keep it only available internally (just do not expose admin port to the public). I'm not really sure it is doable on k8s at the moment without some custom Ingress setup. Basically the whole routing in k8s relies on the ports exposed. Of course one still could hide `admin` APIs via some kind of Proxy or on the edge logic but it is not as solid as having this separated by a port.  Not sure if average cloud setup has all the pieces needed to secure this API properly.

**Comment by aeneasr** [comment]
So there is no plan to change that, this is only about the SDK. Everything else stays the same. In our cloud env, we use oathkeeper to protect admin APIs.

**Comment by harnash** [comment]
Oh. OK. That is good 👍🏻 Looking at the SDK changes I think it is going in good direction. Should help with distinguishing admin/public APIs.
👍🏻 for the API versioning!

**Comment by zhming0** [comment]
I agree with most of the changes 👍🏿 👍🏿 . 

Only have two cents on these two topic:

## API version & maturity tag

I don't find this an issue. Given the nature of the product (headless auth provider), I believe all users would have to read the doc before using any API. The doc can simply mentions the maturity and the coder decide whether to use it. 

For the SaaS, I am a bit unsure how it works with this. When would a customer upgrade their code to use the correct tag? Or are you going to allow different customer running different versions of Kratos? 

## `client.adminCreateIdentity` vs `adminClient.createIdentity`

I understand from SaaS's stand point, admin and public API has the same infrastructure entrypoint. 
However, I'd argue that users would consider admin API and public API as separate services cognitively regardless of OSS or SaaS.

So these two ways of tagging are logically equivalent to users. 
I personally think the current way is a bit clearer.

**Comment by aeneasr** [comment]
Thank you for the feedback! I agree with your sentiment regarding API services.

Our idea was to make it explicit in the SDKs that the methods used are, for example, in alpha stage. This kinda follows the Google / Kubernetes [practice of versioning SDKs](https://github.com/googleapis/google-cloud-go/tree/master/assuredworkloads/apiv1beta1). @zepatrik and I had a discussion about this today as well. What we would like to have, would be something like this:

```
import "github.com/ory/kratos-client-go/identity/v0alpha1"
// import "github.com/ory/kratos-client-go/identity/v0alpha2"
// import "github.com/ory/kratos-client-go/identity/v0beta1"

// ...

service := identity.NewService()
service.CreateIdentity(identity.CreateIdentity{ /* ... */ })
```

From our point of view, that would be superior to all other approaches as it also differentiates between what's admin, what's public, and so on.

Unfortunately, the current tech stack (Go Swagger, OpenAPI 3.0, openapi-generator) do not support this type of SDK generation - neither for Go nor any other programming languages like NodeJS, Ruby, ...

So we're caught in the middle. Do we prioritize versioning? Or modules? Or API services? Unfortunately, we can't use multi-tags in OpenAPI 3.0 - or rather we can, but it offers no benefit except lots of duplication!

So right now, we kind of end up with an experience like so:

```
// endpoint can be both public or admin endpoint! Ory Kratos redirects routes that end up at public, but are available on admin, automatically to admin with a 307 redirect.
func NewSDKForSelfHosted(endpoint string) *ory.APIClient {
	conf := ory.NewConfiguration()
	conf.Servers = ory.ServerConfigurations{{URL: endpoint}}
	cj, _ := cookiejar.New(nil)
	conf.HTTPClient = &http.Client{Jar: cj}
	return ory.NewAPIClient(conf)
}

// ...
	identity, _, err := client.V0alpha0Api.AdminCreateIdentity(ctx).
		AdminCreateIdentityBody(ory.AdminCreateIdentityBody{
			SchemaId: "default",
			Traits: map[string]interface{}{
				"email": "dev+" + x.NewUUID().String() + "@ory.sh",
			},
		}).Execute()
```

Since we're adding lots of tests now this would theoretically allow us to catch any breaking changes and elevate the API versions. Assuming `AdminCreateIdentity` changes in a breaking way, the version would be bumped. When upgrading the SDK dependency you would easily catch this because `AdminCreateIdentity` no longer is available at `V0alpha0Api` but only `V0alpha1Api`.

In the future, we would like to keep the old versions around as well. Meaning, that the old behavior still works unless the upstream API has breaking changes. We currently don't have the pipeline for that though.

For those reasons, we believe that versioning the SDKs would be more advantageous than having admin/public tags!

**Comment by zhming0** [comment]
now I understand the necessity of version tagging. 

Hmm, what if we don't tag the stable APIs and only tag the alpha/beta APIs? 

e.g. 

```
adminClient.createIdentity
adminClient.createIdentity_beta_v1
adminClient.createIdentity_alpha_v0
```

Seems to achieve the same goal, less trouble for most of the users?

**Comment by aeneasr** [comment]
Thank you for the idea! I looked into this idea but there are several issues:

1. Some code-generators do not allow underscores in function names or produce code which does not pass linting (including Golang)
2. Generators will create function calls like
    ```go
	identity, _, err := client.AdminApi.V0alpha0ApiCreateIdentity(ctx).
		V0alpha0ApiAdminCreateIdentityBody(ory.V0alpha0ApiAdminCreateIdentityBody{
			SchemaId: "default",
			Traits: map[string]interface{}{
				"email": "dev+" + x.NewUUID().String() + "@ory.sh",
			},
		}).Execute()
    ```
   making it really hard to read the methods

So I fear we're stuck with the approach proposed in https://github.com/ory/kratos/issues/1424#issuecomment-871353361 for now :/
