### ISSUE TITLE
SMTP Connection URI is not valid

### ISSUE THREAD

**Issue by noliva** [ory/kratos#1435]
**Describe the bug**

AWS SES generates an invalid password for the SMTP connection string.

**Reproducing the bug**

Get a password that contains the `/` character.

For example: 

`smtps://user:BDdPhDS7HGEfacMJrPmg3pDB8zoQ/InsMgsSnJsY9o7f+Ue@email-smtp.eu-west-1.amazonaws.com:587?skip_ssl_verify=false`

**Expected behavior**

It probably should not check weather the SMTP connection string is a URI or a String

**Environment**

- Version: v0.6.0

**Additional context**

When changing the `.schema/config.schema.json` `connection_uri.type` to string it works.

**Comment by aeneasr** [comment]
We can change it to string, maybe it makes sense though to include a pattern which matches `smtp://|smtps://`? Would you be open to a PR?
