### ISSUE TITLE
fix: settings flow error handle should access schemas using configured "local" URLs instead of public URLs

### ISSUE THREAD

**Issue by jertel** [ory/kratos#1448]
### Discussed in https://github.com/ory/kratos/discussions/1373

<div type='discussions-op-text'>

<sup>Originally posted by **jertel** May 23, 2021</sup>
The issue I'm seeing involves Kratos, running in a container, attempting to access schemas via the public URL. `Persister.injectTraitsSchemaURL()` concatenates the schema ID (Ex: `default`) to the configured public self-service URL (specified in the configuration file). Then in error scenarios, such as attempting to change your password to an invalid value, the settings flow's `error.go` handler attempts to sort the traits for an improved UI experience. But that sorting also requires loading the schema, and it does so via `LoadURL()`, from within `GetKeysInOrder()` (in `schema.go`). Since the Kratos process now attempts to access this public self service URL with the concatenated schema ID, it can run into problems if the container does not have the right CAs or DNS or network routes defined to access the public URL (for example when it's running behind a reverse proxy).

Instead of the Kratos process itself trying to lookup schemas via the concatenated public URL, would it be better to have it load the URLs listed in the configuration, under the `identity` block?

```
identity:
  default_schema_url: file:///kratos-conf/schema.json
```
</div>

**Comment by aeneasr** [comment]
Thank you! 

Is also #1448
