### ISSUE TITLE
SDK for JS

### ISSUE THREAD

**Issue by FlockOfBirdz** [ory/kratos#1460]
Hi, I am using Vuejs to develop self-service-ui UI node as a single-page web-application and there is no clear documentation for JS SDK on its npm page (https://www.npmjs.com/package/@ory/kratos-client) or Kratos self-service-ui git-hub page. Please help me with the usage of this SDK and how to use it for manage requests. Thanks a million.

**Comment by vinckr** [comment]
Hey @FlockOfBirdz,
we provide the auto generated SDKs for the community to use. We generally dont use them ourselves. As such we can't provide more comprehensive documentation apart what is coming from the community. 

That being said I want to support you in any way possible to get this going. 
We can collaborate on starting some documentation for this SDK. 
Maybe the [REST API reference](https://www.ory.sh/kratos/docs/next/reference/api/) can also help a bit.
Did `npm install @ory/kratos-client@v0.6.3-alpha.1 --save` run correctly?

**Comment by FlockOfBirdz** [comment]
Hey @vinckr, Thanks for your response. Actually, I guess your [REST API refrence](https://www.ory.sh/kratos/docs/next/reference/api/) link was broken but now it is working fine. I prefer to use my own requests instead of SDK to communicate with Kratos but I couldn't find any documentation for how to write my own requests. I guess your REST API reference could help about that so thanks a lot.
