### ISSUE TITLE
Document new CSRF Cookie requirement

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#1472]
**Is your feature request related to a problem? Please describe.**

https://github.com/ory/kratos/pull/1458 introduces the new CSRF requirement which is not documented yet.

**Comment by pingiun** [comment]
I was just looking at this and I found that the csrf token cookie is always set on the path based on the [public url](https://github.com/ory/kratos/blob/d2b1fce9f1b817a99fa2f134c90f79e6a2d2b601/x/nosurf.go#L136). This means that only sub paths of the kratos public url can access the cookie and thus initiate login/other flows. 

Is this intended behaviour? I think it would be nice to allow self service UIs to live on other paths.

**Comment by aeneasr** [comment]
Ah yeah we definitely need to update that!

**Comment by aeneasr** [comment]
Would you be up for a PR? I think it would be similar to what we do with the session thing. Maybe we can also just reuse the session config
