### ISSUE TITLE
CI task to fully delete pre releases; remove pre tags from config schema

### ISSUE THREAD

**Issue by asnelling** [ory/kratos#1485]
**Describe the bug**

When writing a `kratos.json` configuration file in VS Code using the [schema file](https://raw.githubusercontent.com/ory/kratos/master/.schema/version.schema.json), the IDE complains:

> Problems loading reference 'https://raw.githubusercontent.com/ory/kratos/v0.5.3-alpha.1.pre.0/.schema/config.schema.json': Unable to load schema from 'https://raw.githubusercontent.com/ory/kratos/v0.5.3-alpha.1.pre.0/.schema/config.schema.json': Request vscode/content failed unexpectedly without providing any details.

**Reproducing the bug**

1. Create a [kratos.json](https://www.ory.sh/kratos/docs/reference/configuration) in a new VS Code workspace. Here's mine so far (ignore that it's incomplete):

    ```json
    {
      "version": "v0.6.3-alpha.1",
      "identity": {
        "default_schema_url": "file://identity.schema.json"
      },
      "dsn": "sqlite://kratos.sqlite?_fk=true&mode=rwc"
      ...
    }
    ```

2. Insert the following into the workspace settings under `.vscode/settings.json`:

    ```json
    {
      "json.schemas": [
        {
          "fileMatch": ["kratos.json"],
          "url": "https://raw.githubusercontent.com/ory/kratos/master/.schema/version.schema.json"
        }
      ]
    }
    ```

3. Go back to `kratos.json` and observe VS Code report the above error.

**Expected behavior**

The entire schema should be available for download by IDEs.

# Solution

Create a git tag pointing to [the v0.5.3-alpha.1.pre.0 commit](https://github.com/ory/kratos/commit/0de4f93eb50b414f2eed4b0b013813170be9bc31), then the schema URL that VS Code complains about will resolve.

**Comment by zepatrik** [comment]
The `pre` tags are just pre-releases that we use to test the release process. They should be deleted afterwards again, but you are right they are still part of the config schema. Will fix that by removing them from the config meta schema. Or if you want to take that on?

**Comment by asnelling** [comment]
Understood. I'll put in a pull request

**Comment by aeneasr** [comment]
@zepatrik this needs to be done in the schema config automation tool right?

**Comment by zepatrik** [comment]
Well in the automation we add the pre release, but we delete them manually right? So we maybe should setup a GH action with a manual trigger to delete a pre relase that does all the necessary steps?

**Comment by aeneasr** [comment]
It would be easier to just not generate them on pre tags imo

**Comment by aeneasr** [comment]
Or do you think that could break releases?

**Comment by zepatrik** [comment]
Hm probably not, we'll see I guess :sweat_smile: at least we will not be able to check whether the release pipeline correctly appends the new version.

**Comment by aeneasr** [comment]
Yeah that makes sense ...

**Comment by asnelling** [comment]
It looks like pre-release tags are no longer added to the schema in CI (see below).

https://github.com/ory/cli/blob/6cef594bc4e702521ac4ba76df2dca95971baa88/cmd/dev/schema/render_version.go#L32-L40

This one must have gotten inserted before that snippet of code was added, so manually removing this one should suffice.

**Comment by zepatrik** [comment]
Oh I see, thanks a lot for looking into that. I guess we will then not automate that :sweat_smile: 
and it was me who added that :see_no_evil: https://github.com/ory/cli/commit/24f84742ba29a0f137234d6a83cef57f5e544bc0

**Comment by aeneasr** [comment]
😆
