### ISSUE TITLE
Seprate out login & registeration POST hooks

### ISSUE THREAD

**Issue by evalsocket** [ory/kratos#149]
**Is your feature request related to a problem? Please describe.**
In current Implementation we are using common post hooks for login & registration. in #139 we face same issue where we have to implement POST hook for only login not for registration. Currently we use a blank `ExecuteRegistrationPostHook` but that is extra ideally we have to handle it separately    

**Describe the solution you'd like**

each hook should be handled individually. [registry_default_login.go](https://github.com/ory/kratos/blob/master/driver/registry_default_login.go#L19-L26)
instead of using the `postHook` interface here, we should just iterate over `[]interface` which has all of the hooks, and then do a type assertion

**Describe alternatives you've considered**

**Additional context**

**Comment by evalsocket** [comment]
one solution can be this 

```
#registry_default_login.go
func (m *RegistryDefault) PostLoginHooks(credentialsType identity.CredentialsType) []login.PostHookExecutor {
	a := m.hooksPost(credentialsType, m.c.SelfServiceLoginAfterHooks(string(credentialsType)))
        a = append(a,hook.NewSessionDestroyer(m))
        b := make([]login.PostHookExecutor, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}
# registry_default_registration.go
func (m *RegistryDefault) PostRegistrationHooks(credentialsType identity.CredentialsType) []registration.PostHookExecutor {
	a := m.hooksPost(credentialsType, m.c.SelfServiceRegistrationAfterHooks(string(credentialsType)))
        // add hooks if any in case of registration
	b := make([]registration.PostHookExecutor, len(a))
	for k, v := range a {
		b[k] = v
	}
	return b
}
```
Default registry hook only have common hooks like redirect and sessionIssuer

**Comment by nmlc** [comment]
@evalsocket can I grab this one? Seems like small enough issue to start with :)

**Comment by evalsocket** [comment]
@nmlc discuss it with @aeneasr before starting.
