### ISSUE TITLE
docs: fix warning message not correctly formatted

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1519]
**Describe the bug**

Fix docs on this page: https://www.ory.sh/kratos/docs/concepts/credentials/username-email-password

![image](https://user-images.githubusercontent.com/41120635/125160770-0a9ba200-e17f-11eb-92e5-9918a0fe6a3d.png)

**Comment by aeneasr** [comment]
Already resolved: https://www.ory.sh/kratos/docs/next/concepts/credentials/username-email-password/
