### ISSUE TITLE
Quickstart - latest version 0.7 does not work

### ISSUE THREAD

**Issue by lanphan** [ory/kratos#1537]
**Describe the bug**

When I first try to download and run Kratos quick start, it's version 0.6.3 and it works well.
However, I updated source code yesterday and tried again with version 0.7, but it didn't work:
* All containers started ok
* When I visit 127.0.0.1:4455, it keeps redirect to :4433/self-service/login/browser and back to :4455/auth/login?flow=<flow-id> repeatedly then blocked by Chrome due to max 10 redirect hops --> seems cookie is not recognized

I did checkout again old version, tag 0.6.3 (question: why tag 0.6.3 but docker image used here using version 0.6.2?), everything works fine with same docker-compose.

Command to run:
docker-compose -f quickstart.yml -f quickstart-standalone.yml -f quickstart-mysql.yml up --build --force-recreate

**Reproducing the bug**

Follow Quick start document with latest code

_Server logs_

_Server configuration_

**Expected behavior**

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
Thank you for the report, looks like the ui image wasn't properly updated!

**Comment by lanphan** [comment]
thank @aeneasr, it works now.
