### ISSUE TITLE
Field validation answer status code 422 instead of 400 

### ISSUE THREAD

**Issue by lucassimon** [ory/kratos#1559]
**Is your feature request related to a problem? Please describe.**

When I submit a register, for example, if I send an invalid email or weak password the api responses the status_code 400 and the messages are in the follow json:

```
"nodes": [
  {
    "attributes": {},
    "group": "string",
    "messages": [
    {
      "context": { },
      "id": 0,
      "text": "password length >= 1",
      "type": "string"
    }
],
```

Another case is when I submit a register, for example, and the kratos validates that indentity already exists. It responds the status_code 400 too

``` 

"ui": {
  "action": "string",
  "messages": [
    {
      "context": { },
      "id": 0,
      "text": "This email/identity id/username already exists .....",
      "type": "string"
    }
],
``` 

**Describe the solution you'd like**

My propose is just changing the status code for field validations and the unsuccessful operation continues with 400. In this way I can separate the exceptions:

```rails
def register(flow_id, email, password)
  path = 'self-service/registration/'

  client.post(
    path,
    {
      body:{ 
        schema_id: 'default',
        method: 'password',
        password: password,
        traits: {
          email: email
        }
      }.to_json,
      query: {
        flow: flow_id
      }
    }
  )
rescue Minato::Kratos::UnprocessableEntity => e
  message = 'Email or password invalid'
  details = nil
  raise ApiExceptions::UnprocessableEntity.new(message, e.code, e.body, details)
rescue Minato::Kratos::BadRequest => e
  message = 'Identity arealdy exists'
  details = nil
  if e.body[:ui][:messages]
    message = 'Identity arealdy exists'
    details = e.body[:ui][:messages]  
  end
  raise ApiExceptions::BadRequest.new(message, e.code, e.body, details)
rescue Minato::Kratos::InternalServerError => e
  message = 'An error occurred when register user.'
  details = nil
  raise ApiExceptions::InternalServerError.new(message, e.code, e.body, details)
end
``` 

**Additional context**

It can be played to other endpoints

**Comment by aeneasr** [comment]
Hm, generally I like the idea of not using Bad Request but instead something else (because the request isn't really malformed). It would be however quite a breaking change. Maybe some other folks have an opinion on that.

**Comment by aeneasr** [comment]
Closing as per answer https://stackoverflow.com/questions/3290182/rest-http-status-codes-for-failed-validation-or-invalid-duplicate which I find satisfying in terms of keeping 400 around, especially as it would be a serious breaking change and there appears to be no longer confusion around 400 / 422.
