### ISSUE TITLE
Quickstart fail Kratos migrate on windows

### ISSUE THREAD

**Issue by greenbeam-ita** [ory/kratos#1561]
I try to run quick start project as explain in [https://www.ory.sh/kratos/docs/quickstart](https://www.ory.sh/kratos/docs/quickstart)

But I have this issue after run the command

`docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate`

**Error**

```
Recreating kratos_mailslurper_1 ...
Recreating kratos_kratos-selfservice-ui-node_1 ...
Creating kratos_kratos-migrate_1               ... error
Recreating kratos_mailslurper_1                ... done
Recreating kratos_kratos-selfservice-ui-node_1 ... done
/kratos/contrib/quickstart/kratos/email-password: input/output error

ERROR: for kratos-migrate  Cannot create container for service kratos-migrate: invalid mount config for type "bind": stat /run/desktop/mnt/host/c/Users/MyUser/Workspace/kratos/contrib/quickstart/kratos/email-password: input/output error
ERROR: Encountered errors while bringing up the project.
```

**Environment**

- Docker Engine v20.10.6
- Windows 10 Pro

**Comment by aeneasr** [comment]
Unfortunately I don't have access to a windows machine, so maybe someone else can chime in. However, this really looks like a Docker issue, not an issue in this project, e.g.:

- https://forums.docker.com/t/input-output-error/49849

**Comment by aeneasr** [comment]
Closing this because it looks like a windows issue but feel free to reopen if you think it is a bug in kratos! :)
