### ISSUE TITLE
/self-service/settings/api returning stacktrace

### ISSUE THREAD

**Issue by nanikjava** [ory/kratos#1563]
**Describe the bug**

Accessing the `/self-service/settings/api` with an invalid `flow` parameter gets the following error

```
{
  "error": {
    "code": 403,
    "status": "Forbidden",
    "reason": "This endpoint can only be accessed with a valid session. Please log in and try again.",
    "debug": "rid=\nerror=request does not have a valid authentication session\nreason=No active session was found in this request.\ndetails=map[]\ndebug=\n\ngithub.com/ory/kratos/session.(*ManagerHTTP).FetchFromRequest\n\t/home/.....
....
....
runtime.goexit\n\t/home/Golang/go1.16/src/runtime/asm_amd64.s:1371",
    "message": "The requested action was forbidden"
  }
}
```

**Reproducing the bug**

Execute the following command:

`curl -s -X GET -H "Accept: application/json"   "http://127.0.0.1:4433/self-service/settings/api?flow=XXXX"`

**Expected behavior**

Not sure if this is the expected behaviour but surely sending stack trace to the API caller is not the right approach.

**Comment by nanikjava** [comment]
The `FetchFromRequest` function inside `manager_http.go` is returning 

`return nil, errors.WithStack(ErrNoActiveSessionFound)`

changing to

`return nil, errors.Cause(ErrNoActiveSessionFound)`

got a more reasonable error

```

  "error": {
    "code": 403,
    "status": "Forbidden",
    "reason": "This endpoint can only be accessed with a valid session. Please log in and try again.",
    "debug": "rid=\nerror=request does not have a valid authentication session\nreason=No active session was found in this request.\ndetails=map[]\ndebug=\n",
    "message": "The requested action was forbidden"
  }
}
```

Thoughts ?

**Comment by aeneasr** [comment]
Yeah, we should probably have a config switch to dis/enable traces ending up at the http response (I believer ory/herodot is already capable of it)

**Comment by nanikjava** [comment]
> Yeah, we should probably have a config switch to dis/enable traces ending up at the http response (I believer ory/herodot is already capable of it)

@aeneasr can you kindly take a look a the WIP PR to check whether this is the `herodot` config that you are referring to ?
