### ISSUE TITLE
Different payload for stub:500

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1568]
**Describe the bug**

If I open `/kratos/public/self-service/errors?id=stub:500` the payload I get is different from [the one published here](https://www.ory.sh/kratos/docs/self-service/flows/user-facing-errors#using-stub-errors):

```
{
  "id": "b49be7aa-9042-4c0d-a556-aa7caa5f1211",
  "error": {
    "code": 500,
    "status": "Internal Server Error",
    "reason": "This is a stub error.",
    "message": "An internal server error occurred, please contact the system administrator"
  },
  "created_at": "0001-01-01T00:00:00Z",
  "updated_at": "0001-01-01T00:00:00Z"
}
```

Note the `error` instead of `errors`.

**Environment**

- Version: oryd/kratos:v0.7.0-alpha.1

**Comment by aeneasr** [comment]
That's a bug, nice find!
