### ISSUE TITLE
Unable to send email using SMTP connection with crashing

### ISSUE THREAD

**Issue by kolbma** [ory/kratos#1569]
**Describe the bug**

I try to follow the quickstart.yml setup with mailslurper. I can send mail to mailslurper with a curl command. I've bound the port 1025 for testing. So mailslurper is working. But kratos does not send any mail to mailslurper.  
It is reporting i/o timeout.  
In the log is the output `smtp_ssl_enabled=false`. Why is it disabled, although the config says `smtps`? Is this the problem?

I've had a look in the sources, found `legacy_ssl` and got it to work with  
```connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true&legacy_ssl=true```.  
So maybe you should provide this in the sample config and docs!  

But it shouldn't __crash__.

**Reproducing the bug**

1. Run the quickstart.yml
2. Register a user
3. The mail is not send, there is the error

_Server logs_

```
time=2021-07-18T15:53:24Z level=error msg=Unable to send email using SMTP connection. func=github.com/ory/kratos/courier.(*Courier).DispatchMessage file=/home/ory/courier/courier.go:187 audience=application error=map[message:read tcp 192.168.96.2:37554->192.168.96.4:1025: i/o timeout trace:stack trace could not be recovered from error type *net.OpError] message_from=no-reply@<domain> service_name=Ory Kratos service_version=v0.7.0-alpha.1 smtp_server=mailslurper:1025 smtp_ssl_enabled=false
```

After some time there are also crashes:
```
time=2021-07-18T15:42:24Z level=fatal msg=Failed to run courier worker. func=github.com/ory/kratos/cmd/courier.Watch file=/home/ory/cmd/courier/watch.go:95 audience=application error=map[message:read tcp 192.168.96.2:37474->192.168.96.4:1025: i/o timeout trace:
github.com/ory/kratos/courier.(*Courier).DispatchMessage
	/home/ory/courier/courier.go:188
github.com/ory/kratos/courier.(*Courier).DispatchQueue
	/home/ory/courier/courier.go:225
github.com/ory/kratos/courier.(*Courier).watchMessages.func1
	/home/ory/courier/courier.go:137
github.com/cenkalti/backoff.RetryNotify
	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37
github.com/cenkalti/backoff.Retry
	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/ory/kratos/courier.(*Courier).watchMessages
	/home/ory/courier/courier.go:136
runtime.goexit
```

_Server configuration_

```yaml
courier:
  smtp:                          
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
```

From kratos-container the mailsluper-container is connectable on port 1025:
```
~ $ nc -v mailslurper:1025
mailslurper:1025 (192.168.96.4:1025) open
```

**Expected behavior**

Should send the mail.

**Environment**

- Version: v0.7.0-alpha.1 (official images)
- Environment: Alpine, Docker

**Comment by ms42Q** [comment]
thanks for posting the workaround @kolbma !
Had the same problem and setting `legacy_ssl=true` fixed it for me as well!

**Comment by aeneasr** [comment]
Oh nice find, looks like we forgot to update the quickstart conifg. Would you be up for a PR? :)

**Comment by kolbma** [comment]
@aeneasr I think you've been a little bit too fast with closing this.  

This won't fix the kratos crash in courier watcher when there is a communication problem with the mail server...
The courier watcher is running as part of kratos runtime and not as separate process, so it shouldn't exit the kratos process in this case.

```
time=2021-07-18T15:42:24Z level=fatal msg=Failed to run courier worker. func=github.com/ory/kratos/cmd/courier.Watch file=/home/ory/cmd/courier/watch.go:95 audience=application error=map[message:read tcp 192.168.96.2:37474->192.168.96.4:1025: i/o timeout trace:
github.com/ory/kratos/courier.(*Courier).DispatchMessage
	/home/ory/courier/courier.go:188
github.com/ory/kratos/courier.(*Courier).DispatchQueue
	/home/ory/courier/courier.go:225
github.com/ory/kratos/courier.(*Courier).watchMessages.func1
	/home/ory/courier/courier.go:137
github.com/cenkalti/backoff.RetryNotify
	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37
github.com/cenkalti/backoff.Retry
	/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/ory/kratos/courier.(*Courier).watchMessages
	/home/ory/courier/courier.go:136
runtime.goexit
```

**Comment by aeneasr** [comment]
You can run email sending as a separate task using: https://www.ory.sh/kratos/docs/cli/kratos-courier-watch/#route-identifier.

This is documented here: https://www.ory.sh/kratos/docs/concepts/email-sms/#single-instance

Omit `--watch-courier` when calling `kratos serve`. We have it in the quick start for convenience and easier config.

**Comment by kolbma** [comment]
Yeah, I've seen this, but I think the process should run forever and not exit on a problem. This should be the purpose of the this __cenkalti/backoff__ to handle the environment problems, isn't it?

**Comment by aeneasr** [comment]
Of you can't send emails, but you want to send emails, then the process should crash. Otherwise, you won't receive any emails, but the process looks healthy. Backoff retry eventually fails, it has a limited amount of retries :)

**Comment by kolbma** [comment]
Well, I have a different view on fault tolerant systems...
