### ISSUE TITLE
Replace mail & sms with generic notifications

### ISSUE THREAD

**Issue by khusseini** [ory/kratos#1572]
Hello everyone,

I wanted to use Kratos in my Faas environment in which I use a message queue in order to send out notifications to users based on certain events. While Kratos would be definately a great fit in my architecture, I am still reluctant in using it because it has a hard dependency on SMTP and SMS. I think that this dependency is not needed and is also out of scope of the responsibilities of Kratos and I propose to replace the SMS and SMTP system with a generic notification. 
As a start it could be set up with web hooks, so that Kratos calls up a URL (in my case a function), whenever a SMS or Mail would be sent out. This enables me to detach everything related to mailing into another application and makes also email Templates more maintainable.

What do you think about it?

**Comment by aeneasr** [comment]
We definitely want to keep SMS (which does not exist yet) and SMTPS as first-class citizens. Regarding the idea to use webhooks for notifications, this is already tracked: https://github.com/ory/kratos/issues/776

**Comment by khusseini** [comment]
That's really a bummer. That disqualifies Kratos in my setup

**Comment by khusseini** [comment]
Maybe I am misunderstanding something but from the linked issues I understood, that the feature I am looking for is not yet implemented? I am confused. Nevertheless, I decided to include all Ory components in my project.

**Comment by aeneasr** [comment]
Yes, it’s not yet available - I closed this issue because it is a duplicate of that one. That issue also has much more technical detail and ideas already (because it is older) so it will be easier for someone to pick up if need be.
