### ISSUE TITLE
User input not returned in flow after submission with error

### ISSUE THREAD

**Issue by yholkamp** [ory/kratos#1595]
**Describe the bug**

When submitting a browser flow, such as a registration request via the regular browser-based POST method and that submission results in an error, looking up the flow does not return the user input in the `value` attribute for the ui nodes. This prevents populating the form with the previously entered values in such a scenario, losing information such as the provided name or phone number during signup.

**Reproducing the bug**

1. Run Kratos & a SPA
2. Submit a registration form with values that result in some kind of error (ie identifier already used)
3. You are redirected back to the registration page
4. Retrieve the flow
5. Observe that the previous values are not included, making it hard to populate the form for the end user.

_Server logs_

Do not appear to contain relevant information.

_Server configuration_

quickstart yml produces a similar result.

**Expected behavior**

On earlier Kratos versions, the submitted values were included in the flow lookup under `methods.password.config.fields[x].value`, I was expecting this to be populated on recent versions as well.

**Environment**

- Version: v0.7.1.0-alpha from Docker Hub
- Environment: Docker

**Additional context**

With the added support for AJAX, I suspect using the browser redirects will be less frequently used - I know I'm looking to migrate over as part of this upgrade - but it is still unexpected given that the `value` attribute is listed as a possible property.

**Comment by aeneasr** [comment]
This is still the case, if you get a fresh flow, it means that the CSRF cookie is not properly handled. You will probably observe in your chrome network calls that there's one request to the flow, and then another request to the init endpoint.

**Comment by yholkamp** [comment]
You're right, adding the cookies section to the config resolved the issue for me, #1597 will definitely be helpful in the future.
