### ISSUE TITLE
Auto-Login on Registration flow does not return `session`, only `identity` for SPA requests

### ISSUE THREAD

**Issue by joekrill** [ory/kratos#1604]
**Describe the bug**

According to [the documentation](https://www.ory.sh/kratos/docs/self-service/flows/user-registration#with-auto-login-on-registration-1) on the registration flow:

> If the `session` after hook is enabled, the Ory Kratos Login Session and Ory Kratos Login Session Token are included in the response [...]

However, the response only includes the `identity`. There is no `session` in the response.  

My `kratos.yml` includes this:

```yml
selfservice:
  flows:
    registration:
      lifespan: 2h
      after:
        password:
          hooks:
            - hook: session
```

I can see the session cookie being set, so the user is being logged in. And hitting the `/sessions/whoami` endpoint also reflects that by returning the active session.

**Reproducing the bug**

1. Configure the `session` after hook for registration
2. Initialize the registration flow by using the `/self-service/registration/browser` endpoint and including the `Accept: application/json` header.
3. Submit the form successfully using a POST request and the URL provided by the above request's (2) `ui.action` value, including  the `Accept: application/json` header.
4. Note that the `Set-Cookie` response headers include `ory_kratos_session` cookie, and the body includes an `identity`, but the body does _not_ include a `session`.

_Server configuration_

`oryd/kratos:v0.7.1-alpha.1` docker image

**Expected behavior**

The response should include both the identity _and_ the session, [as detailed in the documentation](https://www.ory.sh/kratos/docs/self-service/flows/user-registration#with-auto-login-on-registration-1)

**Comment by aeneasr** [comment]
That looks like a bug, contributions welcomed!
