### ISSUE TITLE
golang library fails to unmarshal the returned error from the server

### ISSUE THREAD

**Issue by g13013** [ory/kratos#1609]
**Describe the bug**

The golang library fails to unmarshal the error returned by the server with this message

```
cannot unmarshal string into Go struct field GenericError.error.details of type map[string]interface {}
```

**Reproducing the bug**

Calling any endpoint with invalid token or cookie returns what seems to be a generic error

```
{
  "error":{
    "code":403,
    "status":"Forbidden",
    "reason":"The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues.",
    "details":{
      "docs":"https://www.ory.sh/kratos/docs/debug/csrf",
      "hint":"The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token).",
      "reject_reason":"The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow."
    },
    "message":"the request was rejected to protect you from Cross-Site-Request-Forgery"
  }
}
```

but the received error is a golang error which seems to be provoked by this line: https://github.com/ory/kratos-client-go/blob/master/client.go#L381

it apparently tries to unmarshal the payload into [JsonError.GenericError](https://github.com/ory/kratos-client-go/blob/master/model_generic_error.go#L19)

the error seems to be caused by the signature of the details field `map[string]map[string]interface{}` which is incompatible with the returned payload, in fact the details payload contains also `string` fields which does not unmarshal into 

**Possible solution**:
Changing the signature to `map[string]interface{}` fixed the problem for me, which I think is the best solution for this problem since we are dealing with generic errors, we might expect the developer to have the responsibility to further unmarshal the details fields that are of type `interface{}` into which ever suitable to the type of field when he needs to. 

**Environment**:
Library: github.com/ory/kratos-client-go v0.7.0-alpha.1 
Server: v0.7.0-alpha.1

**Comment by aeneasr** [comment]
Thank you for the report, that is indeed very strange.

https://github.com/ory/kratos-client-go/blob/eb6f01330bbbb62ef6a731f7bb7b931e7a7ad0db/model_generic_error_payload.go#L24

should actually be

```go
	Details map[string]interface{} `json:"details,omitempty"`
```

Looking at the spec the "details" https://github.com/ory/sdk/blob/master/spec/kratos/v0.7.1-alpha.1.json are formatted correctly:

```
          "details": {
            "additionalProperties": true,
            "description": "Further error details",
            "type": "object"
          },
```

It is possible that the combination of `additionalProperties: true` and `type: object` somehow instructs the Go generator to think it's an object with objects as values?

**Comment by aeneasr** [comment]
Yeah, self-service error is generated correctly and doesn't have the `additionalProperties` flag set:

https://github.com/ory/sdk/blob/7ef989a77db966dc282079d86290d85a1550fe10/clients/kratos/go/model_self_service_error.go#L23

Difference being that we use `json.RawMessage` here

```
// swagger:model selfServiceError
type ErrorContainer struct {
	Errors json.RawMessage `json:"error" db:"errors"`
}
```

whereas using `map[string]interface{}` in the `DefaultError`:

https://github.com/ory/herodot/blob/503e2664e11b39e4ac9f8659a52c9cea55d08d85/error_default.go#L52

However, it looks like the TypeScript generator has the same issue:

https://github.com/ory/sdk/blob/7ef989a77db966dc282079d86290d85a1550fe10/clients/kratos/typescript/api.ts#L244

Not sure how to fix this without manually patching the resulting schema spec :/

Also found some references to this:

- https://github.com/go-swagger/go-swagger/issues/1228
- https://github.com/go-swagger/go-swagger/issues/1402

So yeah looks like we need to do some patching...
