### ISSUE TITLE
EMail on registration with existing identifier

### ISSUE THREAD

**Issue by martinei** [ory/kratos#1625]
We use e-mail as primary Identifier. If a users tries to register with an already existing email, we don't want to leak information by displaying a specific error message, but just behave as in the successful case  in our web-ui. This can be accomplished by filtering the response for the error code 4000007.

In addition we want **Kratos to send a mail to the existing accounts email**  with information about the attempted (re-)registration and perhaps a link to the self service password recovery.

Does this make sense as a feature for you? Should it be implemented as a hook for failed registration attempts?

**Comment by zepatrik** [comment]
I think this goes hand in hand (or partially covered) with #140 #292 #133
So definitely a valid thing to do.

**Comment by aeneasr** [comment]
> We use e-mail as primary Identifier. If a users tries to register with an already existing email, we don't want to leak information by displaying a specific error message, but just behave as in the successful case in our web-ui. This can be accomplished by filtering the response for the error code 4000007.

That is definitely not enough, you need to disable the session hook! I am not sure how kratos behaves right now if the hook is disabled and a duplicate email address is used.

> In addition we want Kratos to send a mail to the existing accounts email with information about the attempted (re-)registration and perhaps a link to the self service password recovery.

It might make sense to have this as a feature using either recovery or verification email addresses. A hook might be the correct approach also, although it might be difficult for the hook to know if the registration failed (because we execute hooks after success, but not failures). So while theoretically a good idea, it could be difficult to implement in practice.

**Comment by aeneasr** [comment]
Missed the most important part: would be great to have this!

**Comment by martinei** [comment]
> you need to disable the session hook!
Good catch.

> A hook might be the correct approach also, although it might be difficult for the hook to know if the registration failed (because we execute hooks after success, but not failures)

Currently duplicate identifiers are caught after executing of the Post-Registration-Pre-Persist Hook. So there is no sharp line as executing Hooks only on success.

**Comment by aeneasr** [comment]
Ah, yes, you're right - we have the pre persist hook. Totally forgot about that one :)

So yes, then a hook would probably be the best option!

**Comment by lanphan** [comment]
I'd like to add my 2 cents: I think we can apply flow used in recovery flow here:
* always return success
* based on email content to inform user the real result

What do you think, @aeneasr ?

With the new flow above, I think we should think more about how to unify email content for multiple purposes:
* inform user result
* verification email

**Comment by aeneasr** [comment]
>always return success
>
>based on email content to inform user the real result

I am not sure if I understand this use case. Do you mean that we send an email when a unique identifier (e.g. the email) already exists?

**Comment by lanphan** [comment]
yes, @aeneasr 

Like valid and invalid case of recovery flow:
* valid registration: user first registered into system with all valid info

```
Hi,

you have successfully register new account, now you can log into system using link below

{{ .LoginURL }}
```


* invalid registration: email already existed in the system, we can send them email with content like

```
Hi,

you (or someone else) entered this email address when trying to register new account.

However, this email address is already in our database of registered users and therefore the attempt has failed.

If this was you, seems you forgot password, please click here <link to forget password> to recovery password.

If this was not you, please ignore this email.
```

**Comment by aeneasr** [comment]
Got it, sounds great :)

**Comment by camero2734** [comment]
@aeneasr Is this something that Ory Kratos supports in 2025?
