### ISSUE TITLE
Regenerate lookup secrets as part of login when last secret was used

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#1649]
**Is your feature request related to a problem? Please describe.**

For context, see: https://github.com/ory/kratos/issues/26#issuecomment-898366286

**Comment by twnk** [comment]
> Ok, that's interesting - if you use up all of your backup codes in Google then - well - you have used up all your back up codes. There is no dialog, regeneration, or anything else which tells you: you ran out of back up codes. So basically, if you mess it up, you are locked out of your account.
> ...
>     2. Lost TOTP -> use back up code, back up code was last code used

Just my opinion, but I think it would be much more user-friendly to remind users after each use of a backup code "You have n backup codes remaining, do you want to generate new codes?" Maybe with a different strength of reminder as you get close to 0 remaining. E.g. Attempt to force them to renew if 3 or below. 

(Moved this comment from the other thread, hadn't realised there was already a specific issue tracking this feature!)
