### ISSUE TITLE
Support yescrypt

### ISSUE THREAD

**Issue by Donatzsky** [ory/kratos#1651]
Yescrypt seems like it would be a good addition to the current bcrypt and Argon2 options for password hashing.

https://www.openwall.com/yescrypt/

**Comment by aeneasr** [comment]
As we have seen with argon2, it is better to rely on tested and recommended algorithms that have been around for a while. So no plan to support this for the time being.

**Comment by Donatzsky** [comment]
I should probably have added that I don't see this as any kind of priority, but more something to add at some later date. As they themselves say, it's not really ready for wider adoption.

**Comment by aeneasr** [comment]
Ok, in that case I will be closing this as the backlog is large enough already ;) We can always reopen if scrypt becomes a widely adopted algorithm! In any case, thank you for your ideas!
