### ISSUE TITLE
Include password policy information in initial flow/UI

### ISSUE THREAD

**Issue by joekrill** [ory/kratos#1682]
When returning or rendering a registration flow, it would be ideal to also disclose any specific password policies up-front (minimum length, for example). This is generally considered [best practice from a UX perspective](https://www.nngroup.com/articles/password-creation/). 

I'm not sure how this would best be surfaced, exactly - perhaps in the `messages` array of the `UiNode` with a specific type like `hint` or `info`?

The alternative is to hard-code this sort of hint/message into the underlying application. But that doesn't feel like the correct place to do this, because we're relying on Kratos to set these policies based on best practices. And it's certainly possible that those change as time goes on -- so it would be difficult to keep the UI in sync in those cases.

**Comment by aeneasr** [comment]
Yeah, we could potentially add this to messages of the field! The password policy is currently a min length of 6 chars and also not being leaked in HIBP database

**Comment by zepatrik** [comment]
Also we check that the password is not too similar to the identifier, not sure how to communicate that in an easy to understand way.
This is the implementation of both policies:
https://github.com/ory/kratos/blob/f4c00f4cfe4aeb1b52eacd22c18c26e5d25a6700/selfservice/strategy/password/validator.go#L148-L157
