### ISSUE TITLE
chore: update docker images

### ISSUE THREAD

**Issue by bweston92** [ory/kratos#1692]
**Steps to reproduce the behavior**

Command expected to work: `docker pull oryd/kratos:v0.7.2-alpha.1`

Actual output:
```
Error response from daemon: manifest for oryd/kratos:v0.7.2-alpha.1 not found: manifest unknown: manifest unknown
```

Docker registry lookup shows no result:

![Screenshot from 2021-08-27 10-01-54](https://user-images.githubusercontent.com/1764057/131102086-1b00be9a-eb98-4882-8071-d78ff16a4ee3.png)

Installation steps for installing using Docker include pulling an image with a specific tag.

See line here: https://github.com/ory/kratos/blob/149101ed145dae2b75e5150013efc478f5fd0cc3/docs/versioned_docs/version-v0.7/install.md#L14

This tag doesn't exist, also `latest` hasn't been updated in a month.

**Additional context**

Is this a manual job or is there some automation that is broken?

**Comment by aeneasr** [comment]
Resolved on master!
