### ISSUE TITLE
Allow to run non-blocking web-hook

### ISSUE THREAD

**Issue by thomasboni** [ory/kratos#1702]
**Is your feature request related to a problem? Please describe.**

I would like to be able to call a web-hook after a flow that will not produce any effect on the execution flow, even if the call fails.

**Describe the solution you'd like**

An option in `web_hook` configuration that allows failure in endpoint call (ex: `allow_failure`, default value to false):

- If this option is set to `true`: the flow continues its execution anyway
- If this option is set to `false`:  the current behavior. If the endpoint call fails, the flow execution is cancelled. 

**Describe alternatives you've considered**

I haven't found an alternative yet, let me know if you have an idea :) 

**Additional context**

My use case is the following:

When a user verify its account, we want to push his/her information in our CRM system. In order to do that, we want to set up a webhook `after` the `verification` flow that call our CRM API. But, if for any reason the CRM API doesn't work, all user verifications will fails and users will not be able to connect. This is clearly not a good idea to ensure reliability on our platform.

**Comment by aeneasr** [comment]
That sounds like a good idea! I think we could have something like `blocking: true` or `blocking: false` to govern this :) Would you be up for a PR here? :)

**Comment by thomasboni** [comment]
Let me read your contributing guide and I will give it a try ;)

**Comment by aeneasr** [comment]
There's also https://github.com/ory/kratos/pull/1585 just fyi
