### ISSUE TITLE
Outdated part of readme

### ISSUE THREAD

**Issue by adlerhurst** [ory/kratos#1706]
Hi guys first of all I'd like to say thank you for your work! I like this project. 

**Describe the bug**

The readme mentions that kratos is the "first **and only** cloud native Identity and User Management System in the world". 

With this in mind  I'd like to mention, that there are more cloud native IAM's in the world. I don't want to advertise any other solution, that's why i don't provide any links.

**Reproducing the bug**

**Expected behavior**

Catch phrase without wrong information. e.g. correct the first sentence

```old
Ory Kratos is the first and only cloud native Identity and User Management System in the world.
``` 

with this:

```new
Ory Kratos is the first cloud native Identity and User Management System in the world.
```

**Additional context**

Please don't take this too serious and enjoy your day ✌️

**Comment by aeneasr** [comment]
True, that was the case on project's inception but things have changed since then ;)
