### ISSUE TITLE
Can't connect with official postgresql connection string

### ISSUE THREAD

**Issue by fenos** [ory/kratos#1708]
**Describe the bug**

Kratos is unable to connect to a postgres database when the dsn is set to: `postgresql://[userspec@][hostspec][/dbname][?paramspec]`.

Kratos expect the protocol to be `postgres` instead of `postgresql` 

Following the [Postgres documentation ](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) the official protocol used is `postgresql` not `postgres` 

It would be good if you could support `postgresql` too as other libraries defaults to that.

My real-world issue was that I installed a Postgres Operator in my Kubernetes cluster and the `Secret` env generated for the connection string used `postgresql` so there was no way for me to change that.

**Reproducing the bug**

- use `postgresql` instead of `postgres` as the protocol in the `DSN` string

**Expected behavior**

It should work with the `postgresql` protocol

**Environment**

- Version: v0.7.3
- Environment: Debian, Docker, ...

**Comment by aeneasr** [comment]
This is an issue upstream in gobuffalo/pop so I would like to redirect you there: https://github.com/gobuffalo/pop

Once it is resolved there feel free to create a PR here to support postgresql as a DSN URI scheme

**Comment by fenos** [comment]
@aeneasr Hello! thanks for your reply, but it looks like they already support this https://gobuffalo.io/en/docs/db/configuration#dialect

I'll see if I can make a PR

**Comment by aeneasr** [comment]
Closing as upstream issue.
