### ISSUE TITLE
Email Courier SMTP Header Configuration

### ISSUE THREAD

**Issue by emtammaru** [ory/kratos#1725]
**Is your feature request related to a problem? Please describe.**

There's currently no way to configure headers for the SMTP email requests.  For example, when using AWS SES SMTP interface there are headers that need to be set for cross-account sending:  https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-delegate-sender-tasks-email.html#sending-authorization-delegate-sender-tasks-smtp

**Describe the solution you'd like**

The `courier.smtp` configuration object should include a map of static key-value pairs for headers to be included in all smtp requests.

**Describe alternatives you've considered**

Environment variables for specific headers or perhaps even pluggable AWS SES SDK configuration.

**Additional context**

N/A

**Comment by aeneasr** [comment]
Hello there, I believe we have another issue which is asking for adding support for a generic notification interface for the courier. I think this would make most sense to cover all the details of the various available providers that all work a bit different. I would prefer that more than adding e.g. direkt AWS SNS SDK support (which is likely hard to test in open source software). What do you think about that approach?

**Comment by emtammaru** [comment]
Hey, I agree a generic notification interface would cover all possible use cases.  What about both though?  The simplicity of the SMTP configuration is great, and it probably supports the majority of implementations.  Adding just an SMTP header file configuration should straightforward and maintainable.  For example:
```
courier:
  smtp:
    connection_uri: smtps://test:test@my-smtp-server:1025/
    headers: file://path/to/smtp-headers.txt
```
BTW, also wanted to say bravo on the work you've done with kratos.  It's a really well done open-source identity management solution, and I'd recommend it to anyone.  Developers often times don't get a whole lot of praise for their work -- mostly just issues and criticism :) But you've done a great job, so thank you!

**Comment by aeneasr** [comment]
Thank you, appreciate it :) Also slept over it, I think it would make sense to have some header config available here. It is too much hassle to set up a HTTP RPC endpoint just to cover this simplistic use case IMO.

Would you be open to contribute such a change? If so, I think it would make sense to have the headers defined in the config as opposed to a file as that is usually easier to configure. To be accepted the PR should:

- [ ] add a new config option similar to the one you mentioned but the header key/value pairs should be specified in the YAML
- [ ] add documentation related to this (maybe even some AWS specific docs)
- [ ] add test cases to ensure that the config options are propagated and end up at the upstream SMTP server

Thank you :)

**Comment by emtammaru** [comment]
Sounds good! I should have some time in the next couple weeks to do it.

**Comment by aeneasr** [comment]
Nice :)
