### ISSUE TITLE
`res.Body` not correctly closed in client-go docs code

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1727]
**Is your feature request related to a problem? Please describe.**

Using `kratos-client-go` `ToSession` [as documented](https://github.com/ory/kratos-client-go/blob/master/docs/V0alpha1Api.md#tosession) I get a warning for `res.Body` not correctly closed using [golangci-lint and bodyclose](https://github.com/timakin/bodyclose).

**Describe the solution you'd like**

Update that code for a better way to handle the call cycle.

Maybe like the below code, what do you think?

- Before:

```go
resp, r, err := apiClient.V0alpha1Api.ToSession(context.Background()).XSessionToken(xSessionToken).Cookie(cookie).Execute()
if err != nil {
    fmt.Fprintf(os.Stderr, "Error when calling `V0alpha1Api.ToSession``: %v\n", err)
    fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
}
// response from `ToSession`: Session
fmt.Fprintf(os.Stdout, "Response from `V0alpha1Api.ToSession`: %v\n", resp)
```

- After:

```go
session, resp, err := apiClient.V0alpha1Api.ToSession(context.Background()).XSessionToken(xSessionToken).Cookie(cookie).Execute()
if err != nil {
    fmt.Fprintf(os.Stderr, "Error when calling `V0alpha1Api.ToSession``: %v\n", err)
    fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", resp)
}

defer func() {
  if err2 := resp.Body.Close(); err2 != nil {
    // handle error here
  }
}()

// response from `ToSession`: Session
fmt.Fprintf(os.Stdout, "Response from `V0alpha1Api.ToSession`: %v\n", session)
```

**Comment by aeneasr** [comment]
I am pretty sure that the SDK is doing this within it’s reader, so no need to close it on your end! :)

**Comment by frederikhors** [comment]
> I am pretty sure that the SDK is doing this within it’s reader

Are you referring to these lines?

https://github.com/ory/kratos-client-go/blob/master/api_v0alpha1.go#L953-L954

I'll open an issue on https://github.com/timakin/bodyclose for this "false" positive, to see if we can improve the assessment of these cases in the future.

**Comment by aeneasr** [comment]
Exactly :) Thank you! :)
