### ISSUE TITLE
Tag version in docker-compose before commit&tag push

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#1738]
**Is your feature request related to a problem? Please describe.**

The version in docker-compose is being updated after the release passes through. However, that means that the guide https://www.ory.sh/kratos/docs/quickstart#clone-ory-kratos-and-run-it-in-docker will checkout a docker-compose file which refers to the previous version!

**Describe the solution you'd like**

The docker compose file should be changed before commit/pushing the new tag.

**Comment by counter2015** [comment]
Fast catch! I just want to try docker images in v0.7.3-alpha.1, but the auto-gen image version in `quickstart.yml` is  v0.7.2-alpha.1
