### ISSUE TITLE
Spec is incorrect

### ISSUE THREAD

**Issue by jld3103** [ory/kratos#1739]
**Describe the bug**

The spec is not correct in some places

**Reproducing the bug**

See https://github.com/ory/kratos/blob/1cf61cdeedbd8bf5b66310793249681ff976baab/spec/api.json#L1537-L1540 and https://github.com/ory/kratos/blob/1cf61cdeedbd8bf5b66310793249681ff976baab/selfservice/strategy/oidc/strategy_login.go#L49 for example.

**Expected behavior**

Spec should represent what kratos acutally expects/returns.

**Environment**

- Version: 1cf61cdeedbd8bf5b66310793249681ff976baab

**Additional context**

I'd like to start a list of these findings in this issue. Then they can be fixed.
Sadly I didn't make a list with the stuff I noticed previously, but I can probably remember some stuff when I see it again.

**TODO list**:
- [ ] https://github.com/ory/kratos/blob/1cf61cdeedbd8bf5b66310793249681ff976baab/selfservice/strategy/oidc/strategy_login.go#L49
- [ ] https://github.com/ory/kratos/blob/eca7aff2be96c673dd6be5dc36ab1f4850cc44f0/selfservice/strategy/oidc/strategy_registration.go#L61

**Comment by aeneasr** [comment]
That is very helpful! You could also format them as a to do list

```
- [ ] ...
```

which would help in closing them one by one :)

**Comment by jld3103** [comment]
@aeneasr i think basically all of the default values in the spec are wrong. where can i lookup the correct values for example for pagination?

**Comment by jld3103** [comment]
@aeneasr i think in the future it would be useful to have integration tests for one of the generated clients, so we can be sure the client and therefore the spec is correct.

**Comment by aeneasr** [comment]
We do have those in examples/go but covering everything is quite challenging :/
