### ISSUE TITLE
Tracing operation name for API's causes cardinality issues

### ISSUE THREAD

**Issue by harnash** [ory/kratos#1742]
**Describe the bug**

Currently each API have an operation name specified like this https://github.com/ory/x/blob/master/tracing/middleware.go#L15. In conjunctions with paths like this https://github.com/ory/kratos/blob/master/identity/handler.go#L22 (and similar) is generating thousands of unique operations names.

Via https://opentracing.io/docs/best-practices/:
> The operation above refers to the name the server wants to give to the Span. For example, if the HTTP request was a POST against /save_user/123, the operation name can be set to post:/save_user/. 

**Reproducing the bug**

1. Run kratos with any large number of identities.
2. Make API Request to with `curl kratos/identities/YOUR_IDENTITY_UID` and continue with few other identities.
3. Observe the operation names reported to the OpenTracing agent

**Expected behavior**

I believe API paths that include parameters/variables in paths should be grouped in OpenTracing using common operation name (can be as suggested in the best practices). Current setup of tracing is convenient but can cause problems with tracer storage being unnecessarily overloaded. It may be that https://github.com/julienschmidt/httprouter/blob/fe77dd05ab5a80f54110cccf1b7d8681c2648323/router.go#L132 will do exactly what we want but I have not tested it yet.

**Comment by aeneasr** [comment]
Absolutely! This was also recently fixed in Ory Hydra if you want to take a look at joe it was resolved there!
