### ISSUE TITLE
error in docs. Need header. Provided only value

### ISSUE THREAD

**Issue by m-almas** [ory/kratos#1743]
https://github.com/ory/kratos/blob/52434d39f5c22880c2ad6e1563e09430c972fdd2/docs/versioned_docs/version-v0.7/self-service/flows/code/logout/samples/browser/node.txt#L7

**Comment by aeneasr** [comment]
Could you fix that in a PR? :)

**Comment by m-almas** [comment]
> Could you fix that in a PR? :)

Sure :)

**Comment by aeneasr** [comment]
I believe this is resolved
