### ISSUE TITLE
kratos identities import - include "state" property of identity

### ISSUE THREAD

**Issue by lanphan** [ory/kratos#1767]
**Describe the bug**
I follow document here https://www.ory.sh/kratos/docs/cli/kratos-identities-import/ to try command "kratos identities import" and it works. As I see that "identities" table in kratos have "state" column, I'd like to set state of imported identity to "inactive", but seems import process doesn't handle "state", "state" of identity after import is still "active".

Content of file to import here:
```
{
    "schema_id": "default",
    "traits": {
        "email": "foo@example.com",
        "name": {
            "first": "Foo",
            "last": "Last"
        }
    },
    "state": "inactive"
}
```

**Reproducing the bug**

_Server logs_

_Server configuration_

**Expected behavior**

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
That looks like a bug! Fixes welcomed :)
