### ISSUE TITLE
return_to_query_param not honored on OIDC login

### ISSUE THREAD

**Issue by jld3103** [ory/kratos#1773]
**Describe the bug**

I've set `return_to_query_param` in oathkeeper, but when a user logs in via OIDC, they are redirected to a URL that no longer contains the parameter. This breaks expected behavior and is confusing to users.

**Reproducing the bug**

1. Set `serve.errors.handlers.redirect.config.return_to_query_param` to `return_to` in oathkeeper config
2. Navigate to an unauthenticated page `https://test.example.com` -> redirect to login page by oathkeeper with `return_to_query_param` in the URL `https://login.example.com/?return_to=https://test.example.com`
3. Login via OIDC `https://some-oidc-provider.com/some-path` -> redirect to `default_browser_return_url` `https://example.com`, but it no longer contains `return_to_query_param`, so redirect to there is not possible.

**Expected behavior**

`return_to_query_param` should also be present after an OIDC login, so that users can return to the page the came from `https://example.com?return_to=https://test.example.com`.

**Environment**

- Version:  v0.7.6-alpha.1
- Environment: Kubernetes

**Comment by aeneasr** [comment]
Could you maybe include all the URLs in full to better understand your flow and what you want to achieve? :)

**Comment by jld3103** [comment]
I hope this is better. I think the best solution would be to redirect users to the login page again with a login flow which can be requested by the login page which reads the return URL from that flow (and then redirects the user back).

**Comment by jld3103** [comment]
@aeneasr do you think this is something worth fixing?

**Comment by aeneasr** [comment]
First please confirm that return_to is properly propagated in your app to kratos

**Comment by jld3103** [comment]
What do you mean? The parameter works with password login.

**Comment by aeneasr** [comment]
Ah ok, from the complexity of the flow described I was thinking this could be the issue. I'm working on this stuff anyways right now so I can give it a look!y

**Comment by jld3103** [comment]
Thanks!

**Comment by jld3103** [comment]
@aeneasr I see you did something in https://github.com/ory/kratos/pull/1624 about this. Is it already fixed with the changes you made?

**Comment by jld3103** [comment]
Thanks :)
