### ISSUE TITLE
request logger middleware is being run after the request was already handled

### ISSUE THREAD

**Issue by abador** [ory/kratos#1775]
**Describe the bug**

When making a request to kratos, the reqlog.Middleware is being run after the request is finished. Logs don't shop proper times of the request. This impacts other middlewares as well

**Reproducing the bug**

1. Make API Request to any public endpoint(or admin)
2. Verify the order of logs

_Server logs_

"started handling request"
"completed handling request"

**Additional context**

This was checked with a very slow mysql replica, so the problem was easier to find.

**Comment by aeneasr** [comment]
Please provide more detailed logs
