### ISSUE TITLE
doc page for ui error messages

### ISSUE THREAD

**Issue by sashatalalasha** [ory/kratos#1784]
**Problem:** There is no overview of registration and login error messages and their ids. This makes the customization of error messages quite time-consuming.

**Solution:** doc page for all messages including their ids.

**Comment by aeneasr** [comment]
Yes, we definitely need that! In the meanwhile, you can find all error messages in the `message*.go` files: https://github.com/ory/kratos/tree/master/text

There is also a little bit of explanation here: https://www.ory.sh/kratos/docs/concepts/ui-user-interface#messages
