### ISSUE TITLE
Config JSON Schema needs example values

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#179]
**Describe the bug**

Several keys of the configuration JSON Schema are missing example values. The generated docs are therefore not very useful, having things like:

```
dsn: id
```

```
    default_schema_url: https://WUaktPy.ngiv6PeNdvRUJh8sbpA4Y1-zwC7h5V0xKtl-+rac2,hwbmcWU36,49XIcdNld,1rQUVSWNE
```

```
    schemas:
      - []
```

**Expected behavior**

Make use of example values in the JSON Schema.

**Comment by aeneasr** [comment]
The proper way to check would be to go through all the fields in the JSON Schema and check manually :)

**Comment by vinckr** [comment]
Just checked and we have reasonable example values for all fields! 

Should anyone find a value that does not make sense, please create a dedicated issue for it and we'll fix it.
