### ISSUE TITLE
Documentation needed around environment variables with lists

### ISSUE THREAD

**Issue by fmmoret** [ory/kratos#1801]
**Is your feature request related to a problem? Please describe.**

The secrets rotation doc (https://www.ory.sh/kratos/docs/guides/secret-key-rotation/#route-identifier) and the config reference (https://www.ory.sh/kratos/docs/reference/configuration) don't tell you what kind of delimiter is used for all env variables that take lists: SECRETS_DEFAULT, SECRETS_COOKIE, SELFSERVICE_WHITELISTED_RETURN_URLS

**Describe the solution you'd like**

I'd like to know how to supply environment variable list values and I want to avoid generating secrets/values that would contain the delimiter.

**Describe alternatives you've considered**

I tried figuring out how config parsing & translation works in kratos. The dependency chain was too long for me to keep track / follow.

P.S. I would love to know the answer here in this thread before that documentation makes it live if anyone knows the answer 🙏

**Comment by aeneasr** [comment]
You can provide them in CSV format or JSON format!
