### ISSUE TITLE
A separate schema usage for Kratos tables

### ISSUE THREAD

**Issue by Unbuttun** [ory/kratos#1804]
**Is your feature request related to a problem? Please describe.**

Generally when people use postgres, they store their tables in the default schema, and so when kratos creates it's own tables on the same schema, it pollutes the working space considering there are quite a few tables that kratos adds.

**Describe the solution you'd like**
Either a way to make kratos build a new schema, let's say `kratos` and add the tables there by some sort of a config in the YML file, or make it as default one, as kratos is still in beta version, such breaking changes should not create any problems.

Maybe some sort of migrations can be added that will move the tables from default schema to new schema if someone upgrades their kratos image.

**Describe alternatives you've considered**

Alternatives i considered are that creating a schema myself, then running kratos so that it uses the schema, then moving back to the original one.

**Comment by aeneasr** [comment]
https://www.ory.sh/docs/ecosystem/deployment/#sql-persistent :)

**Comment by Unbuttun** [comment]
hey @aeneasr I don't see any option related to schema in that additional DSN params

**Comment by mangalaman93** [comment]
Same here. I can't find a schema either in the options. Do you guys ever plan to support this? If this is already supported, could you help us figure out how to specify a schema. Thanks

**Comment by aeneasr** [comment]
We support all common postgres SQL query parameters, see reference: https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by aeneasr** [comment]
We support all libpq params: https://www.postgresql.org/docs/9.6/libpq-connect.html

**Comment by wawhal** [comment]
I've been trying to setup kratos with `search_path=kratos`. The migrations went through successfully and I can see all the kratos tables in my `kratos` schema of postgres.

But when I try to register an identity, it throws an error saying "Unable to locate the table".

```
auth-1  | time=2024-08-01T19:41:32Z level=error msg=An error occurred while handling a request audience=application error=map[debug: message:Unable to locate the table reason: stack_trace:
auth-1  | github.com/ory/x/sqlcon.handlePostgres
auth-1  | 	/go/pkg/mod/github.com/ory/x@v0.0.623/sqlcon/error.go:59

```
