### ISSUE TITLE
Evaluate replacing GJSON/SJSON syntax with JSON Pointer

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#181]
**Is your feature request related to a problem? Please describe.**

We're currently using tidwall's SJSON/GJSON syntax to set/get JSON values. That syntax is not an open standard but instead specific to the tidwall implementation.

**Describe the solution you'd like**

We would like to evaluate (and maybe use) the [JSON Pointer Standard](https://tools.ietf.org/html/rfc6901) instead as it will be better documented and formally specified.

**Describe alternatives you've considered**

Not moving to JSON Path.

**Additional Context**

This needs to be addressed before releasing into a stable version of ORY Kratos.

**Comment by steffkelsey** [comment]
It could be as simple as using this lib: https://github.com/qri-io/jsonpointer in place of the tidwell gson lib

**Comment by steffkelsey** [comment]
Actually this one looks a bit more mature: https://github.com/dolmen-go/jsonptr

**Comment by aeneasr** [comment]
Thank you, both still look pretty fresh - I would want to have GJSON capabilities (getting and setting values) with JSON Path basically.

**Comment by aeneasr** [comment]
Closing this because too much work without a lot of upside
