### ISSUE TITLE
Support prefixed env vars

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#1855]
_I love Kratos and am "pushing" him into the IT departments of every customer I know. So take my request as a polite invitation for better software, not as a criticism! You did a great job with Ory! Congratulations!_

**Is your feature request related to a problem? Please describe.**

I often install Kratos in an environment where there are already environment variables with the same name (eg.: `DSN` or `LOG_LEVEL`).

**Describe the solution you'd like**

It would be very useful if Kratos read ONLY environment variables with a prefix, such as "`KRATOS_`" (eg.: `KRATOS_DSN` or `KRATOS_LOG_LEVEL`).

And I would like to configure that prefix in the config.yml file, something like:

```yml
environment_variables:
  prefix: "KRATOS_"
```

**Describe alternatives you've considered**

Nothing.

---

Thanks again! :smile:

**Comment by aeneasr** [comment]
Thank you for the idea :) We generally don't have that pattern, the problem being that many systems (e.g. Heroku) expose variables unprefixed (e.g. `PORT` or `DSN`). In general, if you want to scope your environment, you can do this on the shell level:

```
THIS_IS_ONLY_VALID_FOR_THE_FOLLOWING_COMMAND=some-value kratos server ...
```

or alternatively

```
(
  export THIS_IS_ONLY_VALID_FOR_THE_FOLLOWING_COMMAND=some-value;
  kratos server
)
```

test it:

```
(export FOO=BAR; echo $FOO); echo $FOO
```

**Comment by aeneasr** [comment]
I see - in that case we welcome any contributions! I think the prefix should be `ORY_KRATOS_` and it should override any non-prefix environment variables. For example `ORY_KRATOS_DSN` overrides `DSN`. Both options should work though (setting `DSN` AND setting `ORY_KRATOS_DSN`). So:

- [ ] Add another env var loader that is prefixed `ORY_KRATOS_`
- [ ] Ensure prefixed env var loader supersedes the unprefixed env var load
- [ ] Add documentation explaining that we can use prefixed env vars
- [ ] Add tests ensuring this works
  - [ ] when tested in isolation (unit / functional testing)
  - [ ] when tested e2e

:)

**Comment by frederikhors** [comment]
Env `LOG_LEVEL` is a perfect example of the problem I highlighted with this issue. In an environment where kratos coexists with other apps it can be a problem to understand who needs that env.

**Comment by aeneasr** [comment]
@frederikhors you can work around this like so:

```
LOG_LEVEL=info execute-your-app ...
LOG_LEVEL=debug kratos ...
```

**Comment by frederikhors** [comment]
Yes, it is a possibility that I have used before. But it is not practical, I repeat, if there are many variables together and especially if I have to change for example from Heroku without changing the start script, but only the environment variable.

I will gladly wait for the prefix on env vars. Thank you.

**Comment by frederikhors** [comment]
Is not something to do immediately but it will be usefuyto have in the future...

**Comment by aeneasr** [comment]
We are trying to cut down the number of configuration options available to reduce the complexity of setting up Ory. Therefore unfortunately I have to say that we do not plan to support prefixed env vars. Sorry @frederikhors :(

**Comment by renom** [comment]
Can I use shared envfile across ory services? (kratos, hydra, oathkeeper, keto)
Will env var names overlap / conflict?

**Comment by yasithab** [comment]
This is a valid question. In a Kubernetes environment, environment variables are shared within a namespace. For example, in a namespace called _staging_, running hundreds of applications could lead to conflicts if common environment variable names are used, as they can be overridden by other applications using the same names.

While there are workarounds, a better approach is to ensure that applications have unique environment variable prefixes. If this isn't being considered now, it should at least be taken into account in future versions of ORY apps, as this issue also applies to Hydra. Supporting user-defined environment prefixes or changing environment variable names to start with something unique, like ORY_HYDRA, could be the solution.
