### ISSUE TITLE
Courier Watcher should start a (tracing-) span

### ISSUE THREAD

**Issue by martinei** [ory/kratos#1886]
**Describe the bug**

If enabled "courier" runs every second and polls the table of mails to be send. The instrumented db driver then sends a number of spans to the tracing system (sql-tx-begin, sql-conn-query, sql-rows-next, sql-tx-rollback).
	
Those Spans are not correlated. I propose to add a "startSpan" (and span.finish) in courier.go watchMessages to get more readable traces.

**Reproducing the bug**

Enable a tracing provider and start kratos with "--watch-courier".
Lock at the 4 spans create every second.
<img width="1914" alt="grafik" src="https://user-images.githubusercontent.com/795323/138836598-a9814a6d-fd8c-4056-84fd-bed77e52a5ee.png">

**Expected behavior**

Here is how the traces should look using parent span.
![grafik](https://user-images.githubusercontent.com/795323/138836299-bbc0be92-7c8d-45a9-921d-5bd86211580a.png)

**Comment by alnr** [comment]
I believe this was fixed in the meantime. Please reopen if there's still a problem.
