### ISSUE TITLE
Quickstart Issues

### ISSUE THREAD

**Issue by Jaskerv** [ory/kratos#1909]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It seems that the quickstart has an issue with mailslurper. No emails are present in mailslurper when signing up.

Also in `Verify Account`, it is unclear what that text box is:
![image](https://user-images.githubusercontent.com/26532014/139600900-fbea1926-2bd5-41b8-89b5-c8b5ba56665b.png)

### Reproducing the bug

1. Run `docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate`
2. Go to `http://0.0.0.0:4455`
3. Click on `Sign Up`
4. Fill in details, click `Sign Up`
5. Go to `http://localhost:4436`
6. See no emails.

For UI issue.
1. Do sign up
2. Go to `Verify Account`
3. See no labeled required text field

### Version

0.8.0-alpha.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by Jaskerv** [comment]
Can this issue be reopened for the mailslurper issue?

**Comment by aeneasr** [comment]
Oh, sure!

**Comment by aeneasr** [comment]
However, I can't reproduce the mailslurper issue. I believe we had an issue with v0.8.0-alpha.1, but alpha.3 has resolved mailslurper issues. Can you check again?

<img width="1392" alt="Screenshot 2021-11-01 at 23 22 05" src="https://user-images.githubusercontent.com/3372410/139749821-2cddfd8b-a6f2-46f1-b3fa-9a4b7eaa1868.png">

**Comment by Jaskerv** [comment]
Sorry, after performing a clean start. It is indeed working. My apologies!
