### ISSUE TITLE
feat : update oidc tokens on login flow

### ISSUE THREAD

**Issue by david972** [ory/kratos#1912]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently Kratos record the token during the registration and the setting.

If the access_token recorded has expired in the meanwhile or tokens has been revoked it would be useful to update them.
I know in case of expiration we can use the refresh token but not in case of revocation.

Do you see a security concern to update the tokens on login ?

### Describe your ideal solution

I suggest to update oidc tokens on login flow

### Workarounds or alternatives

No workaround available at this moment

### Version

from v0.8.0-alpha.1

**Comment by aeneasr** [comment]
👍 

PRs welcomed!

**Comment by fehrnah** [comment]
If no one is working on this, I would like to give it a try

**Comment by aeneasr** [comment]
sure :)

**Comment by david972** [comment]
on this one #2428

**Comment by fehrnah** [comment]
Looking at your work, I think it would be easy to add #2326 on top of it. I can do it, but I am unsure what the best way to merge it would be.

**Comment by david972** [comment]
not sure is related

**Comment by AndersSoee** [comment]
Would it make sense to store these update tokens on the flow instead of (or in addition to) on the identity?
That would remove some possible race conditions, and would make it easier to couple an identity token to a flow that increases assurance level to perform critical tasks.
