### ISSUE TITLE
Failed to upgrade from 0.7.6-alpha1 -> 0.8.0-alpha3

### ISSUE THREAD

**Issue by meotimdihia** [ory/kratos#1915]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have got these errors from migration logs: 

```shell
kratos-migrate_1  | time=2021-11-01T04:27:48Z level=debug msg=Migration has not been applied but it might be a legacy migration, investigating. audience=application service_name=Ory Kratos service_version=v0.8.0-alpha.3 version=20210504121624000000
kratos-migrate_1  | time=2021-11-01T04:27:48Z level=debug msg=Migration has not yet been applied, running migration. audience=application service_name=Ory Kratos service_version=v0.8.0-alpha.3 version=20210504121624000000
kratos-migrate_1  | time=2021-11-01T04:27:48Z level=debug msg=0.2572 seconds audience=application service_name=Ory Kratos service_version=v0.8.0-alpha.3
kratos-migrate_1  | time=2021-11-01T04:27:48Z level=warning msg=Migrator: unable to dump schema audience=application error=map[message:open schema.sql: permission denied] service_name=Ory Kratos service_version=v0.8.0-alpha.3
kratos-migrate_1  | An error occurred while connecting to SQL: error executing migrations/sql/20210504121624000000_add_identity_states.postgres.up.sql, sql: ALTER TABLE "identities" ADD COLUMN "state" VARCHAR (255) NOT NULL DEFAULT 'active';: ERROR: column "state" of relation "identities" already exists (SQLSTATE 42701)
localhost_kratos-migrate_1 exited with code 1
```

Migration hasn't been finished. An error occurred when I tried to log in.
```
{"id":"d550f409-2d78-4ecc-94a7-27381c3dee39","error":{"code":500,"status":"Internal Server Error","message":"ERROR: column \"internal_context\" of relation \"selfservice_login_flows\" does not exist (SQLSTATE 42703)"},"created_at":"2021-11-01T04:27:41.524363Z","updated_at":"2021-11-01T04:27:41.524363Z"}
```

![WindowsTerminal_2021-11-01_11-32-48](https://user-images.githubusercontent.com/300961/139622043-9e8a3414-a307-4125-a6b2-21cb356c3f85.png)

### Reproducing the bug

`docker-compose -f quickstart.yml  up --build --force-recreate`

### Version

0.7.6-alpha1

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
A few questions:

* Is this affecting a production environment?
* Did the migrator crash or did you run restart something in docker?
* Have you tried reapplying the migration?
* Did you run any pre releases (e.g. your own builds from master branch)?
* Can you reproduce the issue reliably? If so, please provide steps.

Also can you please share the logs of your first migration attempt, and the full log output of the 0.8 migrator?

In general, we have tests for the migration and it passes so I assume it was a flake (e.g. container restarting unexpectedly)

**Comment by meotimdihia** [comment]
My production server is running Kratos 7.6-alpha-1.
I am testing in my PC first, and it failed.
I have a simple Dockerfile on my PC: 
```
version: '3.9'
# docker-compose -f quickstart.yml  up --build --force-recreate -d
services:
  kratos-migrate:
    image: oryd/kratos:v0.7.0-alpha.1
    volumes:
      - type: bind
        source: ./ory
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos2.yaml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.7.0-alpha.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos2.yaml --watch-courier
    volumes:
      - type: bind
        source: ./ory
        target: /etc/config/kratos
      - type: bind
        source: ./courier-templates
        target: /conf/courier-templates

    networks:
      - intranet
```

And I am using Postgresql. I did these steps: 

1. I replaced 0.7.0-alpha.1 => 0.8.0-alpha.3
2. and run the command: ` docker-compose -f quickstart.yml  up --build --force-recreate`.
3. I can't log in to the local website on my PC.
3. Switch back to 0.7.6-alpha.1 and it works again.
4. I switched between 0.7.6-alpha1 0.8.0-alpha.3 multiple times.

**Comment by samcgardner** [comment]
We're also seeing this. To answer your questions:

- Is this affecting a production environment?

Not for us, but I'm confident it would reproduce in one

- Did the migrator crash or did you run restart something in docker?

The migrator terminates with exit code 1 and message `An error occurred while connecting to SQL: error executing migrations/sql/20210817181232000006_unique_credentials.mysql.up.sql, sql: ALTER TABLE `identity_credential_identifiers` MODIFY `identity_credential_type_id` char(36) NOT NULL;: Error 1832: Cannot change column 'identity_credential_type_id': used in a foreign key constraint 'identity_credential_identifiers_type_id_fk_idx'`

- Have you tried reapplying the migration?

Yes, I get the same result every time

- Did you run any pre releases (e.g. your own builds from master branch)?

I can reproduce against a fresh database, so this issue is not directly caused by pre-releases.

- Can you reproduce the issue reliably? If so, please provide steps.

I built commit `810d39ae5982e3a015250483584d16e132d50ddf` and deployed with automigrate enabled to a completely blank database running the `5.7.mysql_aurora.2.10.0` engine.

**Comment by meotimdihia** [comment]
It looks like the file .sql is executed. But it didn't save to schema_migration.

**Comment by aeneasr** [comment]
@meotimdihia `docker-compose -f quickstart.yml up --build --force-recreate` uses SQLite, the opening post mentions postgres though?

**Comment by aeneasr** [comment]
Sorry, looks like I misread 😅

**Comment by meotimdihia** [comment]
@aeneasr it is named `quickstart.yml` but it is not the same as `quickstart.yml`  in Kratos guide. I have used Kratos from version 0.6 with this file.

I have fixed the problem by manually adding missing records in `schema_migartion`,  while running the command: `docker-compose -f quickstart.yml  up --build --force-recreate` repeatedly.

![image](https://user-images.githubusercontent.com/300961/139662981-4a0e4197-4459-4338-96c6-39bce97b5e12.png)

**Comment by aeneasr** [comment]
Ok, can you *please* provide the repo with your full config so that I can reproduce this issue? It is impossible to reproduce this stuff otherwise and I am not able to help you.

I just ran

```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.7.6-alpha.1
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
git checkout v0.8.0-alpha.3
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
```

and it works fine.

**Comment by aeneasr** [comment]
```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.7.6-alpha.1
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
git checkout v0.8.0-alpha.3
docker-compose -f quickstart.yml -f quickstart-standalone.yml -f quickstart-mysql.yml up --build --force-recreate
```

migrates without issues as well

**Comment by meotimdihia** [comment]
@aeneasr yes, I tried a clean installation with other databases on the same PC: 
`dsn: "postgres://username:password@host.docker.internal:5432/database1?sslmode=disable&max_conns=20&max_idle_conns=4"`
=> 
`dsn: "postgres://username:password@host.docker.internal:5432/newdatabase2?sslmode=disable&max_conns=20&max_idle_conns=4"`

And it works fine too. I can't reproduce it again.  😀

**Comment by aeneasr** [comment]
> We're also seeing this. To answer your questions:
> 
> * Is this affecting a production environment?
> 
> Not for us, but I'm confident it would reproduce in one
> 
> * Did the migrator crash or did you run restart something in docker?
> 
> The migrator terminates with exit code 1 and message `An error occurred while connecting to SQL: error executing migrations/sql/20210817181232000006_unique_credentials.mysql.up.sql, sql: ALTER TABLE `identity_credential_identifiers`MODIFY`identity_credential_type_id` char(36) NOT NULL;: Error 1832: Cannot change column 'identity_credential_type_id': used in a foreign key constraint 'identity_credential_identifiers_type_id_fk_idx'`
> 
> * Have you tried reapplying the migration?
> 
> Yes, I get the same result every time
> 
> * Did you run any pre releases (e.g. your own builds from master branch)?
> 
> I can reproduce against a fresh database, so this issue is not directly caused by pre-releases.
> 
> * Can you reproduce the issue reliably? If so, please provide steps.
> 
> I built commit `810d39ae5982e3a015250483584d16e132d50ddf` and deployed with automigrate enabled to a completely blank database running the `5.7.mysql_aurora.2.10.0` engine.

I can not reproduce your issue on vanilla MySQL:

```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.8.0-alpha.3
docker-compose -f quickstart.yml -f quickstart-standalone.yml -f quickstart-mysql.yml up --build --force-recreate
```

**Comment by meotimdihia** [comment]
I have upgraded my production server, and it is successful. But I get this warning when running `docker logs` on `kratos-migrate` container 

> An error occurred while connecting to SQL: error executing migrations/sql/20210816142650000004_flow_internal_context.postgres.up.sql, sql: UPDATE selfservice_registration_flows SET internal_context='{}';: ERROR: could not serialize access due to concurrent update (SQLSTATE 40001)

![WindowsTerminal_2021-11-02_15-26-04](https://user-images.githubusercontent.com/300961/139811383-e73a2330-1afb-4334-94e0-875e1a52684a.png)

I don't know if it is helpful, but it may hint about this bug.

**Comment by aeneasr** [comment]
Interesting, it *should* just restart this transaction if it fails - I assume that since it worked for you that is the case?

**Comment by meotimdihia** [comment]
@aeneasr I don't know if it restarted the transaction because the log doesn't show.
Everything is fine after upgrading. 😀

**Comment by aeneasr** [comment]
Ok, it's really hard to say what happened without more details. Unless someone else has this problem and an easy to reproduce example, I think we can close this issue as we did not observe any issues in our prod env, the tests are passing, and manually testing the upgrade also worked fine. What do you think?

**Comment by meotimdihia** [comment]
@aeneasr yes, it is fine with me. We can open it later if someone has the same problem and find out the reason.

**Comment by sazzle2611** [comment]
Just adding this for info... on a completely fresh install using the kratos helm chart version 0.21.5 and Percona XtraDB Cluster 5.7 database we got this error which is the same as @samcgardner 
```
An error occurred while connecting to SQL: error executing migrations/sql/20210817181232000006_unique_credentials.mysql.up.sql, sql: ALTER TABLE `identity_credential_identifiers` MODIFY `identity_credential_type_id` char(36) NOT NULL;: Error 1832: Cannot change column 'identity_credential_type_id': used in a foreign key constraint 'identity_credential_identifiers_type_id_fk_idx'
```
After several attempts with dropping all database tables in between then we took the manual approach which was to delete the foreign key constraint identity_credential_identifiers_type_id_fk_idx from the table identity_credential_identifiers, then run the alter query in the error message and add back the foreign key constraint.

The migration job then completed.
