### ISSUE TITLE
feat: Add hookType to the templateContext struct

### ISSUE THREAD

**Issue by abador** [ory/kratos#1949]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Sometimes we need to know from what hook and/or stage a web-hook is being called. In case of kratos misconfiguration we might end up calling a hook at a wrong stage and there is no way to debug this

### Describe your ideal solution

We can add additional context in the templateContext struct so if we need to we can use that field in our web-hook calls

### Workarounds or alternatives

this is just handy for global hooks

### Version

0.7 + in-house patches(with https://github.com/ory/kratos/pull/1585/files)

### Additional Context

We can port those changes to upstream pretty easily

**Comment by aeneasr** [comment]
SGTM
