### ISSUE TITLE
feat: Add config support to the web-hook client

### ISSUE THREAD

**Issue by abador** [ory/kratos#1950]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We want to be able to set our own web-hook client configs like:

- number of retries
- status codes that stop retries and log failures

### Describe your ideal solution

We can add configuration and read it during client creation or we can define a config for every web-hook individually

### Workarounds or alternatives

Not much to do, the client is initialized with a default config. Sending 2XX status codes even if something didn't go as planned

### Version

0.7 + in-house patches(with https://github.com/ory/kratos/pull/1585/files)

**Comment by aeneasr** [comment]
SGTM
