### ISSUE TITLE
WebAuth docs are missing

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#1951]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

https://www.ory.sh/kratos/docs/concepts/credentials/webauthn

### Reproducing the bug

-

### Version

master

**Comment by vinckr** [comment]
https://www.ory.sh/kratos/docs/self-service/flows/2fa-mfa-multi-factor-authentication

This is also missing and pointing to a closed issue?

**Comment by aeneasr** [comment]
You're correct!

**Comment by afreakk** [comment]
Is this the reason dotnet SDK is silently failing with:
```
Error converting value "webauthn" to type 'System.Nullable`1[Ory.Kratos.Client.Model.KratosSessionAuthenticationMethod+MethodEnum]'. Path 'authentication_methods[1].method', line 1, position 306.
```
Webauthn is missing from 
`public enum MethodEnum`

Happened on `.ToSession()` call
(Annoying that it silently fails when return code is 200, and it fails to deserialize the response, takes a while to figure out whats going wrong)

**Comment by aeneasr** [comment]
fixed
