### ISSUE TITLE
Conflicting message IDs for node and verification

### ISSUE THREAD

**Issue by jstsddg** [ory/kratos#1956]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The message IDs in the files `text/message_verification.go` and `text/message_node.go` start at the same ID `1070000`, hence there are conflicting IDs. This causes a problem when implementing custom translations in the _self-service UI_, because messages can not identified uniquely.

See:
* https://github.com/ory/kratos/blob/fc17cf8737ff6ebbe00be8399b1a423a0888b670/text/message_node.go#L4
* https://github.com/ory/kratos/blob/a307deb6779dacd2ce54e161a00d347600d2c583/text/message_verification.go#L9

### Reproducing the bug

No specific steps are needed.

### Version

v0.8.0-alpha.3 (master)

**Comment by aeneasr** [comment]
Nice find, would you be open for a fix?

**Comment by jstsddg** [comment]
Yes I can do that, I would suggest updating `text/message_node.go` to `1080000` as this ID range seems to be unused. Do you know of any side effects this change could have? Or can the starting ID simply be updated?

**Comment by aeneasr** [comment]
It can be updated, but we will need to document this as a breaking change!

**Comment by zepatrik** [comment]
The referenced commit does not actually solve this problem but a different one with duplicate IDs.

**Comment by aeneasr** [comment]
my bad
