### ISSUE TITLE
Can not disable sqa-opt-out

### ISSUE THREAD

**Issue by hbrls** [ory/kratos#1959]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Can not disable SQA.

By any or all of the following:

1. env: SQA_OPT_OUT=true
2. env: SQA-OPT-OUT=true
3. yml: sqa-opt-out: true

And the docs about the option spelling are not consistent. [kratos/docs/reference/configuration.md](https://github.com/ory/kratos/blob/master/docs/docs/reference/configuration.md)

### Reproducing the bug

```
hub.docker.com
oryd/kratos   v0.7.6   5a536e1661d5
```

### Relevant log output

```shell
kratos                 | time=2021-11-17T06:43:51Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name=Ory Kratos service_version=v0.7.6-alpha.1
```

### Version

0.7.6

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Try passing it as a flag `kratos serve --sqa-opt-out`

**Comment by hbrls** [comment]
> Try passing it as a flag `kratos serve --sqa-opt-out`

This works. The warning logging disapears.

**Comment by tristanls** [comment]
> Try passing it as a flag kratos serve --sqa-opt-out
This is not possible when using a helm chart. Opened https://github.com/ory/k8s/pull/375 to address.

**Comment by aeneasr** [comment]
Looks like the problem is that we expect sqa to be a top level key in the config, but did not define it like that in the json schrma here. Maybe adding a simple os.Getenv fallback is enough to ensure no regressions happen: https://github.com/ory/x/blob/2459f60c4885e9966b6585bc33f83366a43b52f8/metricsx/middleware.go#L175
