### ISSUE TITLE
Kratos courier: can't evaluate field Identity

### ISSUE THREAD

**Issue by viters** [ory/kratos#1960]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am trying to use Identity in email templates, according to documentation https://www.ory.sh/kratos/docs/concepts/email-sms/#the-identity-attribute.

If I use `.Identity` in template, process breaks.
![obraz](https://user-images.githubusercontent.com/13100466/142287055-ea19c7a4-3825-47b8-9633-14e77b669430.png)

### Reproducing the bug

1. Run Kratos without courier.
2. Run standalone courier.
3. Mount templates to both Kratos and Courier and use `.Identity`.
4. Send email.

### Relevant log output

```shell
time=2021-11-17T21:11:17Z level=error msg=Unable to get email body from template. audience=application error=map[message:template: verification/valid/email.body.gotmpl:144:167: executing "verification/valid/email.body.gotmpl" at <.Identity.traits.name.first>: can't evaluate field Identity in type *template.VerificationValidModel] message_id=bfa3fcf7-3130-4a0b-861f-3f2168bb9d6e service_name=Ory Kratos service_version=v0.8.0-alpha.3
time=2021-11-17T21:15:46Z level=error msg=Unable to get email body from template. audience=application error=map[message:template: recovery/valid/email.body.gotmpl:144:167: executing "recovery/valid/email.body.gotmpl" at <.Identity.traits.name.first>: can't evaluate field Identity in type *template.RecoveryValidModel] message_id=f59ae8a4-5738-4069-a808-07a7f91ece27 service_name=Ory Kratos service_version=v0.8.0-alpha.3
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by viters** [comment]
One more thing, that is kinda counter intuitive:
If separate Kratos courier is used, all templates must be mount both to Kratos and courier. If templates are mount only to courier, only HTML template is applied.

**Comment by aeneasr** [comment]
Interesting find! Bugfixes welcomed :)

> One more thing, that is kinda counter intuitive:
If separate Kratos courier is used, all templates must be mounted both to Kratos and courier. If templates are mounted only to courier, only HTML template is applied.

Isn't this done automatically for our helm charts?

**Comment by viters** [comment]
> Interesting find! Bugfixes welcomed :)

I will try to check it out at the weekend.

> Isn't this done automatically for our helm charts?

Yeah it is, tbh I forgot about them. You are right that Helm charts provide a proper way of attaching those templates. Maybe it would be useful to add a sentence to https://www.ory.sh/kratos/docs/concepts/email-sms/#multi-instance, like "If you are using custom email templates, please remember to provide them both to Kratos and courier."

**Comment by aeneasr** [comment]
> Yeah it is, tbh I forgot about them. You are right that Helm charts provide a proper way of attaching those templates. Maybe it would be useful to add a sentence to https://www.ory.sh/kratos/docs/concepts/email-sms/#multi-instance, like "If you are using custom email templates, please remember to provide them both to Kratos and courier."

Accepting PRs :)

**Comment by jim-obrien-orig** [comment]
I'm not sure why the title for this bug is "separate courier" - this happens regardless of whether a separate courier is used.

**Comment by aeneasr** [comment]
I took a look at the code base, and the `Identity` field is currently available for recovery but not verification. Another issue is probably the access, in Go the type is a `map[string]interface{}`, so access would probably be along the lines of `.Identity.["traits"]["email"]` although I'm not 100% sure that works due to type assertions. We might need some type of template helper for this

**Comment by aeneasr** [comment]
Looks like we have index for this: https://stackoverflow.com/questions/26152088/access-a-map-value-using-a-variable-key-in-a-go-template

**Comment by viters** [comment]
@aeneasr 

This issue comes from the requirement of multilanguage / multitenant mailings. If we do not have access to `Identity` in the email template, I suppose it is impossible to e.g. localize them?

I had an idea that we could run separate Kratos instances and load balance to them based on certain rules (like Accept-Language), and those instances would have different email templates. That looks impossible, because email templates need to be provided to courier as well? TBH, should courier have access / use templates? I mean, Kratos should create an email job, the job should contain the final HTML and text - then courier should just pick the job up and send emails - courier should not fill the template by itself.

**Comment by viters** [comment]
@aeneasr 

I have tested it today on v0.10.1 and seems that everything is working fine. `Identity` is accessible both in verification and recovery, and https://www.ory.sh/docs/kratos/concepts/email-sms#example-i18n-customization works exactly as expected. I am closing the issue then!

**Comment by Igosuki** [comment]
@viters I came upon this error today, it seems Identity is not available in the context of invalid recovery etc flows

**Comment by viters** [comment]
@Igosuki 
I think there cannot be an `Identity` in invalid flows - mainly for practical reasons, but it is also reasonable from security reasons. AFAIK invalid flows are used when flows are initiated for non-existing account (refer to defaults on https://github.com/ory/kratos/tree/master/courier/template/courier/builtin/templates). Without account, there is just no `Identity`.

**Comment by mserikov** [comment]
> @Igosuki I think there cannot be an `Identity` in invalid flows - mainly for practical reasons, but it is also reasonable from security reasons. AFAIK invalid flows are used when flows are initiated for non-existing account (refer to defaults on https://github.com/ory/kratos/tree/master/courier/template/courier/builtin/templates). Without account, there is just no `Identity`.

Hi, @viters. We're using our custom template builder config for all email templates, valid and invalid.
Here's code example of `email.body.gotmpl`:

`
{{- if eq .Identity nil -}}
{{ template "email.body.en.gotmpl" . }}
{{- else if eq .Identity.traits.locale "de" -}}
{{ template "email.body.de.gotmpl" . }}
{{- else if eq .Identity.traits.locale "es" -}}
{{ template "email.body.es.gotmpl" . }}
{{- else if eq .Identity.traits.locale "fr" -}}
{{ template "email.body.fr.gotmpl" . }}
{{- else if eq .Identity.traits.locale "it" -}}
{{ template "email.body.it.gotmpl" . }}
{{- else if eq .Identity.traits.locale "ja" -}}
{{ template "email.body.ja.gotmpl" . }}
{{- else if eq .Identity.traits.locale "nl" -}}
{{ template "email.body.nl.gotmpl" . }}
{{- else if eq .Identity.traits.locale "pt" -}}
{{ template "email.body.pt.gotmpl" . }}
{{- else if eq .Identity.traits.locale "zh" -}}
{{ template "email.body.zh.gotmpl" . }}
{{- else -}}
{{ template "email.body.en.gotmpl" . }}
{{- end -}}
`
It works for valid templates, but in case when we don't have .Identity it fails with error `"template: email.subject.gotmpl:1:10: executing \"email.subject.gotmpl\" at \u003c.Identity\u003e: can't evaluate field Identity in type *email.RecoveryCodeInvalidModel"`.
 
I'm not familiar with gotmpl syntax at all. Could you please clarify, how should I fix the first line `{{- if eq .Identity nil -}}` to ensure that .Identity field is empty and use `email.body.en.gotmpl` in that case?

**Comment by Igosuki** [comment]
The issue is that comms without internationalization is pretty useless. Having the locale available somewhere in there is a requirement for me.

**Comment by viters** [comment]
@mserikov 
I am afraid there is no built-in go template way to check if key exists on struct. You would need to define your own function using `reflect` and expose it to templates, which seems hard to do if you do not want to fork Kratos. I just advise against mixing valid and invalid templates.

@Igosuki 
Let's keep productive and thread-related. This issue is referring to `Identity` exposure in valid templates and it has been fixed. `Identity` contains an identity related to the email - and there is no such thing in invalid flows. 

I understand your concern that exposing `Identity` is not solving the full i18n. An example solution based on `Accept-Language` or other language context, which is later exposed to the email, would be probably more general and work for invalid flows as well - but there is no such feature in Kratos yet. So if you need it - think it through and post an RFC.

If you need a fast workaround - you can experiment with multiple Kratos / couriers instances. You can run a different instance (or multiple, but one courier) per each language and use a middleware to route the traffic based on whatever you like: path param, query param or header.
