### ISSUE TITLE
feat: implement include_credential for oidc tokens in cmd

### ISSUE THREAD

**Issue by AlexandreBrg** [ory/kratos#1970]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The new feature implemented in #1818 adds a new query param into route `GET /admin/identities/:id`. Cmd doesn't implement this query param, so we can't fetch oidc tokens. 

### Describe your ideal solution

Add a cmd flag so for command `kratos identities get ${ID}` we can fetch tokens. 

I suggest adding a flag named `--oidc` to solve the problem. Also, I don't know how to name the alias of `--oidc` as `-o` can be used in the future to define an output file ?  

### Workarounds or alternatives

A workaround for now is to keep using the API to fetch identities

### Version

from v0.8.0-alpha.3

**Comment by aeneasr** [comment]
I'd say it should be `--include-credential oidc` as that allows us to expand it later on: `--include-credential oidc --include-credential webauthn`.

PRs welcomed!
