### ISSUE TITLE
Issue with the quickstart build failure

### ISSUE THREAD

**Issue by enterprisevik** [ory/kratos#198]
**Describe the bug**
The issue is linked to the initial build failure on local also when looked in the docker hub repo the kratos image was missing from there.

**Reproducing the bug**
Please refer the docs and follow the steps to setup the kratos
https://www.ory.sh/docs/next/kratos/quickstart

```kratos git:(master) make quickstart
docker pull oryd/kratos:latest
Error response from daemon: pull access denied for oryd/kratos, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [quickstart] Error 1
```
or 
```
git clone https://github.com/ory/kratos.git
# or if you have git+ssh set up:
#  git clone https://github.com/ory/kratos.git
cd kratos
make quickstart

# or if you don't have make installed:
docker pull oryd/kratos:latest
docker pull oryd/kratos-selfservice-ui-node:latest
docker-compose -f quickstart.yml up --build --force-recreate
```
None . of the steps works as expected

**Comment by aeneasr** [comment]
Thank you for checking this out. Kratos is not yet released, we're still working on the release pipeline (you might have noticed that binaries are missing and tag 0.1.0 is not published yet). You can probably work with `make quickstart-dev` but no guarantees.

**Comment by enterprisevik** [comment]
The above mentioned solution works but seems like the services are not reachable as the auth login renders the login page with request id but its not functional further with sign in or register process.

As its not a public release truly understand the breaking changes. looking ahead for the stable version. Once the release is stable I would be contributing for the twillo and plivo integration in upcoming days for the the sms based one time password feature.

**Comment by aeneasr** [comment]
Awesome! You're probably seeing an older version of the login page which was incapable of rendering error messages. We've fixed that on the current master of https://github.com/ory/kratos-selfservice-ui-node. The README has instructions on building the image for the quickstart. Make sure to comment out `docker pull oryd/kratos-selfservice...` in the Makefile task `quickstart-dev`

Awesome that you want to contribute! We're still lacking a 2FA process as a whole so we have to design that first and add some pluggable connectors for 2FA systems.

Before doing that we'll release 0.1.0-alpha.1 which still needs two PRs as those would break the API in the next release (so we want to do that in this one). You can follow our development process in the [milestones](https://github.com/ory/kratos/milestones) and [project board](https://github.com/orgs/ory/projects/8)

**Comment by enterprisevik** [comment]
Will try to rebuild it and see if it works.
I am already following the ory since last one year, have used almost keycloak, glu and custom oauth implementation but every product has a different complexity of either database dependency or the architecture.  It was a sort of compromise with every solution happy to see ory is changing the dimension of app security.

**Comment by aeneasr** [comment]
Thank you for these kind words, we hope that we can live up to the expectations :)

**Comment by aeneasr** [comment]
I'll be closing this because I think the question is answered and because the quickstart guide will work as soon as the 0.1.0 release is out.
