### ISSUE TITLE
Support for multiple UI login like the return_to param

### ISSUE THREAD

**Issue by Lykos94** [ory/kratos#1982]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I may have missed this feature, but in case here is my use case: I have two applications that use the same identification process and identities. The `return_to` feature allows me to redirect after the login flow to the correct application, but still the login UI url is only one, the one i put in my kratos.yml configuration.

### Describe your ideal solution

I would like to have the possibility to change the UI url for the login with a solution like the `return_to` parameter, something like `ui_login_url` query, but I'm not sure about security issues implication with such solution. Another way could be having a mapping in the kratos.yml for the login UI url in the form `return_to_url: login_ui_url` in order to not expose the parameter. 

### Workarounds or alternatives

Actually, the only thing I can think of right now is having 2 separate instances of kratos, one for each application with differen ui_login url in the configuration

### Version

0.8

### Additional Context

Please feel free to close this issue if I have missed this feature and there is already a solution for that

**Comment by aeneasr** [comment]
You can implement such a redirect to app A/B in a pseudo login app which you have registered in kratos. This is the best way to achieve this.

**Comment by Lykos94** [comment]
Makes sense, I'll do it how you suggested. Thank you

**Comment by aeneasr** [comment]
👍
