### ISSUE TITLE
Allow attaching credentials to identities in CRUD create

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#200]
**Is your feature request related to a problem? Please describe.**

It's currently not possible to create an identity and attach credentials to it using the admin endpoints. This is important though as we might want to have privileged user creation (e.g. within organizations) or because we want to import users from another system.

**Comment by sdalezman** [comment]
This is also important to be able to deploy Kratos to existing systems. You may have a lot of users you need to pull in. 

On that note - I'm not sure I've seen it's possible to set hashing techniques on a per account basis. 

For example you may have imports from systems that had used bcrypt and need to able to support those users logging in.

**Comment by aeneasr** [comment]
Yeah absolutely. There are two ways to achieve multiple hashing sources:

- Require account recovery for everyone without an Argon2 hash
- Require a password update after successful login with the old password

We definitely want to support this feature but for the 0.1.x releases we'll be focusing on new systems before shifting focus to import/export and admin features.

**Comment by aeneasr** [comment]
I overlooked this issue while creating #605 - closing as a dupe.
