### ISSUE TITLE
Provide user last login time as a part of user identities list response

### ISSUE THREAD

**Issue by LeonidChistov** [ory/kratos#2007]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Consider an application with user management UI built on top of Kratos software.

We think it would be useful for administrator to be able to see last login time for every user.

_Case 1_

In a closed system, where user can only login after an invitation from administrator, it is important to understand whether user has ever logged in.

Based on this information, administrator might make a decision about account deactivation or deletion or contacting user via email.

_Case 2_

Find "frozen" users who did not log in for a very long time.

Based on this information, administrator might make a decision about account deactivation or deletion or contacting user via email.

Also, based on this information, special application policy for user email notifications (about new application features, etc) might be implemented.

_Case 3_

Let administrator or other users see person activity status in several UI scenarios:

- Annual review of granted permissions
- Decision to share or unshare specific resource (document)

_Case 4_

Show special onboarding screen or new feature tutorial screen to users who login for the first time or login after some application feature is implemented.

### Describe your ideal solution

Call to `List Identities` (https://www.ory.sh/kratos/docs/reference/api#operation/adminListIdentities) HTTP method shall return last login time as a part of Identity data structure for every user.

### Workarounds or alternatives

It looks like that two workarounds exist for the first case, where we only need to understand if user has ever logged in:

- Demand email verification and use verification status to understand if user has ever logged in
- Demand users to set password on initial login and use `updated_at` attribute of Identity data structure

### Version

0.7

**Comment by aeneasr** [comment]
One option you have right now is to check the sessions of a user. Those will include the latest log in times :) This will be fully available once #2011 is merged!

**Comment by LeonidChistov** [comment]
@aeneasr Thanks! One thing that I could not directly understand from https://github.com/ory/kratos/pull/2011 is a paging response format. Does it provide a total count of sessions in the response?

I mean - would it be quick and simple enough to get the last page (containing latest sessions) or one will have iterate through all pages?
