### ISSUE TITLE
kratos dotnet SDK webauthn deserialization.

### ISSUE THREAD

**Issue by afreakk** [ory/kratos#2026]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Webauthn is missing from
`public enum MethodEnum`

### Reproducing the bug

1. Have a user with enabled webauthn.
2. Call `.ToSession()` with the users cookie.
3. `ToSession()` will return `null` because it couldnt deserialize response from kratos.
4. With step-debugger, you can see why it fails.

### Relevant log output

```shell
Error converting value "webauthn" to type 'System.Nullable`1[Ory.Kratos.Client.Model.KratosSessionAuthenticationMethod+MethodEnum]'. Path 'authentication_methods[1].method', line 1, position 306.
```
```


### Relevant configuration

_No response_

### Version

SDK:  0.8.0-alpha.2
Kratos: 0.8.0-alpha.3

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_
```
### Additional Context

Another related issue is, when you remove webauthn from account-settings, you get this view with self-service:
![image](https://user-images.githubusercontent.com/2227028/144850446-332ac0a0-fb99-4fda-890b-39f3635fe358.png)

**Comment by aeneasr** [comment]
Thank you for the report, that looks indeed like an issue in our SDK definitions!

**Comment by aeneasr** [comment]
Should be resolved on master
