### ISSUE TITLE
E-mail verification link does not sign you in nor redirect to where you started

### ISSUE THREAD

**Issue by mitar** [ory/kratos#2031]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

This is a problem if app wants to require verified e-mail address. The problem is that in that case the app blocks the initial redirect back after registration, showing the user message that they have to go to the e-mail client and click on the verification link. But there is a problem:
* User might open the e-mail verification link in a different browser or [browser container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) (e.g., on iPhone opening a page from an app can have different cookies than from a regular browser) so that the user is not signed in. Opening the link still verifies the account automatically (which is a problem, [#1451](https://github.com/ory/kratos/issues/1451#issuecomment-987808913)) but do not sign you in. I think there should be at least an option if not default (or only) behavior to also sign in the user at that point. Of course after singing you in, it should also redirect you to where you came from originally.
* If user is signed in and they click on the verification link, the user is redirected back to the default landing page and not to the page where they came from originally.

### Reproducing the bug

1. Follow the [quickstart](https://www.ory.sh/kratos/docs/quickstart/) to get Kratos running.
2. Open http://127.0.0.1:4455/settings to access a page which requires authentication.
3. You get redirected to http://127.0.0.1:4455/login?flow=e08be8aa-01df-475e-98ea-f7af07029cbf.
4. Sign in OR create account.
5. You are redirected to http://127.0.0.1:4455/welcome, imagine that this shows an error that you have to verify the e-mail address.
6. Go to your e-mail client and click on the verification link.
7. You are redirected to http://127.0.0.1:4455/welcome and NOT to http://127.0.0.1:4455/settings.

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by meyfa** [comment]
> I think there should be at least an option if not default (or only) behavior to also sign in the user at that point.

This should definitely NOT be the only behavior (though making it configurable sounds great!). For the product we are developing, we need to derive additional cryptographic keys from the user's credentials on login for zero-knowledge stuff. If Kratos were to log the user in without ever entering any password at all, this would break everything.

**Comment by mitar** [comment]
Why do you need to do that after email verification? You can do that on account setup, when you are hashing the password, also generate keys.

**Comment by meyfa** [comment]
The keys need to stay completely client-side, so it needs to happen every time a session is set up. Either way, my point is, that being able to configure this feature to fit individual use cases would be great :)

On a different note, I think there might be security considerations with blindly signing someone in solely based on their access to the email account. Think family-shared inboxes. Or someone enters the wrong email address (not their own), and suddenly a third party has access to the account.

Perhaps that is a more general reason why you might not want this behavior for every application.

**Comment by aeneasr** [comment]
> If user is signed in and they click on the verification link, the user is redirected back to the default landing page and not to the page where they came from originally.

You can customize this behavior by appending a `return_to` query parameter to the initial call (either registration endpoint, or verification endpoint). Alternatively you can customize the return address on several levels in the config. In the reproducible case listed you would call `http://127.0.0.1:4455/login?return_to=/settings`! This is probably not the case for our example app, which just returns you to the login endpoint without appending the return_to. Ory Kratos though is capable of tracing the return address across those flows!

> I think there should be at least an option if not default (or only) behavior to also sign in the user at that point. Of course after singing you in, it should also redirect you to where you came from originally.

Verification is generally seen as verifying ownership of an address, not a method to authenticate. While it often still is the case (e.g. password reset link gets sent to your email) it is not **always** the case and the two are different concepts. This is also important because account verification links or codes are usually valid for a longer period of time (e.g. 24 hours) than password reset links (usually valid for a couple of minutes). Therefore, I really wouldn't want to mix the two!

**Comment by mitar** [comment]
> Ory Kratos though is capable of tracing the return address across those flows!

Just to confirm, does it trace the return also after the verification of an address?

> Therefore, I really wouldn't want to mix the two!

Sure. So I can then make it so that after user clicks on a verification link, e-mail is verified and a sign in form is shown, after user signs-in, the user is redirected to what was initially set to `return_to` (e.g., `/settings`).

**Comment by kmherrmann** [comment]
I believe this was addressed in the meantime. please re-open if needed.
