### ISSUE TITLE
A valid session was detected and thus recovery is not possible

### ISSUE THREAD

**Issue by lanphan** [ory/kratos#2034]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

when I open recovery link from email, I always got error "A valid session was detected and thus recovery is not possible"

### Reproducing the bug

* Log into web app, got cookie
* Logout, cookie is still in browser (just because I set persistent for my session cookie)
* When I open recovery link, it raises error "A valid session was detected and thus recovery is not possible."

I think this is a bug, because session cookie is available, but it's not valid yet (because I did logout in step #2 above)

### Version

0.7.6

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by aeneasr** [comment]
Nice find, that’s definitely a bug! Contributions welcomed :)

**Comment by lanphan** [comment]
This is false alarm, kratos already covers this usecase.
Close this.
