### ISSUE TITLE
"page" REST API parameter is confusing

### ISSUE THREAD

**Issue by mitar** [ory/kratos#2039]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Reading [here](https://www.ory.sh/kratos/docs/next/concepts/rest-api) it says:

> Pages are created based on the values of per_page and page provided in the querystring, where per_page is the page size, and page is the current page.
> In most scenarios, the per_page should be a multiple of the page.

And example has the current `page` at 10, page size at 5, and then the next `page` is 15. This looks to me like `page` should be named `offset`. `page` is generally used when you compute offset by doing `page` * `per_page`. How it is used in Kratos it should be named `offset`.

### Reproducing the bug

See description above.

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
In Kratos `page` is a page and not an offset and you don't need to compute the page, it's always sequential (1,2,3,4,5). Could you update the docs with a wording that makes that easier to understand for you?

**Comment by mitar** [comment]
I mean, the example is then wrong. The example has previous/next links and they increase in the `per_page` amount. I can make a PR.
