### ISSUE TITLE
Document how to run with AWS Aurora Serverless MySQL 

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2044]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

AWS Aurora Serverless MySQL blocks setting column as NOT NULL if there is a foreign key constraint with the column.

Originally reported by @splaunov in #1984

### Describe your ideal solution

Ory Kratos works with AWS Aurora MySQL.

### Workarounds or alternatives

Inquire at AWS why this behaviour differs from official MySQL and wether it's a bug, a limitation, or if there is another workaround to this.

### Version

master

### Additional Context

Potential solutions:

1. Set `SET FOREIGN_KEY_CHECKS = 0;` for the period of the migrations (we do not think this is a good idea as it could lead to a broken database state)
2. Add the possibility to detect AWS AuroraDB in [gobuffalo/fizz](https://github.com/gobuffalo/fizz) and [gobuffalo/pop](https://github.com/gobuffalo/pop) and then add specific AuroraDB migrations which override the MySQL migrations

Given that AWS Aurora is a proprietary fork of MySQL, and does not follow MySQL compatibility, we might close this if AWS can not offer a workaround as we want to avoid adding too many database integration systems.

This is especially true since I don't know of an easy way to test the AWS Aurora integration without having an AWS account - which is a nogo for this project as it hinders the community from doing additional contributions.

**Comment by aeneasr** [comment]
For more details see: https://github.com/ory/kratos/issues/2167#issuecomment-1023556058

**Comment by splaunov** [comment]
https://repost.aws/questions/QUxS9khe0VTxaHMd6ViWIKrg/cannot-change-column-used-in-a-foreign-key-constraint

**Comment by DeepDiver1975** [comment]
Would it be an option to create a full schema dump as of a specific version which can be applied without running all the migrations? This was this specific issue can be bypassed at least for an initial installation.
