### ISSUE TITLE
Recovery link answers with JSON payload for API flows

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2049]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When initializing a recovery or verification link using an API flow, and then clicking on the link, the browser shows a JSON instead of the UI

### Reproducing the bug

Not sure yet

### Version

v0.8.0-alpha.4

**Comment by aeneasr** [comment]
Reported by @sashatalalasha

**Comment by Demonsthere** [comment]
Context: issue related to link expiration.

**Comment by Demonsthere** [comment]
Judging from the JSON response sample, the request_url was missing the return_to parameter: `"request_url":"http://foobar.com/self-service/registration/api?return_to=`
