### ISSUE TITLE
URL with hash sign in after_verification_return_to stays encoded when redirect user in browser

### ISSUE THREAD

**Issue by LukasRada** [ory/kratos#2068]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'd like to redirect a user to dynamic URL after the user is registered and clicked verification link in email. So I need to set `after_verification_return_to` to query string in URL for registration flow. The issue is the dynamic URL includes hash sign (`#` - fragment) with some string and Kratos server redirects user to the dynamic URL but with encoded hash sign (`%23`). Other parts of the URL are decoded properly.

In other words, value of `after_verification_return_to` at registration flow is not the same value where the user is redirected after the user clicked the link in verification email.

### Reproducing the bug

1. Run Kratos instance in docker
2. Complete browser-based user registration with `after_verification_return_to` in URL query string, where the value of `after_verification_return_to` is URL with fragment.
3. Click on verification link in email.
4. After Kratos verifies the link, user is redirected with `Location` header in response with value `after_verification_return_to` but with encoded hash sign (the fragment part of URL)

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

Another communication of this issue on Slack: https://ory-community.slack.com/archives/C012RJ2MQ1H/p1639578551097000
@zepatrik suggested it might be regression of #1040

Technically: the issue could be really the change mentioned in #1040 because it changes implementation. Usage of `url.ParseRequestURI` vs. `url.Parse`
![image](https://user-images.githubusercontent.com/7394177/146224133-70979cfb-4128-4997-a039-f637b74279b2.png)

Could someone please verify the hypothesis?

**Comment by aeneasr** [comment]
We can probably switch back to url.Parse :)

**Comment by LukasRada** [comment]
Are you open to PR to fix this issue? We could probably fix the issue.

**Comment by aeneasr** [comment]
Absolutely
