### ISSUE TITLE
Parameter forwarding to OIDC auth URL

### ISSUE THREAD

**Issue by gingerich** [ory/kratos#2069]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I'm connecting to a OIDC provider that accepts query params described in the [OIDC specification](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest). In particular, I need to pass the `login_hint` query param to the auth URL. This is a per-request value so it can't be a config value or hardcoded in a OIDC strategy. 

For example, Keycloak's auth request supports parameter forwarding to the auth URL of any upstream IdPs. https://www.keycloak.org/docs/latest/securing_apps/#_params_forwarding

For context, the flow I'm trying to achieve is
1. Show form with only email input
2. User submits email and my server-side code checks if they should auth via OIDC based on the email domain
3. If so, user is redirected to the OIDC provider which pre-fills their email address in the login form
4. Otherwise, show password input and submit as usual

### Describe your ideal solution

When submitting a login/registration flow where `method: 'oidc'`, I'd like to pass extra arguments that will be forwarded as query params to the auth url of the oidc provider. I think adding a `params` object to the submit payload containing key/value parameters would be a feasible solution for this.

### Workarounds or alternatives

I haven't found any suitable workarounds yet.

### Version

v0.8.0-alpha.3

**Comment by aeneasr** [comment]
That's a valid point! Do you need to set these always from the callee or do you want to set those globally per provider?

**Comment by gingerich** [comment]
In my case I need to always pass the `login_hint` value from the callee. But I could see in other cases it may be useful to configure auth params globally for a provider.

**Comment by aeneasr** [comment]
Ok, got it. I think we could include parameters which would be set by clients usually (such as login_hint, or locale). Would you be interested in contributing this change? First we should agree on a list of parameters that should be passable.

**Comment by gingerich** [comment]
I have limited experience with Golang but I'm happy to take a stab at it since the scope is small and seems pretty straightforward. I'll put together a brief proposal before I get started, including a parameter list to agree on.

**Comment by aeneasr** [comment]
@Benehiko is actually working on this atm
