### ISSUE TITLE
Wrong port in quickstart

### ISSUE THREAD

**Issue by jblachly** [ory/kratos#2095]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The Ory Kratos quickstart guide mentions port 4434 when it should mention the public API port, 4433.

```
/auth/login redirected you to http://127.0.0.1:4434/self-service/login/browser, which is one of Ory Kratos' APIs used for logging in browser-based applications.
```

This is confusing for a new user reading through the quickstart.

### Reproducing the bug

https://www.ory.sh/kratos/docs/quickstart

### Version

0.7

**Comment by aeneasr** [comment]
Thank you! Would you be open to fix this in a PR? :)

**Comment by jblachly** [comment]
Am on mobile ; will try to when I can fork and pr
