### ISSUE TITLE
Internal Server Error on failed request to Have I Been Pwned

### ISSUE THREAD

**Issue by MicLeey** [ory/kratos#2145]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

This is rare, and it doesn't happen when I choose a certain password over another. 

![image](https://user-images.githubusercontent.com/15386836/149510912-e584a2db-ca85-4f12-a999-f205bcb0aced.png)

### Reproducing the bug

1. Register
2. Hope a request to HIBP fails :)

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Ory Cloud

### In which environment are you deploying?

Ory Cloud

**Comment by aeneasr** [comment]
I received this error in the tests:

```
An error occurred: 500 Internal Server Error
body: {
  "error": {
    "code": 500,
    "status": "Internal Server Error",
    "reason": "Expected password hash from remote to contain two parts separated by a double dot but got: [A8EF9E] (A8EF9E)",
    "message": "An internal server error occurred, please contact the system administrator"
  }
}
```
