### ISSUE TITLE
Identify oidc Microsoft user by id received from https://graph.microsoft.com/v1.0/me

### ISSUE THREAD

**Issue by splaunov** [ory/kratos#2150]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

In PHP world the socialite lib is a popular solution for OAuth logins such as Google, Apple and others.
In case of Microsoft provider they read user info from https://graph.microsoft.com/v1.0/me instead of the standard OAuth `userinfo` endpoint. This means that such users are identified by id received from `me` endpoint and not by `sub` field from `userinfo`.
[https://github.com/SocialiteProviders/Microsoft/blob/3f4ec79e65c3a403a5fe70cccd28d23802f1981e/Provider.php#L64](https://github.com/SocialiteProviders/Microsoft/blob/3f4ec79e65c3a403a5fe70cccd28d23802f1981e/Provider.php#L64)
This makes it hard to migrate PHP systems to Kratos, as oidc Microsoft provider in Kratos relies on `sub` field as user identifier.

### Describe your ideal solution

Extend Microsoft oidc provider in Kratos to support this case.
Would you accept such PR?

### Workarounds or alternatives

Implement a service to process requests before they come to Kratos and convert identifiers.
The conversion might take long or even never end if some users might not choose to re-logion for long.

### Version

0.8

**Comment by aeneasr** [comment]
Addressednon master
