### ISSUE TITLE
Support updating password and traits atomically

### ISSUE THREAD

**Issue by meyfa** [ory/kratos#2169]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

There is already an issue about E2E encryption: https://github.com/ory/kratos/issues/1246
That issue outlines an industry-standard scheme of authenticating users without giving away their password to the server. It works by hashing the password client-side, using the email address as salt. The result of this operation is the pseudo-password (auth key) that Kratos would receive and validate against the stored password hash.

This can largely be done already through client-side manipulation of flow data before submission, and by hooking up a custom API that provides the actual vault data.

One thing that causes quite a headache is updating the user's email address. Due to how the scheme works, a different email address means a different salt, and hence a different auth key. Hence, the client needs to perform two calls to Kratos:

1. Update the email trait
2. Update the password (which has changed as a result of changing salt)

Imagine the first step succeeds but the second step fails (device or application crashes, network connection is lost, Kratos validation of the flow data fails, session has run out in the meantime, ...). Then the user's credentials will only be partially updated. Now, there is no valid combination of credentials which the user could still log in with: Their old email address won't work because it was already updated on the server, and their new email address won't work because the auth key does not match the one stored with Kratos!

### Describe your ideal solution

To solve this, we would need both steps to be just a single step that cannot fail partially (i.e., the settings flow would need to support atomic submission of multiple method bodies). When looking at the documentation (https://www.ory.sh/kratos/docs/reference/api#operation/submitSelfServiceSettingsFlow), we can see only a single method can be provided. We would need to provide multiple methods with their respective values. If validation fails for just a single method, do not perform any updates. Otherwise perform all updates at the same time.

### Workarounds or alternatives

* Not using the email address as salt (bad idea for many reasons)
* Building a custom API that stands in front of Kratos and offers a single endpoint, which internally calls the two Kratos endpoints and makes sure invalid states cannot be reached. This seems difficult to get right and might create more problems than it solves (i.e., we could lose CSRF protection etc.)

### Version

v0.8.0-alpha.3

**Comment by aeneasr** [comment]
Thank you for this proposal. To get a bit of clarification, what would this particular flow enable? Is it about e2e encryption or that the user’s password doesn’t get to the server?

This feature would be quite hard to pull off, we need libraries and SDKs for a large variety of clients that aren’t trivial to write or autogenerate. It’s also not clear how this would interface with non email accounts (eg usernames), or other auth methods such as HSM, Fido2.

Could you give a bit of context about why this would be useful to have and how we could address the fundamental questions around reliable client SDKs that have methods to interface with such APIs?

Thank you :)

**Comment by meyfa** [comment]
Thank you for your very quick response! Please let me try to clarify.

This feature request is about changing/extending the self-service "settings" flow to support multiple strategies as part of a single API request. This could be implemented quite abstractly. E2E encryption is simply what motivates this issue because for the scheme outlined above, it is necessary to update the user's password and email at the same time. I am not requesting an entirely new flow or even special treatment of email authentication. There might be use cases where it would be advantageous to change a username and associated HSM at the same time, too, but that is outside the realm of what we're working with, so I haven't spent much time thinking about it.

Perhaps it helps to look at this from a UI perspective:

When the settings flow is initialized, it returns a form containing all of the supported strategies, with a separate submit button for each strategy. What I am asking for can be thought of as a single submit button at the very end of the form that submits everything (or perhaps a subset of everything). The user could enter a new email address, new username, new street address, new password etc. and finally submit all of that together instead of performing two or more distinct operations.

For our use case the final submit button does not actually have to exist (although it *could* exist, of course), but if we were able to emulate its functionality, that would be great!

I think this would require two major changes:

1. Modify the "settings" flow schema to take an array or a key-value map, mapping some set of methods (password, profile, oidc, ...) to their respectively submitted values.
2. Modify the "settings" flow logic to work in two steps. First, each strategy contained in the flow body is asked to validate its input, potentially returning an error which would abort the request handler immediately. Otherwise, if no strategy returned an error, go through each strategy again and persist the respective changes. (At this point, no more errors must be thrown, because this would break any guarantees we made to the client that the operation would be atomic!)

This sounds like a lot of work indeed, and might put limits on the implementation of each individual strategy. For example, strategy A cannot perform validation based on identity properties managed by strategy B, because during the validation phase, these properties would not have been set yet.

Please let me know whether this extension is considered too complex for implementation in Kratos, which would be entirely reasonable, but we would need to start looking for alternative solutions pretty soon in that case. Thank you!

**Comment by meyfa** [comment]
We have decided on a change to our infrastructure so that we will no longer be needing this feature. Still, thank you!

Seeing as there is probably no broader interest in this proposal, I will go ahead and close it.
