### ISSUE TITLE
Discrepancy in documentation

### ISSUE THREAD

**Issue by shankardevy** [ory/kratos#218]
At this URL https://www.ory.sh/docs/kratos/, the doc says it only supports Postgresql
> ORY Kratos scales horizontally without effort. The only external dependency is a RDBMS - we currently support only PostgreSQL. You will not need memcached, etcd, or any other system to scale ORY Kratos.

However, in the next section, here: https://www.ory.sh/docs/kratos/quickstart, the doc says 

> You might notice that no database is being used in this example. ORY Kratos supports SQLite, PostgreSQL, MySQL, and CockroachDB as database backends. For the quickstart, we're mounting a persistent volume to store the SQLite database in.

Which one is more recent?

**Comment by aeneasr** [comment]
Thank you - we do indeed support SQLite, PostgreSQL, MySQL, and (in a future version) CockroachDB. I have updated the doc and am therefore closing this but feel free to get the discussion going if need be :)
