### ISSUE TITLE
Investigate account recovery with multi-factor enabled

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2190]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When recovering an account with MFA, the UI does not redirect to the AAL2 page, which can cause the UI to fail to display the correct page.

### Reproducing the bug

1. Create account
2. Set up MFA
3. Recover account

### Version

master

### Additional Context

It is possible that this is a bug in the Ory Console only, but we need tests to verify that this actually works as expected.

**Comment by kmherrmann** [comment]
@Benehiko is this a duplicate of what you're working on in https://github.com/ory/network/issues/222 ?

**Comment by Benehiko** [comment]
Yes and https://github.com/ory/kratos/issues/2832

**Comment by aeneasr** [comment]
This is fixed apparently?

**Comment by Benehiko** [comment]
Yes this should be fixed :)
