### ISSUE TITLE
completeSelfServiceRegistrationFlowWithPasswordMethodRaw uses bad URL

### ISSUE THREAD

**Issue by janekolszak** [ory/kratos#2196]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I generated kratos client with openapi-generator typescript-fetch generator and the generated method **completeSelfServiceRegistrationFlowWithPasswordMethodRaw** seems to have a bad URL. Browser says 404.

Finishing flow with form submit or plain fetch works:
`fetch(flow.ui.action, {
      method: props.flow.ui.method,
      body: new URLSearchParams(values),
      credentials: 'include',
      headers: { "Content-Type": "application/x-www-form-urlencoded" }
}
`

### Reproducing the bug

Just run completeSelfServiceRegistrationFlowWithPasswordMethodRaw

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Does this affect the official SDKs also? So `@ory/kratos-client`?
