### ISSUE TITLE
Vue Standalone App

### ISSUE THREAD

**Issue by timalanfarrow** [ory/kratos#2202]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

It would be good to have a standalone interface example written in Vue.

### Describe your ideal solution

I actually already wrote a standalone interface that implements each of the flows and is essentially identical to the React interface but without all the links to documentation.

### Workarounds or alternatives

I guess I could just publish it myself and write a blog/make a YouTube video. I could actually probably do that in addition to giving it to you guys.

### Version

v0.8.2-alpha.1

### Additional Context

Here's the URL to my [Git repository with the Vue source code](https://github.com/timalanfarrow/kratos-selfservice-ui-vue3-typescript), and to [the Docker hub image I generated from that source code](https://hub.docker.com/repository/docker/timalanfarrow/kratos-selfservice-ui-vue3-typescript).

The name of the Git repository follows the pattern from the other UI, and I tagged the versions as v0.8.2-alpha.1 because that is the version of Kratos I built it for. Let me know if I can change/improve anything. I'm assuming you'll want me to give you the Vue repo, or you'll want to fork it before you merge this but I figured I would set it up so you can pull it down and run it if you so choose. It doesn't appear to have broken the other standalone application but I will admit I didn't try some of the other more complex examples and I feel that my changes to the CORS policy in `/contrib/quickstart/kratos/email-password/kratos.yml` may break some of the other quickstart examples. Maybe I can implement a change in my Vue repo to make it unnecessary to change the config in that way. Let me know, I'm on the Slack channel as `@Timothy Farrow`

**Comment by aeneasr** [comment]
That's really awesome! I think vincent has added this to the documentation, so I will be closing this one as I think it is resolved :) Good job!

**Comment by aeneasr** [comment]
I'm closing this as we have this merged as an official show case :)
