### ISSUE TITLE
Tree-shakeable, browser-friendly JS client

### ISSUE THREAD

**Issue by viters** [ory/kratos#2218]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I consider **ory/kratos** project very useful for the client side as well. Shipping a compatible API client is really a time-saver. There are also web app examples using `@ory/kratos-client` library. Although, web apps struggle to deliver the most features with the least performance compromise. Thus, we aim to reduce amount of code sent through internet and parsed by browsers.

`@ory/kratos-client` is not ready for web apps in browser usage at the current state:
1. It is not tree-shakeable - everything is placed in one class, that must be instantiated to use API.
<img width="377" alt="image" src="https://user-images.githubusercontent.com/13100466/153725547-d1bd6440-afa9-451d-9c65-0c9767157860.png">
No matter if you need only one API call - you will need to add 300kb of code into bundle (it's nicely gzipped though, but it takes browser time to parse).

2. It ships with `axios` inside, with version scoped to patch. So you either have to use the same `axios` as client does, or have two axios-es in a bundle.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/13100466/153725564-96251549-da35-4792-a68c-93f8f65811c2.png">

(this may be mitigated using some patching for `@ory/kratos-client` package.json)

350kb may not look like much, but for an app with initial bundle of 3MB of code, it is 10% of that bundle.

### Describe your ideal solution

JS `@ory/kratos-client` is an awesome kick-starter for web projects integration with Kratos, but right now is not a good idea to use it in production browser deployment.

I wonder if it is possible to adjust the client code generation configuration for js, or would it require manually crafted JS library.

### Workarounds or alternatives

N/A

### Version

0.8

**Comment by aeneasr** [comment]
Thank you for the report and the insightful ideas. Unfortunately, the Ory Kratos client is currently auto-generated using openapi-generator. It is quite astonishing that 350kb are neccessary for it, as it should just be a bunch of models and some functions. There's actually the exact same issue for Kubernetes: https://github.com/kubernetes-client/javascript/issues/242

As we have little control over the autogenerators, it will be a long shot to resolve any of this without writing a completely new SDK that does not rely on autogeneration. This is currently out of scope for us at Ory as it is too much work to keep manually written SDKs in sync.

So yeah, I think this would need to be resolved in the generator. I saw that there's an option `withSeparateModelsAndApi` which might help, but no guarantees...
