### ISSUE TITLE
Unable to login after removing the security key - Kratos still requires to solve a challenge

### ISSUE THREAD

**Issue by MrMebelMan** [ory/kratos#2225]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When the security key is disabled via settings, Kratos seems to still remember it, so, during the next login, it redirects to `/self-service/login/browser?aal=aal2` and requires to confirm the action using the security key.

WhoAmI response after the login attempt:
```json
{
  "error":{
    "id":"session_aal2_required",
    "code":403,
    "status":"Forbidden",
    "reason":"An active session was found but it does not fulfill the requested Authenticator Assurance Level. Please verify yourself with a second factor to resolve this issue.",
    "details":{
      "redirect_browser_to":"http://localhost:4433/self-service/login/browser?aal=aal2"
    },
    "message":"Session does not fulfill the requested Authenticator Assurance Level"
  },
  "redirect_browser_to":"http://localhost:4433/self-service/login/browser?aal=aal2"
}
```

Login flow response after being redirected (note the missing nodes):
```json
{
    "id": "e8fa25e4-e363-40bd-ba2e-dbcfa74b30e9",
    "type": "browser",
    "expires_at": "2022-02-14T13:26:53.528845Z",
    "issued_at": "2022-02-14T12:55:53.528845Z",
    "request_url": "http://localhost:4433/self-service/login/browser?aal=aal2",
    "ui": {
        "action": "http://localhost:4433/self-service/login?flow=e8fa25e4-e363-40bd-ba2e-dbcfa74b30e9",
        "method": "POST",
        "nodes": [
            {
                "type": "input",
                "group": "default",
                "attributes": {
                    "name": "csrf_token",
                    "type": "hidden",
                    "value": "wC7XlHivQTZZcv80jRNAMO4mkOONWQnoWZm98WUe1vI7+h592/pDmt1/p3Ra3lkZ6YP8BwboDZULW/+F79xn3g==",
                    "required": true,
                    "disabled": false,
                    "node_type": "input"
                },
                "messages": [],
                "meta": {}
            }
        ],
        "messages": [
            {
                "id": 1010004,
                "text": "Please complete the second authentication challenge.",
                "type": "info",
                "context": {}
            }
        ]
    },
    "created_at": "2022-02-14T12:55:53.537337Z",
    "updated_at": "2022-02-14T12:55:53.537337Z",
    "refresh": false,
    "requested_aal": "aal2"
}
```

### Reproducing the bug

1. Create a webauthn security key.
2. Disable it.
3. Log out.
4. Attempt to log in again.

### Relevant configuration

```yml
selfservice:
  flows:
    settings:
      required_aal: highest_available

session:
  whoami:
    required_aal: highest_available
```

### Version

v0.8.2-alpha.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Thank you for the report! I believe we have a fix for this on master, but it is not yet released!
