### ISSUE TITLE
admin listIdentity API returns indeterministic results

### ISSUE THREAD

**Issue by xuwang-wish** [ory/kratos#2231]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

We are using a private fork of kratos 0.8.2, which is based on ths [commit](https://github.com/ory/kratos/commit/627f4a1ddb378db84510a85013c4580a9d8024ad).

For our one use case, we want to get all identities in prod database, by calling admin listIdentity HTTP API.

**However we noticed 3 things:** 
(In the following examples, _localhost_ is the local admin endpoint)

1. curl -k http://localhost:4434/identities?per_page=500&page=900000000 returns non-empty result
2. curl -k http://localhost:4434/identities?per_page=500&page=0/1/2/3.../8/9 all return same content
3. curl -k http://localhost:4434/identities?per_page=5000&page=900000000 returns non-empty result without error

**Expected result:**

- For No.1 request, empty result is expected. Our application doesn't have so many users. 
- For No.2 request, i just don't know why the behaviour is like that.
- For No.3 request, an error response is expected. According to API doc, max support number for _per_page_ should be 500.

**Running environment**
Kratos docker img in k8s cluster + AWS RDS (mysql 5.7) as datastore

I can confirm that we don't any customization on related code.

### Reproducing the bug

Need to test with a local environment

### Version

0.8.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by aeneasr** [comment]
Any further investigations and fixes are appreciated!

**Comment by aeneasr** [comment]
I can't reproduce this:

```
curl --location --request GET 'https://playground.projects.oryapis.com/api/kratos/admin/identities?per_page=100&page=100000' \
--header 'Authorization: Bearer ory_pat_0PGhdJDioGwmQ4Ce6odv368RDXbnarZw'
[]

curl --location --request GET 'https://playground.projects.oryapis.com/api/kratos/admin/identities?per_page=1&page=1' \
--header 'Authorization: Bearer ory_pat_0PGhdJDioGwmQ4Ce6odv368RDXbnarZw'
  {
    "id": "ffff7d20-0ea4-4b4a-abc4-5130661cf71f",

curl --location --request GET 'https://playground.projects.oryapis.com/api/kratos/admin/identities?per_page=1&page=2' \
--header 'Authorization: Bearer ory_pat_0PGhdJDioGwmQ4Ce6odv368RDXbnarZw'
[
  {
    "id": "ffb68750-d9af-4685-a8a4-2d2f79c6b75e",

```

**Comment by xuwang-wish** [comment]
Can you point me where those tests are located?

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/blob/40b7db3707a2bfe23bdb977d0796e43fb0ac4ad8/identity/test/pool.go#L399

is a good start

**Comment by xuwang-wish** [comment]
Ok. thx.

Feel free to close this for now. We will see if wen can create a failure test case for this.

**Comment by aeneasr** [comment]
Ok thanks for the update :)
