### ISSUE TITLE
Kratos does not support schema based config

### ISSUE THREAD

**Issue by gitn00b1337** [ory/kratos#2236]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Kratos requires a DSN parameter to configure the database. Other libraries like prisma also use this method however they support a schema query parameter, e.g. postgresql://user:secret@host:port/database?schema=xxx

To be clear, I mean a schema not a database (MySQL seems to not differentiate).  Offering this would mean kratos can use the same app database without polluting the public schema. 

### Describe your ideal solution

I would like a query parameter "schema" added to the end which runs all kratos migrations within that schema.

### Workarounds or alternatives

I have not found a work around

### Version

latest

**Comment by aeneasr** [comment]
This is supported for PostgreSQL as our driver supports all libpq configs (see linked doc in https://www.ory.sh/docs/ecosystem/deployment#postgresql)

**Comment by gitn00b1337** [comment]
Hello! Is schema part of libpq though? I dont see any mention here: https://www.postgresql.org/docs/current/libpq-connect.html or here https://www.postgresql.org/docs/current/runtime-config.html

**Comment by aeneasr** [comment]
You're right, it's possible though with:

https://github.com/jackc/pgx/issues/1013

**Comment by gitn00b1337** [comment]
Cheers!
