### ISSUE TITLE
Unable to create identity with different username identifiers that have the same email.

### ISSUE THREAD

**Issue by tristanls** [ory/kratos#2268]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Configured Kratos to use `username` as the primary identifier, however when creating identities with unique usernames but the same email, observing the `an account with the same identifier (email, phone, username, ...) exists already` error.

```
"properties": {
            "traits": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "minLength": 3,
                  "ory.sh/kratos": {
                    "verification": {
                      "via": "email"
                    },
                    "recovery": {
                      "via": "email"
                    }
                  }
                },
                "username": {
                  "type": "string",
                  "minLength": 3,
                  "ory.sh/kratos": {
                    "credentials": {
                      "password": {
                        "identifier": true
                      }
                    }
                  }
                }
              },
              "required": [
                "email",
                "username"
              ],
              "additionalProperties": false
            }
          }
```

I expected to be able to create multiple identities, which is a way to deconflict multiple login methods as explained here https://www.ory.sh/docs/kratos/guides/sign-in-with-github-google-facebook-linkedin#how-to-prevent-username-already-taken, for example:
1. `username: me, email: tristan@example.com`
2. `username: also-me, email: tristan@example.com`

I expected each identity to separately verify the email through the normal email verification flow.

### Reproducing the bug

Configure identity schema as above in the description.

Attempt to create two users with different usernames but the same email.

### Version

v0.8.0-alpha.3

**Comment by tristanls** [comment]
It appears that the problem comes from the following constraints on verification and recovery addresses:
```
"identity_recovery_addresses_status_via_uq_idx" UNIQUE, btree (nid, via, value)
"identity_verifiable_addresses_status_via_uq_idx" UNIQUE, btree (nid, via, value)
```

**Comment by aeneasr** [comment]
Could this sbe related to? https://github.com/ory/kratos/issues/1889#issuecomment-956563575

**Comment by tristanls** [comment]
With the context I have, I don't see the relation you have in mind.

**Comment by aeneasr** [comment]
That bug is also about having two login identifiers in the same schema, which this PR also has. I thought the two bugs could be related.

**Comment by tristanls** [comment]
It seems to me that the problem here might be that the recovery/verification email is the same for two distinct identities.

I also noticed that configuration schema disallows specifying a property other than `"email"` for verification and recovery. This is surprising because I would expect a property to work for verification and/or recovery given it's _format_ was `"email"`. For example:
```
               "my_email_field": {
                  "type": "string",
                  "format": "email",
                  "minLength": 3,
                  "ory.sh/kratos": {
                    "verification": {
                      "via": "my_email_field"
                    },
                    "recovery": {
                      "via": "my_email_field"
                    }
                  }
                }
```
Will result in `^-- value must be "email"`

**Comment by aeneasr** [comment]
Oh I see, I misunderstood your issue. It is not possible to have two identities with the same recovery / verification emails or phone numbers. The use case looks very complex to me, how would we know what account you are verifying when click that link on the email? And which one you intend on recovering when you click on the link? I think there are also many security implications that come with reuse of OOB credentials such as email that are difficult to reliably defend against. So I don't see that we'll ever support this, sorry :(

**Comment by tristanls** [comment]
Ok, thank you.

**Comment by voice0726** [comment]
Hi, I have a question related to this.

In our use case we are currently considering, users can have a unique user id and a non-unique mail address.
In other words, users can have multiple accounts with the same email.
When users try to recover, users should input an userid to the recovery page.

Can Kratos handle such a case? If not, do you have any security concerns on this?

**Comment by alexanderhorner** [comment]
> Hi, I have a question related to this.
> 
> In our use case we are currently considering, identities can have a unique user id and a non-unique mail address. In other words, users can have multiple accounts with the same email. When users try to recover, users should input an userid to the recovery page.
> 
> Can Kratos handle such a case? If not, do you have any security concerns on this?

I'm interested in a similar use case. I understand why recovery emails have to be unique for a standard recovery flow, but what about just verifiable (non-recovery) emails? Why do they have to be unique?
