### ISSUE TITLE
Have `dsn: memory` as an alias for SQLite in memory DSN

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#228]
**Is your feature request related to a problem? Please describe.**

SQLite supports memory with `sqlite://foo.db?mode=memory&_fk=true`. Using `dsn: memory` should be an alias for that.

**Comment by zepatrik** [comment]
The current setup in the quickstart is not working with an in-memory db. Having a container that does the migration and a different one running kratos those two do not share memory (and thus the db has no migrations). I think with the memory alias we should also apply migrations automatically.

**Comment by zepatrik** [comment]
Also the sqlite docs say one should use the file `:memory:` but in fact both URIs work:
1. `sqlite://:memory:?_fk=true`
2. `sqlite://?mode=memory&_fk=true`
Which one should we use?

**Comment by aeneasr** [comment]
That makes sense!
