### ISSUE TITLE
Admin list identities - does not return result as expected with respect to the query parameters

### ISSUE THREAD

**Issue by lbanders** [ory/kratos#2286]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

As part of a user deletion process I want to list all the identities in kratos to find the proper id of my user.

According to the docs I can query the identies using `/identities?page=0&per_page=3` to fetch the 3 identities in the database.

Given the above query and a database with 5 identities I expect I need to perform 2 queries:
* `/identities?page=0&per_page=3`
* `/identities?page=1&per_page=3`

However, the resultset from both these queries are alike, and I need to do a `/identities?page=2&per_page=3` to get the last 2 identities in the list.

### Reproducing the bug

* Create 5 identities
* Perform the queries as mentioned above on the admin interface

### Version

0.8.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

I am using a MySQL database for the users.

I have another service calling these endpoints.

**Comment by aeneasr** [comment]
page 0 == page 1, basically we always start at 1

**Comment by lbanders** [comment]
Ok - was just confused from the API documentation as it stated the page started from 0.

Thanks for clarifying :)

**Comment by aeneasr** [comment]
Yes, thank you for the report :) I fixed the API docs! :)
