### ISSUE TITLE
Unable to connect to database, failed to parse as URL

### ISSUE THREAD

**Issue by AurimasNav** [ory/kratos#2294]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

automigrate container fails due to failed parsing of postgres address as URL.

### Reproducing the bug

1. configure dsn for postgres on azure in helm values with password including symbols `#!$%&+{}<>:`
2. try to deploy with helm

### Relevant log output

```shell
> time=2022-03-08T08:32:42Z level=warning msg=Unable to connect to database, retrying. audience=application error=map[message:cannot parse `postgres:xxxxxx@dev-psql:xxxxxx@dev-psql.postgres.database.azure.com:5432/orykratos-dev-psqldb?sslmode=verify-full`: failed to parse as URL (parse "postgres://**user**:**password_fragment**": invalid port ":**password_fragment**" after host)] service_name=Ory Kratos service_version=v0.8.0-alpha.3
```

### Relevant configuration

```yml
kratos:
  config:
    dsn: postgress://user:password_with_special_symbols_#!&+{}<>:@postgres_fqdn:port/db_name_etc.
```

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

Not sure if qualifies as a bug, if not then it would be nice if in the configuration docs it would be mentioned that symbols in dsn need to be percent-encoded for url parsing.

**Comment by aeneasr** [comment]
Try url-encoding it, so `password_with_special_symbols_%23%21%26%2B%7B%7D%3C%3E%3A`, see https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls
