### ISSUE TITLE
Option to log traits along with the identity ID

### ISSUE THREAD

**Issue by defensivedepth** [ory/kratos#2308]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Consider the following log:

`{"audience":"audit","http_request":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","cache-control":"max-age=0","connection":"close","content-length":"178","content-type":"application/x-www-form-urlencoded","cookie":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","origin":"https://x.x.x.x","referer":"https://x.x.x.x/login/?flow=86e75d15-ae69-4900-a992-336f14cc3662","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Google Chrome\";v=\"99\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"macOS\"","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"same-origin","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","x-forwarded-for":"x.x.x.x","x-forwarded-proto":"https","x-real-ip":"x.x.x.x"},"host":"x.x.x.x","method":"POST","path":"/self-service/login","query":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".","remote":"x.x.x.x43038","scheme":"http"},"identity_id":"4c0d83a5-71a2-40cb-bbaa-2322dddca2d7","level":"info","msg":"Identity authenticated successfully and was issued an Ory Kratos Session Cookie.","service_name":"Ory Kratos","service_version":"master","session_id":"0613141d-9b8b-42f4-be74-763ab4480a8a","time":"2022-03-10T19:21:28Z"}`

There is no quick way to determine the human-readable user for this log - I would need to use the identity_id and look that up  to pull some type of trait (ie user email / username etc)

### Describe your ideal solution

The ability to log traits along with identity_id.

### Workarounds or alternatives

Post-ingest of Kratos logs (into the SIEM), query the kratos database and add the traits to the logs. This is not ideal because it requires more moving parts and performance issues (editing already-ingested logs).

### Version

0.8.2-alpha.1

### Additional Context

https://github.com/ory/kratos/discussions/2208

**Comment by aeneasr** [comment]
Thank you for the idea! The problem here is that we actually try to not log any sensitive information generally. The problem is that identity traits SRE considered PII and thus subject to eg right to be forgotten, which is difficult to adhere to on logs which are compressed and cold stored!

**Comment by defensivedepth** [comment]
I completely understand, which is why I think this feature would need to be optional, off by default.

**Comment by defensivedepth** [comment]
@aeneasr Is this a possibility? If not, I will find a way around it.

**Comment by aeneasr** [comment]
I guess we could hide it behind `log.leak_sensitive_values = true` settings similar to the other logs. So if `log.leak_sensitive_values = true` you would see the identity's traits and if it's false (default) you would not. WDYT?

**Comment by defensivedepth** [comment]
Yes that would be great!

**Comment by defensivedepth** [comment]
Hello there! Was wondering if there has been any movement on this?

Thanks!

**Comment by aeneasr** [comment]
Not from our end, but we do welcome contributions :)

**Comment by defensivedepth** [comment]
Just sent you all an email with an idea :)

**Comment by defensivedepth** [comment]
Can we reopen this?

**Comment by aeneasr** [comment]
We aren’t planning on doing this at this time, as we don’t want to leak PII to long term storage such as logs.
