### ISSUE TITLE
Support w3c tracing standard

### ISSUE THREAD

**Issue by bodymindarts** [ory/kratos#2312]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We use distributed tracing and would like to connect our traces when we call kratos.
[As far as I can tell](https://github.com/ory/x/blob/master/tracing/tracer.go#L90) the only way kratos can connect with upstream trace data is via the `B3` propagation scheme. However we are using the [w3c standard](https://www.w3.org/TR/trace-context/) in all of our services. 

### Describe your ideal solution

Kratos should support the `w3c` tracing standard in addition to `Zipkin`.

### Workarounds or alternatives

We can investigate switching out our tracing to use `Zipkin` format but its a heavy lift simply to integrate kratos.

### Version

https://github.com/ory/k8s/releases/tag/v0.21.8

**Comment by aeneasr** [comment]
I don't know much about these standards, but we support a variety of tracing services, including OpenTelemetry:

https://github.com/ory/x/blob/66f9180dbd54967c47b42e1020eed84165d64862/tracing/tracer.go#L175

There's also a refactoring en route to replace OpenTracing with OpenTelemetry but it will take some time.

**Comment by aeneasr** [comment]
And if you think that there's an easy fix to this, PRs are always welcomed!

**Comment by bodymindarts** [comment]
> I don't know much about these standards, but we support a variety of tracing services, including OpenTelemetry:

To be clear its not about the format you _export_ its about the headers that you user to propagate tracing information ie. if kratos is behind a proxy that injects headers will pick it up?
Anyway I will experiment and see if switching to OTEL tracer will pick up the headers correctly.

**Comment by bodymindarts** [comment]
> https://github.com/ory/x/blob/66f9180dbd54967c47b42e1020eed84165d64862/tracing/tracer.go#L175

I'm looking for an example of how to configure the `otel` tracing - how do you pass the endpoint to the collector?

**Comment by aeneasr** [comment]
I see, @icyphox is implementing this feature, he might have some ideas :)

**Comment by icyphox** [comment]
> To be clear its not about the format you export its about the headers that you use to propagate tracing information

If I understand correctly, we can resolve this by adding something like this to the OTEL tracer setup (ref: https://pkg.go.dev/go.opentelemetry.io/otel/propagation):

```go
prop := propagation.NewCompositeTextMapPropagator(
	propagation.TraceContext{},
	propagation.Baggage{},	
)
otel.SetTextMapPropagator(prop)
```

Where TraceContext and Baggage are the W3C tracing standards. @bodymindarts will this solve your use-case?

**Comment by bodymindarts** [comment]
Yes that's exactly right together with the ability to specify the collector endpoint. Currently (afaict) the otel tracer config doesn't support that.

**Comment by plarsson** [comment]
It's not possible to set otel as the tracing provider:

```
The configuration contains values or keys which are invalid:
tracing.provider: otel
                  ^-- value must be one of "jaeger", "zipkin", "datadog", "elastic-apm", "instana"
```

**Comment by aeneasr** [comment]
It's not yet released, please be patient with us

**Comment by aeneasr** [comment]
I think this is releaesd now

**Comment by bodymindarts** [comment]
I don't think this is actually included in the [latest release](https://github.com/ory/kratos/releases/tag/v0.10.1) (dated June 1st) since the [commit that made it configurable](https://github.com/ory/x/commit/8fbaa6b2a17a4070502a3e726c54422f6154c07f) didn't land until late august.
