### ISSUE TITLE
serve.admin.request_log.disable_for_health broken in v0.9.0-alpha.2

### ISSUE THREAD

**Issue by drigz** [ory/kratos#2329]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

In my config, I have set serve.admin.request_log.disable_for_health=true. However, I see this in the Ory Kratos logs:

```
time=2022-03-22T16:40:29Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* connection:close referer:http://172.26.0.191:4434/health/alive user-agent:kube-probe/1.23] host:172.26.0.191:4434 method:GET path:/admin/health/alive query:<nil> remote:172.26.0.56:58218 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate content-type:application/json; charset=utf-8] size:16 status:200 text_status:OK took:1.272463ms]
time=2022-03-22T16:40:29Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* connection:close referer:http://172.26.0.191:4434/health/ready user-agent:kube-probe/1.23] host:172.26.0.191:4434 method:GET path:/admin/health/ready query:<nil> remote:172.26.0.56:58216 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate content-type:application/json; charset=utf-8] size:16 status:200 text_status:OK took:1.088813ms]
```

I guess this might be tied to the new `/admin` prefix.

### Reproducing the bug

I deployed the Kratos helm chart at v0.22.2, overriding `image.tag` to v0.9.0-alpha.2 and with a config including `serve.admin.request_log.disable_for_health=true`. The Kubernetes health checks appear in the logs.

### Version

v0.9.0-alpha.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
It's possible that this isn't propagated appropriately. Any contributions towards fixing this are welcomed. It should be relatively easy to do!

**Comment by aeneasr** [comment]
Resolved on master
