### ISSUE TITLE
Update an identity's credentials when update an identity

### ISSUE THREAD

**Issue by TheFu527** [ory/kratos#2334]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, in v0.9.0, creating a password when creating identity is supported (`POST /admin/identities`).

However, the corresponding update does not implement the relevant features (`PUT /admin/identities/{id}`).

### Describe your ideal solution

Make it possible to update an identity's credentials using the Update an Identity API (`PUT /admin/identities/{id}`).

### Workarounds or alternatives

At present, I implement this feature by creating my own API and directly modifying the related tables in MySQL.

### Version

v0.9.0

**Comment by vinckr** [comment]
It does seem sensible, but can you share a bit of details on your use case? 

I think usually end-users would update credentials in a self-service flow. And the (POST /admin/identities) works when creating identities. 

This would be a case where the end-user already has an identity in Kratos created and then you need to change the password without end-user interaction, is that correc?

**Comment by TheFu527** [comment]
> This feature would be for a case where the end-user already has an identity in Kratos created and then you need to change the password without end-user interaction, is that correct?

Yes, it is. We need the administrator to directly modify the password of any user without end-user interaction.

**Comment by aeneasr** [comment]
That makes sense :) For anyone looking, I think this should be realtively easy to implement. Just port the functionality from POST to PUT!

**Comment by tsirkin** [comment]
Hi 
Submitted a PR to fix this.  
I have problems running the tests (unrelated to the PR), please review/let me know what is the problem with tests/how to run them.
