### ISSUE TITLE
LICENSE contains placeholder values

### ISSUE THREAD

**Issue by a-c-m** [ory/kratos#2337]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

/LICENSE showing the Apache 2 license on line 189, has the placeholder text as follows

`   Copyright [yyyy] [name of copyright owner]`

See https://github.com/ory/kratos/blob/master/LICENSE#L189

I suspect this is not intentional and these values should be replaced with real ones.

### Reproducing the bug

View https://github.com/ory/kratos/blob/master/LICENSE#L189

### Version

N/A

**Comment by aeneasr** [comment]
Thank you for the question. That is correct, the license is to be copied verbatim.

**Comment by a-c-m** [comment]
Not so much a question, more pointing out the licence is not really complete (wondering if that makes it invalid?) without these placeholder details being filled in.

**Comment by aeneasr** [comment]
The cited text is to be used for header files (we dont really do that though) the license itself must not be touched :)
