### ISSUE TITLE
Refresh login doesn't work

### ISSUE THREAD

**Issue by sawadashota** [ory/kratos#2341]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Refresh login flow shows no forms.

![image](https://user-images.githubusercontent.com/21254456/160093246-433ea0c8-dcb8-4fb8-aa96-214e24bcbcd6.png)

### Reproducing the bug

1. Run `docker-compose -f quickstart.yml -f quickstart-oathkeeper.yml up -d`
2. Access to http://127.0.0.1:4455/.ory/kratos/public/self-service/login/browser?refresh=true
3. Login page asks sign in but no inputs appeared.

### Version

v0.9.0-alpha.2

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Looks like you're not signed in yet. So that should resolve the issue. However, we should of course handle this correctly in the login endpoint :)

**Comment by sawadashota** [comment]
Thanks you for quick answer!
So kratos changed behavior of `refresh` parameter, right? It should have been behavior which shows always login before 0.8.2-alpha.1.

**Comment by aeneasr** [comment]
It looks like a bug / regression!

**Comment by sawadashota** [comment]
Thank you for your fixing!
