### ISSUE TITLE
Design document: Certificate based authentication for smtp client

### ISSUE THREAD

**Issue by alexGNX** [ory/kratos#2350]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Context and scope

Current implementation of the SMTP client in Kratos only supports username/password authentication.
Some SMTP servers enforces client certificate based authentication, hence the need for it to be supported by Kratos.
Aside from that, it is also not possible in the current implementation to start an smtps connexion with an SMTP server that is hosted on a subdomain but that uses a non-wildcard domain certificate (e . g., the server is hosted on sub.mysmtpserver.net but uses a non wildcard certificate which CN is mysmtpserver.net). This design document will tackle this aswell.

### Goals and non-goals

- be able to provide a client certificate and a client private key to be used when initializing the SMTP client
- be able to provide a domain name that is distinct from the server hostname and that matches the server certificate CN

### The design

The client certificate and private key file paths will be provided by adding 2 configuration fields this way:

```
smtp:
    client_cert_path:
    client_key_path:
```

If both of those configuration fields are set, the key pair will be loaded when initializing the SMTP client., and passed to the dialers TLSConfig.
For the domain name to validate the server CN against, it will be provided as a parameter of the SMTP connection URI, e. g. :

```
smtp:
    connection_uri: smtps://subdomain.my-mailserver:1234/?server_name=my-mailserver"

```

**Comment by aeneasr** [comment]
Merged!
