### ISSUE TITLE
Docs: messages are not required

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2357]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

~The `messages` field of the `uiNode` is marked as `required` in the HTTP API documentation. However, the field is not returned when getting a registration flow via `/self-service/registration/flows`.~

### Version

v0.9.0-alpha.3

**Comment by aeneasr** [comment]
With no messages do you mean that the key is missing from the object, or that the array is empty? :)

**Comment by woylie** [comment]
I meant that the key is missing :)

**Comment by aeneasr** [comment]
Got it , thank you :)

**Comment by woylie** [comment]
I assume that the `type` key for `selfServiceRecoveryFlow` should be required as in all other flows.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/13847569/162133437-bc84c1e5-d021-41da-91ba-dd96b463e783.png">
