### ISSUE TITLE
Confusing input value for submit input

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2358]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The UI node for the submit button of the registration form is a bit confusing (this is the parsed result in my Elixir application, but fields and values match the JSON response):

```elixir
%Kratos.UiNode{
  attributes: %Kratos.UiNodeAttributes{
    disabled: false,
    name: "method",
    node_type: :input,
    type: "submit",
    value: "password"
  },
  group: "password",
  messages: [],
  meta: %Kratos.UiNodeMeta{
    label: %Kratos.UiText{
      context: %{},
      id: 1040001,
      text: "Sign up",
      type: "info"
    }
  },
  type: :input
}
```

This tells me to render an input with type `submit` and value `password`. There's even a name `method`. At the same time, it also gives me a label. Together, I would render this information as:

```html
<label>Sign up</label>
<input name="method" type="submit" value="password">
```

But this of course doesn't make a lot of sense.

1. The `value` on an `input` with type `submit` is used as the button label. `password` doesn't make any sense here.
2. There should not be a separate label for the submit button.
3. The submit button should not have a `name` attribute.

I can work around this by first checking the `attributes.type` value and adjusting the rendering if it is a `submit` type, but I'd prefer the API response to be consistent for all inputs (same Elixir format as above):

```elixir
%Kratos.UiNode{
  attributes: %Kratos.UiNodeAttributes{
    disabled: false,
    node_type: :input,
    type: "submit",
    value: "Sign up"
  },
  group: "password",
  messages: [],
  type: :input
}
```

### Reproducing the bug

Get self-service registration flow at `GET /self-service/registration/flows`.

### Version

v0.9.0-alpha.3

**Comment by woylie** [comment]
Seems like `name: method, value: password` should be rendered as a hidden input. Can it be that the submit input and the hidden input for the method get jumbled up? 

```
  %{
        "attributes" => %{
          "disabled" => false,
          "name" => "method",
          "node_type" => "input",
          "type" => "submit",
          "value" => "password"
        },
        "group" => "password",
        "messages" => [],
        "meta" => %{
          "label" => %{
            "context" => %{},
            "id" => 1040001,
            "text" => "Sign up",
            "type" => "info"
          }
        },
        "type" => "input"
      }
```

**Comment by woylie** [comment]
I ended up with this logic, but I still think it's inconsistent.

```elixir
    <%= if @node.attributes.type == "submit" do %>
      <input
        disabled={@node.attributes.disabled}
        name={@node.attributes.name}
        type="hidden"
        value={@node.attributes.value}
      />
      <input
        disabled={@node.attributes.disabled}
        type="submit"
        value={@node.meta.label.text}
      />
    <% else %>
      <div class="field">
        <%= if @node.meta.label do %>
          <label><%= @node.meta.label.text %></label>
        <% end %>
        <input
          disabled={@node.attributes.disabled}
          name={@node.attributes.name}
          onclick={@node.attributes.onclick}
          pattern={@node.attributes.pattern}
          required={@node.attributes.required}
          type={@node.attributes.type}
          value={@node.attributes.value}
        />
        <.field_info messages={@node.messages} />
      </div>
    <% end %>
```

**Comment by woylie** [comment]
Same thing with buttons. I would expect this:

```elixir
%{
        "attributes" => %{
          "disabled" => false,
          "name" => "webauthn_register_trigger",
          "node_type" => "input",
          "onclick" => "...",
          "type" => "button",
          "value" => ""
        },
        "group" => "webauthn",
        "messages" => [],
        "meta" => %{
          "label" => %{
            "id" => 1050012,
            "text" => "Add security key",
            "type" => "info"
          }
        },
        "type" => "input"
      },
```

To be this:

```elixir
    %{
        "attributes" => %{
          "disabled" => false,
          "name" => "webauthn_register_trigger",
          "node_type" => "input",
          "onclick" => "...",
          "type" => "button",
          "value" => "Add security key"
        },
        "group" => "webauthn",
        "messages" => [],
        "meta" => %{}
        },
        "type" => "input"
      },
```

**Comment by aeneasr** [comment]
Thank you for the report! Unfortunately, we rely on the `value` parameter to decide which method was used during the submission. It is possible to submit several types of e.g. login methods such as social, totp, webauthn, ... - and therefore required for the value to be set to something that helps us identify what method the user chose.

Therefore, I don't think it will be possible for us to fix this as you suggested.

Apart from that, at least in HTML, it's trivial to set the label of a button different from the value:

```
<button value="bla">my label</button>
```

and the same applies to submit:

```
<button value="bla" type="submit">my label</button>
```

For more code examples, check out our reference implementation: https://github.com/ory/kratos-selfservice-ui-node/tree/master/views/partials

Thanks!

**Comment by woylie** [comment]
@aeneasr I'm sorry, but I don't understand why the `value` has to come from the `button`, and why it cannot come from an additional hidden input instead? Also, even if Kratos wants really needs you to render an input node with type button as a button node as you describe, surely Kratos can return what is required right away? The point of this issue is that I need to know special rules for rendering the UI because Kratos does not return what I actually need to render consistently.

**Comment by aeneasr** [comment]
Because a hidden input will be overwritten. Consider:

```
<input type="hidden" name="method" value="password">
<input type="hidden" name="method" value="oidc">
<input type="hidden" name="method" value="magiclink">
<input type="submit" value="Register">
```

When cou click the submit button, is `method` `password` or `oidc`? It depends on what the browser decides to send. So we don't know whether the user wanted to sign using OIDC (which means we need to redirect) or using a password or `magiclink`.

With the method we are using, this is possible. Because the click tells the browser "set `method`" to whatever value the user clicked.

**Comment by woylie** [comment]
I see. I didn't notice that because I'm rendering a separate form for each group.

I think the confusion arises from the UI node type for the button still being `input`, although it has to be rendered as a `<button>`. I think it would be better to add `button` as a UI node type. What do you think?
