### ISSUE TITLE
Replace onclick attributes to support CSP nonces

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2376]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

At the moment, some `input` nodes have `onclick` attributes that are not compatible with CSP nonces. Adding a CSP directive like `script-src 'self' 'unsafe-inline' 'nonce-iv1ZtgmmTDzw_PeRb8HtXw';` will cause these `onclick` script to be blocked. The `nonce` attribute cannot be added to `<input>` elements.

### Describe your ideal solution

Instead of relying on `onclick` attributes, the click handler script could be added as separate `script` nodes.

Before:

```json
[
  {
    "attributes": {
      "name": "webauthn_register_trigger",
      "node_type": "input",
      "onclick": "window.__oryWebAuthnRegistration(...)",
      "type": "button",
      "value": ""
    },
    "group": "webauthn",
    "messages": [],
    "meta": {
      "label": {
        "id": 1050012,
        "text": "Add security key",
        "type": "info"
      }
    },
    "type": "input"
  }
]
```

After:

```json
[
  {
    "attributes": {
      "id": "webauthn_register_trigger",
      "name": "webauthn_register_trigger",
      "node_type": "input",
      "type": "button",
      "value": ""
    },
    "group": "webauthn",
    "messages": [],
    "meta": {
      "label": {
        "id": 1050012,
        "text": "Add security key",
        "type": "info"
      }
    },
    "type": "input"
  },
  {
    "attributes": {
      "name": "webauthn_register_trigger",
      "node_type": "input",
      "src": "document.addEventListener('DOMContentLoaded', function () {document.getElementById('webauthn_register_trigger').addEventListener('click', function () { window.__oryWebAuthnRegistration(...)});});",
      "type": "script"
    },
    "group": "webauthn",
    "messages": [],
    "meta": {},
    "type": "script"
  }
]
```

This way, we can just add the nonce attribute to the script tag.

### Workarounds or alternatives

none

### Version

v0.9.0-alpha.3

**Comment by aeneasr** [comment]
Thank you for the idea! Would dynamically loaded scripts not have the same issue with nonces too though? One problem I see with the proposed solution is that it will work for static HTML, but not in scenarios where e.g. React is used which modifies the DOM as it sees fit.

Is there an alternative to this? Maybe we could initialize the flow with a nonce? Not sure if that would be acceptable from a security standpoint though

**Comment by woylie** [comment]
Using CSP nonces for inline scripts will block any `onclick` attributes, but it will not block any `click` event listeners added dynamically with JS, as long as the JS loads. So `<script nonce="u9i8aekm">document.getElementById('webauthn_register_trigger').addEventListener('click', ...);</script>` does actually work.

An alternative would be to serve the script with Kratos and return the `src` and `integrity` attributes instead of the code itself, as it is already done with the Webauthn script.

I'm not sure what to do about React and co. While it's possible to [add script tags with vanilla JS to React applications](https://stackoverflow.com/questions/34424845/adding-script-tag-to-react-jsx), the `DOMContentLoaded` event listener would be problematic.

If all elements that currently have an `onclick` attribute get a fixed `id` attribute, it might be possible to serve a single additional script with Kratos that needs be loaded any time a Kratos UI is rendered (as opposed to returning a script node in the specific API response). This script could add something like an `initKratosEventListeners` (or just `initKratos`) function to `window`. You could then call that function whenever and however it makes sense in the framework you are using to add the onclick handlers. For example, in LiveView, I could just add the line `window.addEventListener("phx:page-loading-stop", (info) => window.initKratos());`. I'm guessing that in React you could call the function in the `componentDidMount` hook or something like that?

> Maybe we could initialize the flow with a nonce? Not sure if that would be acceptable from a security standpoint though

What do you mean by that?

**Comment by aeneasr** [comment]
My idea was basically calling `/selfservice/login/browser?jsnonce=1234` which would then init the flow with the given nonce. But I’m not sure whether that would be considered good practice. I think it may be ok as the server would still be responsible for setting the nonce and the request above would just tell kratos to use it, and it would not be easily possible to spoof it for attackers as they would still need to hack the nonce server side. Not sure if that explanation makes sense 😅

Alternatively you could also just set the nonce in your UI as that’s probably setting the nonce header? Or alternatively, we could also introduce the nonce on the flow object and require the UI to set it as an HTTP header - would not work for SPAs though, probably.

**Comment by woylie** [comment]
I think we're reden aneinander vorbei :)

I can generate a nonce on my own or take one generated by Kratos, I don't really care. Since my UI application might serve additional content as well, I'd probably just set the CSP header logic up globally for all routes independently of Kratos. Wherever I get that nonce from, I can add it to the CSP header in my UI application:

```
Content-Security-Policy: default 'self'; script-src 'self' 'unsafe-inline' 'nonce-iv1ZtgmmTDzw_PeRb8HtXw';
```

This will now block any inline JavaScript unless I add the nonce. The `unsafe-inline` directive is added for backwards compatibility and is ignored by browsers that support nonces.

If I want to allow additional scripts to be loaded from the Kratos server, I can add the URL as well (base URL or specific URL of the script):

```
Content-Security-Policy: default 'self'; script-src 'self' 'nonce-iv1ZtgmmTDzw_PeRb8HtXw' https://kratos.myapplication.example/path/to/webauthn.js;
```

This is blocked:

```html
<script>
  alert("I am blocked!");
</script>
```

This is also blocked:

```html
<script src="https://evil.example/uglycolors.js"></script>
```

This is not blocked:

```html
<script nonce="nonce-iv1ZtgmmTDzw_PeRb8HtXw">
  alert("I am not blocked!");
</script>
```

This is not blocked:

```html
<script src="https://kratos.myapplication.example/path/to/webauthn.js"></script>
```

So far so good. However, inline scripts of event attributes will also be blocked:

```html
<input type="button" value="add security key" onclick="window.__oryWebAuthnRegistration(...)">
```

And here, it is _not_ possible to add a nonce attribute. So this has to be rewritten without `onclick` attribute. This means with the current implementation, I cannot use nonces for `script-src` if I want to use Webauthn with Kratos. I _must_ allow `unsafe-inline` without nonces.

**Comment by aeneasr** [comment]
Oh, I see. That makes sense. In that scenario, the easiest way to do it would be to add your own listener to the button and call `window.__oryWebAuthnRegistration` on trigger to initialize the flow. I don't think that we can provide an easy-to-use solution that works out of the box for a variety of use cases here (as pointed out above with React/Vue/...) due to the way DOMReady works :/

**Comment by woylie** [comment]
I think we still can do some things to make dynamically adding those click handlers easier:

- at least add `id` attributes to all nodes with `onclick` attributes
- potentially serve another script that assigns a single function to `window` which sets up all click handlers dynamically as described above; then I have the choice between either rendering the `onclick` attributes or calling that function in a lifecycle hook

> If all elements that currently have an onclick attribute get a fixed id attribute, it might be possible to serve a single additional script with Kratos that needs be loaded any time a Kratos UI is rendered (as opposed to returning a script node in the specific API response). This script could add something like an initKratosEventListeners (or just initKratos) function to window. You could then call that function whenever and however it makes sense in the framework you are using to add the onclick handlers. For example, in LiveView, I could just add the line window.addEventListener("phx:page-loading-stop", (info) => window.initKratos());. I'm guessing that in React you could call the function in the componentDidMount hook or something like that?

**Comment by aeneasr** [comment]
> potentially serve another script that assigns a single function to window which sets up all click handlers dynamically as described above; then I have the choice between either rendering the onclick attributes or calling that function in a lifecycle hook

That should already be possible by doing (as described in the OP):

```
<button id="foo">
<script nonce="...">
document.getElementById("foo").onClick(() => {
window.__oryWebAuthnRegistration()
})
</script>
```

The problem with registering two ways of triggering the action is that, in normal cases, the action will be triggered twice - unless of course we completely deprecate the onClick handler.

And as said above, the proposed way of per default handling `DOMLoaded` with event listeners is that this will only work for plain HTML sites. Yet, most people using Ory are using something like Angular, Vue, or React where this solution won't work at all and will require a custom workaround.

I think for now the best option is to disable the CSP causing trouble for this particular page and wait for CSP3's https://www.w3.org/TR/CSP3/#unsafe-hashed-attributes-usage attribute to land.
