### ISSUE TITLE
Support `PATCH` for identities

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#2380]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).

### Describe your problem

I think it sholud be possible to use `adminUpdateIdentity` without passing a traits object in it (or a `nil`).

I'm using it only to change state of the identity (active/inactive).

Is there another way?

### Version

0.9.0-alpha.3

**Comment by aeneasr** [comment]
Using `PUT` (update) requires you to send the full identity as it replaces all of the contents. We do not support `PATCH` yet but it would be a good idea to add it and support updating only individual fields

**Comment by renom** [comment]
Supporting JSON Patch would be useful for updating arrays in an identity. Could it be added too?

**Comment by jonas-jonas** [comment]
@zepatrik [JSON Patch](https://jsonpatch.com/) might be a good solution for "merging" traits, as we talked about in #2380. I would even say it might be in scope of the existing PR, and I would be willing to take a look at it over there. There are Golang SDKs available: https://jsonpatch.com/#go WDYT?

**Comment by aeneasr** [comment]
We have PATCH support in Hydra already, we can for sure just copy the approach :) 

https://github.com/ory/hydra/blob/5a753234bea813f875869d5dd9042dc96482e3ef/client/handler.go#L343

**Comment by frederikhors** [comment]
Why I cannot find this PATCH in https://www.ory.sh/docs/kratos/reference/api#operation/adminUpdateIdentity?

**Comment by aeneasr** [comment]
Hope this fixes it: https://github.com/ory/kratos/pull/2784

**Comment by frederikhors** [comment]
I still cannot see it in docs page:

![image](https://user-images.githubusercontent.com/41120635/194009687-035dc52d-e798-4def-92c3-ad7be7d4cb5a.png)

**Comment by aeneasr** [comment]
It is not yet released, only merged

**Comment by frederikhors** [comment]
Ok. Sorry.

**Comment by renom** [comment]
Is there no way to patch the identity with HTTP API from frontend at the moment?

**Comment by aeneasr** [comment]
This has long been released

**Comment by renom** [comment]
> This has long been released

I mean a use-case when a logged in user patches their own identity.

**Comment by renom** [comment]
Patching `metadata_admin` doesn't work.

Request:
```
GET http://server_url/admin/identities/identity_id
```
Response:
```
{
    "id": "identity_id",
    "credentials": {
        // credentials data
    },
    "schema_id": "default",
    "schema_url": "http://schema_url",
    "state": "active",
    "state_changed_at": "2023-02-07T12:38:46.777687Z",
    "traits": {},
    "metadata_public": {},
    "metadata_admin": {},
    "created_at": "2023-02-07T12:38:46.781842Z",
    "updated_at": "2023-02-07T12:38:46.781842Z"
}
```
Request:
```
PATCH http://server_url/admin/identities/identity_id
[
  { "op": "add", "path": "/metadata_admin/field1", "value": "value1" }
]
```
Response:
```
{
    "error": {
        "code": 400,
        "status": "Bad Request",
        "reason": "add operation does not apply: doc is missing path: \"/metadata_admin/field1\": missing value",
        "message": "The request was malformed or contained invalid parameters"
    }
}
```

**Comment by renom** [comment]
An extra example.

Request:
```
GET http://server_url/admin/identities/identity_id
```
Response:
```
{
    "id": "identity_id",
    "credentials": {
        // credentials data
    },
    "schema_id": "default",
    "schema_url": "http://schema_url",
    "state": "active",
    "state_changed_at": "2023-02-07T12:38:46.777687Z",
    "traits": {},
    "metadata_public": {},
    "metadata_admin": {
        "field1": ""
    },
    "created_at": "2023-02-07T12:38:46.781842Z",
    "updated_at": "2023-02-07T12:38:46.781842Z"
}
```
Request:
```
PATCH http://server_url/admin/identities/identity_id
[
  { "op": "add", "path": "/metadata_admin/field1", "value": "value1" }
]
```
Response:
```
{
    "error": {
        "code": 400,
        "status": "Bad Request",
        "reason": "add operation does not apply: doc is missing path: \"/metadata_admin/field1\": missing value",
        "message": "The request was malformed or contained invalid parameters"
    }
}
```

**Comment by renom** [comment]
Request:
```
GET http://server_url/admin/identities/identity_id
```
Response:
```
{
    "id": "identity_id",
    "credentials": {
        // credentials data
    },
    "schema_id": "default",
    "schema_url": "http://schema_url",
    "state": "active",
    "state_changed_at": "2023-02-07T12:38:46.777687Z",
    "traits": {},
    "metadata_public": {},
    "metadata_admin": {
        "field1": ""
    },
    "created_at": "2023-02-07T12:38:46.781842Z",
    "updated_at": "2023-02-07T12:38:46.781842Z"
}
```
Request:
```
PATCH http://server_url/admin/identities/identity_id
[
  { "op": "replace", "path": "/metadata_admin/field1", "value": "value1" }
]
```
Response:
```
{
    "error": {
        "code": 400,
        "status": "Bad Request",
        "reason": "replace operation does not apply: doc is missing path: /metadata_admin/field1: missing value",
        "message": "The request was malformed or contained invalid parameters"
    }
}
```

**Comment by renom** [comment]
Similar requests for `metadata_public` work fine.
