### ISSUE TITLE
Import identities with custom id

### ISSUE THREAD

**Issue by markusnissl** [ory/kratos#2388]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I searched the discussions, docs, etc. but could not found a feature regarding custom identity ids.

At a gateway/reverse proxy I check the "/sessions/whoami" endpoint whether the identity is authorised. This request provides the "X-Kratos-Authenticated-Identity-Id" header which is forwarded to my service and uniquely identifies the current identity.

In order to simplify testing/make the migration from a different system easier, it would be nice to provide these ID when importing the credentials instead of auto-generating the uuid. 

### Describe your ideal solution

It would be nice when it is possible when creating a user identity over the cli, to have the possibility to specify next to schema attributes like email address and password also the id of the identity. 

### Workarounds or alternatives

I also thought of introducing an additional field and manually assign the id to it instead of using the Kratos-Ids. However, the header is bound to the Kratos-Id and hence I would require an additional request at the service to get the custom ID specified. One possibility to allow this is to make the provided return headers of the whoami endpoint customisable, so that not only the ID is returned, but one can select which header elements should be injected. But I think, there may be again some issues in case different schemas are used.

Current Workaround:
At a moment I use a service which maps the new Ids to the old Ids for the old users.
For test cases, I create dynamic seeders that fetch the created uuid and include them in the following tests.

I am open also for other solutions or nice workarounds. These are just the ideas I had in mind at the moment.
 

### Version

v0.9.0-alpha3

**Comment by aeneasr** [comment]
Unfortunately this is not possible and never will be! This is due to security and performance reasons. We will introduce an additional metadata field in the identity object which you may use to store the legacy IDs.

**Comment by markusnissl** [comment]
That's a good point with security and performance. An additional metadata field sounds like a good option and is not limited to this use case.

**Comment by designermonkey** [comment]
> Unfortunately this is not possible and never will be! This is due to security and performance reasons.

Please can you explain a little more why being able to provide pre-calculated UUIDs for new users is a security and performance concern?

Surely not having to calculate a UUID is a performance boost? And, as long as the provided UUID is valid, surely that isn't a security hole?

It's one thing I find really frustrating with Kratos; that I can't provide the UUIDs that we already have used as the identities for users. Why should we have to map existing UUIDs to Kratos ones when the easier and simpler solution would be to accept existing UUIDs if they are provided?

**Comment by aeneasr** [comment]
The problem is that we let the database generate the UUIDs which means that it can do optimizations, reducing write time significant. This is especially important when batch importing millions of IDs.

We're working on a solution in Ory Network to circumvent this somehow because the use-case is very much valid!

**Comment by aeneasr** [comment]
The problem with imported UUIDs is that we do not know the algorithm used that generated the UUIDs. If the algorithm is faulty and is not evenly distributed, we'll introduce hot-spots to our database which can lead to significant performance degradation!
