### ISSUE TITLE
Microsoft B2C OIDC provider is using invalid `iss` value

### ISSUE THREAD

**Issue by mooijtech** [ory/kratos#2404]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I am trying to implement OAuth2 with Microsoft but the issuer URL returned does not match as Microsoft does not seem to follow the OIDC specification: 
- https://github.com/coreos/go-oidc/issues/159#issuecomment-517750749
- https://github.com/MicrosoftDocs/azure-docs/issues/38427

```
An internal server error occurred, please contact the system administrator reason:Unable to initialize OpenID Connect Provider: oidc: issuer did not match the issuer returned by provider, expected "https://login.microsoftonline.com/common/v2.0" got "https://login.microsoftonline.com/{tenantid}/v2.0"
```

### Describe your ideal solution

Add a configuration option to skip verification of the issue_url.

### Workarounds or alternatives

I currently implement the OAuth2 endpoints myself but would like to switch to Ory Kratos.

### Version

v0.9.0-alpha.3

**Comment by aeneasr** [comment]
Did you set the tenant in your config?

**Comment by mooijtech** [comment]
@aeneasr There is no tenant, I want to use the "common" endpoint.

**Comment by mooijtech** [comment]
My problem is Ory Kratos checks the issuer_url (if it matches the issuer returned by the provider) but Microsoft does not follow the specification so I'm getting this error (see the references I posted).
So there needs to be an option to skip checking the issuer_url.

**Comment by aeneasr** [comment]
That is not possible as it would be an extreme security vulnerability. I’m sure though that what you want to do is possible, but without your configuration (please see issue template) or an easily reproducible case it won’t be possible to assist. A good option would also be to ask others on Slack or this repository‘s discussion, as they might have already set this up! :)

**Comment by mooijtech** [comment]
@aeneasr I already looked at existing issues related to this, they all say Microsoft doesn't follow the specification so they ended up skipping the issuer_url verification as that is the only solution and Microsoft won't fix it.
So because Ory Kratos does not support skipping the issuer_url even if the auth_url and token_url are set, this means you don't plan on supporting Microsoft OAuth2?

**Comment by mooijtech** [comment]
Please see this issue: https://github.com/coreos/go-oidc/issues/159#issuecomment-517750749
Ory Kratos is using go-oidc and it's implemented there.

**Comment by mooijtech** [comment]
This would also mean that other people can't implement Microsoft OAuth2, like this person: https://github.com/ory/kratos/discussions/1966

**Comment by aeneasr** [comment]
Thank you for the added context, I read through https://github.com/MicrosoftDocs/azure-docs/issues/38427 and it appears that there is no possible configuration. As a small rant, I dislike Microsoft for this. They implement OAuth2 and OIDC everywhere and it's just terrible. Just getting from service A to B can sometimes end up in infinite redirects and so many other issues. Not sure what their auth team is thinking...

Anyways, we'll look into options to fix this. Skipping the issuer URL check is not an option due to several security issues but we'll probably be able to find another workaround!

**Comment by aeneasr** [comment]
Looks like this is the correct way to implement this: https://github.com/coreos/go-oidc/pull/315/files#diff-e4bf9a582a73202cd7e001d3504364515fba25bd9bbd56a5d891dc880bf3fb96R72

**Comment by mooijtech** [comment]
Thank you for your quick responses and for looking into this!

My use case is getting the user profile (email) and then the token for IMAP access.
Microsoft requires two scopes for getting the user profile and then the token (same endpoint, with different scopes).
Which was going to be my next question: is it possible after the user has authenticated with Microsoft that the redirect performs the second scope requests and updates the session (traits)?

Looking forward to a workaround for this as I need IMAP integration with Outlook for my forensic software I'm working on.

**Comment by aeneasr** [comment]
The fastest way to get this on master is to provide a PR with tests that covers this use case! Most of Ory is on vacation currently, and we have many other high priority topics :)

**Comment by ericb-summit** [comment]
Hey guys when I tried to use azure ad oidc with a project based on dex at first I ran into the same problem you have, but when I switched to an issuer URL like below, it worked.

https://sts.windows.net/YOUR_TENANT_UUID/.well-known/openid-configuration

HTH.

**Comment by aeneasr** [comment]
Oh, nice! @mooijtech can you try this?

**Comment by mooijtech** [comment]
@ericb-summit What if I don't want a specific tenant but any Microsoft Azure user? I would have to use the common endpoint so your solution unfortunately doesn't work. Your endpoint only works for one tenant.

**Comment by mooijtech** [comment]
I don't know in advance what tenant the user is from, that's what the common endpoint is for.

**Comment by mooijtech** [comment]
If you read the issues I referenced they are all having the same problem.

**Comment by aeneasr** [comment]
@mooijtech I understand that this issue is pressing to you. Everyone here is just trying to help. It would be great if you could use the edit button to update your comments and / or try out the suggestions made by others. If they do not work point to what's missing, if they do work please share your findings in a technical manner.

Contrary to slack or other forms of communication like WhatsApp, a lot of people are monitoring the repository here and get email pings and notifications for every comment made, which is why we ask everyone to condens their technical findings into a well described comment that helps others helping you. Thanks! :)

**Comment by mooijtech** [comment]
I was working on implementing a workaround by overriding the issuer URL provider returned and in the source code I saw you can set the `microsoft_tenant` to `common`!
Also I didn't see this: https://www.ory.sh/docs/kratos/guides/sign-in-with-github-google-facebook-linkedin#microsoft

So my issue is solved, it works now.
