### ISSUE TITLE
Pagination metadata

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2405]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

At the moment, the list queries (e.g. `GET /admin/identities`) only return a list of items without any meta information like the total item count, the total page count, or whether there is a next page. This makes it difficult to render pagination in a user interface.

### Describe your ideal solution

Instead of just returning a list of items, the list endpoints would return additional meta information. For example:

```json
{
  "items": [
    {
      "created_at": "2019-08-24T14:15:22Z",
      "id": "string",
      "updated_at": "2019-08-24T14:15:22Z",
    },
    ...
  ],
  "meta": {
    "has_previous_page": true,
    "has_next_page": true,
    "page": 5,
    "per_page": 20,
    "total_count": 158,
    "total_pages": 32
  }
}
```

In an ideal world, Kratos would also give the option to switch between page-based pagination and cursor-based pagination.

- no query parameters, or either `page` or `per_page` set: use page-based pagination, response as above
- at least one of `first`, `after`, `last` or `before` set in query: use cursor-based pagination

In the case of cursor-based pagination, the response would look like this:

```json
{
  "items": [
    {
      "created_at": "2019-08-24T14:15:22Z",
      "id": "string",
      "updated_at": "2019-08-24T14:15:22Z",
    },
    ...
  ],
  "meta": {
    "has_previous_page": true,
    "has_next_page": true,
    "start_cursor": "9876f9kzhgfikuafgebkf9kbeai",
    "end_cursor": "iaqe8kbuiaqe98bukiaeq8biahbeq98"
  }
}
```

We could follow the Relay cursor connections specification (sections "Arguments" and "PageInfo") for cursor-based pagination (which also makes sense outside the context of GraphQL APIs).

### Workarounds or alternatives

As a workaround, I have to run a second query with `page = page + 1` at the moment to determine whether to render a `next` link. One step better would be additional `count` queries.

### Version

v0.9.0-alpha.3

**Comment by aeneasr** [comment]
We do! It’s (or should be) in the HTTP Headers: https://www.ory.sh/docs/kratos/concepts/rest-api

**Comment by woylie** [comment]
Whoa, didn't see that! Thanks!
