### ISSUE TITLE
password_identifier property in SubmitSelfServiceLoginFlowWithPasswordMethodBody interface noted as deprecated but not marked as optional

### ISSUE THREAD

**Issue by perjo927** [ory/kratos#2408]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am using the `SubmitSelfServiceLoginFlowWithPasswordMethodBody` to type args to a request body designated for the Kratos login endpoint, so that the request body is correctly populated.

However, since `password_identifier` is not followed by a question mark, Typescript will complain the that the property is required although in reality it is not recommended to use. 

![image](https://user-images.githubusercontent.com/2391754/164013305-2d1db949-3fe3-45a2-bd3c-6e06046c09c5.png)

### Reproducing the bug

1. Install "@ory/kratos-client": "0.9.0-alpha.3" in a Javascript project.
2. Use the SubmitSelfServiceLoginFlowWithPasswordMethodBody for typing the request body

### Version

0.9.0-alpha.3

### On which operating system are you observing this issue?

macOS

### Additional Context

A question mark following the password_identifier property should suffice (?)

**Comment by aeneasr** [comment]
As a workaround setting it to an empty string should be enough!

**Comment by perjo927** [comment]
gotcha:)
