### ISSUE TITLE
Move away from UUID-based challenges and responses

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#241]
**Describe the bug**

We are currently using UUIDs as challenge/response payloads. Those have only 122 bit of randomness and while still hard to guess (especially with expiry) it would be better to move to e.g. 512 instead.

**Additional context**

Should be solved together with #236

**Comment by ashley-3r** [comment]
Is there a point to going to more than 256 bits of entropy ? As SHA-256 hash function used for JWT validation relies on the order of magnitude of 256. In practice, i think more than 90 bits is the bare requirement without non reliable pseudo generators. Going to 256 would compensate for lack of entropy of underlying generators particularly if no brute force checks are in place.

**Comment by aeneasr** [comment]
256 is probably probably more than enough!

**Comment by aeneasr** [comment]
I took a deeper dive into this topic. According to [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions) the chance of collision is:

> For example, the number of random version-4 UUIDs which need to be generated in order to have a 50% probability of at least one collision is 2.71 quintillion, computed as follows:[14]
>
> [...]
>
> This number is equivalent to generating 1 billion UUIDs per second for about 85 years. A file containing this many UUIDs, at 16 bytes per UUID, would be about 45 exabytes.
>
> The smallest number of version-4 UUIDs which must be generated for the probability of finding a collision to be p is approximated by the formula:
>
> [...]
>
> Thus, the probability to find a duplicate within 103 trillion version-4 UUIDs is one in a billion.

Given that alle of our TOTPs have a TTL shorter than a day, typically shorter than an hour, the chance of collision is small enough and do not justify the effort to move away from UUIDs which would include:

- Adding new columns for these identifiers with a `VARCHAR` big enough, an index, and a unique key.
- Outfitting all relevant requests with the new identifiers while still keeping UUIDs around for joins.
