### ISSUE TITLE
Identity metadata should be settable through web hooks

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2412]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The new metadata fields are not possible to be modified by web hooks.

### Describe your ideal solution

Once web hooks can modify identities, they should also be able to modify the metadata of those identities.

### Workarounds or alternatives

none

### Version

unreleased

**Comment by sayoun** [comment]
hello, we are interested in that feature as we must handle a legacy system and the new kratos, so we need to populate some metadata for each identity from the legacy system.

how high is this feature regarding the kratos roadmap/priority ?

**Comment by aeneasr** [comment]
Hi there, it has a high priority. But it probably won't be done before next year
