### ISSUE TITLE
Docs: Webauthn yaml configuration incorrect

### ISSUE THREAD

**Issue by perjo927** [ory/kratos#2414]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Following the [configuration described here](https://www.ory.sh/docs/kratos/guides/two-factor-authentication-2fa-mfa#configuration), in the "Full Config" tab, the `methods` property is nested under `selfservice`/`flows`.

I believe `methods` should be a direct child to `selfservice` instead of a child to `flows`.

![image](https://user-images.githubusercontent.com/2391754/164444542-abeb81a4-bd33-4e69-b6a0-089330f87057.png)

### Reproducing the bug

1. Copy the configuration described [here](https://www.ory.sh/docs/kratos/guides/two-factor-authentication-2fa-mfa#configuration), from the tab "Full Config"

### Version

v0.9.0-alpha.3 

### Additional Context

Apologies if this should belong to another category than a bug report.

**Comment by aeneasr** [comment]
Thank you for the report, you're right :) Would you be open to contribute this in a PR?

**Comment by perjo927** [comment]
Would be my pleasure!
