### ISSUE TITLE
Include additional query parameters when starting browser login flow.

### ISSUE THREAD

**Issue by Urbansson** [ory/kratos#2424]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When implementing a browser based self service login flow sometime extra query parameters might be included in the login in request, one example is the `login_challenge` from Hydra but it could also be application specific parameters   like tracking ID:s and so on.

## Example: 

Hydra will redirect to your login page at `/login?login_challange=<challangeID>`.

In the login handler we will have to redirect to browser to Kratos to start the login flow at `/self-service/login/browser`and we then get redirected back to `/login?flow=<flowID>`.

 At this point we have lost all of our initial query parameters that was provided, in this case `login_challange=<challangeID>`. 

### Describe your ideal solution

When getting redirected back from starting a browser based self service login flow all additional query parameters that was provided when starting the flow should be included in the redirection.

## Example

When starting the flow with:
`/self-service/login/browser?foo=bar`
The redirection should be:
`/login?flow=<id>&foo=bar`

### Workarounds or alternatives

One workaround is to set cookies in the login handler containing all addition parameters and then check it when getting redirected back to your handler.

You could also add all your extra query paramets to the login flow request and then get the flow from the API and check the `"request_url"` field that contains the raw request and extract all the query parameters from that.

### Version

v0.9.0-alpha.2

**Comment by aeneasr** [comment]
> You could also add all your extra query paramets to the login flow request and then get the flow from the API and check the "request_url" field that contains the raw request and extract all the query parameters from that.

That is the recommended way!

@vinckr this is coming up every couple of weeks it feels like - do we have this documented? If so, where and if not, where would be a good place for this?
