### ISSUE TITLE
AdminExtendSession not working as expected

### ISSUE THREAD

**Issue by vinckr** [ory/kratos#2427]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

- I found examples for the earliest_possible_extend in the docs, but also references to earliest_refresh  https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions#reduce-database-load
- The docs for configs also has examples of earliest_possible_extend, but I can’t set this value without getting an error https://www.ory.sh/docs/kratos/reference/configuration
- I cannot see AdminExtendSession on 0.9.0-alpha.3 here https://github.com/ory/kratos/blob/v0.9.0-alpha.3/internal/httpclient/README.md but can see it here https://github.com/ory/kratos/blob/e0fc0dfe337360c2975ba72ed9a3a8193b1b1dbf/internal/httpclient/docs/V0alpha2Api.md#adminextendsession
- I found this PR https://github.com/ory/kratos/pull/2146 where aeneasr merged the admin session extend feature 28 days ago (to where, I have yet to figure out)
- I have tried to make request directly to localhost:4434/admin/sessions/{id}/extend only to hit 404 and 403 errors

---
 
I tried using it for Ory Cloud as described in the documentation 

```
ory patch identity-config <your-project-id> \\
  --replace '/session/earliest_possible_extend="24h"'
```

There was no error but the config also does not seem to have changed.

### Reproducing the bug

Use `earliest_refresh`
as described here:
https://www.ory.sh/docs/guides/session-management/refresh-extend-sessions#reduce-database-load

### Version

latest

### On which operating system are you observing this issue?

Ory Cloud

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
This feature is indeed not yet released, but it was already merged to the docs. Once released, it will be available :)

**Comment by kszafran** [comment]
@aeneasr Do you have any estimates on when a Kratos version with this feature might be released? I hope it's not months. We'd really welcome this feature.

**Comment by groue** [comment]
> This feature is indeed not yet released, but it was already merged to the docs. Once released, it will be available :)

Hello @aeneasr, how do we know if the feature is released or not?

Today, it looks like the `/session/whoami/refresh_allowed` identity config key is not supported yet:

```
$ ory patch identity-config $PROJECT --replace '/session/whoami/refresh_allowed=true'
The request was malformed or contained invalid parameters
Unable to validate config: I[#] S[#/oneOf] oneOf failed
  I[#] S[#/oneOf/0] validation failed
    I[#] S[#/oneOf/0/allOf/1] allOf failed
      I[#] S[#/oneOf/0/allOf/1/$ref] doesn't validate with "static://ory.cloud.schema.json#"
        I[#/session/whoami] S[#/properties/session/properties/whoami/additionalProperties] additionalProperties "refresh_allowed" not allowed
...
```

**Comment by aeneasr** [comment]
> Today, it looks like the /session/whoami/refresh_allowed identity config key is not supported yet:

If I recall correctly, we decided against introducing that specific feature flag - so that flag never made it into the product. Instead, you have to use the Admin API to refresh the session. This is documented here: https://www.ory.sh/docs/kratos/session-management/refresh-extend-sessions

> [EDIT]: According to the [Ory Release Notes](https://www.ory.sh/release-notes/), nothing new has shipped since your answer from April.

Oh, that's embarassing. We have to either remove that page or update it. We ship features on a daily basis and the ory network is also usually ahead of the open source releases

@kmherrmann @mszekiel fyi

**Comment by groue** [comment]
Thank you very much @aeneasr :-)
