### ISSUE TITLE
selfservice/profile: sudo mode for updating auth related stuff

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#243]
- [ ] To allow updating auth related stuff we need to reauthenticate the user after a certain amount of time (15-30min seems good). The session already stores an "authenticated_at" timestamp.
- [x] This time has to be configurable.
- [x] We also need a new UI url endpoint that is responsible for reauthentication. This differs from login by: password strategy identifier is fixed, oidc has to force reauthentication

**Comment by aeneasr** [comment]
The login edpoint(s) currently only work(s) when logged out, so this needs to be adjusted.

For OIDC we need to use `prompt=login` to force proper re-authentication at the upstream OIDC provider.

**Comment by zepatrik** [comment]
Done: 
- do reauthentication #248 
- update protected traits when the session is new enough (incl. configuring that time) #266 

Still missing:
- add post-update hooks

**Comment by zepatrik** [comment]
todo:
- handle case when UpdateProfileRequest was initiated within "sudo time" but POST was after that
we should then redirect to the login screen that would ideally be aware of the identifier and just asks for credentials to then submit the changes

**Comment by zepatrik** [comment]
- disable protected traits only when it is not allowed to change them
