### ISSUE TITLE
Inconsistent CLI commands in master

### ISSUE THREAD

**Issue by carloschida** [ory/kratos#2435]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When building and executing the docker image (via `make docker`) in [current master](https://github.com/ory/kratos/commit/e6b38c253466f9f724d2762b01c18485ed96f648) , I get the following inside the container:

```shell
/ $ kratos version
Unable to determine version because the build process did not properly configure it.
Build Commit:   e6b38c253466f9f724d2762b01c18485ed96f648
Build Timestamp:        2022-04-30T20:39:15Z
/ $ kratos
Usage:
  kratos [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  courier     Commands related to the Ory Kratos message courier
  delete      Delete resources
  format      Helpers for formatting code
  get         Get resources
  hashers     This command contains helpers around hashing
  help        Help about any command
  import      Import resources
  lint        Helpers for linting code
  list        List resources
  migrate     Various migration helpers
  remote      Helpers and management for remote Ory Kratos instances
  serve       Run the Ory Kratos server
  validate    Validate resources
  version     Show the build version, build time, and git hash

Flags:
  -h, --help   help for kratos

Use "kratos [command] --help" for more information about a command.

```

On the other side, when using the [published docker image with version v0.9.0-alpha.3](https://hub.docker.com/layers/kratos/oryd/kratos/v0.9.0-alpha.3/images/sha256-28953d0e7d08a011564afbb9acc76716a076932861e16438c2571347b05de620?context=explore), I get the following:

```shell
~ $ kratos version
Version:                        v0.9.0-alpha.3
Build Commit:   32e36d4e75f888e69653625a52171200b4968a6c
Build Timestamp:        2022-03-25T09:35:43Z
~ $ kratos
Usage:
  kratos [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  courier     Commands related to the Ory Kratos message courier
  hashers     This command contains helpers around hashing
  help        Help about any command
  identities  Tools to interact with remote identities
  jsonnet     Helpers for linting and formatting JSONNet code
  migrate     Various migration helpers
  remote      Helpers and management for remote Ory Kratos instances
  serve       Run the Ory Kratos server
  version     Show the build version, build time, and git hash

Flags:
  -h, --help   help for kratos

Use "kratos [command] --help" for more information about a command.
```

Note the difference in the CLI commands.

As far as I can tell from `cm/root.go` the latter is expected but somehow on master it's not the case.

### Reproducing the bug

For the current master:

```shell
git checkout e6b38c253466f9f724d2762b01c18485ed96f648
make docker
docker run -d --name kratos_master oryd/kratos:latest
docker exec kratos_master kratos version
docker exec kratos_master kratos
```

For the v0.9.0-alpha.3:
```shell
docker run -d --name kratos_090alpha3 oryd/kratos:v0.9.0-alpha.3
docker exec kratos_090alpha3 kratos version
docker exec kratos_090alpha3 kratos
```

### Version

latest and v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

My goal is to have a docker container with this fix (https://github.com/ory/kratos/issues/2367) since it's not yet published in DockerHub.

**Comment by carloschida** [comment]
My confusion comes from the inconsistency in the folder/package structure of the package `cmd` and the documentation.
This was introduced in https://github.com/ory/kratos/commit/73910a329b1ee46de2607c7ab1958ef2fb6de5f4#.

I'll make a PR shortly that refactors the `cmd` package.

**Comment by aeneasr** [comment]
The CLI has changed quite a lot since 0.9.0 but this is not yet released. Once master is released, this will be equal - closing :)
