### ISSUE TITLE
Bulk Identity Fetch Api

### ISSUE THREAD

**Issue by nxy7** [ory/kratos#2448]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Using kratos as single source of truth might lead to some suboptimal workflows. Because you can get identities only one by one or paginated list of all identities, it might be necessary to make N requests instead of one bulk request.
Let's say you store just id's from kratos in main app database and you have comments table {userId, text}. I think it would be for the best to store traits in just one place - kratos db, if that's the case you need one additional request to get user traits for every single comment if you want to use data from traits. 

### Describe your ideal solution

Make new kratos endpoint accepting array of 'id's. 

### Workarounds or alternatives

Duplicate traits in main app database or make too many fetch requests :P

### Version

v0.7.1-alpha.1

**Comment by RubenWerdmuller** [comment]
Any news on this end? 👀

**Comment by nxy7** [comment]
I'm willing to try implementing this myself, one question though. Is it fine if we leave the same endpoint and make it accept /admin/identities/{id} and /admin/identities/{id}&{id}&{id}&{id}?

**Comment by RubenWerdmuller** [comment]
@nxy7 I think a conventional solution for this is desirable. I'm not familiar with all patterns, but I'd suggest sending a body that includes the parameters needed. In our case `ids`.

[Similar to how elastic queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html)

**Comment by nxy7** [comment]
Sounds good to me. Would you accept PR modifying `/admin/identities` endpoint then?

**Comment by alnr** [comment]
What's wrong with firing several requests instead? You can also do it in parallel if latency is the issue.

I'm wary of adding APIs like this because they end up getting more and more complicated over time. Each use case requires a totally different code path. The first feature requests are [already coming in](https://github.com/ory/kratos/issues/2448#issuecomment-1211470576) even though the base functionality doesn't even exist yet 😆

**Comment by nxy7** [comment]
@alnr Mentioned 'feature request' isn't really related to bulk fetching api :P
I think that there's huge value to bulk fetching and it's weird to me that someone thinks forcing people to do N+1 requests is correct choice. It can quickly turn into unplanned stress testing kratos instances that can be avoided just by being a little more efficient. 
It would make client side code more readable too. Why wait for all promises/goroutines/stream of futures if you can make one request instead?
I'd understand your logic if that was some esoteric feature, but bulk fetch is just extending current fetch or adding filter to identity list. Both seem reasonably easy to implement and maintain.

**Comment by hperl** [comment]
If we go ahead with this I think the best query syntax is `/admin/identities?ids=id1&ids=id2&ids=id3`, so that it will get parsed into an array through Go: https://go.dev/play/p/MkdZWEX7s26

Other than that I think that this proposal makes sense.
