### ISSUE TITLE
Kratos configuration editor not working

### ISSUE THREAD

**Issue by tomekpapiernik** [ory/kratos#2457]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The configuration editor for Ory Kratos doesn't work. When you try to access it, a blank page is shown. 

https://www.ory.sh/docs/kratos/reference/configuration-editor

### Reproducing the bug

Go to https://www.ory.sh/docs/kratos/reference/configuration-editor

### Version

current

### On which operating system are you observing this issue?

macOS

### Additional Context

The same behavior is true in Chrome and Safari.

**Comment by tomekpapiernik** [comment]
Maybe @gen1us2k could handle that? Might be a similar problem to the one you fixed for the Hydra editor.

**Comment by gen1us2k** [comment]
@tomekpapiernik I opened PR to the [docs repo ](https://github.com/ory/docs/pull/805 ). It's because of recent [open-telemetry changes](https://github.com/ory/kratos/commit/121a4d3fc0f396e8da50ad1985cacf68a5c85a12)

**Comment by tomekpapiernik** [comment]
@gen1us2k thanks! The fix worked so I merged your PR. Closing this issue.
