### ISSUE TITLE
use appropriate input type for enum traits

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2459]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When a trait is defined as an enum, Kratos should return the node either as a select or a group of radio buttons. At the moment, it returns a text input.

This has been requested before in #175, but the related PR only handled the `pattern` attribute.

### Describe your ideal solution

see above

### Workarounds or alternatives

none

### Version

v0.9.0-alpha.3

### Additional Context

I'm storing the user's locale in Kratos. With the information returned by Kratos, the form only shows the allowed values in the validation message that is returned after submission.

```json
{
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "locale": {
          "type": "string",
          "enum": ["en", "ja"],
          "default": "ja"
        }
      }
    }
  }
}
```

**Comment by aeneasr** [comment]
This is a good idea! The implementation however will be more difficult as selects work a bit differently on every platform (e.g. native vs web). I think the best way to support complex fields is to write your own UI or extend the ones we provide, as the flexibility of the Ory Kratos form builder will have several limitations

**Comment by woylie** [comment]
In that case, I think the easiest thing to do would be to add the enum values to the node. Then I can easily map any text node with an enum attribute to a select. Shall I open a PR for that?

**Comment by aeneasr** [comment]
Makes sense! Is there a well-known property we could use for this? Similar to `disabled` or `pattern`?

**Comment by woylie** [comment]
I don't think so. Are the `attributes` supposed to map directly to HTML attributes (with the exception of the `node_type` field)? Then we have two options: either use a `data` attribute (`data-enum`), or add the enum values to `node.meta` instead.

**Comment by woylie** [comment]
Still relevant, partly implemented.

**Comment by Orlandoiii** [comment]
I'd like to request this be reopened. Currently, UI nodes for enum traits don't provide the available options, which forces the frontend to either hardcode values or perform manual schema lookups. Since select elements are a core part of most identity schemas, the UI nodes lose much of their utility if they aren't self-describing enough to render these options automatically. Maybe is a skill issue of my part please is someone knows a workaround please let me know.
