### ISSUE TITLE
Kratos Cli check command to check config file 

### ISSUE THREAD

**Issue by gen1us2k** [ory/kratos#2461]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Kratos checks a configuration file and reports configuration errors during runtime. One needs to use any of the commands (`migrate`, `serve`, or else). The only way to understand is the output to stdout which sometimes can be messy when one uses it under the docker container. Hence, it's hard to troubleshoot configuration errors. 

### Describe your ideal solution

It would be best to have `kratos check -c /path/to/config.yml` command. In that case, engineers can use it in their CI/CD pipelines or deploy Kratos to clean VMs using `systemctl` or something similar

### Workarounds or alternatives

Read logs to understand what's going wrong. 

### Version

v0.8

**Comment by aeneasr** [comment]
Great idea!
