### ISSUE TITLE
Verify email through admin endpoints

### ISSUE THREAD

**Issue by MilesNorton** [ory/kratos#2473]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

At the moment we are trying to invite a user to our platform using the recovery method described here: https://github.com/ory/kratos/discussions/1342

This process requires them to access their emails for the invitation where they will then be redirected to create a password.
I feel like this is sufficient enough for showing that they are verified. 

So with that being said it would be nice to have an admin endpoint to manually update their verified status to true. We could high jack the admin identity update endpoint to do this. The create endpoint allows you to specify a verified email but that requires an id which can't be obtained because the email hasn't been registered in out system

### Describe your ideal solution

When creating/updating an identity through the admin endpoints we should be able to set a verified email address.

### Workarounds or alternatives

Manually access the kratos database

### Version

v0.9.0-alpha.3

**Comment by plarsson** [comment]
I'm looking into the same issue.  The email in question is verified implicit when user completes the recovery flow triggered by the link in the mail.  Shouldn't Kratos automatically treat this as verified and update the verified status?

**Comment by aeneasr** [comment]
I wanted to say that you can have a verified address (verifiy@example.org) and a recovery address (recovery@example.org) which are not the same. But then I thought that it would probably be possible to verify an the address when you're recovering an address that is equal to it.

**Comment by halvardssm** [comment]
I am also seeking this feature. My use case is when dealing with e2e tests, as it would be great to have a simple admin endpoint for verifying created users as a part of the test flow so that it does not fail from the `require_verified_address` hook.

**Comment by nonparibus** [comment]
Just wanted to flag that this is also a thing we'd get value from, in case additional voices might help guide prioritization.

**Comment by sgrannan** [comment]
This would be helpful since we upgraded to Ory Kratos v11+ because of the expanded Admin APIs. We've been able to implement a better Invite System but we have to create Identities with `"verified" : true ` right now. While the invited user cannot login, they do have the means to initiate a recovery flow. 

In lieu of making this part of the whole User Invites Flow (#2525), would it be possible just to get this end point in a minor update? 

`POST /admin/verification
identity_id: {id}
identifier: {id}`

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/pull/3059 introduces this feature for webhooks, so this is now possible in the business logic and probably quite easy to expand to the admin api!

**Comment by Sytten** [comment]
Since there is no dedicated API I managed to do it via a PATCH on the identity.
I used to do it in the database directly but thats too sketchy even for me.

For a simple email sign-up you have:
```json
"verifiable_addresses": [
    {
      "id": "128183b9-e51c-49b9-8367-751c447f4db3",
      "value": "xxxx@example.com",
      "verified": false,
      "via": "email",
      "status": "sent",
      "created_at": "2024-06-12T18:44:35.264778Z",
      "updated_at": "2024-06-12T18:44:35.264778Z"
    }
  ],
```

And a "verified" one looks like:
```json
"verifiable_addresses": [
    {
      "id": "128183b9-e51c-49b9-8367-751c447f4db3",
      "value": "xxxx@example.com",
      "verified": true,
      "via": "email",
      "status": "completed",
      "verified_at": "2024-06-12T18:54:27.477414Z",
      "created_at": "2024-06-12T18:44:35.264778Z",
      "updated_at": "2024-06-12T18:54:27.546953Z"
    }
  ],
```

Here is the rust code:
```rust
pub async fn verify(&self, identity_id: &str) -> Result<()> {
        let now = time::OffsetDateTime::now_utc()
            .format(&Rfc3339)
            .expect("Invalid format");

        let patches = vec![
            JsonPatch {
                from: None,
                op: "replace".to_string(),
                path: "/verifiable_addresses/0/verified".to_string(),
                value: Some(serde_json::Value::Bool(true)),
            },
            JsonPatch {
                from: None,
                op: "replace".to_string(),
                path: "/verifiable_addresses/0/status".to_string(),
                value: Some(serde_json::Value::String("completed".to_string())),
            },
            JsonPatch {
                from: None,
                op: "replace".to_string(),
                path: "/verifiable_addresses/0/verified_at".to_string(),
                value: Some(serde_json::Value::String(now)),
            },
        ];
        identity_api::patch_identity(&self.admin_client, identity_id, Some(patches)).await?;
        Ok(())
    }
```

**Comment by aeneasr** [comment]
Using the path endpoint is the correct way of doing this!
