### ISSUE TITLE
Consider implementing JSON Web Token Exchange endpoint

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2487]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

In some cases, developers want to receive a JSON Web Token to be used with APIs that do not neccessarily need/want to call Ory's APIs.

This is useful in cases where it is acceptable to interpret a session as active even if it has logged out within the last (for example) 5 minutes. Using a JSON Web Token at the backend can significantly reduce latency in the service as no API of Ory has to be called.

### Describe your ideal solution

Having an endpoint such as `/sessions/tokenize?format=jwt` which generates a JSON Web Token with a customizable payload and expiry time, for example

```
{
  "sub": "1234"
  "traits": {
    "email": "..."
  }
  ...
}
```

Customization of the JSON Web Token would probably be done using a JsonNet snippet.

Setting the expiry time would be done through a global config value. It could either be a fixed amount, or a maximum amount (e.g. `1h`) where the caller indicates their preferred expiry time.

### Workarounds or alternatives

Issue JSON Web Tokens at the ingress - requires work at the implementor to add this capability to their e.g. API Gateway.

### Version

master

**Comment by matyasf** [comment]
hi!
What are the plans of this feature? Can we expect that it will be implemented? Or could we write a PR for this feature?
Thanks!

**Comment by vinckr** [comment]
> hi! What are the plans of this feature? Can we expect that it will be implemented? Or could we write a PR for this feature? Thanks!

Hello @matyasf, sorry for the late answer! 
We created this feature to gauge how and if the community would be interested in it. 
Would it be relevant to your use case? 

We are of course always open for contributions, so if you already have an idea how to implement it, I suggest to [open a design document issue](https://github.com/ory/kratos/issues/new?assignees=&labels=rfc&template=DESIGN-DOC.yml) and then work from there.

**Comment by kasir-barati** [comment]
Hi @vinckr, Thanks for this amazing open source work of art. I guess JWT undoubtedly is needed. But I also acknowledge that most of the times sessions are the rescuer. BTW I like to see how would you consider developing this feature? I mean how would you decide whether to implement JWT or not.

Keep shining
Cheers

**Comment by Karitham** [comment]
Hi!

I would greatly appreciate the JWT feature, since it is useful not only for all the usual JWT reasons, but especially for performance reasons.

Having signed tokens ensures we aren't being spammed with fake ones, since the cost of ensuring a token is valid right now is huge compared to decoding the token and comparing the signature.

Downsides to JWT are obvious and they are often misused, so sessions are often the right choice and they surely should stay the default, but signed tokens are desirable too!

Love the docs btw, excellent work!

**Comment by aep** [comment]
sessions tokens are just transparent arbitrary strings aren't they? could just format sessions as JWT tokens and keep all the existing apis unchanged.

**Comment by philhug** [comment]
I'd love to see this, if it allows a browser-initiated session to get access to JWT, which then can be used for API access.

**Comment by localhosted** [comment]
I was going to try Ory Cloud as our auth solution for our next project because for some reason I though this already was available, this is a blocker

**Comment by aep** [comment]
we ended up adapting our system to the way ory works instead of the other way around. 

It's a bit of a learning curve to _unlearn_ all the ideas you have when you're used to oauth but it was worth it. We now have a system that is considerably simpler to reason about.

**Comment by aeneasr** [comment]
Thank you <3 I hope we can do better to make this transition easier in the future :)

**Comment by winston0410** [comment]
I think this would be a very useful feature. Currently I am building a microservice, and I use Ory Kratos to manage all the identities. If I need to secure my microservice, a JWT would be a reasonable choice to do so.

What I don't know is, if this feature does not exists, what existing alternatives do we have now from Kratos to get a token? Or is it expected for us to call a certain endpoint?

**Comment by vinckr** [comment]
> I think this would be a very useful feature. Currently I am building a microservice, and I use Ory Kratos to manage all the identities. If I need to secure my microservice, a JWT would be a reasonable choice to do so.
> 
> What I don't know is, if this feature does not exists, what existing alternatives do we have now from Kratos to get a token? Or is it expected for us to call a certain endpoint?

Hello @winston0410 

Until the above feature is available it is recommended to use Ory Oathkeeper id-token mutator for this purpose: 
https://www.ory.sh/docs/oathkeeper/pipeline/mutator#id_token

> This mutator takes the authentication information (such as subject) and transforms it to a signed JSON Web Token, and more specifically to an OpenID Connect ID Token. Your backend can verify the token by fetching the (public) key from the /.well-known/jwks.json endpoint provided by the Ory Oathkeeper API.

You have to host Ory Oathkeeper on your infrastructure.

**Comment by philhug** [comment]
> Until the above feature is available it is recommended to use Ory Oathkeeper id-token mutator for this purpose: https://www.ory.sh/docs/oathkeeper/pipeline/mutator#id_token

Unfortunately this does not solve the problem that a SPA is not able to get access to the ory session.
And using cookies on APIs comes with a lot of other problems and security issues. (especially if your app is not using the same host name for api and the SPA)

**Comment by aeneasr** [comment]
> And using cookies on APIs comes with a lot of other problems and security issues. (especially if your app is not using the same host name for api and the SPA)

Sorry, but that's just not true! Cookies are neither more or less secure than tokens. In fact, storing tokens outside of the browser's cookie mechanism is less secure as there are many simple attack vectors (such as XSS) one can fall victim too. HttpOnly and secure cookies have the best security gaurantees out there, and the best part is that the browser is completely dealing with refresh and expiry mechanisms, so it even saves you lots of code - which makes your app even more secure (less code, less complexity, more secure).

The only problem cookies have is that they do not work cross-domain from exampleA.org to exampleB.org. In those scenarios, one does need a different mechanism.

**Comment by winston0410** [comment]
> > I think this would be a very useful feature. Currently I am building a microservice, and I use Ory Kratos to manage all the identities. If I need to secure my microservice, a JWT would be a reasonable choice to do so.
> > What I don't know is, if this feature does not exists, what existing alternatives do we have now from Kratos to get a token? Or is it expected for us to call a certain endpoint?
> 
> Hello @winston0410
> 
> Until the above feature is available it is recommended to use Ory Oathkeeper id-token mutator for this purpose: https://www.ory.sh/docs/oathkeeper/pipeline/mutator#id_token
> 
> > This mutator takes the authentication information (such as subject) and transforms it to a signed JSON Web Token, and more specifically to an OpenID Connect ID Token. Your backend can verify the token by fetching the (public) key from the /.well-known/jwks.json endpoint provided by the Ory Oathkeeper API.
> 
> You have to host Ory Oathkeeper on your infrastructure.

Having set up Ory Oathkeeper during the weekend, I think the current solution is working fine, just tedious to set up and deploy everything. Maybe this feature is not that useful

**Comment by vinckr** [comment]
Thanks for the feedback @winston0410. 
Anything comes to mind we could improve today to make it less tedious?

**Comment by winston0410** [comment]
> Thanks for the feedback @winston0410. Anything comes to mind we could improve today to make it less tedious?

it would be great if the documentation provide configuration snippets, so the developer would just need to copy and paste to integrate Ory Kratos and Oathkeeper, but otherwise I cannot think of other improvements. The devops there is inevitable.

**Comment by vinckr** [comment]
Did you see the Ory Oathkeeper community examples: https://github.com/ory/examples/tree/master/oathkeeper ?
If you can think of an example that would be a good addition feel free to open an issue in the ory/example repo so it can be tracked 🙏

**Comment by jmls** [comment]
would be great to have this feature. Will try oath keeper as well

**Comment by jaekook** [comment]
Would be great to have this feature. 
I need the below one...
https://hasura.io/learn/graphql/hasura-authentication/integrations/ory/

**Comment by vinckr** [comment]
@jaekook 
The hasura integration should be possible already, check it this repo: https://github.com/gen1us2k/hasura-ory-webhook (feel free to contact me directly on the [Slack](https://slack.ory.sh/) if you are running into issues with it.)

**Comment by jaekook** [comment]
> @jaekook The hasura integration should be possible already, check it this repo: https://github.com/gen1us2k/hasura-ory-webhook (feel free to contact me directly on the [Slack](https://slack.ory.sh/) if you are running into issues with it.)
Thank you for the reply. But I want to use JWT authn....

**Comment by geekyme** [comment]
My use case is my company have a lot of different websites on different domains, and they hit a single central API for auth. It's going to be tough without a JWT-based solution.

**Comment by giovannidegani** [comment]
I also have a case in our company that JWT would be a must...

**Comment by florian-besser** [comment]
I would add a +1 to this; while it is possible to work with ORY by validating session tokens it would be very nice to get JWTs side-by-side.

While researching JWT usage in ORY I found your (excellent) article at [link](https://www.ory.sh/oauth2-openid-connect-do-you-need-use-cases-examples/). You mentioned KeyCloak in there which I agree with, but while KeyCloak is certainly an interesting product they do not have your SaaS capability for quick and easy onboarding. I can't just "play around" with KeyCloak as easily as I can with ORY.

**Comment by aeneasr** [comment]
PR is linked above, this will be available soon
