### ISSUE TITLE
Add filters to admin api

### ISSUE THREAD

**Issue by gperdomor** [ory/kratos#249]
**Is your feature request related to a problem? Please describe.**

Hi, i want to build some kind of CRUD around kratos, a kind of kratos wrapper, but I don't see a way to apply filters, for example, i want to filter based on identity type (user/device/customer) or by the first name of a customer...

**Describe the solution you'd like**

Maybe we can use just query params for that, or some path param to handle the identity type and query params for the rest of fields, but the second approach we can't list for example users and devices, we are limited to one type 🤔

**Comment by aeneasr** [comment]
Hey, this is definitely on the roadmap! We were planning to do something with GraphQL because building REST query languages sucks! :)

However, traits need to be indexed and stuff, so this is a bit further down the roadmap currently. We might even need something like Sphinx or Elastic.

**Comment by UkonnRa** [comment]
1. If mentioned about queries on RESTful, you can check the discussion from JSON:API: https://github.com/json-api/json-api/issues/1445
2. Designing a query language IS a difficult problem, even using GraphQL

Right now I want to apply some complex queries when using Kratos (filter identities by some specific trait fields) and Cursor-based pagination. So I wonder:
1. **if I can do some queries on the SQL level?**
2. **are the schemas of SQL tables stable enough for customization?**

**Comment by aeneasr** [comment]
> if I can do some queries on the SQL level?

You probably can, if your database supports JSON indexing!

> are the schemas of SQL tables stable enough for customization?

Could you explain what you mean with stable? We definitely will have migrations applied to the tables in the future!

**Comment by g13013** [comment]
@aeneasr 

> However, traits need to be indexed and stuff, so this is a bit further down the roadmap currently. We might even need something like Sphinx or Elastic.

I suggest https://blevesearch.com/ for that to avoid 3rd party dependency, supporting basic searchability would be supported by kratos, and most advanced search capabilities could be the responsibility of the app provider

**Comment by aeneasr** [comment]
Nice, that looks like a pretty cool tool and could work for small installations (similar to SQLite)! Not sure if we could use this in HA or larger envs?

**Comment by g13013** [comment]
I think it can do more than that, for basic search capabilities I think that it's more than enough

here are some benchmarks https://blevesearch.com/bleve-bench/

**Comment by fdelucchijr** [comment]
Probably related: #2448 

There’s any way we can do batching for now? N+1 Problem is a pretty serious thing with rest...
@aeneasr maybe for now its better a GraphQL with traits, metadata_public, metadata_admin as JSON without the auto generation and indexing as a short term solution?

**Comment by aeneasr** [comment]
We're planning on adding a proper elastic-backed search API. That however will reside outside of this project and more generally be applicable to all of Ory's stack. This issue is tracked internally. We don't think that we'll be able to work on this before Q3/Q4 this year (maybe even later).

"Simple" filtering will not be available in Ory Kratos' APIs as it doesn't scale.
