### ISSUE TITLE
Add IF NOT EXISTS to sql creating auth tables

### ISSUE THREAD

**Issue by nxy7** [ory/kratos#2499]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

For quiet some time i was figuring what's the best way to integrate kratos into my app. At first i've used webhooks, but i'm kinda paranoid about one service going down and webhooks not reaching each other.
I think for small services it's okay to bundle app database and kratos database together and keep em in separate schemas. This way you avoid webhooks and have single source of truth. 
The way identities table is currently set up makes it somewhat harder to set up kratos with app migrations. Because some tables may depend on identities (or you may want to set up kratos in postgres schema other than 'public') it would be nice if i could set it up from my own migrations. It's currently not possible because identities table is created with "CREATE TABLE" and not "CREATE TABLE IF NOT EXISTS".
Because of that I need to split database migrations into 3 steps.
1. Database init migrations (if you want to set up ory in schema other than 'public')
2. Run ory migrations
3. Run my app migrations

### Describe your ideal solution

Change ory identities migrations to 'CREATE TABLE IF NOT EXISTS'.
With that change it's possible to have 'init migrations' together with app migrations and app initialization would look like:
1. Run app migrations
2. Run ory migrations

I believe it would make for easier workflows with ory kratos and I don't think there are any side effects to this approach

Another way to mitigate this extra 'initialization' step would be allowing to prepend user defined migrations that ory-kratos-migrate would run.

### Workarounds or alternatives

Additional migrations step.

### Version

latest

**Comment by aeneasr** [comment]
Thank you for the suggestion! Unfortunately we have a policy of not changing existing migrations unless there is a bug or regression introduced in, for example, a new database version. For that reason, it won't be possible to change the behavior of this. Sorry!

**Comment by nxy7** [comment]
Totally understandable. Maybe you could introduce a way to append/prepend custom migrations in the future, that would also solve the issue. Anyway it's still great software and thanks for wokring on it :-)

**Comment by hiendaovinh** [comment]
Is there any workaround to address this? I'm trying to compose both hydra-migrate and kratos-migrate together.

**Comment by aeneasr** [comment]
You need to database schemas, you can't run both on the same database schema / namespace

**Comment by hiendaovinh** [comment]
Thanks for your help!
