### ISSUE TITLE
CSRF token is missing or invalid

### ISSUE THREAD

**Issue by sczj** [ory/kratos#250]
{"error":{"code":400,"status":"Bad Request","reason":"CSRF token is missing or invalid

.","message":"The request was malformed or contained invalid parameters"}}

![image](https://user-images.githubusercontent.com/54340421/74583115-a2cf3f00-4ffe-11ea-81e5-3b9cc3b028fa.png)
![image](https://user-images.githubusercontent.com/54340421/74583119-afec2e00-4ffe-11ea-8833-7dee2b486909.png)
![image](https://user-images.githubusercontent.com/54340421/74583126-bbd7f000-4ffe-11ea-8871-0325e8aac36d.png)

**Comment by sczj** [comment]
# serve controls the configuration for the http(s) daemon
serve:
  admin:
    port: 1234
    host: 127.0.0.1
  public:
    port: 1235
    host: 127.0.0.1

dsn: mysql://root:admin@tcp(localhost:3306)/kratos?parseTime=true&multiStatements=true

log:
  level: debug

courier:
  smtp:
    connection_uri: smtp://foo:bar@baz/

urls:
  default_return_to: http://127.0.0.1:3000/auth/login
  mfa_ui: http://127.0.0.1:3000/mfa
  login_ui: http://127.0.0.1:3000/auth/login
  profile_ui: http://127.0.0.1:3000/auth/profile
  verify_ui: http://127.0.0.1:3000/auth/verify
  registration_ui: http://127.0.0.1:3000/auth/registration
  self:
    public: http://127.0.0.1:1235
    admin: http://127.0.0.1:1234
  error_ui: http://127.0.0.1:3000/error
  whitelisted_return_to_domains:
    - http://return-to-1-test.ory.sh/
    - http://return-to-2-test.ory.sh/

identity:
  traits:
    default_schema_url: http://127.0.0.1:3000/default-identity.schema.json
    schemas:
      - id: other
        url: http://127.0.0.1:3000/other-identity.schema.json

hashers:
  argon2:
    memory: 1048576
    iterations: 2
    parallelism: 4
    salt_length: 16
    key_length: 32

secrets:
  session:
    - session-key-7f8a9b77-1
    - session-key-7f8a9b77-2

selfservice:
  strategies:
    password:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: github
            provider: github
            client_id: a
            client_secret: b
            schema_url: http://127.0.0.1:3000/default-identity.schema.json
  logout:
    redirect_to: http://127.0.0.1:3000/auth/logout
  login:
    request_lifespan: 99m
    before:
      - job: redirect
        config:
          default_redirect_url: http://127.0.0.1:3000/
          allow_user_defined_redirect: false
    after:
      password:
        -
          job: revoke_active_sessions
        - job: session
        - job: redirect
          config:
            default_redirect_url: http://127.0.0.1:3000/
            allow_user_defined_redirect: true
      oidc:
        -
          job: revoke_active_sessions
        - job: session
        - job: redirect
          config:
            default_redirect_url: http://127.0.0.1:3000/
            allow_user_defined_redirect: true
  registration:
    request_lifespan: 98m
    before:
      - job: redirect
        config:
          default_redirect_url: http://127.0.0.1:3000/auth/registration
          allow_user_defined_redirect: false
    after:
      password:
        -
          job: session
        -
          job: redirect
          config:
            default_redirect_url: http://127.0.0.1:3000/auth/registration
            allow_user_defined_redirect: true
      oidc:
        -
          job: session
        -
          job: redirect
          config:
            default_redirect_url: http://127.0.0.1:3000/auth/registration
            allow_user_defined_redirect: true

#      - job: account_activation
#        config:
#          redirect:
#            pending:
#            success:
#            invalidate_after: 10h

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by sczj** [comment]
[.kratos.txt](https://github.com/ory/kratos/files/4211384/default.kratos.txt)
![backend_error](https://user-images.githubusercontent.com/54340421/74617276-49ceea80-5167-11ea-9a81-e872d1a7d30b.png)
![csrf_token_missing](https://user-images.githubusercontent.com/54340421/74617277-4b001780-5167-11ea-8db6-ed88dfea19da.png)
![frontend_error](https://user-images.githubusercontent.com/54340421/74617278-4b98ae00-5167-11ea-838b-11baf68ca533.png)
![login_html](https://user-images.githubusercontent.com/54340421/74617280-4c314480-5167-11ea-8882-789ef187898a.png)

**Comment by sczj** [comment]
All error reports and configurations are in the files and pictures here. Please help to see what's going on

**Comment by aeneasr** [comment]
You haven't included any requests, any request payloads, no log files. I do not know when you're seeing the CSRF error, I do not know what requests you made (did you try to log in? sign up?). What URLs you're accessing. Obviously, what cookies are included in those requests. Please, adhere to the repository's policy when creating issues. It is not possible to help otherwise.

Here is a good example of an issue: https://github.com/ory/hydra/issues/1546

Here is what you should have filled out:
https://github.com/ory/kratos/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by aeneasr** [comment]
It appears that you're running the login ui and kratos at several ports. That will cause issues. Please refer to the quickstart (it has network graphs) to see how to set up oathkeeper to share a common domain.

**Comment by sczj** [comment]
Now I compile the project myself. I don't use docker or inherit oauthkeeper. I just want to test the communication between Kratos and Kratos SelfService UI node. Now I have problems

**Comment by sczj** [comment]
time="2020-02-25T21:18:26+08:00" level=info msg="started handling request" method=POST name="public#http://127.0.0.1:1235/" remote="127.0.0.1:57960" request="/self-service/browser/flows/registration/strategies/password?request=e0a1b11d-f02c-4da9-b35f-4747c22649be"
time="2020-02-25T21:18:26+08:00" level=warning msg="A request failed due to a missing or invalid csrf_token value" expected_token="LRv4sQo69HHmXUvuuPTqBnMem8Y5HJXSyZ4QjniJNUPWdKoqvWi0iavRWMmOyAAwVciPSplr9TdT9DwqJPEJww==" received_token="2tQHZxP7y/awtj/MuwGZzx0cR1d3sADzqWmEZeCnBnINviBUTOtvr6oJ7aH02zAN25hSsHkGvs1aulqg2gLRjw==" received_token_form="2tQHZxP7y/awtj/MuwGZzx0cR1d3sADzqWmEZeCnBnINviBUTOtvr6oJ7aH02zAN25hSsHkGvs1aulqg2gLRjw=="
time="2020-02-25T21:18:26+08:00" level=error msg="An error occurred while handling a request" code=400 debug= details="map[]" error="The request was malformed or contained invalid parameters" reason="CSRF token is missing or invalid." request-id= status=400 trace="Stack trace: \ngithub.com/ory/kratos/x.NewCSRFHandler.func1\n\tD:/go_project/src/kratos-master/x/nosurf.go:65\nnet/http.HandlerFunc.ServeHTTP\n\tE:/Go/src/net/http/server.go:2007\ngithub.com/justinas/nosurf.(*CSRFHandler).handleFailure\n\tD:/go_project/pkg/mod/github.com/justinas/nosurf@v0.0.0-20190118163749-6453469bdcc9/handler.go:193\ngithub.com/justinas/nosurf.(*CSRFHandler).ServeHTTP\n\tD:/go_project/pkg/mod/github.com/justinas/nosurf@v0.0.0-20190118163749-6453469bdcc9/handler.go:175\ngithub.com/urfave/negroni.Wrap.func1\n\tD:/go_project/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46\ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\tD:/go_project/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\tD:/go_project/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/metricsx.(*Service).ServeHTTP\n\tD:/go_project/pkg/mod/github.com/ory/x@v0.0.95/metricsx/middleware.go:261\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\tD:/go_project/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/ory/x/reqlog.(*Middleware).ServeHTTP\n\tD:/go_project/pkg/mod/github.com/ory/x@v0.0.95/reqlog/middleware.go:140\ngithub.com/urfave/negroni.middleware.ServeHTTP\n\tD:/go_project/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38\ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\tD:/go_project/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96\ngithub.com/gorilla/context.ClearHandler.func1\n\tD:/go_project/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141\nnet/http.HandlerFunc.ServeHTTP\n\tE:/Go/src/net/http/server.go:2007\nnet/http.serverHandler.ServeHTTP\n\tE:/Go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\tE:/Go/src/net/http/server.go:1890\nruntime.goexit\n\tE:/Go/src/runtime/asm_amd64.s:1357" writer=JSON
time="2020-02-25T21:18:26+08:00" level=info msg="completed handling request" method=POST name="public#http://127.0.0.1:1235/" remote="127.0.0.1:57960" request="/self-service/browser/flows/registration/strategies/password?request=e0a1b11d-f02c-4da9-b35f-4747c22649be" status=400 text_status="Bad Request" took=1.9974ms

**Comment by aeneasr** [comment]
Can you please create a github repository with instructions how to set up the environment you want to test? Otherwise I can not help and will close this issue. It is not clear to me what you are trying to achieve, and CSRF errors typically mean that your network set up is incorrect. Without a repository that includes a reproducible test case, options for help are exhausted. Thank you

**Comment by sczj** [comment]
Repository and description document address created

https://github.com/sczj/kratos-master/blob/master/Kratos-Test-Document.md

Please help to see what the problem is ？thanks,

**Comment by aeneasr** [comment]
Thank you, that is very, very helpful!

I think one problem is that you are not using the `--dev` flag for Kratos. The `--dev` flag disables several security measures such as the `secure` flag for cookies. I think that is what is causing your issues. If you check the docker-compose file you will find that we are using the dev flag there. Sorry that this is not properly documented yet.

I wasn't able to identify the issue yet, but it seems that there are two request IDs that don't fit (`d737a431-dbc0-42f4-a3a9-38293a57e222` and `841b2c5b-d09a-4927-9e20-b70ac379fd8d`) together:

```
#3 Click Register to test
http://127.0.0.1:3000/auth/registration?request=d737a431-dbc0-42f4-a3a9-38293a57e222
# 4 Fill in the account password and other information, click Register
http://127.0.0.1:1235/self-service/browser/flows/registration/strategies/password?request=841b2c5b-d09a-4927-9e20-b70ac379fd8d
```

What is also helpful is to use Google Chrome DevTools (or Firefox) to check the requests and also see which cookies are being sent. From what I can tell so far, it looks like everything should be working.

By the way, you don't need to run `soda` but can use `kratos migrate sql` to achieve the same :)

**Comment by sczj** [comment]
Thank you very much. Now you can register and log in normally. Thank you.

**Comment by sczj** [comment]
Thank you very much. Now you can register and log in normally. Thank you.

**Comment by aeneasr** [comment]
Awesome! Glad I was able to help out. Can we close this issue then? :)

**Comment by ourlang** [comment]
Now I compile the project myself. I don't use docker or inherit oauthkeeper. I just want to test the communication between Kratos and Kratos SelfService UI node. Now I have problems。
I can register normally, and the database can also be stored. However, if I log in to the homepage "dashboard.hbs", I am wrong. The error is" no authorization token was found"

**Comment by ourlang** [comment]
Now I compile the project myself. I don't use docker or inherit oauthkeeper. I just want to test the communication between Kratos and Kratos SelfService UI node. Now I have problems。
I can register normally, and the database can also be stored. However, if I log in to the homepage "dashboard.hbs", I am wrong. The error is" no authorization token was found"

**Comment by ourlang** [comment]
![image](https://user-images.githubusercontent.com/32355185/75608656-7954fe00-5b3c-11ea-9ffb-5fa3da69efa0.png)

**Comment by ourlang** [comment]
//The error report appears here. How to deal with it
  // bearer = undefined
  console.log("bearer=",bearer)
  if (bearer) {
    // The header will be in format of `Bearer eyJhbGci...`. We therefore split at the whitespace to get the token
    // itself only.
    let token = bearer.split(' ')[1]
    return {
      raw: token,
      claims: req.user,
    }
  }

**Comment by ourlang** [comment]
![image](https://user-images.githubusercontent.com/32355185/75608716-1748c880-5b3d-11ea-9621-acf8fb831caf.png)

**Comment by ourlang** [comment]
Please help me to have a look. I look forward to your reply. Thank you

**Comment by sczj** [comment]
I have the same problem. Please help me deal with it. Thank you

**Comment by aeneasr** [comment]
This became a general help issue which is not the purpose of how we use GitHub. If you still have problems please go to the forums ( https://community.ory.sh ) or open a new, detailed, issue. Thank you!
