### ISSUE TITLE
Pass through complete POST body from custom user registration page into webhooks

### ISSUE THREAD

**Issue by udyanrajsharma** [ory/kratos#2500]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We are using ORY Kratos registration flow with our signup UI page having few additional fields like Organization Name and Resume other than identity registration fields of Name, Email and Password.
What we want is to call our signup service post successful registration in Kratos via webhook to save data in our DB, but we want those 2 fields (Organization Name and Resume) as well via form-data but it seems like webhook doesn't have any handle to complete data coming in from registration UI page rather only the fields which are used for identity registration.

### Describe your ideal solution

There should be a way to pass additional data fields in registration flow and those fields should allow for a object stream type as well. And complete data-set should reach to webhook

### Workarounds or alternatives

None found so far

### Version

v0.9.0-alpha.3

**Comment by CaptainStandby** [comment]
@udyanrajsharma could you please elaborate on your specific use case and why you are unable to achieve your goal using a customized identity schema with the required data defined as `traits`? (https://www.ory.sh/docs/kratos/manage-identities/customize-identity-schema#advanced-schema)
The `traits` will be available via the post registration webhook (https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#customizing-request-body-with-jsonnet)

**Comment by CaptainStandby** [comment]
This seems to be way out of scope for an identity service.
What you could do alternatively would be to upload the file beforehand into an s3 bucket and pass the object ID as a trait when completing the signup.

**Comment by CaptainStandby** [comment]
We are currently implementing https://github.com/ory/kratos/issues/3102 which should help in solving more complex use cases.

Since passing the complete POST body is a security risk and uploading files through Kratos is problematic and not something we want to support, I'm closing this as `won't fix`.

Please take a look at https://github.com/ory/kratos/issues/3102 once it's finished.
