### ISSUE TITLE
Start verification flow when updating verifiable address via API (or send or generate verification link via API)

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2515]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I implemented an email update flow based on one `primary_email` trait and one `secondary_emails` trait (as described in https://github.com/ory/kratos/discussions/2501). I'm hiding those traits from the UI during the settings flow. These traits can only be updated via a custom UI that uses the Kratos API to update the identity.

Now the problem is that both the primary email and the secondary emails are verifiable, but when I update the `secondary_emails` trait via the Kratos API, no verification flow is initiated.

### Describe your ideal solution

If a verifiable address is changed in the settings flow, a verification mail is automatically sent to the new address. Ideally, I would expect this to happen when I update the value via the API as well.

### Workarounds or alternatives

Alternatively, there could be an API endpoint to trigger the verification flow for the given identity ID and address.

Another less convenient option would be to add another endpoint for just creating a verification link that I can send to the user in my Kratos client application (analogous to the `POST /admin/recovery/link` endpoint).

Right now, the only option is to redirect the user to the verification form and ask them to submit the form, which is certainly less than ideal from a UX perspective.

### Version

0.10.1

**Comment by aeneasr** [comment]
There are two things for this:

1. Managing a user as an admin probably does warrant in most cases to trigger the verification flow
2. Importing users in most cases won't warrant this email

So I think this has to be optionally enabled, maybe similar to the recovery admin flow.

**Comment by woylie** [comment]
For reference: #595
