### ISSUE TITLE
Add support for "groups" in OIDC claims

### ISSUE THREAD

**Issue by akshay196** [ory/kratos#2528]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I was trying to store the "groups" information from claims received into user traits after OIDC login. Unfortunately `claims` variables in mapper Jsonnet only allowed specific standard claims defined [here](https://github.com/ory/kratos/blob/master/selfservice/strategy/oidc/provider.go), that does not include groups attribute.
I tried with GitLab and Okta OIDC login as for now. Both supports groups in its claims.

### Describe your ideal solution

Claims variable should have groups attribute that is of type array of strings.

### Workarounds or alternatives

I couldn't find alternative to fetch groups that OIDC user is part of after successful login.

### Version

v0.9.0-alpha.3

**Comment by aeneasr** [comment]
Makes sense to include all claims, maybe as another variable in the context like `raw_claims` or something like that - PRs welcomed :)

**Comment by deepto98** [comment]
Can I pick this up?

**Comment by aeneasr** [comment]
Sure!

**Comment by fehrnah** [comment]
This would also require  #1912 to make sure the groups stay up to date with the IdP.

**Comment by akshay196** [comment]
Hey @deepto98, Just checking if there is any progress on this. Thanks.
