### ISSUE TITLE
Admin API authentication

### ISSUE THREAD

**Issue by Sytten** [ory/kratos#2553]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently the admin for the open source kratos is not authenticated.
This is a bad practice even if the API is only available in a private network, because it's an escalation path for an SSRF. We see that a lot with the metadata API of cloud providers.
Thus the open source solution should provide ways to authenticate the admin API.

### Describe your ideal solution

What I suggest to start would be to allow static secrets similar to the list currently used for encryption.
That should be simple/fast to implement and get the ball rolling.
More complex use-cases can use a sidecar.

### Workarounds or alternatives

You can always run a side-car that deals with authentication, but this complexifies the setup for simpler use-cases.

### Version

0.10.1

**Comment by Sytten** [comment]
That I can understand, but by that same logic the webhook would not be authenticated either as they don't support PKI.

That being said, this issue should be to rewritten to something along the lines of writing documentation for production deployment that includes a section on the admin api. It could suggest a few basic nginx, caddy, etc configurations that are secure and easy to deploy for a simpler setup.

**Comment by aeneasr** [comment]
Absolutely, that makes sense! We definitely need some documentation around it :) We can also include some guide using Ory Oathkeeper for example.

**Comment by samwinslow** [comment]
Hello @Sytten, fancy seeing you here 😄  I wondered if you were eventually able to connect to the admin APIs.

So far, I've tried getting into the Kratos pod with `kubectl exec -it <podname> -- sh` then using `wget` to get _any_ response from the Admin APIs, even the health check endpoint, but that doesn't work.

- `kubectl exec` doesn't authenticate me as the `ory` user, but rather an unknown user with uid:100. That means no read/write access to temp files and therefore `wget` fails internally with `Permission denied`.
- Is there a different/better way to send an HTTP request within the private network (AWS, if that matters)?

Any advice is appreciated.

If we stay with self-hosted we'll set up ngrok at some point, especially if there were guidance about this in the docs, but for now... totally fine to dump JSON to a terminal. I'm being stumped by k8s itself it seems.

**Comment by Sytten** [comment]
Easiest would be to either deploy a sidecar container that has more permissions or bind the admin port so its accessible at least internally in the cluster. You will probably want a sidecar anyway since the admin endpoint is not protected.

Are you guys dead set on using kratos? You can ping me if you want to chat we have been running it for a few months now and I have opinions.
