### ISSUE TITLE
Allow configuration of same-site cookie

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#257]
**Describe the bug**

It's currently not possible to set SameSite for session cookies. This should be possible.

**Comment by zepatrik** [comment]
What should the config key and path be? `selfservice.login.request_cookie_same_site` ? (and with all the other requests)

**Comment by aeneasr** [comment]
i think this should be handled globally in one config key for all cookies

**Comment by zepatrik** [comment]
`security.session.cookie.same_site`
