### ISSUE TITLE
Enabling 2FA without email verification allows identifier reservation/blocking

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#2577]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Enabling 2FA but not requiring email verification means an attacker can

1. register with a not owned email address
2. enable any 2FA
3. the real owner of the email cannot use it anymore to sign up because to do account recovery they need the second factor
 
The same procedure can be applied to non-verifiable identifiers (like usernames), but we cannot do much about that.

### Describe your ideal solution

We should at least make it configurable to require email verification for 2FA, similar to how you can require that for login.
The same procedure can be applied to non-verifiable identifiers (like usernames), but we cannot do much about that.

### Workarounds or alternatives

Advise anyone concerned with this problem to require verification for sessions to be issued.

### Version

all

**Comment by Rupachandran** [comment]
Reference Reports 👍 
https://hackerone.com/reports/699200
https://hackerone.com/reports/649533

Siverity ====> Medium to High

IMPACT : 

when the victim wants to register on this [site](https://console.ory.sh/), they can't, because they email claims by an attacker.
and if the victim resets the password to get back the email, he can, but he can't log in because he needs a 2FA code.

**Comment by Rupachandran** [comment]
Hello, Any Update on my submission??Its been more than a Week.
