### ISSUE TITLE
WebAuthN with SPA: allow customized form submission

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#2578]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Especially with flutter which is canvas/webassembly based, it is **very** hard/impossible to implement webauthn (ask @sashatalalasha).
One can as a workaround render a non-visible form that the `/.well-known/webauthn.js` script can pick up and use for processing, but on form submit the browser navigates away from the SPA.

### Describe your ideal solution

Instead of using `form.submit()`, which does not emit a submit event but instead straight away submits the form, we could use [`form.requestSubmit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit).

> The obvious question is: Why does this method exist, when we've had the [submit()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) method since the dawn of time?
>
> The answer is simple. submit() submits the form, but that's all it does. requestSubmit(), on the other hand, acts as if a [submit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event) button were clicked. The form's content is validated, and the form is submitted only if validation succeeds. Once the form has been submitted, the submit event is sent back to the form object.

The code in question is: https://github.com/ory/kratos/blob/a11841399956963bab319ce233a64ccb295d9b1d/selfservice/strategy/webauthn/js/webauthn.js#L87

### Workarounds or alternatives

Allow customizing the behavior of the script by defining callbacks.

### Version

latest

**Comment by alantbarlow** [comment]
If this would solve the issues you were having with implementing webauthn with flutter then I'm all for it. I too wanted to use webauthn as my primary login/sign-up method while utilizing flutter for the UI. 

This solution seems easy to implement, do you guys have any thoughts on this?

**Comment by mxknt** [comment]
Hello, I was hoping we could revive this issue. I'm currently trying to add the passkey strategy into my custom Nuxt frontend, and having this feature (at least as option) would save me a great deal of trouble. 

Thanks!
