### ISSUE TITLE
Title disappears after submitting empty email in Verification Flow

### ISSUE THREAD

**Issue by erolkskn** [ory/kratos#2591]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When submitting empty email adress to the verification flow endpoint, input's title disappears. 

**Before:**
![before](https://user-images.githubusercontent.com/15334973/179098784-16b8a497-cec5-4208-93b6-4b0294ea5893.png)

**After posting form with empty email:**
![after](https://user-images.githubusercontent.com/15334973/179098820-2321d5d1-2c4a-4dc2-aa2a-9e55e07109f6.png)

### Reproducing the bug

1. Go into the verification flow page.
2. Submit form with an empty email address value
3. Observe the output screen

### Relevant configuration

```yml
I'm using quickstart config with postgres.
```

### Version

**v0.10.1**

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

### Additional Context

It seems like after submitting empty form, **meta.label** field of **email node** suddenly disappears. One can observe it by executing the query `SELECT ui FROM selfservice_verification_flows;`, before and after submitting form.

**Comment by aeneasr** [comment]
Thank you for the report!

**Comment by erolkskn** [comment]
While i was working on it, i have seen that there are other cases title is disappearing.

- It doesn't matter whether e-mail input is empty or not, Input Title disappears after submitting Verification form.
- Same thing is happening on Recovery Flow too. Input Title disappears after submitting Recovery form.
