### ISSUE TITLE
Deno compatibility

### ISSUE THREAD

**Issue by arnemolland** [ory/kratos#2600]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Me and my team would love a Deno/Deno-compatible SDK. While it's possible to use NPM packages with Deno via CDN (e.g. esm.sh or skypack.dev), the current SDK is using Axios which is not exported as an ES module and is based off XHR. Deno only supports ESM and the newer Fetch API, which makes it hard to bridge the current JS SDK unless Axios is switched out. I along with the team @gameflow-tv would be happy to help with an implementation.

### Describe your ideal solution

Switch out Axios' XHR with the Fetch API.

### Workarounds or alternatives

Use a Fetch implementation of the Axios API surface, e.g. [redaxios](https://github.com/developit/redaxios), or implement a Deno-specific library without Axios and publish to deno.land. Though at that point why not switch out the entire JS SDK?

### Version

Ory Cloud

**Comment by aeneasr** [comment]
Unfortunately axios is the best of the worst options openapi-generator provides. If you want you can play around with the different generators to see what sticks with deno.

The axios generator is the only one that works in browser JS, node, and native; any generator replacing axios would at least need to cover these use cases as well and be stable

**Comment by xet7** [comment]
@arnemolland 

Deno has added experimental npm support:
https://deno.com/blog/v1.25#experimental-npm-support

Deno is adding more compatibility with node and npm:
https://deno.com/blog/changes#compatibility-with-node-and-npm

Does that help?

**Comment by arnemolland** [comment]
> @arnemolland 
> 
> 
> 
> Deno has added experimental npm support:
> 
> https://deno.com/blog/v1.25#experimental-npm-support
> 
> 
> 
> Deno is adding more compatibility with node and npm:
> 
> https://deno.com/blog/changes#compatibility-with-node-and-npm
> 
> 
> 
> Does that help?

This certainly is a step in the right direction as it removes the need for a third-party CDN, though I'm not yet sure if it will solve this particular issue. I guess we'll wait and see, but unless they're patching out XHR from the dependencies, the Ory JS SDKs might fall under the 10-20% of packages that won't be compatible. Hoping for the best though.

**Comment by aeneasr** [comment]
I believe deno has progressed. Closing as an upstream issue
