### ISSUE TITLE
Pin-code as a second factor auth

### ISSUE THREAD

**Issue by splaunov** [ory/kratos#2604]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

TOTP might be too complex for non-technical users. We need a simple second factor auth method which doesn't require user to install or configure additional software of devices.

### Describe your ideal solution

Implement new second factor auth method which uses short digital pin codes.

### Workarounds or alternatives

Implement it in app server.

### Version

0.9

**Comment by aeneasr** [comment]
We already have that - called lookup secrets :)

**Comment by splaunov** [comment]
There is a significant difference. Every lookup code can be used only once (?), but pin-code can be re-used until user chooses to change it.

**Comment by aeneasr** [comment]
I see, Ttht would just be a secondary password though right? I don't think that we can slip that through as second factor authentication.

Given that Apple and Google are moving fast towards native WebAuthn, I think that we'll end up with Touch / Face ID for 2FA in the near future as the default.

**Comment by splaunov** [comment]
>I see, Ttht would just be a secondary password though right?

Yes, exactly

>I don't think that we can slip that through as second factor authentication.

Wouldn't you accept this feature as a contribution?

>Given that Apple and Google are moving fast towards native WebAuthn

This still will take some time. Nobody can estimate how long.

**Comment by aeneasr** [comment]
> Wouldn't you accept this feature as a contribution?

Depends a bit, but I don't think this follows the NIST Digital Identity Guidelines when it comes to multi-factor authentication. Basically, you have now two passwords - both are immutable but known to the user and suspect to phishing, leaking, and other potential security issues. So it doesn't add a layer of security as far as I understand. Looking from that angle, I don't see why it should be added then even though I understand the opening statement regarding user experience.

But I'm always someone that can be convinced otherwise :)

**Comment by aeneasr** [comment]
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf

**Comment by splaunov** [comment]
>but I don't think this follows the NIST Digital Identity Guidelines when it comes to multi-factor authentication

It seems to be true. Nothing similar is listed in "4.2.1 Permitted Authenticator Types"

**Comment by aeneasr** [comment]
A pin code which doesn't change is of type "memorized secret". Similarly, passwords are also "memorized secrets". And memorized secrets are not a permitted "AAL2" authenticator type:

<img width="1053" alt="Screenshot 2022-07-20 at 13 06 41" src="https://user-images.githubusercontent.com/3372410/179967491-8b72c7ea-0024-467e-b357-d32eef9135c1.png">

**Comment by splaunov** [comment]
Ok, we still need this feature but maybe I shouldn't have named it a "second factor".

Maybe it's not related to AAL at all.

The problem we are tying to solve by this is that when the app is using long (perpetual) sessions, we need some way to refresh it before running some sensitive operations in the app.
So this case is more similar to "privileged" sessions. But we need a very user friendly way to get it. Without going to the full auth flow.

It looks like pins are a very common way to achieve this in many apps on the market. At least in Europe.
And hopefully kratos could benefit from adding this feature.

**Comment by splaunov** [comment]
What you think @aeneasr ? Would it make sense as a feature to better support long sessions cases?

**Comment by nrutherford** [comment]
We are attempting to implement a similar solution (pin codes) for our native apps - primarily for those devices that don't have biometrics. In our solution, we are enrolling the user's device as a separate "identity" and the PIN code is stored server side linked to the device - thus the PIN code becomes the "something you know" and the specific device is the "something you have"

**Comment by L11R** [comment]
In my opinion PIN codes only can enhance security if they are used as local authentication. Android and iOS can protect KeyStore/KeyChain entries like operation on keypair with PIN/pass/biometry authentication.
