### ISSUE TITLE
Add a clear guide how to use Kratos without Oathkeeper

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#262]
**Is your feature request related to a problem? Please describe.**

Feedback in the chat is that learning Oathkeeper on top of Kratos is a lot of work, and that the way Oathkeeper works isn't really explained well.

We should write a simple code example that explains how one could create a small middelware for ExpressJS, Golang, ...

Since the request is really easy this could probably be done in a few lines of code.

**Comment by davidthor** [comment]
Not a guide, but I did run into this in my own testing and found some of the snippets that let the kratos ui-node proxy through to kratos to make this work. Details and discussion can be found here:
https://community.ory.sh/t/kratos-csrf-issues-without-oathkeeper/1603/2?u=davidthor
