### ISSUE TITLE
SQLite database errors in quickstart

### ISSUE THREAD

**Issue by designermonkey** [ory/kratos#263]
```
kratos_kratos-migrate_1 exited with code 1
kratos-migrate_1              | An error occurred planning migrations: CREATE TABLE "schema_migration" (
kratos-migrate_1              | "version" TEXT NOT NULL
kratos-migrate_1              | );
kratos-migrate_1              | CREATE UNIQUE INDEX "schema_migration_version_idx" ON "schema_migration" (version);: database or disk is full
```
This is the repeated output when trying the quickstart

`docker-compose -f quickstart.yml up --build`

or

`make quickstart`

**Expected behavior**

The netwrk starts up and migrates data into the SQLite database.

**Environment**

* Version: `origin/master`
* Environment: MacOS

**Comment by designermonkey** [comment]
Mounting a SQLite database from a host folder works as expected. Maybe for the documented quicksart it would be safer to do that instead?

**Comment by aeneasr** [comment]
> database or disk is full

This means that your docker volume (depends on what docker you have installed) is out of disk space. You probably have a lot of old images or volumes in the system or you allocated too little for the VM.

> Mounting a SQLite database from a host folder works as expected. Maybe for the documented quicksart it would be safer to do that instead?

Definitely an option, might even work better if you want to debug the SQLite database :)

**Comment by designermonkey** [comment]
Is this something to add to the roadmap or should I close it?

**Comment by aeneasr** [comment]
I’ve already fixed this but was not able yet to push it as I am traveling right now.

**Comment by designermonkey** [comment]
Awesome, thanks :)
