### ISSUE TITLE
Privileged Session state should be included in `whoami` response

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#2633]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Clients currently have no easy way to determine whether a session is privileged.

From https://ory-community.slack.com/archives/C012RJ2MQ1H/p1659099978177669

> 1. I am calling self-service/settings/browser
> 2.  I use the return value to get the flow id and the csrf token
> 3.  I call /self-service/settings with the flow id, the csrf token and a NEW PASSWORD
> 4.  I receive error session_refresh_required with a redirect_browser_to url
> 5.  I redirect to the specified url /self-service/login/browser which contains query params for refresh=true and a return_to url that is /self-service/settings
> 6.  I log in with the user's credentials with refresh true
> 7.  I call the /self-service/settings
> 8.  The PASSWORD doesn't seem to be updated

Also requested by @tc-amorevino

### Describe your ideal solution

It would be nice for the UX to be able to see whether the `Update Password` field should be displayed, or instead a `login?refresh=true` flow should be initiated. A `privileged_until` timestamp will probably be better for the technical side than a boolean, because the client could preemptively trigger the re-login if the session would be non-privileged within a short time. It also means the response does not change over time (assuming the session is not revoked/prolonged). 

### Workarounds or alternatives

Determine the "privileged" status on the client side by knowing the privileged session lifespan.

### Version

all

**Comment by brahmlower** [comment]
I started working on implementing this feature this weekend. I've got a branch in progress with the implementation working, but it's taking longer than I anticipated to get the tests updated. I think I'm relatively close to getting the tests finished though- hopefully in the next day or two.

**Comment by zepatrik** [comment]
Awesome!

**Comment by brahmlower** [comment]
Hey @zepatrik do you have any opinions or concerns with the implementation plan I described above?

**Comment by jeremy-serenne** [comment]
Hi ! This is exactly what we are looking for ! Do you know when this could be done ? @zepatrik

**Comment by brahmlower** [comment]
@jeremy-serenne same here 😁 and I'm happy to put the changes together, but I'd like to first confirm with the maintainers first that they're comfortable with the [approach I've described above](https://github.com/ory/kratos/issues/2633#issuecomment-1488973473) before I sync a lot time into the implementation.

**Comment by zepatrik** [comment]
Sorry, somehow missed the discussion here.  Maybe it makes more sense to do this on the handler layer, as that means less piping. You can quite easily write tests for the handlers that ensure they all have the field set.

**Comment by brahmlower** [comment]
Sorry to be late with my reply as well 😛 (it's like a game of sorry-tag)

I can take a look at implementing this at the handler layer- I really appreciate the guidance there 👍 I have a lot of stuff going on for q4 though, so I won't have a chance to start this until around the start of December if that's alright?

**Comment by zepatrik** [comment]
In case someone needs this earlier, they (or we) can do it earlier 😉
