### ISSUE TITLE
Add API Endpoint to fetch emails

### ISSUE THREAD

**Issue by jonas-jonas** [ory/kratos#2639]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, there is no way to fetch emails that were generated by kratos via the API. This also applies to SMS messages and messages that failed to deliver.

### Describe your ideal solution

The admin API should provide an endpoint to fetch all messages generated by kratos at `/admin/courier/messages`

The endpoint would return an array of items with the following structure. Example:
```json
{
  "id": "1ff05f9e-0684-4d45-adcf-ef896667ba84",
  "status": "ABANDONED",
  "type": "EMAIL",
  "recipient": "test-recipient-1@example.org",
  "subject": "stub email subject test-subject-1",
  "template_type": "stub",
  "send_count": 1,
  "created_at": "2022-08-02T16:29:26.978027+02:00",
  "updated_at": "2022-08-02T16:29:26.978027+02:00"
}
```

For the fields `status` and `type` we need some kind of string enums to make them better understandable. Currently, these fields are of type integer in the database, which results in `status=4` (abandoned) and `type=1` (Email).

The endpoint should also provide a way to filter for the message's `status` field to only fetch, e.g. `MessageStatusAbandoned` messages.

It should also have pagination support.

### Workarounds or alternatives

None, currently.

### Version

v0.10.1

**Comment by aeneasr** [comment]
> The admin API should provide an endpoint to fetch all messages generated by kratos at /courier/messages

```
- The admin API should provide an endpoint to fetch all messages generated by kratos at /courier/messages`
+ The admin API should provide an endpoint to fetch all messages generated by kratos at /admin/courier/message
```

or alternatively:

```
/admin/courier/deliveries
```

> The endpoint would return an array of items with the following example:

The email body will contain sensitive information such as the recovery code or token. Do we really want to include it in the payload?

> For the fields status and type we need some kind of string enums to make them better understandable. Currently, these fields are of type integer in the database, which results in status=4 (Abandoned) and type=1 (Email).

Good idea, you can use `MarshalJSON` and `UnmarshalJSON` to convert them to and from human readable strings.

> The endpoint should also provide a way to filter for the message's status field to only fetch, e.g. MessageStatusAbandoned messages.

Absolutely! I think it should also be able to filter per recipient

**Comment by jonas-jonas** [comment]
> The email body will contain sensitive information such as the recovery code or token. Do we really want to include it in the payload?

I think it would be nice to be able to see the body for "debugging" purposes, but probably unsafe even on admin endpoints.
Also, the body will rarely be the issue for undeliverable messages which this endpoint will be used for primarily, I suspect.
So I guess we can leave the body out.

**Comment by aeneasr** [comment]
> I think it would be nice to be able to see the body for "debugging" purposes, but probably unsafe even on admin endpoints.
Also, the body will rarely be the issue for undeliverable messages which this endpoint will be used for primarily, I suspect.
So I guess we can leave the body out.

We can also include the body if kratos runs in `--dev` mode and omit it otherwise. That will help with debugging during development and resolve leaking sensitive data in production. WDYT?

**Comment by jonas-jonas** [comment]
That sounds good. This needs to be documented well, though, as it might be confusing to some.

Maybe instead of `body` we could name the field `only_in_dev__body` to make it obvious?

**Comment by aeneasr** [comment]
Yes or replace the body with `<redacted-unless-dev-mode>`

**Comment by erolkskn** [comment]
I would like to implement this one if someone is not working on this currently.

**Comment by aeneasr** [comment]
Epic! @jonas-jonas can help @erolkskn in case there are problems? :)

**Comment by jonas-jonas** [comment]
@erolkskn yes, let me know if you need assistance. :)

**Comment by erolkskn** [comment]
@jonas-jonas Alright, thank you :)

**Comment by erolkskn** [comment]
@jonas-jonas Hi Jonas, while i was working on this issue i'm stuck on something. Regarding @aeneasr 's first comment we should keep types of `courier.MessageStatus` and `courier.MessageType` as it's (i mean int) but we should convert them to and from human readable strings. This can easily be done with `MarshalJSON` and `UnmarshalJSON` as @aeneasr  suggested. 

But there is a problem with this and that is Swagger 2.0 spec generation. We can't keep `MessageStatus` or `MessageType`'s actual type as `int` and make it seem like(or convert it to) `string` in Swagger 2.0 Spec. We can actually make it appear as `string` in OpenAPI Spec 3.0 thanks to this utility: `ory dev openapi migrate`. This utility takes a bunch of patch files and applies them while migrating the Swagger 2.0 spec to OpenAPI Spec 3.0. So creating a patch for it in the `.schema/openapi/patches` solves the problem for OpenAPI Spec 3.0 but  the problem with Swagger 2.0 spec still remains.

May be we can create a command in ory/cli that would take an input swagger.json and bunch of patch files and produce an output swagger.json. For example:

`ory dev swagger patch -p courier.yaml swagger.json patched-swagger.json`

What do you think about this idea ?

**Comment by aeneasr** [comment]
@erolkskn your analysis is on point!

We no longer use swagger anywhere except for using it as input to generate OpenAPI Spec 3.0 - so no need to make changes to the CLI, adding the changes to the patch file is enough :))
