### ISSUE TITLE
MailSlurper is not sending the verification email

### ISSUE THREAD

**Issue by flusflas** [ory/kratos#264]
**Describe the bug**

Email verification does not work running the [quickstart](https://www.ory.sh/docs/next/kratos/quickstart) project. MailSlurper is getting the request but email is not being sent. Also, MailSlurper UI shows a few errors (`There was a problem performing your search` and `There was an error getting mail items!`) and email list is empty.

**Reproducing the bug**

1. Run `make quickstart` from kratos project directory.
2. Go to http://127.0.0.1:4455/auth/registration and register an user.
3. Dashboard is shown, so registration was successful, but confirmation email is not received.
4. Go to http://127.0.0.1:4455/verify and reenter the registered email. Behavior is the same (no email sent).

*Server logs*

```
...
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="Worker 3 queued to handle connections from 172.24.0.5:50206" who="SMTP Server Pool"
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="Reading data from client connection..." who="SMTP Writer 3"
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="QUIT command received" connection="172.24.0.5:50206" who="SMTP Worker 3"
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="Closing connection 172.24.0.5:50206" who="Connection Manager"
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="Connection closed" connection="172.24.0.5:50206" who="Connection Manager"
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="New mail item written to database." who=MailSlurper
mailslurper_1                 | time="2020-02-21T11:46:37Z" level=info msg="Mail item db26d609-9654-4872-778d-2729e5287fa0 written" who="Database Receiver"
kratos_1                      | time="2020-02-21T11:46:37Z" level=debug msg="Courier sent out message." message_id=55cde8ee-2f39-4f1d-8079-98a905844001 message_subject="Please verify your email address\n" message_type=1
...
```

*Server configuration*

Unmodified quickstart example configuration.

**Expected behavior**

A verification code email should be sent to the registered user's email.

**Environment**

* Version: v0.1.1-alpha.1+oryOS.17
* Docker over Ubuntu 18.04.2 LTS

**Comment by aeneasr** [comment]
Ahh yeah MailSluper is kinda buggy. Can you try hard reloading the page or navigating around? Alternatively delete the localStorage (using eg chrome console) and mage sure you have mailsurper latest pulled (I fixed some bugs)

**Comment by flusflas** [comment]
Ok, I think deleting localStorage did the trick. Thank you!

**Comment by aeneasr** [comment]
Awesome!
