### ISSUE TITLE
Set the recovery link

### ISSUE THREAD

**Issue by sshanzel** [ory/kratos#2652]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We configured the link method for recovery, and we have set the `base_url` - and this value is utilized across link-related concerns which can have different expected endpoints (recovery and verification). Example value: `base_url: http://127.0.0.1:5002`

But then the value of `.RecoveryURL` in the template the value becomes `http://127.0.0.1:5002/self-service/recovery?flow=some-id`, which we wanted to point to our own password recovery UI. I have checked the docs and I can't seem to find the relevant page if there is any available configuration for it.

### Describe your ideal solution

Allow the recovery link to be configurable and just pass the query parameters instead of passing the `/self-service/recovery` part.

### Workarounds or alternatives

I had to concatenate the strings, that is for **each** template.

### Version

0.10.1

### Additional Context

Currently using the self-hosted instance

**Comment by jonas-jonas** [comment]
Hi, could you provide more information on your use-case here? 
The `/self-service/recovery` endpoint is on your Ory Kratos instance. So a user clicks on the link, Kratos performs the recovery and redirects the user to the settings UI with a privileged session, which you can provide a custom UI via the `selfservice.flows.settings.ui_url` key for. So in essence, the `.RecoveryURL` variable should not be configurable as it points to a specific endpoint on Kratos itself.

**Comment by sshanzel** [comment]
Hi, thanks for the response. That is what I did now. Though I was thinking if it would be possible to change the recovery to instead of redirecting, point to the settings UI which would manually initialize the flow passing the parameters included in the recovery link (which will then validate and set the session) instead of going through the `/self-service/recovery`.
