### ISSUE TITLE
Authentication by scanning a qr code

### ISSUE THREAD

**Issue by romain63110** [ory/kratos#2661]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

kratos does not have a system allowing the user to authenticate by scanning a qr code from their phones

### Describe your ideal solution

it would be nice if there were an API allowing to: 

(for where the qr code is displayed) 
- recover the data from the qr code
- a HTTP Long Polling to the server to know when the qr code will have been flashed (*1)
- a HTTP Long Polling to the server to receive the session token (*2)

(for where the qr code is flashed) 
- to say that the qr code has been flashed (*1)
- to say that the server can send the session token(validation) (*2)

### Workarounds or alternatives

I have not found a workarounds or alternatives

### Version

v0.10.1

### Additional Context

![scanning-qr-code](https://user-images.githubusercontent.com/49534124/184162778-4bcacc48-b646-4387-9f05-cdb571ad4e60.gif)

**Comment by aeneasr** [comment]
We decided to move this issue to won't fix, as it requires some advanced set up where a mobile app is available and authenticated. If you want, you can still use PassKeys for QR-based login. See also https://www.ory.sh/overview-login-password-passkey-webauthn-totp-sso-faceid/
