### ISSUE TITLE
User-friendly error messages for Kratos API endpoint 400 responses

### ISSUE THREAD

**Issue by RubenWerdmuller** [ory/kratos#2670]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When calling the Kratos `adminCreateIdentity` endpoint, the 400 response error messages are not quite user-readable.

For example, having an `email` in the identity schema, mark is required and filling it as an empty string produces the following response:

```
code: 400
message: "The request was malformed or contained invalid parameters"
reason: "I[#/traits/email] S[#/properties/traits/properties/email/format] "" is not valid "email""
request: "1c475a8b6751ddc7ee6ced7232a13449"
```

Also, see this conversation on Slack: https://ory-community.slack.com/archives/C02PSRUGUAV/p1660570115446989

### Version

Helm chart 0.23.1 and Kratos v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

A proposed solution is to re-use the code that creates the error messages for other flows and insert it for all relevant Kratos endpoints. For example, when using the `kratos-self-service-UI-react-next`, the `<Flow/>` component already receives and presents these messages user-friendly.

**Comment by aeneasr** [comment]
Good point, we for sure need to improve this!

**Comment by RubenWerdmuller** [comment]
Any updates on this particular issue? 🚢
