### ISSUE TITLE
Getting 500 server error on sending "totp_code"

### ISSUE THREAD

**Issue by rostyk110** [ory/kratos#2680]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [x] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Auth app - **Google Authenticator** 

When I try to add Auth app, I get 500 Server Error. It happens after: connect Auth App (_successfully_), disconnect (_successfully_), connect again (_getting Error_). 

**Response:** 
```
{
    "code": 500,
    "status": "Internal Server Error",
    "request": "65abe04a-f758-9d46-b662-36482f537b32",
    "reason": "Could not find they TOTP key in the internal context. This is a code bug and should be reported to https://github.com/ory/kratos/.",
    "message": "An internal server error occurred, please contact the system administrator"
}
```

### Reproducing the bug
Sorry, recording is 24.2MB, so I compressed it. 

[Screen Recording 2022-08-22 at 22.09.45.mov.zip](https://github.com/ory/kratos/files/9396994/Screen.Recording.2022-08-22.at.22.09.45.mov.zip)

Or here is youtube link:
https://www.youtube.com/watch?v=_37Fns4AkT0

### Relevant log output
```
{
   "audience":"application",
   "error":{
      "debug":"",
      "message":"An internal server error occurred, please contact the system administrator",
      "reason":"Could not find they TOTP key in the internal context. This is a code bug and should be reported to https://github.com/ory/kratos/.",
      "status":"Internal Server Error",
      "status_code":500
   },
   "http_request":{
      "headers":{
         "accept":"application/json, text/plain, */*",
         "accept-encoding":"gzip, deflate, br",
         "content-length":"142",
         "content-type":"application/json",
         "cookie":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
         "origin":"http://localhost:3000/",
         "referer":"http://localhost:3000/",
         "sec-ch-ua":"\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
         "sec-ch-ua-mobile":"?0",
         "sec-ch-ua-platform":"\"macOS\"",
         "sec-fetch-dest":"empty",
         "sec-fetch-mode":"cors",
         "sec-fetch-site":"cross-site",
         "user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
         "via":"2.0 e4bbc916b7f96771ed58c0d668318acc.cloudfront.net (CloudFront)",
         "x-amz-cf-id":"Vwgs-HOIWh0o5WJKHK6_9ciQSLaifwf0f9eY8p0pkOGmoYWad21yDw==",
         "x-amzn-trace-id":"Root=1-62fe293b-3de7faed303877921a841dcf",
         "x-forwarded-for":"[removed]",
         "x-forwarded-host":"[removed]",
         "x-forwarded-port":"443",
         "x-forwarded-proto":"https",
         "x-forwarded-scheme":"https",
         "x-original-forwarded-for":"[removed], [removed]",
         "x-real-ip":"[removed]",
         "x-request-id":"95b5058376e1b05312ed1685c9027fd5",
         "x-scheme":"https"
      },
      "host":"[removed]",
      "method":"POST",
      "path":"/self-service/settings",
      "query":"Value is sensitive and has been redacted. To see the value set config key \"log.leak_sensitive_values = true\" or environment variable \"LOG_LEAK_SENSITIVE_VALUES=true\".",
      "remote":"[removed]:43220",
      "scheme":"http"
   },
   "http_response":{
      "status_code":500
   },
   "level":"error",
   "msg":"An error occurred while handling a request",
   "service_name":"Ory Kratos",
   "service_version":"v0.10.1",
   "time":"2022-08-18T11:57:47Z"
}
```

### Version

v0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

### Additional Context

**cURL:**

`curl 'http://localhost:3006/api/.ory/self-service/settings?flow=6469be6f-c9d8-49f4-826d-949fa43c8bad' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9,uk;q=0.8' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: csrf_token_dc00b226a17ebfc20ec30276b3639d78899dea58cd5bfa217fda35d=knZgAiXII00Ai3yj/DR7W2ExgN3jrhVIBTKvnsYQ=; ory_session_playground=MTY2MTE5NTMyMnw3MVlXVVJOR0w1YUwwVlFBTXlNaHJfMVZEanVYYXdxRnl4Si1WWmJSTlVKM2otdXFjMXJnSTBpMEhrZS1fcVRrSzVLUGV4M09ORXhJS2Z1YwWmxITjQwZk1ZOUdjdlRoU3FSTDl6UUljWk5hYURyQS1NMkJ5YlZDNWpoTkc4d3pjN21qcEZjV3Z0WEVJZDZ2TWNPWloxbHBNR2xMNllOR0NWcExpMERsYVFQRXo5ek1sQURKWmdfeDRvaWRQcVhLSmsxdGJtcXktTWd1VFJmek5WSTVoYUE9PXx7X1LLIvbtYh5ngb01VhqlNOaqb9SULFuNSvS3XaXzhA==' \
  -H 'Origin: http://localhost:3006' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3006/settings?flow=6469be6f-c9d8-49f4-826d-949fa43c8bad' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"csrf_token":"iEUaHOidwsWWzNC7IpImB1yjpMpWuNOpBFGQQaVXhiJZOr5n9uvF4d1cPZIkF7UWxuEBYz/fZn==","totp_code":"650204","method":"totp"}' \
  --compressed`

**Comment by aeneasr** [comment]
Can you please include the log lines?

**Comment by rostyk110** [comment]
> Can you please include the log lines?

Done! 
You can see logs in **Relevant log output**

**Comment by aeneasr** [comment]
Thank you for the report, that is helpful! Looks like we forgot to do this

https://github.com/ory/kratos/blob/39bb84dd78df3737c68b864ae4a04dbf9cf00282/selfservice/strategy/totp/settings.go#L263-L272

around here:

https://github.com/ory/kratos/blob/39bb84dd78df3737c68b864ae4a04dbf9cf00282/selfservice/strategy/totp/settings.go#L229

As a workaround you can create a new settings flow after you have disconnected the app. It looks like we do not properly reset the TOTP state in the flow after disconnecting!

Fixes (with tests please :) ) highly appreciated!

**Comment by kszafran** [comment]
I'll see if I can reproduce this and devise a fix.

**Comment by kszafran** [comment]
@aeneasr I looked into this more and I think I found the root cause. At the end of every successful settings submission, Kratos regenerates the UI nodes: https://github.com/ory/kratos/blob/0856bd719b7e06a6d2163bf428ff6513d86376db/selfservice/flow/settings/hook.go#L223 Some flows modify the `InternalContext` in their `PopulateSettingsMethod` (TOTP and WebAuthn do that). **However, while the UI nodes are copied into the current flow, `InternalContext` isn't.**

If I add `ctxUpdate.Flow.InternalContext = newFlow.InternalContext` after the line I shared above, linking and unlinking TOTP works as expected. Of course, this will probably break other flows, and what we should really do is merge `newFlow.InternalContext` into `ctxUpdate.Flow.InternalContext`, not just overwrite it. I don't know if gjson/sjson can merge two JSONs, though.

I made some other observations, too, while looking at the code:
- **It seems likely to me that WebAuthn has the same bug.** However, we don't use it, so I wasn't able to test it.
- Some methods seem to modify the flow object unnecessarily. For example, lookup codes modify `UI.Nodes` and even persist the flow on `continueSettingsFlowDisable`: https://github.com/ory/kratos/blob/0856bd719b7e06a6d2163bf428ff6513d86376db/selfservice/strategy/lookup/settings.go#L182-L198 But that seems pointless, because `PostSettingsHook` will overwrite those changes anyway.

How would you like to proceed with this? It seems to me that merging the `InternalContext`s in `PostSettingsHook` is the most generic solution, and one that's easy to maintain.

**Comment by rostyk110** [comment]
@aeneasr any chance to fix that next week? :(

**Comment by kszafran** [comment]
@aeneasr Could you comment on my findings? I want to contribute a fix once we agree on the proper solution. It would be nice to get a fix into the next release.

**Comment by aeneasr** [comment]
Yeah, I think that the remove option is missing basically this:

```

		e := NewSchemaExtension(id.ID.String())
		_ = s.d.IdentityValidator().ValidateWithRunner(r.Context(), id, e)

		// No TOTP set up yet, add nodes allowing us to add it.
		key, err := NewKey(r.Context(), e.AccountName, s.d)
		if err != nil {
			return err
		}

		f.InternalContext, err = sjson.SetBytes(f.InternalContext, flow.PrefixInternalContextKey(s.ID(), InternalContextKeyURL), key.URL())
		if err != nil {
			return err
		}

		qr, err := NewTOTPImageQRNode(key)
		if err != nil {
			return err
		}

		f.UI.Nodes.Upsert(NewTOTPSourceURLNode(key))
		f.UI.Nodes.Upsert(qr)
		f.UI.Nodes.Upsert(NewVerifyTOTPNode())
		f.UI.Nodes.Append(node.NewInputField("method", "totp", node.TOTPGroup, node.InputAttributeTypeSubmit).WithMetaLabel(text.NewInfoNodeLabelSave()))
```

**Comment by aeneasr** [comment]
Sorry, my last comment was a bit quick to write. To be honest, I'm not sure. The code you linked though is using `lookup_secrets` and not `totp` (which is the issue linked here). I think in the end we are not setting the internal context after we remove the credentials.

I think the best option we have is to create go and cypress test cases that emulate this behavior and then fix it by working backwards in identifying the bug.

**Comment by kszafran** [comment]
As an update, I'm currently busy with other tasks. I won't be able to work on this for some time, unfortunately.
