### ISSUE TITLE
Will multi-user import be supported in the future

### ISSUE THREAD

**Issue by Answerlord** [ory/kratos#2682]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

hello,I have used kratos for several months,it's very helpful for my work,and now I have a prolbem that I need import multi-users into my user system which depends on kratos,but I can't find the multi-import API in offical sdk document,only the single user register API is provided,I wanna an API that support import(register)muti-user,will it be supported in the future?

### Describe your ideal solution

I wanna an API that can register multi-user in one register flow ,for example the administrators of the user system can user this API to import multi-user into kratos.Maybe you can provide a an API like your self register API but the traits is slice now (It doesn't matter if the password is the same).

### Workarounds or alternatives

I have no alternatives now.

### Version

v0.9.0-alpha.2

**Comment by aeneasr** [comment]
We currently do not have an API for that but it would be possible to add an API for batch import operations!

**Comment by Answerlord** [comment]
> We currently do not have an API for that but it would be possible to add an API for batch import operations!

thks,I'm really looking forward to it.

**Comment by vinckr** [comment]
Can you not use the CLI for that @aeneasr ?
https://www.ory.sh/docs/kratos/cli/kratos-import-identities

> Import identities from files or STD_IN.
> Files can contain only a single or an array of identities. 

It says credentials are not supported, but afaik they are need to update the CLI docs there.

**Comment by aeneasr** [comment]
You can, but it will be slow for a big number of identities!

**Comment by Answerlord** [comment]
> You can, but it will be slow for a big number of identities!

thks for your notice,does it update in offical sdk document?

**Comment by Answerlord** [comment]
> > You can, but it will be slow for a big number of identities!
> 
> thks for your notice,does it update in offical sdk document?

I don't find the  API for batch import operations in your offical sdk document (in github.com/ory/kratos-client-go) @aeneasr . Do I search for it in a wrong place?

**Comment by vinckr** [comment]
Hey @Answerlord,
there is not yet a SDK batch import method AFAIK, but you can use the CLI for batch operations as described here: https://www.ory.sh/docs/kratos/cli/kratos-import-identities

The current/proper SDK is client-go!
Check the docs here: https://github.com/ory/client-go/blob/master/docs/AdminIdentityImportCredentials.md

**Comment by Answerlord** [comment]
> Hey @Answerlord, there is not yet a SDK batch import method AFAIK, but you can use the CLI for batch operations as described here: https://www.ory.sh/docs/kratos/cli/kratos-import-identities
> 
> The current/proper SDK is client-go! Check the docs here: https://github.com/ory/client-go/blob/master/docs/AdminIdentityImportCredentials.md

I see, thks a lot.

**Comment by Answerlord** [comment]
Thanks,u guys do me a huge favor!




绝版答案
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ory/kratos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月14日(星期二) 凌晨0:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ory/kratos] Will multi-user import be supported in the future (Issue #2682)





 
We're currently working on this, see ory/network#266
