### ISSUE TITLE
Add Social Security Number (SSN) to JSONNET claims object

### ISSUE THREAD

**Issue by erikuusitalo** [ory/kratos#2697]
### Preflight checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Not able to map SSN to an identity trait using JSONNET.

### Describe your ideal solution

This should work:

```jsonnet
local claims = std.extVar('claims');

{
  identity: {
    traits: {
       ssn:  claims.ssn
    },
  },
}
```

### Workarounds or alternatives

Not found any workarounds.

### Version

v0.10.1

### Additional Context

Found this while browsing the docs:

```go
package oidc

type Claims struct {
    Issuer              string `json:"iss,omitempty"`
    Subject             string `json:"sub,omitempty"`
    Name                string `json:"name,omitempty"`
    GivenName           string `json:"given_name,omitempty"`
    FamilyName          string `json:"family_name,omitempty"`
    LastName            string `json:"last_name,omitempty"`
    MiddleName          string `json:"middle_name,omitempty"`
    Nickname            string `json:"nickname,omitempty"`
    PreferredUsername   string `json:"preferred_username,omitempty"`
    Profile             string `json:"profile,omitempty"`
    Picture             string `json:"picture,omitempty"`
    Website             string `json:"website,omitempty"`
    Email               string `json:"email,omitempty"`
    EmailVerified       bool   `json:"email_verified,omitempty"`
    Gender              string `json:"gender,omitempty"`
    Birthdate           string `json:"birthdate,omitempty"`
    Zoneinfo            string `json:"zoneinfo,omitempty"`
    Locale              string `json:"locale,omitempty"`
    PhoneNumber         string `json:"phone_number,omitempty"`
    PhoneNumberVerified bool   `json:"phone_number_verified,omitempty"`
    UpdatedAt           int64  `json:"updated_at,omitempty"`
    HD                  string `json:"hd,omitempty"`
}
```

As I understand, the claim given to you by a provider has to be named as above, otherwise it will not get added to the JSONNET claims object, is this correct? If that is the case wouldn't it be nice if all claims given by a provider were accessible through the JSONNET claim object?

**Comment by aeneasr** [comment]
Hi, this is now available with `raw_claims` :)
