### ISSUE TITLE
Provide YAML config string option as a parameter for CLI

### ISSUE THREAD

**Issue by prajaybasu** [ory/kratos#2717]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I am running a simple single instance setup using the docker image published on Docker Hub and right now environment variables are working perfectly fine for configuration however I would like to be able to specify the configuration in the YML (JSON) format.

### Describe your ideal solution

I am also running Envoy alongside Kratos as a L2 proxy to protect the admin APIs and it supports a yaml string in the args using the  `--config-yaml` option.  So Kratos could also provide a similar option.  

https://www.envoyproxy.io/docs/envoy/latest/operations/cli  

My deployment pipeline then injects the config yaml to the Envoy args without issue.

I don't expect config files to be large, however most deployment pipelines have a limit so I would like an option to do this without base64 encoding my config yaml.

This will also help with providing an alternative to issues like https://github.com/ory/kratos/issues/2659

### Workarounds or alternatives

I just use environment variables for now

### Version

0.10.1

**Comment by aeneasr** [comment]
You can use config files like this:

```
kratos serve --config path/to/config.yaml
```

we also support json and some other formats iirc

**Comment by prajaybasu** [comment]
@aeneasr I re-read my issue and it seems like I missed elaborating on the main issue.  

I already know about the YAML *file* configuration. I want to provide the YAML string directly as a CLI option. A JSON escaped YAML string.

**Comment by aeneasr** [comment]
I see, I don't think that we will support that. It's quite easy to do this in bash:

```
echo $contents config.yml
kratos --config config.yml
```

**Comment by prajaybasu** [comment]
> I see, I don't think that we will support that. It's quite easy to do this in bash:
> 
> ```
> echo $contents config.yml
> kratos --config config.yml
> ```

Not if #2719 is ever considered :)
