### ISSUE TITLE
Provide an option to run migrations before startup for the kratos serve command for single instance setups

### ISSUE THREAD

**Issue by prajaybasu** [ory/kratos#2718]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I have a simple single instance setup of kratos and right now I have to run the kratos migrate command in my deployment pipeline (which also requires giving IP access to the database outside of the cloud) before a deployment.

Unfortunately, the way my apps are hosted (Azure Container Apps), I have not found a way to easily run the migrate command on startup in a reliable manner.  

### Describe your ideal solution

I would like a CLI option in the serve flag to auto run the migrate command on startup and also provide a startup health check so that the readiness probe does not cause a failure restart loop.

### Workarounds or alternatives

None

### Version

0.10.1

**Comment by Serhii-the-Dev** [comment]
@prajaybasu we are also using Kratos in managed cloud containers and managed to deal with this issue with a custom Docker image that includes a shell script for "booting" Kratos. Besides migrations it also provides some configuration templating, here is a simplified representation of such a "boot" script:
```bash
#!/bin/sh

echo "Running migration"

# Run migrations if needed
kratos migrate sql -e --yes

echo "Starting auth server"

# Run auth server
kratos serve -c /home/ory/.kratos.yml
```
And Dockerfile:
```dockerfile
FROM oryd/kratos:v0.10.1

WORKDIR /home/ory

COPY ./kratos/kratos.sh ./kratos/.kratos.yml ./kratos/person.identity.schema.json ./

ENTRYPOINT [ "sh", "/home/ory/kratos.sh" ]
```
