### ISSUE TITLE
Provide a distroless container image

### ISSUE THREAD

**Issue by prajaybasu** [ory/kratos#2719]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Right now kratos images published on Docker Hub use alpine as base which has an inbuilt shell and other utilities.

Whether distroless is better for security or not is a long discussion, however I see the container not having an inbuilt shell or a package manager as a feature at least.

### Describe your ideal solution

It would be nice to have an option for a distroless flavor of the images published on Docker Hub - using the base debian distroless images published by Google, or if size and attack surface are concern, [apko](https://blog.chainguard.dev/introducing-apko-bringing-distroless-nirvana-to-alpine-linux/) could be used to build an alpine image that would be even smaller

### Workarounds or alternatives

Building your image

### Version

0.10.1

**Comment by aeneasr** [comment]
We had scratch container images for a long time but people often complained that it was not easy to debug so we decided to base on Alpine instead. In practice, it's not a lot of work to add distroless - just a matter of whether we want to go back on this and re-introduce distroless images.

**Comment by prajaybasu** [comment]
> We had scratch container images for a long time but people often complained that it was not easy to debug so we decided to base on Alpine instead. In practice, it's not a lot of work to add distroless - just a matter of whether we want to go back on this and re-introduce distroless images.

It should be an option. I would definitely prefer alpine for debugging and dev images or for images that run a set of jobs offline but not for the instance that is serving the public web

**Comment by jonas-jonas** [comment]
We have a distroless [Dockerfile](https://github.com/ory/kratos/blob/master/.docker/Dockerfile-distroless-static) and publish it to [Docker Hub](https://hub.docker.com/layers/oryd/kratos/v1.0.0-distroless/images/sha256-7e5cc969675d194a8713c22ed3c46ecdae82ff607f8c76db1dae5b4012216062?context=explore) now.
