### ISSUE TITLE
can_interrput is missing

### ISSUE THREAD

**Issue by LukaJaj** [ory/kratos#2764]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm trying to configure kratos.yml to use can_interrupt webhooks after registration
so my after registration webhook looks like this:

    registration:
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: web_hook
              config:
                url: http://host.docker.internal:port/hook
                method: POST
                body: file:///etc/config/kratos/body.jsonnet
                can_interrupt: true

when I run kratos with this config I'm getting error:

^-- additionalProperties "can_interrupt" not allowed
^-- doesn't validate with "#/definitions/selfServiceAfterRegistration"
 ^-- doesn't validate with "#/definitions/selfServiceWebHook"
 ^-- anyOf failed
...

### Reproducing the bug

1. add on registration webhook can_interrupt:true / false into kratos.yml (config) file 

### Version

v0.10.1

### On which operating system are you observing this issue?

macOS

**Comment by jonas-jonas** [comment]
Hi, this seems to be fixed on the latest master branch, but I can’t say since when… 
There will probably be another release of kratos in the near future, but we have no date yet. 

In the meantime, you could build the docker image directly from master, where this should be  fixed.

**Comment by vstreame** [comment]
@jonas-jonas Is there a planned release of Kratos coming out? The last release was a little over 5 months ago where this bug is present. Is HEAD in a place where it can be used in production environments?

**Comment by jonas-jonas** [comment]
@vstreame we have not decided on a new release date yet, as there are a few issues we need to take care of first.
