### ISSUE TITLE
Search engine

### ISSUE THREAD

**Issue by david972** [ory/kratos#2783]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Context and scope

The goal is to design the search engine feature to retrieve and filtering the results

### Goals

- Add a search field
- Review the paging

### Alternatives considered

https://github.com/ory/kratos/pull/2442#issuecomment-1190867502

**Comment by david972** [comment]
> @ofairfoul
> https://github.com/ory/kratos/pull/2442#issuecomment-1190867502
> Would it be possible to simply expose FindByCredentialsIdentifier on the Admin Identity API?
> I think this would meet the needs of the majority of people who just want to find usernames(emails) which are already registered.
> e.g. https://developer.okta.com/docs/reference/api/users/#get-user-with-login

**Comment by kmherrmann** [comment]
Yes, I believe that makes sense!

**Comment by Windfarer** [comment]
It would be better if we can query by the fields from `public_metadata` and `admin_metadata`

**Comment by aeneasr** [comment]
> @ofairfoul
> [#2442 (comment)](https://github.com/ory/kratos/pull/2442#issuecomment-1190867502)
> Would it be possible to simply expose FindByCredentialsIdentifier on the Admin Identity API?
> I think this would meet the needs of the majority of people who just want to find usernames(emails) which are already registered.
> e.g. https://developer.okta.com/docs/reference/api/users/#get-user-with-login

That's a good idea IMO! @zepatrik probably also needs this!

**Comment by david972** [comment]
let me know I can spend time on it

**Comment by kmherrmann** [comment]
@david972 a PR would be much appreciated! :)

**Comment by viters** [comment]
@david972 @kmherrmann 
Hows it going? Seems like a really nice feature to have with not a lot of work required to deliver, I could try to pick it up if it got stuck. I see only one closed PR https://github.com/ory/kratos/pull/2442 related to this, with different approach to implementation.

**Comment by david972** [comment]
Very well and you ?
The other one was to "translate" the call into sql query
this one is to expose a method on admin side

**Comment by jonas-jonas** [comment]
FYI, we now shipped the `credentials_identifier` query parameter in the `listIdentities` endpoint: 
- Changelog: https://changelog.ory.sh/announcements/an-api-to-fetch-identities-by-email-or-username 
- API Documentation: https://www.ory.sh/docs/reference/api#tag/identity/operation/listIdentities

**Comment by artsiommiksiuk** [comment]
@jonas-jonas,  by any chance, idk if you aware, but what about "preview_credentials_identifier_similar" field in ```listIdentities```? It states that it will be removed, but some fuzzy search functionality is also needed for my use cases. I can't find any info about this field.

Also, I don't see any resolution nor discussion about lookup in metadata fields as well.
Every ticket and discussion leading here, and it was just closed with only exact match filtering. Exact match lookup is barely can be called a search engine functionality IMHO. 

Would be nice to understand if there's any plan, or discussion which I just overlooked about identities search .

**Comment by jonas-jonas** [comment]
The problem with that parameter is, that the underlying database needs to support it well, which hasn't always been the case, yielding inconsistent results and database issues.

Adding support for search engines is a huge topic, that is not on our immediate roadmap, unfortunately. That includes metadata lookup, which is similarly complex, because of the schema-less nature of metadata.

**Comment by artsiommiksiuk** [comment]
That's a bummer. So, if we need it, the only option for us is to implement own GDPR compliant (because we are in EU) index for that?

**Comment by jonas-jonas** [comment]
`preview_credentials_identifier_similar` is based on such an index, so for now it will keep working.

**Comment by aeneasr** [comment]
We removed it, it’s not scalable
