### ISSUE TITLE
Same version of migration version 20191100000010 caused test failure

### ISSUE THREAD

**Issue by tododo** [ory/kratos#279]
**Describe the bug**

I did some debug and found that there are two migration file with same version, and in migrator.go line 92 it uses Version 20191100000010 to verify if the migration exists. And this caused the forced column never added.

exists, err := c.Where("version = ?", mi.Version).Exists(mtn)

**Reproducing the bug**

*Server logs*

--- FAIL: TestPersister/database=sqlite/contract=login.TestRequestPersister (0.00s)
            --- PASS: TestPersister/database=sqlite/contract=login.TestRequestPersister/case=should_error_when_the_login_request_does_not_exist (0.00s)
            --- FAIL: TestPersister/database=sqlite/contract=login.TestRequestPersister/case=should_create_with_set_ids (0.00s)
                persistence.go:57: 
                    	Error Trace:	persistence.go:57
                    	Error:      	Received unexpected error:
                    	            	table selfservice_login_requests has no column named forced
                    	            	sqlite create
                    	            	github.com/gobuffalo/pop/v5.(*sqlite).Create.func1
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/dialect_sqlite.go:88
                    	            	github.com/gobuffalo/pop/v5.(*sqlite).locker
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/dialect_sqlite.go:125
                    	            	github.com/gobuffalo/pop/v5.(*sqlite).Create
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/dialect_sqlite.go:62
                    	            	github.com/gobuffalo/pop/v5.(*Connection).Create.func1.1
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/executors.go:240
                    	            	github.com/gobuffalo/pop/v5.(*Connection).timeFunc
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/connection.go:228
                    	            	github.com/gobuffalo/pop/v5.(*Connection).Create.func1
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/executors.go:175
                    	            	github.com/gobuffalo/pop/v5.(*Model).iterate
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/model.go:222
                    	            	github.com/gobuffalo/pop/v5.(*Connection).Create
                    	            		/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.0.9/executors.go:174
                    	            	github.com/ory/kratos/persistence/sql.(*Persister).CreateLoginRequest
                    	            		/go/src/github.com/ory/kratos/persistence/sql/persister_login.go:19
                    	            	github.com/ory/kratos/selfservice/flow/login.TestRequestPersister.func2.3
                    	            		/go/src/github.com/ory/kratos/selfservice/flow/login/persistence.go:57
                    	            	testing.tRunner
                    	            		/usr/local/go/src/testing/testing.go:909
                    	            	runtime.goexit
                    	            		/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by aeneasr** [comment]
@zepatrik please tackle this

**Comment by aeneasr** [comment]
Since this isn’t released yet you can simply rename the newly added migrations. In the future, we need to make sure that the IDs are unique. There should be a test for that.

**Comment by zepatrik** [comment]
we should use this command (from the gobuffalo docs)

> The soda command will generate SQL migrations (both the up and down) files for you.
>
> `soda generate fizz name_of_migration`
