### ISSUE TITLE
Can’t update Identity credentials with adminUpdateIdentity

### ISSUE THREAD

**Issue by fdelucchijr** [ory/kratos#2797]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I do change the identity credentials in kratos via adminUpdateIdentity the hash in the identity_credentials table for the user isn’t updated. I needed to update it manually.
Kratos responds to the API with 200 [ok].

### Reproducing the bug

This is my current script:

```typescript
let r: Identity | undefined | null;

for (let index = 1; !r; index++) {
  const aa = await OryAdminApi.adminListIdentities(100, index);
  if (aa.data.length < 1) throw new Error(‘User doesn’t exists);
  r = aa.data.find((p): boolean => { return p.traits.email === email });
}

const generatedPassword = generateRandomString(4);
const b = await OryAdminApi.adminUpdateIdentity(r.id, {
  traits: { email: r.traits.email },
  schema_id: r.schema_id,
  metadata_public: r.metadata_public,
  metadata_admin: r.metadata_admin,
  state: r.state!,
  credentials: {
    password: {
      config: {
        hashed_password: ‘’,
        password: generatedPassword.trim()
      }
    }
  }
});
```

### Relevant log output

This is the data from ‘credentials’ after the update (as you can see indeed the update_at date changed, but no the version): 

```javascript
{
  password: {
    type: 'password',
    identifiers: [ ‘aaa@aaa.com' ],
    version: 0,
    created_at: '2022-09-27T22:03:40.06492Z',
    updated_at: '2022-10-12T22:05:42.224187Z'
  }
}
```

### Version

docker.io/oryd/kratos:v0.10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
You can since import identity credentials, see: https://www.ory.sh/docs/kratos/manage-identities/import-user-accounts-identities#:~:text=Import%20identities-,Import%20identities,must%20provide%20the%20credentials%20field.
