### ISSUE TITLE
Add tests to prevent duplicate migration files

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#282]
**Describe the bug**

As #279 showed, if migration files have the same name they will fail to execute. We should have a test that ensures that no files are named with duplicate timestmaps.

**Comment by zepatrik** [comment]
Looks like gobuffalo has some functions to deal with that file version stuff. Maybe we can include some simple command into their cli that has a non-zero exit code if there are some versions multiple times?

**Comment by aeneasr** [comment]
I think that listing the files and running their ID function on it and looking for duplicates should also work :)

The CLI is just another dependency needed to run the tests.

**Comment by aeneasr** [comment]
Given that we have quite a different migration pipeline now (with tests and all) this is no longer relevant / already covered.
