### ISSUE TITLE
CI setup uses master versions of the tools/scripts

### ISSUE THREAD

**Issue by harnash** [ory/kratos#2839]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It seems that some pipelines are referring to master/latest versions of tools which is problematic when working on an older version whenever the tool updates and causes issues. For example
* sdk/swagger tool updated to newest version caused incompatibilities on non go 1.9 branches/version
* linter started to throw errors regarding deprecated functions and modules

Some example references:
* https://github.com/ory/kratos/blob/master/Makefile#L58
* https://github.com/ory/kratos/blob/master/.github/workflows/ci.yaml#L20 etc.

### Reproducing the bug

1. Run CI workflows on v0.10 version (not master)

### Version

v0.10.1

### On which operating system are you observing this issue?

Other

### In which environment are you deploying?

Kubernetes

### Additional Context

It is probably not an easy/straightforward change which will probably require versioning of the ory/ci repo and ory/meta. It could be referenced via git hash but it will be harder to maintain and prone to errors.

**Comment by aeneasr** [comment]
This is on purpose / by design. It's the only way to ensure that we can push CI changes across all repos quickly. Regaring Golang etc - we use generics now anyways so upgrading Go is mandatory (and easy)

**Comment by harnash** [comment]
Right. So how one can have v0.10.1 compatible with current CI setup? At the moment running official latest version through CI yields errors.
I know this is right now a concern only for forked repos but in the future when there will be (probably) multiple versions supported it will be quite difficult to be sure code is correct and is conforming to standards. I believe CI/checks should be passing on all supported versions (LTS) and having CI point to the bleeding edge versions which Ory doesn't have control over is asking for problems.

**Comment by aeneasr** [comment]
> Right. So how one can have v0.10.1 compatible with current CI setup? 

That's a good point, for those cases it would make sense to use versioned set ups. Unfortunately, the amount of extra work we'll have to do every day if we were to change it to fixed versions is too much at the moment :(

Not sure if there's an alternative solution available

**Comment by harnash** [comment]
I can imagine this is a substantial work. I don't have an easy solution for that either. I hope that such breaking changes will not be introduced too often. 

Anyway I hope we can fix v0.10.1 CI without much effort and don't introduce massive conflict on next merge/upgrade.
If we find an recipe to keep forks intact I will try to share it.

Cheers!

**Comment by aeneasr** [comment]
Thank you @harnash :)
