### ISSUE TITLE
Admin endpoint should implement CORS similar to public endpoint

### ISSUE THREAD

**Issue by jongpieter** [ory/kratos#2859]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently the Ory Kratos Admin endpoint does not implement CORS, leading to issues connecting with a client to the admin endpoints. As the endpoint can be used by a web-application it should use CORS similar to the public endpoint, this to prevent CORS issues. 

At this moment a lot of example projects are using a proxy to enforce CORS compatibility, which does not seem correct in my opinion. Second this leads to having developers implement alternatives as a workaround for a simple fix. 

In respect to the issue #2553 this would also help improve security for the admin endpoint.

### Describe your ideal solution

The admin endpoint should support CORS similar to how this is supported with the public endpoint

### Workarounds or alternatives

Current workaround is a proxy to enforce CORS. In my opinion the should be avoided as this might lead to more security issues.

### Version

v0.10.1

**Comment by aeneasr** [comment]
See https://github.com/ory/kratos/pull/2860#pullrequestreview-1168051606
