### ISSUE TITLE
Support email verification paswordless login

### ISSUE THREAD

**Issue by sturdyhippo** [ory/kratos#286]
This flow would send a verification email containing an auth token/code on each login attempt which can then be exchanged for the access token or cookie. This is the effective equivalent of doing a password reset for every login (which many users do anyway for infrequently accessed accounts), but would remove the burden of creating and trying to remember passwords for every login. The main downside to this approach vs. a username+password login with the email as the identity is that the user doesn't have a backup method if they lose access to their email, but this is an acceptable trade-off for non-critical applications. This could also be overcome by providing a one-time code that the user can save as a backup auth method, as is common for many login systems when enabling 2FA.

If there is interest in accepting a PR to implement this, I'd be happy to work on this myself.

**Comment by aeneasr** [comment]
This is a great idea and has been on our internal roadmap. Before work starts with implementation, we need to fit it in the current architecture. Do you have an idea what that could look like? :)

**Comment by JovanShandro** [comment]
Hi! Is there any progress on this?

**Comment by aeneasr** [comment]
#2669
