### ISSUE TITLE
Support for WebAuthn discoverable credentials/resident keys

### ISSUE THREAD

**Issue by roccodev** [ory/kratos#2868]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, you can set up "passwordless" WebAuthn first-factor authentication.

However, this still requires an ID on login, as seen here:
![immagine](https://user-images.githubusercontent.com/13873938/200385067-ca607345-c629-421e-b87b-1b72c1646535.png)

### Describe your ideal solution

The WebAuthn specification defines [client-side discoverable credentials](https://www.w3.org/TR/webauthn-2/#client-side-discoverable-credential) (formerly known as *resident keys*) that allow WebAuthn authentication without the user manually inputting an ID.

### Workarounds or alternatives

This would essentially replace the ID input with just a single button (the "Sign in with security key" button), which can then be moved outside the login form, e.g. near "Sign up", or OIDC options.

### Version

v0.10.1

**Comment by nielsmeima** [comment]
I am also interested in this. An excellent demo of this feature is shown here: https://www.passkeys.io/.

**Comment by aeneasr** [comment]
This is now indeed supported by the PassKey stratgy.
