### ISSUE TITLE
Serve the schemas in the common API and have it documented

### ISSUE THREAD

**Issue by sandhose** [ory/kratos#287]
It can be useful to apps to be able to fetch the schema associated with an identity. Right now, the identity admin API has a `traits_schema_id` and a `traits_schema_url`. The issue is that the URL is the public one and the schemas API is not served by the admin API. 
In my case, my app only has access to the admin API, which means that I have no simple way to fetch the traits schema associated with an identity.

Also the schemas endpoints are not included in the swagger API doc, and I think they could be.

**Comment by aeneasr** [comment]
Makes sense!

**Comment by sandhose** [comment]
I can try to implement this if you want, I kinda want to start contributing to Kratos and this looks easy enough for that :p

**Comment by aeneasr** [comment]
Of course! If you need any pointers let us know :)
