### ISSUE TITLE
Remove requirement of at least one trait in schema

### ISSUE THREAD

**Issue by netthier** [ory/kratos#2895]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, the identity schema requires at least one trait to be defined: https://github.com/ory/kratos/blob/b3dca5642868cd0f8fe7a4962b97d8c2611d4030/embedx/identity_meta.schema.json#L26
As identities can also have read-only or invisible metadata fields traits don't always make sense, e.g. if only external data retrieved from social login claims is stored with an identity.

### Describe your ideal solution

The requirement for at least one trait should be removed, just as is currently the case with the metadata fields.

### Workarounds or alternatives

A workaround that is currently needed is defining a placeholder trait like this (courtesy of @zepatrik)
```json
{
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "placeholder": {
          "const": null
        }
      }
    }
  }
}
```

### Version

Ory Console

**Comment by aeneasr** [comment]
Hm, that's an interesting use-case. It's true that social sign in probably does not need any traits at all. However, I'm not sure if changing that could break something in the code, as it expects to have at least one trait.

**Comment by netthier** [comment]
True, maybe directly deleting that line from the schema.json might be a bad idea. 
IMO this should be investigated more then though.
