### ISSUE TITLE
Refresh identity traits on social / SSO login

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2898]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, social sign in only executes the JsonNet during registration. However, multiple questions have come up in several issues how this can be solved for linking sign ins, or when the user sign ins again - to keep the data fresh.

Example of such a discussion: https://github.com/ory/network/issues/164#issuecomment-1285989251 (there are more!)

### Describe your ideal solution

The jsonnet should be executed on sign in and on linking social sign in as well. It will have to respect the existing user data as well (so it needs to be available in the context).

### Workarounds or alternatives

There are no workarounds for this.

### Version

master

**Comment by netthier** [comment]
Already posted this in one of the other issues, but I'm wondering what would happen to the user data if the Jsonnet code and schema are changed between logins.
Would the user be effectively recreated with the most recent schema and Jsonnet, or would some old version be run?

**Comment by aeneasr** [comment]
We would add the current identity data to the jsonnet context, and then it's your decision

**Comment by netthier** [comment]
Has  there been any progress on this?

**Comment by kmherrmann** [comment]
We've added the ability to update identities from webhooks, see here: https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#update-identity-traits

Would that solve the problem for you?

**Comment by netthier** [comment]
> We've added the ability to update identities from webhooks, see here: https://www.ory.sh/docs/guides/integrate-with-ory-cloud-through-webhooks#update-identity-traits
> 
> Would that solve the problem for you?

No, as I need the update to happen during sign-in and the docs state the following:
> Modifying the identity is currently only possible during the registration and settings flows.

In my case an external social login is the source of truth for identity data. I want the Jsonnet logic that constructs the identity from the JWT to run on every sign-in, potentially updating out-of-sync values.

**Comment by kmherrmann** [comment]
I see, makes sense, thanks. I'll add it to the backlog, but a PR would accelerate it :)

**Comment by kghost** [comment]
@kmherrmann would you please reopen this one ? this issue is not fixed yet.

**Comment by kriscoleman** [comment]
@kmherrmann we ran into this too. 

We updated our claims and now existing users seem to now be broken.
Having a way to resync the traits on sign-in would be a graceful way to fix this.

**Comment by aeneasr** [comment]
This isn’t on the roadmap right now due to lack of commercial demand (hence we can’t prioritize it) but it’s certainly a good and welcomed feature. We‘ll let you know if something changes!

**Comment by Sese-Schneider** [comment]
This feature is still a important open topic for us. https://github.com/ory/kratos/issues/4084

**Comment by baszalmstra** [comment]
Im also still quite interested in this!

**Comment by beanow-at-crabnebula** [comment]
Hi @hperl could you share some reference to *how* this was implemented / can be used?

I'm assuming it's part of this commit?
https://github.com/ory/kratos/commit/4fcb2999a6250c4b63aa36c7536064c99661d6ad

**Comment by hperl** [comment]
> Hi [@hperl](https://github.com/hperl) could you share some reference to _how_ this was implemented / can be used?
> 
> I'm assuming it's part of this commit? [4fcb299](https://github.com/ory/kratos/commit/4fcb2999a6250c4b63aa36c7536064c99661d6ad)

Exactly! Docs are here: https://github.com/ory/docs/pull/2479, but basically you set `update_identity_on_login` to `automatic` in the provider config, and then the mapping will also be applied to the identity on login.
