### ISSUE TITLE
[kratos] MariaDB-Automigration missing default values (20200317160354000002_create_profile_request_forms)

### ISSUE THREAD

**Issue by DrBu7cher** [ory/kratos#2909]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/k8s/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/k8s/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have tried to set type to both "job" and "initContainer" in a newly installed cluster with an empty MariaDB-database.
The error goes away if I add `CURRENT_TIMESTAMP` as default value for both `updated_at` and `created_at` in `selfservice_profile_management_request_methods` table on `kratos` database.

```SQL
ALTER TABLE `selfservice_profile_management_request_methods` ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `selfservice_profile_management_request_methods` ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;
```

### Reproducing the bug

1. Install a new k8s cluster
2. Bring up a new MariaDB database
3. Install kratos with Helm chart v0.26.2
4. Set the `kratos.automigration.enabled: true`
5. (optional) Set the `kratos.automigration.type: "initContainer"`
6. Watch the logs of kratos-automigrate

### Relevant log output

```shell
kratos-automigrate An error occurred while connecting to SQL: error executing migrations/sql/20200317160354000002_create_profile_request_forms.mysql.up.sql, sql: INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;: Error 1364: Field 'created_at' doesn't have a default value
```

### Relevant configuration

```yml
kratos:
  kratos:
    automigration:
      enabled: true
      type: "initContainer"
```

### Version

v0.26.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
Hi there, MariaDB is not supported and we do not plan to add support for it. It's expensive to add database support due to the amount of work required when writing and testing migrations. Sorry!

**Comment by DrBu7cher** [comment]
Also for keto (on MariaDB) it was necessary to run
```SQL
ALTER TABLE `ory_keto`.`keto_uuid_mappings` ADD CONSTRAINT keto_uuid_mappings_chk_1 CHECK (1 != 0);
```

**Comment by DrBu7cher** [comment]
Following [this](https://github.com/ory/kratos/issues/770#issuecomment-755264164) and adding `sql_mode=""` in the DSN fixed the problems for kratos.
My DSN is now: `mysql://$(DB_USER):$(DB_PASSWORD)@tcp($(DB_HOST):$(DB_PORT))/$(DB_NAME)?sql_mode=''`
Keto still needed help as mentioned above.

**Comment by designermonkey** [comment]
This error is still present in the `20200317160354000002_create_profile_request_forms` migration also:

```
ory-kratos_migrate-1   | Error: error executing migrations/sql/20200317160354000002_create_profile_request_forms.mysql.up.sql, sql: INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;: Error 1364 (HY000): Field 'created_at' doesn't have a default value
ory-kratos_migrate-1   | Usage:
ory-kratos_migrate-1   |   kratos migrate sql <database-url> [flags]
ory-kratos_migrate-1   | 
ory-kratos_migrate-1   | Flags:
ory-kratos_migrate-1   |   -c, --config strings   Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
ory-kratos_migrate-1   |   -h, --help             help for sql
ory-kratos_migrate-1   |   -e, --read-from-env    If set, reads the database connection string from the environment variable DSN or config file key dsn.
ory-kratos_migrate-1   |   -y, --yes              If set all confirmation requests are accepted without user interaction.
ory-kratos_migrate-1   | 
ory-kratos_migrate-1   | error executing migrations/sql/20200317160354000002_create_profile_request_forms.mysql.up.sql, sql: INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;: Error 1364 (HY000): Field 'created_at' doesn't have a default value
o
```

@DrBu7cher's suggestion fixes it.

**Comment by DrBu7cher** [comment]
The error is a "won’t fix" because MariaDB is not officially supported :)

**Comment by digitive** [comment]
Although MariaDB is not officially supported, this bug should still be fixed and the fix is quite simple.

The cause is because in table `selfservice_profile_management_requests` the field `created_at` is set NOT NULL, but in service query the `created_at` is not specified.

```
INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;
```

The fix is simple, just set the correct default value for `created_at` ( as well as `updated_at` ), like

``` 
ALTER TABLE `selfservice_profile_management_request_methods` ALTER COLUMN `created_at` SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `selfservice_profile_management_request_methods` ALTER COLUMN `updated_at` SET DEFAULT CURRENT_TIMESTAMP;
```

**Comment by jonasbadstuebner** [comment]
Does not make sense to fix a bug for something that is not supported - that is the whole point of not supporting it. If it does work as expected on all supported DBMS', this is not an issue.

Thank you anyway for posting the explanation for the problem and a fix.
