### ISSUE TITLE
Support GRPC for Open Telemetry

### ISSUE THREAD

**Issue by martinei** [ory/kratos#2913]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Kratos (or better ory/x) supports Sending Open Telemetry Data via http, I would be great to additionally have the option to use grpc.

### Describe your ideal solution

I see two options:  Introduce a new TRACING_PROVIDER value ("otel_grpc") or add an additional Config Value for the existing "otel" variant (like protocol=grpc) to switch between http and grpc.

### Workarounds or alternatives

We have have quick and dirty patch in our private fork that basically exchange the usage of go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp against go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc in https://github.com/ory/x/blob/master/otelx/otlp.go but is currently not configurable.

### Version

master

**Comment by tampler** [comment]
otel grpc is still unimplemented as of kratos v1.3.1
