### ISSUE TITLE
feat: oidc provider for lark 

### ISSUE THREAD

**Issue by CNLHC** [ory/kratos#2924]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Lark is a widely used collaboration software in China. It can be used as an OIDC identity provider. 

Supporting the lark OIDC provider will be useful for  Chinese customers.

### Describe your ideal solution

An extra provider strategy that supports lark OIDC flow. 

### Workarounds or alternatives

Since Lark does not support standard `/.well-known/openid-configuration`, the `generic` provider can not be used.

### Version

0.11.0

**Comment by AUSBird** [comment]
I have a similar requirement but for patreon. It does not have an OIDC configuration endpoint either and it's oauth paths seem to be a bit odd.

We could have another option along side `generic` that gives us options to specify the paths for the required endpoints, or we can use generic but add config

Thoughts?

**Comment by CNLHC** [comment]
> I have a similar requirement but for patreon. It does not have an OIDC configuration endpoint either and it's oauth paths seem to be a bit odd.
> 
> We could have another option along side `generic` that gives us options to specify the paths for the required endpoints, or we can use generic but add config
> 
> Thoughts?

I think it is hard to cover all the cases with a single generic provider. Although we can add more configuration options for those who do not have `/.well-known/openid-configuration`, there remain more situations, for example: 

1. providers may require different request formats. e.g. during the token exchange, some providers use `clientId` while others use `client_id`. Besides the field name, the way to pass the client secrets to the upstream may differ too.
3. providers may have non-standard field names for claims. 

With all of these subtle edge cases, configuring a new provider (with a complicated config file) may be harder than implementing a new dedicated provider.

**Comment by AUSBird** [comment]
Claims are mapped to identity traits already using some form of mapper that can be custom configured.
And yeah, if an identity provider have a different parameter names for client id and stuff, then yeah it probably would need a custom oidc provider, but I was more wondering if lark needed more than a way to specify urls to required endpoints. If it did I would go raise my own feature request to get help with making a PR for what I mentioned

I was about to raise my own feature suggestion, I just saw this one and didn't want to duplicate it lol

**Comment by vinckr** [comment]
Closing as this has been implemented: https://www.ory.sh/docs/kratos/social-signin/lark

**Comment by Etran-H** [comment]
PR #2925 has not been merged yet. Is the related implementation here open source? 
Does Lark's use of different domain names in different regions (https://open.feishu.cn/open-apis/authen/v1/ and https://open.larksuite.com/open-apis/authen/v1/) need to be configurable?
