### ISSUE TITLE
Allow import peppered password hashes

### ISSUE THREAD

**Issue by ci42** [ory/kratos#2946]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

 We need support for importing [peppered (and salted) password hashes](https://en.wikipedia.org/wiki/Pepper_(cryptography)).

### Describe your ideal solution

The PHC string format has no support for pepper values and they shouldn't stored alongside the password hash anyway. The hash comparsion in [hash_comparator.go](https://github.com/ory/kratos/blob/master/hash/hash_comparator.go) uses free functions which can not hold state like the pepper value (secret salt).

I would propose to introduce an interface analogous to the [Hasher](https://github.com/ory/kratos/blob/master/hash/hasher.go) interface, like this:

```
type HashComparator interface {
    // compare password and hash
    Compare(password []byte, hash []byte) error
    // wether the HashComparator understand the hash format
    Understands(hash []byte) bool
}
```

and to rewrite the free functions in [hash_comparator.go](https://github.com/ory/kratos/blob/master/hash/hash_comparator.go) to types which implements the above interface. The types should be configured like `hashers` in the kratos configuration file, so that only configured hash comparator will be checked in [`Compare`](https://github.com/ory/kratos/blob/master/hash/hash_comparator.go#L28) and not all supported hash comparators.

This will make it easier to support other legacy hashing algorithms. Changing [hash_comparator.go](https://github.com/ory/kratos/blob/master/hash/hash_comparator.go) would no longer be necessary to add new hashing algorithms, you could just add a new file with the implementation.

### Workarounds or alternatives

Reset the passwords of all imported users, which is not desirable.

### Version

0.10.1

### Additional Context

Support for other legacy hashing algorithms has been discussed in #2422 and implemented in #2725 and #2741.

**Comment by aeneasr** [comment]
The PHC format allows us to define additional parameters which could also, in theory, be used to transport the pepper: `$sha$pepper=foo,salt=bar$...`. While probably counter intuitive (because we don't want to store the pepper alongside the password) it would be a simpler approach that fits with the existing approach and has benefits:

1. Works potentially for more than one algorithm
2. If the pepper changed over time (not uncommon), we can import passwords anyways

The pepper will be removed as soon as the user signs in once, so I think the security trade off is ok, especially because pepper for password hashing is a rather old and uncommon method today.

**Comment by ci42** [comment]
Thanks for your Feedback @aeneasr.

> especially because pepper for password hashing is a rather old and uncommon method today.

Even if they are uncommon today, pepper-likes are still recommended by NIST (secret salt in NIST lingo): [_In addition, verifiers SHOULD perform an additional iteration of a key derivation function using a salt value that is secret and known only to the verifier. (...) The secret salt value SHALL be stored separately from the hashed memorized secrets_](https://pages.nist.gov/800-63-3/sp800-63b.html)

> If the pepper changed over time (not uncommon), we can import passwords anyways

This can easily be achieved in my proposed solution by using a pepper-id `$pssha$pepper-id=<pepper-id>, salt=yummy$...`

> The pepper will be removed as soon as the user signs in once, so I think the security trade off is ok,

I would disagree here. Consider importing several million users., surely some will never log in again, even if their last login was just before the import. Or, in an OIDC scenario, users may obtain a fresh token through a refresh token grant flow for a very long time and don't need to (re-)authenticate. This will leave the pepper value exposed in the phc for an indefinite period of time.

IMHO, my proposed solution has additional benefits:

1. Using a uniform interface makes the code more comprehensible
2. It would not only allow peppered hashes but also makes it easy to support encrypted hashes ([like dropbox does](https://dropbox.tech/security/how-dropbox-securely-stores-your-passwords#why-is-the-global-pepper-used-for-encryption-instead-of-hashing) - unfortunately using the word "pepper" for the secret key) like `$aes-gcm-256-sha$aes-key-id=<key-id>, salt=yummy$<base64 encoded salt>$<base 64 encoded aes encrypted hash>`

**Comment by ci42** [comment]
Please have a look at the current version of #3057. I've simplified it a bit so that does not change the API of the `hasher` package.
