### ISSUE TITLE
Can't update metadata with patch

### ISSUE THREAD

**Issue by woylie** [ory/kratos#2950]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Not sure whether it's a bug, or not supported (the HTTP API docs don't mention metadata patching not being supported, though), or whether I'm doing something wrong. I'm trying to update a single `metadata_admin` field via the identity patch endpoint, but depending on the JSON patch operation I use, I'm either getting an error or the metadata is set to `NULL`.

### Reproducing the bug

1. create an identity with `metadata_admin` set to `{"state_detailed": "active"}`
2. `PATCH /admin/identities/{id}` with this request body:

```json
[
  {
    "op": "replace",
    "path": "/state",
    "value": "inactive"
  },
  {
    "op": "add",
    "path": "/metadata_admin/state_detailed",
    "value": "suspended"
  }
]
```

This results in the error `add operation does not apply: doc is missing path: \"/metadata_admin/state_detailed\": missing value`.

On the other, when I run the request with this request body:

```json
[
  {
    "op": "replace",
    "path": "/state",
    "value": "inactive"
  },
  {
    "op": "add",
    "path": "/metadata_admin",
    "value": {
      "state_detailed": "suspended"
    }
  }
]
```

I'm getting a success respone, but now `metadata_admin` is `NULL` in the database (same with replace). 

### Version

0.11.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by quintilation** [comment]
is this patch released?
I believe I am still seeing this problem when running the quickstart docker images
