### ISSUE TITLE
Calls from kratos to an external IP address even with `--sqa-opt-out`

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#2968]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm using the cli flag `--sqa-opt-out` like this:

`kratos -c ./config.yml serve --dev --watch-courier --sqa-opt-out`

and in production too.

Sometimes the corporate firewall detects and blocks calls from kratos to an external IP address.

What is it about?

### Version

0.10.1

### On which operating system are you observing this issue?

Windows / Linux

### In which environment are you deploying?

Binary

**Comment by aeneasr** [comment]
Thank you for the report! Can you please include the IP that is being called? Maybe you're seeing calls to HaveIBeenPwned for password checking.

**Comment by frederikhors** [comment]
I disabled the `HaveIBeenPwned`. I do not have the IP now, I'll post it here if you want ASAP.

**Comment by frederikhors** [comment]
The IP is: 142.250.185.179.

**Comment by frederikhors** [comment]
Yes they are still present. I'm on the latest stable version.

No webhooks. No other info unfortunately.

**Comment by aeneasr** [comment]
I believe this was a bug in one of the older Kratos versions. Can you upgrade your system?

**Comment by frederikhors** [comment]
I'm on `oryd/kratos:v1.0.0` for a few days.

I'll let you know if this is still a thing. I remember yes unfortunately. But I'll monitor 1.0.0 from now on.

**Comment by frederikhors** [comment]
Using v1.0.0 just now the firewall blocked a call to: `tcp://142.250.180.147`.

`kratos.exe`

`443 (https)`

**Comment by aeneasr** [comment]
Could also be the SMTP server connection

**Comment by frederikhors** [comment]
> Could also be the SMTP server connection

Yeah. Maybe. I will monitor further and let you know.

**Comment by jakharra** [comment]
Hi @aeneasr   to get remote IP address at the time of JWD middle ware authentication in Kartos framework
