### ISSUE TITLE
Support for multiple passwords per account

### ISSUE THREAD

**Issue by mitar** [ory/kratos#2986]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Users generally login with their credentials into multiple places: mobile phones, laptop, different browsers, maybe even public computers. These days they also often use password managers on those devices. I would like to be better trace which of those devices/sessions become active and to differentiate between them. Also I would like to be better at tracing from which password manager credentials were lost. And ideally, not have to update the password in all other devices one a password is lost on one device.

### Describe your ideal solution

I think the easiest way would be to be able to have multiple paswords per account. I could then on each device use a different password. In the case that one password is lost, only that one password can be revoked. Moreover, it is then easier to identify each device/session as each would have a different password, which can then be shown in an audit log ("device with password1 has logged in") (each password could have a nick-name/label). Before traveling, you could add a temporary password you would use on public computers to login, and then remove only that password so that it is not reused.

### Workarounds or alternatives

I could not really find any to achieve this.

### Version

v0.11.0

**Comment by kopernic-pl** [comment]
I'm afraid that it's not how things are done in authX world...
