### ISSUE TITLE
Attachments in E-Mails

### ISSUE THREAD

**Issue by SlateDave** [ory/kratos#3008]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I'd like to attach some images used within the E-Mail in order to don't rely on linking them to my web-server.

By adding images with links to your web-server you must ensure they stay online and don't change in the future (to preserve the original design for the e-mail).

The benefit of attaching them in the e-mail is also that they don't get automatically blocked from loading by some e-mail clients.

### Describe your ideal solution

The best way is to add an attachment and reference this on the image.

### Workarounds or alternatives

I know you can convert images to base64 and use this as link but many e-mail clients don't support this feature and you end up with a e-mail with non-working images.

### Version

0.11.0

**Comment by SlateDave** [comment]
For example: Gmail doesn't support base64 images: https://www.caniemail.com/features/image-base64/

**Comment by RobinGasi** [comment]
+1

**Comment by vinckr** [comment]
IMO I dont see the problem with storing them on a server and updating that link whenever the template changes. In Ory Network for example you add the base64 to the template, update, and it handles the storing&serving of images.
I think that would also work for your problem?

**Comment by SlateDave** [comment]
Base64 is not supported by all email clients.

Using a link and saving the images on a server will introduce maintenance concerns. It could also lead to older emails being corrupted if, for example, you change your logo in the future and now there is a new logo in the emails from the past that does not match the overall design of the email. So we would have to preserve those old links and switch to a new link.

However, the biggest disadvantage of using links is that almost all email clients nowadays block loading of external images until the user manually approves them, which makes the email ugly until the user agrees to a "possible invasion of privacy".

So the best solution is to attach the images and reference those attachments. This way they will be loaded by any email client and preservation maintenance will be avoided.

**Comment by kmherrmann** [comment]
To set expectations, we don't have plans to add such capabilities - maybe at some point later, but it's not on our roadmap right now. 
Instead, we plan to enable HTTP/Webhook delivery via email, so as to enable the use of CRMs, dedicated email systems with templating engines like Mailgun, and custom implementations. That will add more flexibility for customers, including ways to do localization, additional logic and data fetching, etc.

For reference, see
https://github.com/ory/kratos/issues/1030
https://github.com/ory/kratos/issues/2825
