### ISSUE TITLE
Bulk retrieval of identities by Ids

### ISSUE THREAD

**Issue by co7e** [ory/kratos#3015]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We have a user management website for our customers (organisations). Our customers have a page listing their users in a table that contains some security information, like whether 2FA has been enabled. We need to retrieve this information from Ory, and it could be for hundreds of users. Currently, we would have to fire off hundreds of requests to get each user one-by-one. This is slow and inefficient.

### Describe your ideal solution

Having an API endpoint to retrieve identities for a set of identity ids would be extremely useful, please.

### Workarounds or alternatives

Retrieving identities individually along with caching of the results to prevent hammering Ory Network.

### Version

n/a

### Additional Context

Closely connected to https://github.com/ory/kratos/issues/2448, but Thomas mentioned adding our use case would be useful for Ory.

Also, partially related to https://github.com/ory/kratos/issues/249.

**Comment by vinckr** [comment]
Closing as AFAICT this has been implemented here: https://github.com/ory/kratos/pull/3598
Let me know if your issue is not resolved by this.
