### ISSUE TITLE
Flow's returning "ID" instead of "Email" for label text

### ISSUE THREAD

**Issue by hyperknot** [ory/kratos#3041]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am using the official Email and Password identity template. The template has the label field filled in, saying "Email".

```
"properties": {
  "email": {
    "type": "string",
    "format": "email",
    "title": "Email",
```

Kratos still returns a flow UI with "ID" for label text, instead of "Email".

```
"label":
{
  "id": 1070004,
  "text": "ID",
  "type": "info"
}
```

### Reproducing the bug

1. Set up Kratos or Ory Network with the official Email and Password ID schema.
2. Try registration or login
3. Look at the UI or at the Flow JSON.

### Version

0.11.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Binary

**Comment by aeneasr** [comment]
Thank you for the report! This is currently a limitation because it’s theoretically possible to have more than one identifier (eg username AND email). However, if only one identifier is set, we should display the right title.

**Comment by hyperknot** [comment]
Sorry, my first snippet might have been too short, but of course in the official example there is only one identifier.

**Comment by hyperknot** [comment]
I made this workaround for now:

```js
function fixInitialFlow(flow: LoginFlow): LoginFlow {
  for (const node of flow.ui.nodes) {
    if (node.attributes['name'] === 'identifier') {
      node.meta.label.text = 'Email'
    }
  }
  return flow
}
```

**Comment by kmherrmann** [comment]
We added this to our backlog and will address it soon!

**Comment by filipbekic01** [comment]
This is much needed, our clients are confused with ID.
