### ISSUE TITLE
return_to state does not persist from the registration to the verification flow

### ISSUE THREAD

**Issue by dotubutis** [ory/kratos#3046]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The `return_to` state does not persist from the registration flow to the verification flow when following a verification email sent after the registration. Once the verification flow is fetched in the self-service UI, the `return_to` state is not present in the `flow` object.

You would expect `return_to` to persist in order to redirect a user back to the original application after completing the verification. 

- Workaround with `after_verification_return_to` param is possible in most cases, except when the sign-up flow is started by trying OIDC login first (see [slack discussion](https://ory-community.slack.com/archives/C02MR4DEEGH/p1673990616306549)). 
- Using a default return URL is not an option when using many different applications with the self-service UI.

[Slack discussion](https://ory-community.slack.com/archives/C02MR4DEEGH/p1674059415531279?thread_ts=1673621972.642429&cid=C02MR4DEEGH)

### Reproducing the bug

Steps to reproduce the behaviour: 

1. Configure Kratos send verification emails (`link` strategy)
2. Sign up for an Ory identity
2. Click the Verification URL in the email
3. During the verification flow the flow object fetched does not contain the `return_to` param that was set during the registration flow. 

### Relevant configuration

```yml
verification:
            after:
              hooks: []
            before:
              hooks: []
            enabled: true
            lifespan: 30m0s
            ui_url: https://auth.<root_domain>.ca/verification
            use: link
```

### Version

Latest

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

Ory Network

**Comment by aeneasr** [comment]
I believe this to be resolved :)
