### ISSUE TITLE
refresh login -> recovery flow broken

### ISSUE THREAD

**Issue by hyperknot** [ory/kratos#3047]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Recovery flow always returns `session_already_available` for logged in users.

This is usually OK, but what happens if the user need to get a privileged session and forgot their password? 

1. They go to login with refresh: true
2. They click the link "Forgot Password?"
3. This sends them to the recovery page.
4. Here, we try to run createBrowserRecoveryFlow which will return error 400 with id: "session_already_available", as the user is already logged in.

Am I missing something or it's not even possible to do this flow even in theory?

I'm using Elements but I don't think it's making a difference, it's just the logic of the browser JSON endpoints.

### Reproducing the bug

explained above

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Thank you for the report, I guess we shouldn't show the recovery link in such a case? @Benehiko what do you think?

**Comment by Benehiko** [comment]
Yeah I think then we should hide it. Doesn't make sense to recover your account in this case. Maybe we should just show a logout url instead here?

**Comment by aeneasr** [comment]
Yeah, totally!

**Comment by aeneasr** [comment]
https://github.com/ory/kratos-selfservice-ui-node/pull/263
