### ISSUE TITLE
UI message ID 1070007 is used for multiple messages

### ISSUE THREAD

**Issue by dantman** [ory/kratos#3051]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The UI message ID `1070007` is used for both "Email" and "Resend code".

### Reproducing the bug

Look at the documentation:
https://www.ory.sh/docs/kratos/concepts/ui-user-interface#email-1070007

Or write a password recovery flow and look at the label IDs.

### Version

cloud

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

Ory Network

### Additional Context

Ory's recovery flow uses both of these messages as a result trying to do `node.meta.label?.id === 1070007` will match BOTH the "Resend code" button **and** the initial "Email" input field.

**Comment by kmherrmann** [comment]
This may be related to #2974

**Comment by jonas-jonas** [comment]
Hi, thanks for the report. The message definition was just using the wrong ID. Should be fixed with #3067.

**Comment by dantman** [comment]
Lovely, I'll wait for it to reach the Ory Network and update my UI code.
