### ISSUE TITLE
Social Provider hydra integration

### ISSUE THREAD

**Issue by nsklikas** [ory/kratos#3052]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am trying to setup locally Hydra + Kratos + my own implementation of the UI and use that as an OIDC identity broker. I am using the `oauth2_provider.url` kratos config to accept the hydra login from kratos. The problem that I am facing is that the first time a user logs in using an external provider, they get redirected to the Kratos configured browser_return_url instead of Hydra. On subsequent logins the user gets redirected to hydra as expected.

I decided to try to track down this bug and I think that it is caused by the way the registration flow is initialized in the oidc callback (https://github.com/ory/kratos/blob/master/selfservice/strategy/oidc/strategy_login.go#L96). Neither the `login_challenge` nor the hydra login request get passed to the registration flow, so kratos does not call the hydra API and returns the user to the configured redirect_url.

My go skills are very limited, by I can try to open a PR fixing this if you want.

### Reproducing the bug

Run an installation with Hydra + UI + Kratos + External OP using the `oauth2_provider.url` config in Kratos. The first login will redirect you back to the registration redirect_url rather than Hydra.

### Version

oryd/kratos:v0.11.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by vinckr** [comment]
Hello @nsklikas 
thanks for the report!
I assume you are using the latest version of Ory Hydra?
Are you able to share some steps or ideally a repository to reproduce this? 
I don't think this is a bug in Ory Kratos (as this integration is working out of the box on Ory Network), it is more likely a configuration or an issue in your custom UI.
See also this discussion for pointers how to set up the integration: https://github.com/ory/kratos/discussions/2976

**Comment by nsklikas** [comment]
In the issue you have sent I can see that there is this line https://github.com/DrBu7cher/ory-selfservice-ui-node/blob/master/src/routes/login.ts#L74, which initiates a registration flow with the login_challenge before redirecting the user. This seems like a hack, but if this is how we are supposed to handle the flow it should be documented.

I have uploaded my UI implementation along with a docker-compose at https://github.com/nsklikas/ory-ui.
To run it you need to:
```console
# Fetch the repo
git clone https://github.com/nsklikas/ory-ui.git
cd ory-ui
# Build the docker image
docker build . -t ory-ui
docker-compose up
```

Make sure that you create a hydra client for Kratos to use and add that to Kratos config file. I run:
```console
hydra create client \
    --endpoint http://127.0.0.1:4445 \
    --grant-type client_credentials \
    --scope openid --scope offline_access 
```

Finally you need to add an extra oidc provider to the kratos config to enable social login (i used Azure AD).

Let me know if you need anything else

**Comment by nsklikas** [comment]
@vinckr I don't know if you had time to look into it, let me know if you need any more clarifications.

Thanks

**Comment by vinckr** [comment]
Hello Nikos, 
apologies I did not have time to look into it yet. 
I have it on my list for this week for sure 🙏

**Comment by aeneasr** [comment]
I believe we fixed this recently
