### ISSUE TITLE
Allow overriding the redirect from the Create Settings Flow for Browsers endpoint

### ISSUE THREAD

**Issue by dantman** [ory/kratos#3089]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Instead of profile and password, etc... being part of the same settings page I would like to put them on separate settings pages.

However when I send a user to the "Create Settings Flow for Browsers" (`/self-service/settings/browser`) it always redirects to the `selfservice.flows.settings.ui_url` setting and this cannot be changed. As a result visiting any of the settings pages without a `flow` already present will always redirect to the same page.

### Describe your ideal solution

Browser flow creation endpoints should accept a query parameter to tell them what UI url to redirect back to. This of course can be validated with the validations done on `return_to`.

There are a variety of potential names `redirect_to`, `ui_url`, `flow_ui`.

### Workarounds or alternatives

One alternative would be to instead add an opaque `state` query parameter that gets passed to the UI flow either in a query parameter or in the "Get X Flow" response. Like OAuth's `state` parameter. This could be used to redirect to the correct place.

I have also considered essentially proxying the `/self-service/settings/browser` (calling it with cookies and copying the set-cookie headers) and overriding the location. But this seems unnecessarily complex.

### Version

Ory Network

**Comment by aeneasr** [comment]
If I'm not mistaken, the flow payload has a `request_url` which has the original URL. There, you can check for additional parameters like your own `show_page=` parameter to filter the nodes you want to display. I think that should be a relatively quick solution that does not require a lot of coding. It's also what we suggest doing in these cases :)
