### ISSUE TITLE
Logout flow should support `return_to` query parameter

### ISSUE THREAD

**Issue by Benehiko** [ory/kratos#3100]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

It is currently not possible to have the default redirect behavior overwritten by a `return_to` query parameter in the Logout flow.

### Describe your ideal solution

Add the `return_to` query parameter to the logout flow handler 

https://github.com/ory/kratos/blob/master/selfservice/flow/logout/handler.go#L127-L139

### Workarounds or alternatives

A workaround on this would be to make an AJAX call in the background instead and have the application do the redirect instead of Ory.

### Version

v0.11.1

**Comment by aeneasr** [comment]
Wow, I thought we had this implemented already 😨

**Comment by Benehiko** [comment]
Hmm, this seems to be here https://github.com/ory/kratos/commit/1c146dd21d616a56f510019abadd37402782bb39

I think when this issue was raised, the problem existed within AX instead. Or since you do not add the `return_to` query parameter on the create logout flow API request it might be quite confusing since that is the normal "template" other flows follow. 

A solution would be to:
1. Document this outlier behaviour 
2. Carry over the `return_to` query parameter to the returned logout URL inside the create logout flow handler.

**Comment by Benehiko** [comment]
This should already be on Ory Network. As for the open source release, we do one every quarter.  https://www.ory.sh/docs/open-source/commitment#binary-and-docker-releases
