### ISSUE TITLE
`listIdentities` lists identities multiple times with `credential_identifier` set

### ISSUE THREAD

**Issue by jonas-jonas** [ory/kratos#3105]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When having identities with multiple credential types, the `listIdentities` endpoint lists identities once per credential type they have set up.

### Reproducing the bug

1. Create an identity with a `password` and setup webauthn
2. Call `/admin/identities?credentials_identifier={email_of_the_account}`
3. See the same identity listed twice

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

![image](https://user-images.githubusercontent.com/5540255/219091899-9ee2c34f-1a5b-4a0b-a364-116fb79bc4c1.png)

**Comment by aeneasr** [comment]
A select distinct should fix this
