### ISSUE TITLE
Webauthn default user data for settings flow 

### ISSUE THREAD

**Issue by mszekiel** [ory/kratos#3110]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

For settings flow kratos is creating webauthn data but it's using `placeholder` for user `name` and placeholder url for icon. 
`selfservice/strategy/webauthn/nodes.go`
`selfservice/strategy/webauthn/settings.go:364`

### Reproducing the bug

Create settings flow for project with webauthn enabled 

### Version

0.11.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by woylie** [comment]
During the registration flow, Kratos also uses `placeholder` values.

```js
{
  "user":{
    "name": "placeholder",
    "icon":"https://via.placeholder.com/128",
    "displayName": "placeholder",
    "id":"0Bp5Gd2rTNunTsqYcriAjw=="
  }
}
```

This isn't ideal, because some browsers render those placeholder values in the Webauthn dialogue. For example, this is how it looks in Chrome:

<img width="435" alt="image (7)" src="https://user-images.githubusercontent.com/13847569/224589379-b26f6411-f857-4ff3-8b01-f7135fdbff8e.png">
