### ISSUE TITLE
JSONNet VM errors with `signal: killed` on OIDC auth

### ISSUE THREAD

**Issue by baszalmstra** [ory/kratos#3121]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When people registered using Github oidc we would run into an error in ory kratos where only this error was returned:

```
{
    "id": "4f25bccd-e61d-4bd6-af4e-13f65bae5c83",
    "error": {
        "code": 500,
        "status": "Internal Server Error",
        "message": ": signal: killed"
    },
    "created_at": "2023-02-21T19:39:37.731426Z",
    "updated_at": "2023-02-21T19:39:37.731426Z"
}
```

This happens when people click the Signup with Github OIDC button right after receiving the callback from github. It also happens when updating a user with the settings flow. Note that both these flows use hooks to our backend, none of these hooks ever reach our backend though.

We run Ory Kratos in Kubernetes using the official helm charts so my first guess was that Kratos ran out of memory. However, looking at the metrics it was only using about 40-60 Mb of RAM. The official helm charts also don't seem to add any resource limits. The nodes themselves were also not running out of memory. 

After trying to figure out what the issue was I simply killed the `kratos` pod after it automatically restarted the issue was gone.Kratos

### Reproducing the bug

I have not reproduction other than waiting for a long period of time. This has already happened on two occasions.

### Relevant log output

```shell
time=2023-02-21T20:04:00Z level=info msg=started handling request http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.5 content-length:245 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:https://prefix.dev referer:https://prefix.dev/ sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-site sec-gpc:1 te:trailers user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 x-forwarded-for:10.0.0.4 x-forwarded-host:auth.prefix.dev x-forwarded-port:443 x-forwarded-proto:https x-forwarded-server:traefik-ingress-84cdc6c6f5-6cp6p x-real-ip:10.0.0.4] host:auth.prefix.dev method:POST path:/self-service/settings query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:192.168.3.14:59776 scheme:http]
time=2023-02-21T20:04:03Z level=info msg=Encountered self-service settings error. audience=audit error=map[message:: signal: killed] http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.5 content-length:245 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:https://prefix.dev referer:https://prefix.dev/ sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-site sec-gpc:1 te:trailers user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 x-forwarded-for:10.0.0.4 x-forwarded-host:auth.prefix.dev x-forwarded-port:443 x-forwarded-proto:https x-forwarded-server:traefik-ingress-84cdc6c6f5-6cp6p x-real-ip:10.0.0.4] host:auth.prefix.dev method:POST path:/self-service/settings query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:192.168.3.14:59776 scheme:http] service_name=Ory Kratos service_version=v0.11.1 settings_flow=&{5686baea-a4a0-44d6-a398-d4fb43758201 browser 2023-02-21 21:03:54.677536 +0000 UTC 2023-02-21 20:03:54.677536 +0000 UTC https://auth.prefix.dev/self-service/settings/browser   0xc001a6a4b0 0xc001b868c0 show_form [123 125] 1c96cd68-a4c0-4dc3-afd0-fe21edc24e74 2023-02-21 20:03:55.772443 +0000 UTC 2023-02-21 20:03:55.772443 +0000 UTC 83dee570-6d2c-4261-81ab-c7da5ba7fec8}
time=2023-02-21T20:04:03Z level=info msg=An error occurred while handling a request audience=application error=map[message:: signal: killed] http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.5 content-length:245 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:https://prefix.dev referer:https://prefix.dev/ sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-site sec-gpc:1 te:trailers user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 x-forwarded-for:10.0.0.4 x-forwarded-host:auth.prefix.dev x-forwarded-port:443 x-forwarded-proto:https x-forwarded-server:traefik-ingress-84cdc6c6f5-6cp6p x-real-ip:10.0.0.4] host:auth.prefix.dev method:POST path:/self-service/settings query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:192.168.3.14:59776 scheme:http] http_response=map[status_code:400] service_name=Ory Kratos service_version=v0.11.1
time=2023-02-21T20:04:03Z level=info msg=completed handling request http_request=map[headers:map[accept:application/json, text/plain, */* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.5 content-length:245 content-type:application/json cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". origin:https://prefix.dev referer:https://prefix.dev/ sec-fetch-dest:empty sec-fetch-mode:cors sec-fetch-site:same-site sec-gpc:1 te:trailers user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 x-forwarded-for:10.0.0.4 x-forwarded-host:auth.prefix.dev x-forwarded-port:443 x-forwarded-proto:https x-forwarded-server:traefik-ingress-84cdc6c6f5-6cp6p x-real-ip:10.0.0.4] host:auth.prefix.dev method:POST path:/self-service/settings query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:192.168.3.14:59776 scheme:http] http_response=map[headers:map[access-control-allow-credentials:true access-control-allow-origin:https://prefix.dev access-control-expose-headers:Content-Type, Set-Cookie cache-control:private, no-cache, no-store, must-revalidate content-type:application/json vary:Origin] size:85 status:400 text_status:Bad Request took:2.87382158s]
```

### Version

0.11.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

### Additional Context

I understand this is hard to solve, but maybe you can help me debug this issue? Could it be a memory issue? Or something else? I have no idea what might trigger this.

**Comment by giautm** [comment]
I just ran into the same issue today, after I made some changes in the GitHub app for permissions. Kill Kratos pods and it works again.

I also run Kratos on k8s, with custom helm charts. Use Kratos's hook but none of them was triggered after the flow.

**Comment by giautm** [comment]
Look like it's timed-out, the context setting for 1s. But our traces show it takes 2s for execution

https://github.com/ory/x/blob/v0.0.537/jsonnetsecure/jsonnet_processvm.go#L27-L48

**Comment by zepatrik** [comment]
We fixed one of the symptoms related to webhooks #3111, but I don't really know why it would take so long tbh... Increasing the timeout is obviously an option, what do you think @hperl?
I would guess it is the OS restricting the process in some way, but it could be anything really.

**Comment by hperl** [comment]
The culprit is that Jsonnet is Turing-complete and can for malicious inputs consume huge (practically infinite) amounts of memory. This is why we needed to contain the Jsonnet VM somehow. Currently we execute a new short-lived process for each Jsonnet VM.

Increasing the timeout a bit is fine, but at some point we need to then invest into proper sandboxing.

**Comment by zepatrik** [comment]
Agreed, but in this case we are not talking about malicious code. Instead we run into `signal: killed` errors also in cases with very small snippets that do not consume resources exhaustively. Do you have any ideas how we could debug this better and understand what is going on?

**Comment by hperl** [comment]
This should be fixed by https://github.com/ory/x/pull/679
