### ISSUE TITLE
Verification re-sent code not working

### ISSUE THREAD

**Issue by hyperknot** [ory/kratos#3123]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

On Ory Cloud, hosted UI, no application needed.

Send a verification code. Then because it doesn't arrive within 5 minutes, send a verification code again. 

Eventually, when they arrive, you'll get two emails with two codes. If you try to enter the codes in the UI, they won't work.

However when you click on the links in the email they do work.

### Reproducing the bug

Verify email, re-send it again, wait for emails, enter code.

### Version

Ory Cloud only

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by hyperknot** [comment]
To make life complicated I cannot reproduce this. But it happened while I was trying to debug why the emails are not delivered. Codes didn't work but the link with the flow-id and the code did.

**Comment by aeneasr** [comment]
Thank you for the report! It's possible that there was a mix up with the flow IDs, causing this problem. Will close it but if there is a reproducible case please reopen! :)
