### ISSUE TITLE
Mailslurper doesn't show emails due to clock differences

### ISSUE THREAD

**Issue by fmmoret** [ory/kratos#3135]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Preface: I wouldn't be surprised if this accounts for 95%+ of mailslurper related tickets. Especially when it comes to "flaky" or "buggy" mailslurper behavior once it was set up properly on your machine.

We are using mailslurper via quickstart.yml

We found that the mailslurper image is using a UTC timezone but is not using timezones when filtering in the UI.

The UI adopts your browser's timezone. 

When you run kratos flows that send off emails (say at 11pm Jan 1st local time but 1am Jan 2nd UTC) mailslurper only looks back in time relative to your current day. So for some timezones, it will "seem" like mailslurper didn't receive messages (despite logs indicating a message was written) or may "seem" like it takes X hours for them to get delivered.

Setting the TZ env variable at container creation does not fix the issue for us either -- it "changes" the timezone displayed in the container but the nominal time displayed still matches UTC. (1am Jan 2nd UTC) -> (1am Jan 2nd XXX)

### Reproducing the bug

Be in the USA -> do kratos flows in the late afternoon after next day has rolled over in UTC time -> see that mail isn't there until midnight (or following work day)

### Version

oryd/mailslurper:latest-smtps

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Thank you for the report - however this is only a test server we use for e2e testing and it's also a forked project, so there is little appetite to fix this.
