### ISSUE TITLE
Undefined sessions.StoreExact In cookie.go

### ISSUE THREAD

**Issue by rishabh-bhatnagar-xebia** [ory/kratos#3142]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

`session.StoreExact` type doesn't exist in the gorilla's [session](https://github.com/gorilla/sessions/) package. 
It has several usages in the the [cookie.go](https://github.com/ory/kratos/blob/master/x/cookie.go) file.

### Reproducing the bug

It can be verified by reading the codebase or maybe running one of the examples in which x package's cookie is being.

### Version

v0.11.1

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Binary

**Comment by aeneasr** [comment]
Please use a recent version of Go and enable go modules, thanks!

**Comment by rishabh-bhatnagar-xebia** [comment]
I'm using go1.20.1 windows/amd64

**Comment by taufik-rama** [comment]
Sorry if this might cause some notification, I want to ask the same question & I think I found the issue: `kratos` module replaces `gorilla` with some kind of different fork, you can check it by going to the [`go.mod`](https://github.com/ory/kratos/blob/80402beb109c8aef20cad7785d41175a86cb0379/go.mod#L10) file

The solution (at least for me) is to also replace the module with the expected replacement inside your `go.mod`:

```go.mod
// ...
replace github.com/gorilla/sessions => github.com/ory/sessions v1.2.2-0.20220110165800-b09c17334dc2
// ...
```
