### ISSUE TITLE
Code verification flow renders UI wrongly

### ISSUE THREAD

**Issue by omarhachach** [ory/kratos#3146]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When updating a recovery flow with an email with the code strategy, it renders two inputs with type submit.

This is a problem when dynamically rendering the UI. The response looks like this: (CSRF and other irrelevant info omitted)
```json
{
  "id": "000ba1bf-a2ca-484f-a622-132f555097a2",
  "type": "browser",
  "active": "code",
  "ui": {
    "nodes": [
      {
        "type": "input",
        "group": "code",
        "attributes": {
          "name": "code",
          "type": "text",
          "required": true,
          "disabled": false,
          "node_type": "input"
        }
      },
      {
        "type": "input",
        "group": "code",
        "attributes": {
          "name": "method",
          "type": "hidden",
          "value": "code",
          "disabled": false,
          "node_type": "input"
        }
      },
      {
        "type": "input",
        "group": "code",
        "attributes": {
          "name": "method",
          "type": "submit",
          "value": "code",
          "disabled": false,
          "node_type": "input"
        }
      },
      {
        "type": "input",
        "group": "code",
        "attributes": {
          "name": "email",
          "type": "submit",
          "value": "contact@omarhachach.com",
          "disabled": false,
          "node_type": "input"
        }
      }
    ]
  },
  "state": "sent_email"
}
```
I triaged the bug and tracked it down to this line: https://github.com/ory/kratos/blob/d2506508571130f4e2d74b2d7ed7666f452c1e5d/selfservice/strategy/code/strategy_verification.go#L171

I think the email should be a hidden field after the verification flow has been updated and state is set to `sent_email`

EDIT: I just realized that the bug is that the method field appears twice. The second `submit` method input should not be there: https://github.com/ory/kratos/blob/d2506508571130f4e2d74b2d7ed7666f452c1e5d/selfservice/strategy/code/strategy_verification.go#L160-L167

### Reproducing the bug

1. Start kratos however needed, see the relevant configuration.
2. Create a verification flow
3. Update the verification flow with the email
4. Response includes double submit types

I observed this using `@ory/kratos-client@0.11.1`. (Also has the quirk of not allowing link strategy? - but not confirmed)

### Relevant configuration

```yml
selfservice:
  methods:
    code:
      enabled: true
    link:
      enabled: true

  flows:
    verification:
      enabled: true
```

### Version

v0.11.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Docker

### Additional Context

I am available to help with this.

**Comment by jonas-jonas** [comment]
Hi! Thanks for the report and the quick fix! 

However, this is the intended behavior. One is the button to submit the code, and the other is a button to resend the code.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/5540255/223066776-5bec7f47-7adc-4731-a915-0964b6adae32.png">

**Comment by omarhachach** [comment]
Ah super, thank you

**Comment by jtabelingGSE** [comment]
> Ah super, thank you

Hey, maybe just to get back to the "problem". I have 

> Hi! Thanks for the report and the quick fix!
> 
> However, this is the intended behavior. One is the button to submit the code, and the other is a button to resend the code. <img alt="image" width="586" src="https://user-images.githubusercontent.com/5540255/223066776-5bec7f47-7adc-4731-a915-0964b6adae32.png">

Hey, possibly I understand something incorrectly but for me the issue with this UI is that the resend button is inside the same form as the required verification code field is. So when you want to send a new code the Verify code field has to be filled out, which makes no sense to me.
