### ISSUE TITLE
Validation reports wrong error code

### ISSUE THREAD

**Issue by DASPRiD** [ory/kratos#3149]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

According to [this code](https://github.com/ory/kratos/blob/master/text/id.go), different validation errors like MinLength and such should return specific error codes.

In the latest version of Ory Kratos they all return 4000001 though (Generic). This makes it impossible to customize the messages.

### Reproducing the bug

- Create a project with e.g. the NextJS skeleton.
- `console.log()` the flow messages when producing an error.
- Observe that a `MinLength` validation error returns 4000001 instead of 4000003.

### Version

0.11.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by alnr** [comment]
Dup of https://github.com/ory/kratos/issues/2103
