### ISSUE TITLE
Invalid TLDs allowed in email field

### ISSUE THREAD

**Issue by Catzilla** [ory/kratos#3154]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It's possible to create identity with emails like `x@x.x` or `x@x` (invalid top-level domain with single letter) using registration self-service flow, even when `"format": "email"` present in schema

### Reproducing the bug

1. Open any Web UI for Kratos, proceed to registration flow
2. In browser web inspector replace `type="email"` with `type="text"` to bypass client-side validation
3. Fill the form with `x@x` instead of real email
4. Submit the form, identity will be stored in database

### Relevant configuration

```yml
...
"traits": {
  "type": "object",
  "properties": {
    ...
    "email": {
      "type": "string",
      "format": "email",
      ...
    },
    ...
  }
},
...
```

### Version

git master, commit d2506508571130f4e2d74b2d7ed7666f452c1e5d (> 0.11.1)

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by BengtHagemeister** [comment]
x@x is actually a valid email. Emails don't necessarily need a tdl. Technically an email could be something like:

x@localhost
x@myinternalcompanyemailserver
x@[IPv6:2001:db8::1]
x@142.250.184.195


Also x@x.x can be a correct email, as the "x" can be an internal tdl. Something like: x@mycompany.internal or x@office.int.

**Comment by DarkProtocol** [comment]
Oh, have the same issue, so thank you for perfect work

**Comment by alnr** [comment]
Like @BengtHagemeister said, email address validation is complicated. Really, the only way to do it is to send email and see if it arrives.

Even if we disallowed `x@x`, an attacker could still easily spam you with addresses like `OWdTe6M8yajF5tCu@gmail.com` and `96QBvxozis3vbopFLQKH@gmail.com`.  So a regex is no defense.
