### ISSUE TITLE
Kratos offline, disable network checks

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#316]
I'm trying to use kratos offline.

Is there a way to disable password check on https://haveibeenpwnd.com and similar network constraints (eg. Kratos Public APIs)?

**Comment by aeneasr** [comment]
You can currently not change the password policy, but we'll add that at a later stage.

**Comment by frederikhors** [comment]
> You can currently not change the password policy, but we'll add that at a later stage.

This is very urgent for anyone who uses a completely offline environment.

So for now there is no way unless you edit the code and recompile it, right?

**Comment by aeneasr** [comment]
> This is very urgent for anyone who uses a completely offline environment.
>
> So for now there is no way unless you edit the code and recompile it, right?

Why don't you create a PR instead?

**Comment by frederikhors** [comment]
I would love to know where to start! :)

**Comment by aeneasr** [comment]
Looking at the code, it looks like this should be the case already: https://github.com/ory/kratos/blob/master/selfservice/strategy/password/validator.go#L53-L68

Maybe there's a bug though. Would probably be best to write a test case for that and see if it works as intended :)

https://github.com/ory/kratos/blob/master/selfservice/strategy/password/validator_test.go#L30

**Comment by frederikhors** [comment]
But after the call to `NewDefaultPasswordValidatorStrategy()` this line https://github.com/ory/kratos/blob/master/selfservice/strategy/password/validator.go#L72 set it to `false`.

```go
func NewDefaultPasswordValidatorStrategyStrict() *DefaultPasswordValidator {
	v := NewDefaultPasswordValidatorStrategy()
	v.ignoreNetworkErrors = false
	return v
}
```

Maybe is this?

**Comment by jakhog** [comment]
I can confirm that the validator gets stuck in an infinite loop here https://github.com/ory/kratos/blob/d743ae8d1b91adb6e0eb0380c1b4d1f99940e754/selfservice/strategy/password/validator.go#L168-L178 if Kratos is not able to connect to the online password check. I'll try to make a test case and fix it (shouldn't be that hard).

Would it however also make sense to enable a configuration setting for not performing online checks at all? Not sure, but maybe in a given deployment it would not return an error right away but after a long timeout, which isn't that great for the UX...

**Comment by frederikhors** [comment]
I agree with the option to disable it at all.

**Comment by jakhog** [comment]
I fixed the bug in #589 so that it can work, but I have not added an option to disable the online check. I'll leave the decision if that is something you want to you @aeneasr.

**Comment by harsimranmaan** [comment]
What are the thoughts on providing a static list of pwned db for offline use?

**Comment by jakhog** [comment]
It's quite big (see https://haveibeenpwned.com/Passwords) so I don't think that's a good way to go?

**Comment by aeneasr** [comment]
Yeah it's pretty big and it's also not downloadable if I'm not mistaken
