### ISSUE TITLE
Complete API-based recovery flow

### ISSUE THREAD

**Issue by renom** [ory/kratos#3163]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The last step of an API-based recovery flow requires redirecting to the HTML form (URL to the settings page in the `redirect_browser_to` field).

### Describe your ideal solution

The complete flow should be API-based.

### Workarounds or alternatives

-

### Version

v0.11.1

**Comment by jonas-jonas** [comment]
Hi, we are working on this already. No timeline yet, but soon™️.
