### ISSUE TITLE
Social Login: add support of OIDC single logout - part one: logout user in back channel

### ISSUE THREAD

**Issue by hugotiburtino** [ory/kratos#3166]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Open ID Connect has already some specs on how to make Single Logout (SLO). 
Our application needs to have it implemented and the best way of doing it is through Kratos.

### Describe your ideal solution

Now, since SLO is a relatively big topic, it would be better to split the development of its support into minor tasks. 
Here I propose to add just the support of [back channel logout](https://openid.net/specs/openid-connect-backchannel-1_0.html)

The OIDC provider is going to send a POST request to Kratos, containing in body `logout_token` with the sub and/or sid (session id, which was specified at the login). If it gets only the sub, it means all sessions of the user should be finished (currenty, we can easily find the sub searching in the table `identity_credentials`). But the sid at the login is currently not stored anywhere, so, first we should add this information in the database (ideally in the table `sessions`) and then add the support of the logout, if the sid is sent at the post request.

### Workarounds or alternatives

At moment, it seems only fearsible to make an after webhook at the oidc logout in order to make our application to end all sessions from an specific user. But in order to end just a specific session, I can't see any alternatives, besides making quite complicated webhooks and developing an extra infrastructure for something that would be much easier to do in kratos itself.

### Version

0.11.1

### Additional Context
https://github.com/ory/network/discussions/219

**Comment by hugotiburtino** [comment]
"Hints are welcome" is the new "PRs are welcome"

**Comment by aeneasr** [comment]
Do you want Kratos to sign out the session when the upstream provider logs out (i.e. user clicks "Sign out" at Google, then user is also signed out in Kratos)? If so, what's the concrete provider (Google, Spotify, ...) that you want to use in this scenario and how is backchannel logout implemented there?

**Comment by hugotiburtino** [comment]
> Do you want Kratos to sign out the session when the upstream provider logs out (i.e. user clicks "Sign out" at Google, then user is also signed out in Kratos)? 

Yes, that's the scope of this issue.

> If so, what's the concrete provider (Google, Spotify, ...) that you want to use in this scenario and how is backchannel logout implemented there?

My specific case is a generic provider (specifically Keycloak) and the logout_token has the following JWT (example):
> eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzRV8wYy1yU0xrZGJFSXpwM3VoRFN3TXBYNXZMOFI1elZiNFI3a1FybGtrIn0.eyJpYXQiOjE2Nzg1MDI2OTIsImp0aSI6IjExYWU3MTQ1LWYzNzUtNDIyYy1hZTMyLWEzZDdkMzExNzU1MyIsImlzcyI6Imh0dHA6Ly9uYnA6ODA4MC9yZWFsbXMvbWFzdGVyIiwiYXVkIjoic2VybG8iLCJzdWIiOiJkM2EwZjdhMi0xZGI5LTQ2NDItODRhMC0wOGZlMDE3MTU1NDMiLCJ0eXAiOiJMb2dvdXQiLCJzaWQiOiI2MmI4YjM5Mi0wNzkzLTQwNzYtYTlkYy1kYmZiM2NmODQ4YmYiLCJldmVudHMiOnsiaHR0cDovL3NjaGVtYXMub3BlbmlkLm5ldC9ldmVudC9iYWNrY2hhbm5lbC1sb2dvdXQiOnt9fX0.UhbrMlKlx1LILv1W4hnQqmFm_VwTWx2nnmmakv8XrwJL_UVh_uWGi7KwIrkEaySHoZ57AldIIN23pzaRc--6gDyR3Wj57GM54URotnKe7lmyKU8LTJkxZyofTzLsK2WyVnNE8H6LM2V4VGdT_5iwo6eJ7sOnxZAPPLLNRPtzt36qrBvyrEZYFF-xib6XOm_3C9J9SPDbR-BNUigAa5qfCz_JAHU-j3384zRQY6Vljqhju-KEv_uI6qabzsn8Cg4lrJrwxfqXjthaO4BF4PkgCfnzNicMGnfQG8VTZzHPUL_VCaBvfji4nMX1E5LMHdIbnS06Ncro9wZoTw8GxALI_w


decoded payload:
```json
{
  "iat": 1678502692,
  "jti": "11ae7145-f375-422c-ae32-a3d7d3117553",
  "iss": "http://nbp:8080/realms/master",
  "aud": "serlo",
  "sub": "d3a0f7a2-1db9-4642-84a0-08fe01715543",
  "typ": "Logout",
  "sid": "62b8b392-0793-4076-a9dc-dbfb3cf848bf",
  "events": {
    "http://schemas.openid.net/event/backchannel-logout": {}
  }
}
```

But I think it would be better to implement it in a kind of interface for all providers (not only generic, although, as far as I could see in the code, the generic provider is used for other providerrs...)

**Comment by hugotiburtino** [comment]
> I see, that makes sense! Will add this to the backlog but we have many other priorities at the moment

I can try to implement it by myself (for us it is high priority).
Would you have some hints for me? Ideally, a similar PR; otherwise, tell me which files have to be changed or at least to start with.

Needed changes:
- At login: store the sid in the sessions table (along with the corresponding session)
- At logout: support post request and recognize the body.
- Invalidate the sessions of the identity (if only sub is sent) or invalidate just the specific session (corresponding to the sid).

**Comment by aeneasr** [comment]
The high level plan sounds ok, but it would be great to have a proper design document to iron out potential problems. It will also be problematic when we're looking at Ory Edge Sessions and using backchannel - so we'll have to respect the system limitations there too.

**Comment by hugotiburtino** [comment]
Hey @aeneasr What do you think of this Design Document
https://github.com/aeneasr/gh-template-test/issues/2
(I couldn't get the problem with Ory Edge Sessions, would you mind to complement it?)
