### ISSUE TITLE
Support `include_credential` param for ListIdentities API

### ISSUE THREAD

**Issue by bcordobaq** [ory/kratos#3190]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, the List Identity API service returns the Identity data without the `credentials` section, and I you want to get it, you need to use the individual Get Identity service.

### Describe your ideal solution

Include the credentials section as optional only if the user adds the `include_credential` param when calling the ListIdentities API. It's the same param that already has the Get Identity API.

### Workarounds or alternatives

Return by default the credentials section, but it wouldn't be a good solution, since it's not solved like this for the other related Identity APIs.

### Version

0.11

**Comment by LukaJaj** [comment]
https://github.com/ory/kratos/pull/3652

**Comment by jonas-jonas** [comment]
Fixed via https://github.com/ory/kratos/pull/3343
