### ISSUE TITLE
Support passing session ID webhook context where possible

### ISSUE THREAD

**Issue by mfzl** [ory/kratos#3203]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Right now after login and after registration hooks have no way to link to active session. I haven't found anyway to link and identify the current session the hook is being fired from.  

It also doesn't need to pass any sensitive information, just passing session ID is enough to make it work, other details can then be retrieved from admin API if desired.

### Describe your ideal solution

Making session ID available in the webhook context or possibly other non sensitive information in the context passed to Jsonnet, if session is available.

### Workarounds or alternatives

There are none so far

### Version

0.11.1

**Comment by mfzl** [comment]
I'm willing to contribute if it's acceptable

**Comment by mfzl** [comment]
Now that I think about it, `Session` is already declassified and it can only be passed to the `web_hook` if it's configured to pass the session information. I don't see a downside of making the entire session object available in template context.

**Comment by aeneasr** [comment]
Sure, makes sense :)
