### ISSUE TITLE
"Account access attempted"emails sent by default and "notify_unknown_recipients" is ignored

### ISSUE THREAD

**Issue by uvinw** [ory/kratos#3226]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The documentation states that Ory Kratos no longer sends the "Account access attempted emails" if some tries to recover someone else's account ("anti-account-enumeration measures"). 

[This PR](https://github.com/ory/kratos/pull/3075) made it configurable via the `notify_unknown_recipients` config. 

However, neither of these seem to be working on the current version of Kratos with the email being sent by default on email recovery flows.

### Reproducing the bug

- Follow the quickstart guide:
```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.11.1
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
```
- click forgot password and enter an email you control (but not in Kratos)
- the "Account access attempted" email will be in your inbox

### Version

v0.11.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

**Comment by jonas-jonas** [comment]
>git checkout v0.11.1

The PR that introduced that flag has not been part of a release yet. So the only way to get this working is by building the image from master and using that. For example, by using the `quickstart-dev` make target.

**Comment by jonas-jonas** [comment]
Yes, before the PR, Kratos would always send these emails.

**Comment by jonas-jonas** [comment]
>docs are based on master but releases are not.

Pretty much. 

The [Ory Network](https://www.ory.sh/network/) is a bit ahead of releases, and the documentation is more or less tied to that.

FWIW, the next release is going to be released soon, as well.

**Comment by jonas-jonas** [comment]
>I don't see a v0.12 branch, 

Not yet.

> Is there any way to see whats included in it?

Pretty much everything that's been pushed to master since v0.11.1: https://github.com/ory/kratos/compare/v0.11.1...master
