### ISSUE TITLE
can't patch metadata if metadata is null

### ISSUE THREAD

**Issue by woylie** [ory/kratos#3244]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

While #3103 now allows patching metadata in general, it is still not possible to patch metadata if the value is `null`. Since that is the value to which the metadata fields are set initially, there is no reliable way to atomically patch metadata public/admin.

This could be solved by:

- applying a patch operation to an empty object if the metadata value is null
- setting the default for the metadata columns to `{}` and adding a not-null constraint

### Reproducing the bug

1. create an identity with `metadata_admin` set to `null`
2. `PATCH /admin/identities/{id}` with this request body:

```json
[
  {
    "op": "replace",
    "path": "/metadata_admin/shoe_size",
    "value": 41
  }
]
```

This fails with the message `replace operation does not apply: doc is missing path: /metadata_admin/shoe_size: missing value`. The same happens with `"add"`.

On the other hand, this:

```json
[
  {
    "op": "add",
    "path": "/metadata_admin",
    "value": {}
  },
  {
    "op": "replace",
    "path": "/metadata_admin/shoe_size",
    "value": 41
  }
]
```

Will succeed the first time when the metadata value is `null`, but when the metadata field already has other fields, they will be removed.

### Version

0.13.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

### Additional Context

The issue was reported before in #3099. A related issue was reported in #2950 and fixed in #3103.

**Comment by IchordeDionysos** [comment]
It's not yet actually fixed, only the root cause has been fixed.
The ory/x dependency needs to be updated to the latest version in Kratos for the fix to be active.

**Comment by IchordeDionysos** [comment]
Should hopefully be fixed soon on Ory-network
