### ISSUE TITLE
Add automatic extension of session expiry

### ISSUE THREAD

**Issue by kamilkloch** [ory/kratos#3246]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Automatic session extension on every successful user request is arguably a standard and widely practiced approach.
This feature is missing in kratos. 
Currently, the only way to extend a user session involves interacting with the kratos admin api. This defeats the purpose of making the downstream services oblivious to the kratos layer (as the downstream service possibly needs to interact with kratos admin as a reaction to the ~~received webhook~~ authenticated request).

### Describe your ideal solution

Add configuration optin for the automatic extension of session expiry. 

### Workarounds or alternatives

~~Webhook from kratos on successful authentication~~, POST to kratos admin from the downstream services as a reaction to the ~~hook~~ authenticated request. 

### Version

0.13.0

**Comment by kmherrmann** [comment]
> Webhook from kratos on successful authentication

actually, that would only work to customize the lifetime after login, right?
One challenge here is that to automatically extend sessions, we would probably have to do extend based on /whoami calls. This would downgrade performance for a latency-optimized endpoint that currently doesn't do writes; and it wouldn't work in all cases, depending how the applications use /whoami.

That's why we leave it to the application to decide on when to extend sessions.

**Comment by kmherrmann** [comment]
also see here: https://github.com/ory/kratos/issues/615

**Comment by kamilkloch** [comment]
@kmherrmann Thanks for the response. I updated the issue (removed confusion around the webhook).

> One challenge here is that to automatically extend sessions, we would probably have to do extend based on /whoami calls. This would downgrade performance for a latency-optimized endpoint that currently doesn't do writes; and it wouldn't work in all cases, depending how the applications use /whoami.

Session need not be extended on every /whoami call - it would suffice to track the timestamp of the most recent successful /whoami and prolong the session, say at most once a minute. Negligible performance penalty. This is how we intend to solve it on our side, hovewer, it would be nice if kratos supported it out of the box :)

**Comment by jacobrayschwartz** [comment]
This looks like the issue went stale but there was no development or decision to not move forward which I can see. Are folks also interested in Kratos having some configuration which allows the session to auto refresh on calls to `whoami` after the `earliest_possible_extend`? 

I'm currently working on integrating Kratos into our SPA's and this would save me some headache, assuming this is an appropriate action to head towards. 

This is the only other info I've found so far on folks auto-extending sessions https://github.com/ory/kratos/discussions/3837#discussioncomment-9899854 the solution was to have the SPA's back end API deal with the extension itself, it seems

**Comment by mathportillo** [comment]
Maybe useful to note that [aeneasr](https://github.com/aeneasr) said on the [session renew PR](https://github.com/ory/kratos/pull/2146#issuecomment-1080434473) that automatic extension by read operations like /whoami would be suceptible to CSRF

He is referencing to [this comment](https://github.com/ory/kratos/issues/615#issuecomment-666985082) on the issue that preceded the PR

So the current conclusion is that no config would auto refresh by read only operations like whoami
