### ISSUE TITLE
Session cookie (ory_kratos_session) expired time should be configurable

### ISSUE THREAD

**Issue by duytruong** [ory/kratos#326]
**Is your feature request related to a problem? Please describe.**

Currently, session cookies expires after 1 month.

**Describe the solution you'd like**

Session cookie (`ory_kratos_session`) expired time should be configurable. A `ttl.session` config already exists in the code base but can't be used, IMO schema config doesn't add this field atm.

**Describe alternatives you've considered**

**Additional context**

**Comment by duytruong** [comment]
It's good if you let me know where to start :)

**Comment by aeneasr** [comment]
The [current key](https://github.com/ory/kratos/blob/master/driver/configuration/provider_viper.go#L55) is kind of old, I don't think we should use it! Instead, it would make sense to add a `ttl` to the session hook config around [here](https://github.com/ory/kratos/blob/master/driver/registry_default_hooks.go#L23) (see [example config for redirection hook](https://github.com/ory/kratos/blob/master/driver/registry_default_hooks.go#L34)). This would need tests and the Configuration Schema also needs to be updated around [here](https://github.com/ory/kratos/blob/master/.schema/config.schema.json#L60-L71)
