### ISSUE TITLE
Kratos admin does not support CORS

### ISSUE THREAD

**Issue by kamilkloch** [ory/kratos#3262]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Hello all, when trying to use kratos admin https://github.com/dfoxg/kratos-admin-ui I am running into CORS problems. Admin running on kamilk:3002 , kratos config contains `allowed origins: - http://kamilk:3002/`, browser fails to GET http://kamilk:4434/admin/identities due to CORS error: `missing allowed origin`. Indeed, kratos response does not contain `Access-Control-Allow-Origin` header.

Here is the 200 response from kratos, which is rejected by the browser due to "missing allowed origin":
```
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Length: 3
Content-Type: application/json; charset=utf-8
Date: Mon, 03 Apr 2023 07:50:44 GMT
Link: <http://kamilk:4434/identities?page=0&page_size=250&page_token=eyJvZmZzZXQiOiIwIiwidiI6Mn0&per_page=250>; rel="first",<http://kamilk:4434/identities?page=1&page_size=250&page_token=eyJvZmZzZXQiOiIyNTAiLCJ2IjoyfQ&per_page=250>; rel="next",<http://kamilk:4434/identities?page=-1&page_size=250&page_token=eyJvZmZzZXQiOiItMjUwIiwidiI6Mn0&per_page=250>; rel="prev"
X-Total-Count: 0
```

It looks that kratos admin does not support CORS.

### Describe your ideal solution

Support CORS in kratos admin, just like in kratos public.

### Workarounds or alternatives

None

### Version

0.13.0

**Comment by jonas-jonas** [comment]
The admin API is not supposed to be accessed via browser and is not secured by design. Please use a reverse proxy like Ory Oathkeeper in front of it to configure CORS and auth for the admin APIs.

See also https://github.com/ory/kratos/issues/3223

**Comment by kamilkloch** [comment]
Thank you for the hint. As for the oathkeeker, we currently disabled CORS due to https://github.com/ory/oathkeeper/issues/1100
