### ISSUE TITLE
Quick start fails

### ISSUE THREAD

**Issue by jrozentur** [ory/kratos#3267]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

following quick start page https://www.ory.sh/docs/kratos/quickstart
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate|
...migrations...

 I[#/selfservice/flows/registration/after] S[#/properties/selfservice/properties/flows/properties/registration/properties/after/$ref] doesn't validate with "#/definitions/selfServiceAfterRegistration"
kratos-kratos-1                      |   I[#/selfservice/flows/registration/after/password] S[#/definitions/selfServiceAfterRegistration/properties/password/$ref] doesn't validate with "#/definitions/selfServiceAfterRegistrationMethod"
kratos-kratos-1                      |     I[#/selfservice/flows/registration/after/password/hooks/1] S[#/definitions/selfServiceAfterRegistrationMethod/properties/hooks/items/anyOf] anyOf failed
kratos-kratos-1                      |       I[#/selfservice/flows/registration/after/password/hooks/1] S[#/definitions/selfServiceAfterRegistrationMethod/properties/hooks/items/anyOf/0/$ref] doesn't validate with "#/definitions/selfServiceSessionIssuerHook"
kratos-kratos-1                      |         I[#/selfservice/flows/registration/after/password/hooks/1/hook] S[#/definitions/selfServiceSessionIssuerHook/properties/hook/const] value must be "session"
kratos-kratos-1                      |       I[#/selfservice/flows/registration/after/password/hooks/1] S[#/definitions/selfServiceAfterRegistrationMethod/properties/hooks/items/anyOf/1/$ref] doesn't validate with "#/definitions/selfServiceWebHook"
kratos-kratos-1                      |         I[#/selfservice/flows/registration/after/password/hooks/1] S[#/definitions/selfServiceWebHook] validation failed
kratos-kratos-1                      |           I[#/selfservice/flows/registration/after/password/hooks/1] S[#/definitions/selfServiceWebHook/required] missing properties: "config"
kratos-kratos-1                      |           I[#/selfservice/flows/registration/after/password/hooks/1/hook] S[#/definitions/selfServiceWebHook/properties/hook/const] value must be "web_hook"
kratos-kratos-1 exited with code 1
(repeats in a loop)

### Reproducing the bug

https://www.ory.sh/docs/kratos/quickstart

### Version

v0.13.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by vinckr** [comment]
Hello @jrozentur 
when you checkout 0.13.0 change the version of Kratos in 
`quickstart.yml`
&
`contrib/quickstart/kratos/email-password/kratos.yml`

from `v0.11.0` to `v0.13.0`

Let me know if that helps.

**Comment by jrozentur** [comment]
This fixes it, thanks @vinckr!

**Comment by vinckr** [comment]
Good to hear @jrozentur 
https://github.com/ory/kratos/pull/3268 will fix this for the next release.

**Comment by SangI762** [comment]
Hello, @vinckr. I have the same issue, what exactly should I do to fix it? I can't understand what you meant in your previous answer. Thanks a lot.

**Comment by vinckr** [comment]
The tags in the quickstart.yml are not properly updated with new releases, see [here](https://github.com/ory/kratos/pull/3268).

So change the tag in kratos.yml from `v0.11.0` (old version) to `v0.13.0` (current version). 

This is fixed on master, but unfortunately not fixable in the v0.13 release (unless we re-release it)

Let me know if that makes it clearer @SangI762
