### ISSUE TITLE
Transfer OIDC provider context to Hydra

### ISSUE THREAD

**Issue by BugGambit** [ory/kratos#3270]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to know which OIDC provider the user used to sign in with when we reach the consent flow so we can include it in the access token. Hydra [added support](https://github.com/ory/hydra/pull/1353) to pass data from the accept-login endpoint to the consent flow, but Kratos doesn't utilize this field today.
We want Kratos to provide details about the login flow (at least provider ID for generic OIDC) in the context object after a successful authorization code flow against the OIDC provider. We have yet to find a way to work around this problem and secure ourselves against man-in-the-middle attacks.

### Describe your ideal solution

Populate the context object field when calling [Hydra's Accept OAuth2 Login Request](https://www.ory.sh/docs/hydra/reference/api#tag/oAuth2/operation/acceptOAuth2LoginRequest) with details about the IdP used to sign in the user. This must happen for the [login](https://github.com/ory/kratos/blob/master/selfservice/flow/login/hook.go#L238) and [registration](https://github.com/ory/kratos/blob/master/selfservice/flow/registration/hook.go#L246) flow (?).

Kratos doesn't utilize this field today, resulting in `context == null` in Hydra's consent flow.

### Workarounds or alternatives

We haven't found a workaround that prevents man-in-the-middle attacks. Only Kratos can guarantee which IdP the user signed in with.

### Version

0.13.0

### Additional Context

[Slack thread](https://ory-community.slack.com/archives/C012RJ2MQ1H/p1683205442395029) in Ory Community.

**Comment by BugGambit** [comment]
We are willing to create a pull request which implements this feature if it sounds reasonable.

**Comment by kmherrmann** [comment]
I think this is a good idea - the PR would be welcome!
@hperl @jonas-jonas any concerns with the approach proposed?

**Comment by hperl** [comment]
Sounds good to me!
