### ISSUE TITLE
Kratos as library for any Golang project

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#328]
It would be amazing to use Kratos as a library in any Go project (like https://github.com/volatiletech/authboss) and without oathkeeper or with oathkeeper too.

Is this already possible?

**Comment by aeneasr** [comment]
Unfortunately not, and it's also a non-goal for this project. You can still use it in a Go project though and the next release also includes a version without oathkeeper!

**Comment by frederikhors** [comment]
Do you have news on this, @aeneasr? Is there a way to use Kratos-as-a-library in a Golang project?

**Comment by aeneasr** [comment]
No there is none and it remains a non-goal

**Comment by frederikhors** [comment]
What a pity! I cannot deploy another binary!
