### ISSUE TITLE
Support AppLinks on Social Sign in for Android 

### ISSUE THREAD

**Issue by Maragues** [ory/kratos#3282]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Goal: Create the best UX on Android for social sign in

Ory recently released [Social Sign in for Native APIs](https://www.ory.sh/docs/kratos/social-signin/native-apps). 

One of the steps in the workflow requires the applications to capture a redirect link and extract a code from the query parameter.

Android supports this in [different ways](https://developer.android.com/training/app-links), but the best UX is provided by [App Links](https://developer.android.com/training/app-links#android-app-links). 

<details>
<summary>Benefits of AppLinks</summary>

If you simply declare that your project wants to capture a URL, the user will be prompted with a dialog on whether he wants to open it with a url or with your application. With App Links, the url is opened directly on your application.

</details>

For security reasons, AppLinks requires that the target domain of the url hosts a public file at `<domain>/.well-known/assetslinks.json`. With that, Android can verify that the domain allows an application with a given package + certificate is allowed to capture the link.

<details>
<summary>Structure of assetlinks.json file</summary>

```
[{
  "relation": ["delegate_permission/common.handle_all_urls"],
  "target": {
    "namespace": "android_app",
    "package_name": "com.company.name",
    "sha256_cert_fingerprints": ["..:..:....."]
  }
}]
```

</details>

### Describe your ideal solution

1. Kratos hosts an `assetlinks.json` file, provided by the client, at `/.well-known/assetlinks.json`
2. We can configure the return url for social sign in to have a custom schema, such as `example://gizmos`. I don't know if this is already possible.

I don't know if the latter should be configurable per-social-sign-in provider

### Workarounds or alternatives

We use an nginx to route the traffic. If the request path is `/.well-known/assetlinks.json`, then we serve that file. Otherwise, it goes to Kratos.

### Version

I actually don't know, because we use a fork. But it's up to date on the latest social sign in commit. I'm not the maintainer of that.

**Comment by Maragues** [comment]
To clarify, this is only needed if you can't set a `SELFSERVICE_DEFAULT_BROWSER_RETURN_URL` to a custom scheme.

If we are allowed to do something like this without interfering with other features, then there's no need to host the assetlinks.json file

> SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: mycompany://kratos_return_url

**Comment by jonas-jonas** [comment]
I cleared up a few things internally:

1. we do support custom URI schemes, you just need to allow the URL in the config: 
```yaml
selfservice:
  # ...
  allowed_return_urls:
    # ...
    - my.company.app://test # replace with your actual URI
```

2. We still recommend to use app links instead, as custom URI schemes seem to be deprecated in favor of them. For that, you should be able to just self-host the necessary JSON files on a domain you control and specify that as the `return_to` URL (don't forget to allow it!). Serving this file from Kratos is too device/framework specific and would require extensive configuration options, that we cannot maintain.

**Comment by Maragues** [comment]
Thanks for clarifying that we can return whatever url. I'm not the one in the team dealing with kratos.
