### ISSUE TITLE
Browser+JSON flow feature parity with Browser+HTML flow

### ISSUE THREAD

**Issue by hperl** [ory/kratos#3287]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Using the browser+JSON flows (i.e., browser API + accept JSON) is currently lacking a couple of features:

* After a successful OIDC login the response does not contain the correct callback URL to follow up with the consent. Draft PR here: https://github.com/ory/kratos/pull/3271
* The value of the `ory_kratos_continuity` cookie is not returned as part of the JSON response when submitting a login/registraton flow.

### Describe your ideal solution

Implement the missing features.

### Workarounds or alternatives

User Browser+HTML flow

### Version

master

**Comment by BrandonNoad** [comment]
I wanted to add a bit more context.

> After a successful OIDC login the response does not contain the correct callback URL to follow up with the consent. Draft PR here: https://github.com/ory/kratos/pull/3271

In the scenario above, the user is signing in to a third-party service and Ory is acting as the OAuth/OIDC provider.

> The value of the ory_kratos_continuity cookie is not returned as part of the JSON response when submitting a login/registraton flow.

In the scenario above, the user is using Ory's "Social Sign-In" feature to sign into the application. Ory is acting as the OAuth/OIDC client.

The two scenarios above could also be combined together in a single flow.
