### ISSUE TITLE
Ability to import `crypt(3)` hashes

### ISSUE THREAD

**Issue by indietyp** [ory/kratos#3291]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We're currently using `md5-crypt` (from the [`libcrypt`](https://manpages.debian.org/bullseye/libcrypt-dev/crypt.3.en.html) ) to hash passwords (it is part of the POSIX C library), which are currently not supported by Kratos.

Adding support for them would be very beneficial, as many systems, especially older ones that seek to move Kratos, use `crypt(3)` functions for their hashes.

### Describe your ideal solution

Ability to ideally import any `crypt(3)` hash, but at least have the ability to import [`md5crypt`](https://manpages.debian.org/bullseye/libcrypt-dev/crypt.5.en.html#md5crypt) hashes.

### Workarounds or alternatives

There are currently no workarounds, as the algorithms for `md5crypt` based hashes is not compatible with the `md5` import (it uses `md5` internally).

### Version

v0.13.0

### Additional Context

Having looked around the go ecosystem, it seems that there are quite a lot existing libraries that support `crypt(3)` hashes.

**Comment by aeneasr** [comment]
Sounds good, please use the PHC hashing format for this
