### ISSUE TITLE
Test Token / Cookie for Integration Testing or manual testing of Backend

### ISSUE THREAD

**Issue by Leon0402** [ory/kratos#3301]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

A standard project consists of an ory instance, frontend (e.g. spa) and backend. A key challenge is testing the frontend / backend manually while developing, as well as automatic testing with unit / integration / e2e tests.

For the frontend, the situation is rather easy. There, you have implemented a login process with ory Kratos. Thus, it's easy manually testing your frontend and automatic testing is very easy as well (there are frameworks to make this easier as well), because you can just create once a test user and then use the login functionality to obtain a valid session and test whatever you need to test.

The backend part though is much more involved. Consider the scenario where you implemented a new API Rest Endpoint in the backend (not yet in the frontend) which needs a valid token and / or cookie and our two use cases: 

1. Manual Testing: Assume you want to test your new endpoint with something like Postman or similar. How do you get the valid token / cookie?   => Your backend has no function to directly obtain this as in the frontend. Spinning up your frontend and doing the login there first, then extracting the cookie and copying it over to postman, is really painful. You could also develop a separate script to get the cookie. Less painful, but still always some extra steps, and you actually need to develop such a script.
2. Automatic Testing: Say for instance some integration test, so you actually want to test that it is working with Ory Kratos. Even more painful, you cannot obtain this manually with your frontend. So implementing a login process is mandatory. Again, this is work, and additionally it makes the test more complex, slower to run, more fragile.

Developing / Testing is hard enough by itself. When I need five additional steps to simply test my endpoint with postman, it is incredibly demotivating. 

### Describe your ideal solution

Ory Kratos should have some sort of Developer Setup (with security measurements to prevent it from being used in production in this mode!). In developer mode it should be possible to hardcode Cookies **and** Tokens which will always be accepted by Ory Kratos as valid. 

This makes manual and automatic testing a breeze. Just hardcode the cookie / token (depending on the setup) in your test or copy it into postman (you can even save queries there with this hardcoded cookie) and it just works.
Testing and developing is almost as easy and painless as without Ory Kratos, which should be the ultimate goal. 

### Workarounds or alternatives

1. The current approach of developing some scripts. As explained above: Somebody needs to develop & maintain them. And it is still an extra step for manual testing. For automatic testing, it makes everything more complex / fragile / longer to run.

2. Implement an Ory Cli / Admin Endpoint to obtain some test cookie / token. This is similar to alternative one. The advantage would be that the script does not need to be developed / or maintained. Less overhead to integrate this into automatic testing as well. But the point of complexity, fragility, ... still stands.

### Version

v0.13.0

**Comment by sgrannan** [comment]
We are just now implementing integration testing using `testcontainers` and this is the exact issue I ran into today. We want to test our backend APIs and all the infrastructure included to support them, which includes Kratos. Our APIs require the a Kratos session cookie, but I have no way of easily doing this without several other steps that I'm not sure will work consistently (yet).  

As the user mentioned above, at the very least would it be possible to introduce CLI commands for self-hosted that could be issued directly to the docker container in "test" mode?
