### ISSUE TITLE
Default sorting of sessions

### ISSUE THREAD

**Issue by marcinfigiel** [ory/kratos#3307]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, the sessions returned by the `/admin/sessions` and `/admin/identities/{id}/sessions` endpoints are not sorted in a useful manner. This poses challenges or even renders these endpoints unusable, depending on the use case. For example, it becomes difficult to find a user's last login time. 
Having a default sorting that returns the newest session first would greatly enhance the usability of these endpoints.

### Describe your ideal solution

Sort the sessions so the newest ones are returned first. 

### Workarounds or alternatives

I can fetch all the sessions and sort them on my end to find what I'm looking for, but it's not a feasible solution.

### Version

SaaS

**Comment by kelkarajay** [comment]
@marcinfigiel there was work in progress to fix that here - https://github.com/ory/kratos/pull/2939. There was (iirc) one failing test that remained
