### ISSUE TITLE
OIDC login fails to complete OAuth2 flow the first time a user logs in

### ISSUE THREAD

**Issue by flusflas** [ory/kratos#3321]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I try to perform an OIDC login using a user for the first time (OIDC registration flow?), Kratos is registering the user and redirects the browser to the value configured in `selfservice.flows.registration.after.oidc.default_browser_return_url`. I'm getting a session cookie, but there is no `login_challenge` that I can use to complete the OAuth2 login flow.

However, when the user is already registered and I try to log in using OIDC (OIDC login flow), everything works fine: Kratos redirects to the consent endpoint of my IdP UI and the OAuth2 flow ends successfully. Actually, the return URL set in `selfservice.flows.login.after.oidc.default_browser_return_url` is not used at all.

As I see it, the OIDC registration flow should register the user and then behave the same way as the OIDC login flow, resuming the OAuth2 flow. Am I doing/understanding anything wrong?

I looked into Kratos code and I managed to find the cause of this problem. When an OIDC login flow finishes and the browser redirects to the Kratos callback URL (`/self-service/methods/oidc/callback/<provider>`):
1. It tries to get the identity.
2. Since it is the first time the user logs in using the external provider, the user doesn't exists, so it starts a new registration flow.
3. This registration flow doesn't include the `login_challenge` that was associated to the OIDC login flow, so the OAuth2 flow cannot finish.

This is the code that is ignoring the `login_challenge`:
https://github.com/ory/kratos/blob/7c14f29fa143006b9ce730615ff4ab499a7ff833/selfservice/strategy/oidc/strategy_login.go#L103-L108

The solution for my problem is to simply add the `login_challenge` to the new registration flow. Something like this:
```go
	if a.OAuth2LoginChallenge.Valid {
		opts = append(opts, registration.WithFlowOAuth2LoginChallenge(a.OAuth2LoginChallenge))
	}

	// This flow only works for browsers anyways.
	aa, err := s.d.RegistrationHandler().NewRegistrationFlow(w, r, flow.TypeBrowser, opts...)
```

I committed the changes to a forked repo (see [here](https://github.com/flusflas/kratos/commit/c8f7f2fdad30c97f23719cca140717084218825c)), but I wanted to know if any of this makes sense or I'm just doing anything wrong.

### Reproducing the bug

1. Set up an OIDC provider in Kratos config.
2. Run Kratos and Hydra.
3. Start an OAuth2 login flow (the browser will redirect to the IdP login page with a `login_challenge`).
4. Create a self-service login flow for browser with the `login_challenge`.
5. On the login page, click on a Social Login button (e.g. "Sign up with Google").
6. Login on the external provider login page and accept consent.
7. The browser redirects to `/self-service/methods/oidc/callback/<provider>`.
8. Kratos creates a new registration flow, ignoring the previous `login_challenge`.
9. Kratos creates the new identity successfully.
10. Kratos redirects to the default registration page configured with no parameters, and the OAuth2 flow that was started in (1) doesn't finish.

### Version

0.13.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

None

**Comment by jonas-jonas** [comment]
Hi! Thanks for the report. I created a PR to fix this by applying your changes, and just saw, that you also had a commit lined up. We did some changes to the types here, though, so your code would've needed some adjusting anyway.

Feel free to review the PR at https://github.com/ory/kratos/pull/3419 and provide feedback. Thanks!
