### ISSUE TITLE
Wrong ID UUID in after password hook

### ISSUE THREAD

**Issue by jbmolle** [ory/kratos#3340]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [x] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have a Jsonnet registration after password hook which was working fine in previous versions of Kratos.
I'm trying to send the user ID to a backend service and the jsonnet returns { authentication_id: ctx.identity.id }.
Now the ID returned is 00000000-0000-0000-0000-000000000000 for all the users.
The ID in the database is correct though.

I tried to dump the all ctx.identity object and I've found that recovery_addresses and verifiable_addresses also have an id 00000000-0000-0000-0000-000000000000 and created_at and updated_at are 0001-01-01T00:00:00Z

I'm using the docker image tagged v0.13.0

### Reproducing the bug

1. Run docker image v0.13.0
2. Create an registration after password hook with jsonnet returning ctx.identity.id
3. Send the after registration hook to a docker container with image mendhak/http-https-echo
4. The dump shows an identity ID of 00000000-0000-0000-0000-000000000000

### Relevant log output

```shell
"identity": {                                                                                                                                    
                "created_at": "0001-01-01T00:00:00Z", 
                "id": "00000000-0000-0000-0000-000000000000",                                                                                                
                "metadata_public": null,                                                                                                                     
                "recovery_addresses": [
                    {                                                                                                                                        
                        "created_at": "0001-01-01T00:00:00Z",                                                                                                
                        "id": "00000000-0000-0000-0000-000000000000",                                                                                        
                        "updated_at": "0001-01-01T00:00:00Z",                                                                                                
                        "value": "jbxxx@xxxx.com",                                                                                                        
                        "via": "email"                                                                                                                       
                    }                                                                                                                                        
                ],                                                                                                                                           
                "schema_id": "user-v0",                                                                                                                      
                "schema_url": "",                                                                                                                            
                "state": "active",                                                                                                                           
                "state_changed_at": "2023-06-22T11:17:11.271293525Z", 
                "traits": {                                                                                                                                  
                    "email": "jbxxx@xxxx.com"                                                                                                             
                },
                "updated_at": "0001-01-01T00:00:00Z",                                                                                                        
                "verifiable_addresses": [                                                                                                                    
                    {
                        "created_at": "0001-01-01T00:00:00Z",                                                                                                
                        "id": "00000000-0000-0000-0000-000000000000",                                                                                        
                        "status": "pending",                                                                                                                 
                        "updated_at": "0001-01-01T00:00:00Z",                                                                                                
                        "value": "jbmolle@gmail.com",                                                                                                        
                        "verified": false,                                                                                                                   
                        "via": "email"                                                                                                                       
                    }                                                                                                                                        
                ]                                                                                                                                            
            },
```

### Version

0.13.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by jbmolle** [comment]
I have the same bug with the quickstart:
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate

In quickstart.yml, I've added this:
```
  my-http-listener:
    image: mendhak/http-https-echo:30
    environment:
      - HTTP_PORT=8888
      - HTTPS_PORT=9999
    ports:
      - "8080:8888"
      - "8443:9999"
    networks:
      - intranet
```

And in contrib/quickstart/kratos/email-password/kratos.yml, I have this:
```
 flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://my-http-listener:8888
                method: POST
                body: base64://ZnVuY3Rpb24gKGN0eCkgeyB1c2VySWQ6IGN0eC5pZGVudGl0eS5pZCB9Cg==
                response:
                  ignore: false
                  parse: true
            - hook: session
            - hook: show_verification_ui
```

**Comment by aeneasr** [comment]
If can_interrupt = false and response.parse = false the identity ID should be available in the webhook

**Comment by alnr** [comment]
Hi @jbmolle.

You are correct, the behavior was changed in #3042.

If you want to pass the identity ID to a CMS, set `{ "response": { "parse": false } }`. That will make the hook run after the identity has been persisted to the database, and the UUID will be available in the jsonnet context.

I've created a new issue to track improvements to the webhook config: https://github.com/ory/kratos/issues/3352

**Comment by jbmolle** [comment]
Hi @aeneasr and @alnr 
Thanks a lot for your answer! That will solve our problem for the moment.
In our case we have a transient body with extra data to pass to the CMS. So with parse=false we could end up with a flow that creates the identity in the kratos database but an api call that fails in the CMS (for example if the CMS is down). 
In this case the transient body would be lost. I guess is the point 4 of #3352  -> maybe we have to think of a retry mechanism or so, just an idea...

**Comment by vladyslav2** [comment]
I think @jbmolle has a point. Whole reason to have `can_interrupt: true` is cause we want to have consistency between different databases

**Comment by alnr** [comment]
> I think @jbmolle has a point. Whole reason to have `can_interrupt: true` is cause we want to have consistency between different databases

If you write data to a CRM from an interrupting webhook, the request flow in Kratos can still fail for a variey of reasons after that. The change would then be in your CRM, but not in Kratos. In other words, this doesn't help with data consistency.

The only way to get guaranteed consistent data is to reconcile the data periodically afterwards.
