### ISSUE TITLE
feat: list call GET /admin/idenitities should return all fields

### ISSUE THREAD

**Issue by borisroman** [ory/kratos#3342]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The current implementation of the `/admin/identities` endpoint makes a selection on the fields returned. As an admin, I expect to access all fields associated with identities in a single request. The `/admin/identity/[uuid]` does return all fields for a single identity. Having to make a call for every identity to /admin/identity/[uuid] to retrieve the needed fields is cumbersome.

### Describe your ideal solution

The solution is to modify the /admin/identities endpoint to return all the fields associated with identities.

### Workarounds or alternatives

Do a list call first and then a call for every identity, imposing a heavy load on the system.

### Version

v0.13.0

**Comment by aeneasr** [comment]
What fields are missing in your mind?
