### ISSUE TITLE
Quickstart: configuration invalid

### ISSUE THREAD

**Issue by radekg** [ory/kratos#335]
**Describe the bug**

When starting with kratos using the default latest docker images, kratos complains that the `settings_ui` is an invalid property of `urls`. Looking at the configuration under https://www.ory.sh/kratos/docs/reference/configuration reveals that, indeed, `settings_ui` is invalid and `profile_ui` should be in there instead.

Relevant line: https://github.com/ory/kratos/blob/master/contrib/quickstart/kratos/email-password/.kratos.yml#L65

Additionally, the oathkeeper config from quickstart has to be modified: https://github.com/ory/kratos/blob/master/contrib/quickstart/oathkeeper/access-rules.yml#L47 to use `/profile` instead of `/settings`.

**Reproducing the bug**

```
docker-compose -f quickstart.yml up
```

*Server logs*

```
kratos_1                      | time="2020-04-11T19:54:28Z" level=fatal msg="The configuration is invalid and could not be loaded." config_key[1]=urls validation_error[1]="additionalProperties \"settings_ui\" not allowed"
```

*Server configuration*

Default quickstart configs.

**Comment by aeneasr** [comment]
Thank you! We should definitely add a git checkout to the guide, otherwise we're operating on master which is sometimes not in line with the most recent release! So basically:

```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.1.1-alpha.1
make quickstart
```
