### ISSUE TITLE
Google OIDC not containing the necessary cookie to resume session when using HTTP API

### ISSUE THREAD

**Issue by eddingston** [ory/kratos#3384]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am trying to set up Google social login in my Sveltekit Application using the Ory Kratos HTTP API. 

So far, I have been successful with setting up Registration, Login, and Logout flows. 

But now I am having troubles with the Google OIDC. 

I am able to get to the Google sign in page but when I choose my account, I get the following error:

`An error occurred with the following message: The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!`

It is unclear to me what I am missing. Vincent(ORY) has suggested that I need to include the CSRF cookie and the Ory Session cookie. In the other flows (Registration, Login, Logout), I passed the data in the `Set-Cookie` and the body of the HTTP request as `'Content-Type': 'application/json'`, but that does not seem to work for this situation.

I have a trimmed down version of the issue posted here:
- https://github.com/eddingston/ory-kratos-google-issue

The flow starts at https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/routes/%2Bpage.svelte. 
- This page is preloaded with the initial login flow data by going through the following path:
  - https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/routes/%2Bpage.ts - (SSR that loads the data after retrieving it from below)
  - https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/lib/auth/frontend/auth.ts - (Frontend HTTP request to the backend to workaround CORS issues with Ory Kratos Server) 
  - https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/routes/api/auth/login/%2Bserver.ts - (Backend handler for the HTTP request above which initializes the login flow and retrieves the form details through helper functions that make HTTP requests to the Ory Kratos Server)
  - https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/lib/auth/backend/auth.ts (Helper functions for the handler above)
  
 The above is what retrieves the CSRF cookie. I don't think a session is active at this point because we have no logged in with any users. 

Finally, at https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/routes/%2Bpage.svelte, if we click the 'Sign in with Google' button, it will run the handler above in the same file. This will make a call to https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/routes/api/auth/google/%2Bserver.ts, which returns a redirection url. 

The frontend should now be redirected to the Google sign in page. If we pick an account it will show the error. 
- `An error occurred with the following message: The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!`
 
 
 Thank you for your time! I look forward to hearing from the Ory team!

### Reproducing the bug

EDIT: At the time of editing this, it is required to add `127.0.0.1	edd-test.com` to `/etc/hosts` for the app to work. 

1. `git clone git@github.com:eddingston/ory-kratos-google-issue.git`
2. `cd ory-kratos-google-issue`
3. Open up the `kratos.yml` and make sure that a valid Google client_id and client_secret has been set.
3. `cd kratos && docker-compose up -d`
4. `cd .. && npm install && npm run dev`
5. Go to ~~http://localhost:5173/~~ http://edd-test.com:5173
6. Click the 'Sign in with Google' button
7. You should have been redirected to the Google sign in page. Please login/select an account. 
8. You should now see the error. 

### Relevant log output

```shell
An error occurred with the following message: The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!
```

### Relevant configuration

```yml
Ory Kratos Server Configs:
https://github.com/eddingston/ory-kratos-google-issue/tree/master/kratos
```

### Version

oryd/kratos:v0.13.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by mooijtech** [comment]
References https://github.com/ory/kratos/discussions/3074

**Comment by mooijtech** [comment]
Please make sure to use `localhost` since for cookies this is not the same as `127.0.0.1`.
Cookies will not work on `localhost`, you will have to map a domain (`/etc/hosts` on Linux).

If the message is saying `Token is expired` make sure your system clock is up-to-date.

**Comment by eddingston** [comment]
Thanks @mooijtech for your response. 

Are you referring to my `kratos.yml`? That is the only place in the example where I have `127.0.0.1`. I changed all of these to `localhost` and it still produced the same error.
- `An error occurred with the following message: The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!`

I also was able to get the Registration, Login, and Logout flow working with this `localhost` and `127.0.0.1` combination. 

I appreciate your input and I have updated all `127.0.0.1` to `localhost`. However, I believe the issue may be related to the redirection to the Google sign in page due to the changing of domains. I no longer see the cookie in my browser storage. I think I may be losing the cookie at this point. Or perhaps my flow is not passing the CSRF cookie correctly. 

- Could @vinckr or someone experienced please take a look at https://github.com/eddingston/ory-kratos-google-issue/blob/master/src/routes/api/auth/google/%2Bserver.ts to see if I am passing the required parameters properly? I couldn't find documentation on how to use the `/self-service/login` with a provider (https://www.ory.sh/docs/kratos/reference/api#tag/frontend/operation/createBrowserLoginFlow) or how to pass parameters to it properly. 
  - I know we need the flow id. Currently I am using the flow id that I originally retrieved `self-service/login/browser`. Is this the right one to use or do I need to initiate another flow specifically for OIDC?
  - I assume we need to send a CSRF cookie but I am not sure on how to properly pass this through. 
  
Thank you all for your time.

**Comment by mooijtech** [comment]
`localhost` does not allow cookies, can you try map to a domain via `/etc/hosts` on Linux?

**Comment by eddingston** [comment]
Thanks for your response @mooijtech. That slipped my mind earlier, however I tried it now and it seems to fail.

The issue now is due to Google's OAuth 2.0 policy requirements. Mapping `127.0.0.1` to `test.local` fails because:
- `Invalid Redirect: must end with a public top-level domain (such as .com or .org).`
- `Invalid Redirect: must use a domain that is a valid [top private domain ](https://github.com/google/guava/wiki/InternetDomainNameExplained#public-suffixes-and-private-domains).`

To quickly hack around this I tried mapping `127.0.0.1` to `edd-test.com`. Google was willing to accept this redirect URL (http://edd-test.local:4433/self-service/methods/oidc/callback/google). But in the end, I still got the error: `An error occurred with the following message: The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!`. 

@mooijtech Do you think that this experiment is enough to conclude that the issue is not with the `localhost` domain or should I deploy this properly to a public address before I conclude this? 

Thank you for your time.

**Comment by eddingston** [comment]
Thanks for your response @mooijtech. That slipped my mind earlier, however I tried it now and it seems to fail.

The issue now is due to Google's OAuth 2.0 policy requirements. Mapping `127.0.0.1` to `test.local` fails because:
- `Invalid Redirect: must end with a public top-level domain (such as .com or .org).`
- `Invalid Redirect: must use a domain that is a valid [top private domain ](https://github.com/google/guava/wiki/InternetDomainNameExplained#public-suffixes-and-private-domains).`

To quickly hack around this I tried mapping `127.0.0.1` to `edd-test.com`. Google was willing to accept this redirect URL (http://edd-test.com:4433/self-service/methods/oidc/callback/google). But in the end, I still got the error: `An error occurred with the following message: The browser does not contain the necessary cookie to resume the session. This is a security violation and was blocked. Please clear your browser's cookies and cache and try again!`. 

@mooijtech Do you think that this experiment is enough to conclude that the issue is not with the `localhost` domain or should I deploy this properly to a public address before I conclude this? 

Thank you for your time.

**Comment by aeneasr** [comment]
Hi @eddingston - you ticked "This issue affects my [Ory Network](https://www.ory.sh/) project." - can you please share the URL with us so we can reproduce?

**Comment by eddingston** [comment]
Hello @aeneasr, I assumed that "This issue affects my [Ory Network](https://www.ory.sh/) project." meant "This issue affects my project which uses an Ory product." since it the hyperlink just brought me to the Ory homepage. 

The steps to reproduce are listed in the ticket. Would it be easier for you to investigate if I were to get this deployed to a public URL? 

Thanks!

**Comment by mooijtech** [comment]
Consider running [Caddy](https://caddyserver.com/) (or NGINX) so you have HTTPS locally, possibly cookies are being rejected on HTTP.
`Caddyfile`:
```
auth.example.com:443 {
        reverse_proxy localhost:4433
        tls internal
}

auth-admin.example.com:443 {
        reverse_proxy localhost:4434
        tls internal
}

example.com:443 {
        reverse_proxy localhost:3000
        tls internal
}
```

**Comment by tomcastro** [comment]
@eddingston I am getting the same issue all of a sudden on a NextJS project with Ory Network (so no self-hosted in my case). It happens on both Apple and Google Oauth flows.

On the Ory Network welcome page, I can login successfully, but I cannot do this on a NextJS website either by using localhost, 127.0.0.1 or a custom domain as @mooijtech pointed out.

@aeneasr I set up an Ory Network [project](https://modest-zhukovsky-l9yv1b7haw.projects.oryapis.com) that can reproduce this with Google sign in. It works when using username and password, but not with Google. Again, I'm using the base code in this [example](https://github.com/ory/docs/tree/master/code-examples/protect-page-login/nextjs)

**Comment by tomcastro** [comment]
@mooijtech just tried with Caddy and correctly have an HTTPS domain, but I get the same error when logging in through any OIDC provider.

<img width="605" alt="image" src="https://github.com/ory/kratos/assets/9694556/88ef96f9-f88b-4127-98c0-1f48de42749b">

<img width="472" alt="image" src="https://github.com/ory/kratos/assets/9694556/c3980de1-2dd0-4f92-8a4f-9e3b53aebb68">

**Comment by viiicky** [comment]
> @eddingston I am getting the same issue all of a sudden on a NextJS project with Ory Network (so no self-hosted in my case). It happens on both Apple and Google Oauth flows.
> 
> On the Ory Network welcome page, I can login successfully, but I cannot do this on a NextJS website either by using localhost, 127.0.0.1 or a custom domain as @mooijtech pointed out.
> 
> <img alt="image" width="511" src="https://user-images.githubusercontent.com/9694556/257554508-f20b3809-4a66-4449-a387-10912460911c.png">
> @aeneasr I set up an Ory Network [project](https://modest-zhukovsky-l9yv1b7haw.projects.oryapis.com) that can reproduce this with Google sign in. It works when using username and password, but not with Google. Again, I'm using the base code in this [example](https://github.com/ory/docs/tree/master/code-examples/protect-page-login/nextjs)

did you get this working @tomcastro  I am facing the exact same issue.

**Comment by viiicky** [comment]
> > @eddingston I am getting the same issue all of a sudden on a NextJS project with Ory Network (so no self-hosted in my case). It happens on both Apple and Google Oauth flows.
> > On the Ory Network welcome page, I can login successfully, but I cannot do this on a NextJS website either by using localhost, 127.0.0.1 or a custom domain as @mooijtech pointed out.
> > <img alt="image" width="511" src="https://user-images.githubusercontent.com/9694556/257554508-f20b3809-4a66-4449-a387-10912460911c.png">
> > @aeneasr I set up an Ory Network [project](https://modest-zhukovsky-l9yv1b7haw.projects.oryapis.com) that can reproduce this with Google sign in. It works when using username and password, but not with Google. Again, I'm using the base code in this [example](https://github.com/ory/docs/tree/master/code-examples/protect-page-login/nextjs)
> 
> did you get this working @tomcastro I am facing the exact same issue.

okay, I was finally able to fix it - okay, I was able to fix it. I had to set `first_name` and `last_name` fields in my Identity Schema in order for the data returned from Google to be mapped in correctly.
