### ISSUE TITLE
i have a query regarding integration of ory kratos with my gui (other than the self service gui image) using ory python sdk  in self hosting environment, i am stuck on implementing it .Can you please help me or provide any reference,it would be a great help!

### ISSUE THREAD

**Issue by Ankit-Mandloi47b** [ory/kratos#3403]
i have a query regarding integration of ory kratos with my gui (other than the self service gui image) using ory python sdk  in self hosting environment, i am stuck on implementing it .Can you please help me or provide any reference,it would be a great help!

_Originally posted by @Ankit-Mandloi47b in https://github.com/ory/kratos/discussions/3402_

**Comment by aeneasr** [comment]
https://github.com/ory/examples/discussions/79
