### ISSUE TITLE
Disable email verification for OIDC

### ISSUE THREAD

**Issue by renom** [ory/kratos#3410]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

OIDC registrations require email verification if it's enabled in kratos.yml, since it can only be enabled for all auth methods, but we need a configuration to have email verification enabled only for email/password registrations.

### Describe your ideal solution

An option to auto set up `"verified": true` for an email address after OIDC registration (sending a verification code should be skipped for OIDC when the option is enabled).

### Workarounds or alternatives

-

### Version

v1.0.0

**Comment by mooijtech** [comment]
References https://github.com/ory/kratos/issues/1057

**Comment by Sytten** [comment]
Can close this @aeneasr
