### ISSUE TITLE
docs: bring settings docs up to speed with recent developments

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#345]
- [ ] Document profile strategy
- [ ] Document password strategy
- [ ] Document return_to policy
- [ ] Document privileged fields
- [ ] Document missing account enumeration prevention

**Comment by juliandroid** [comment]
Documentation at https://www.ory.sh/kratos/docs/reference/configuration seems a bit funny. Not sure whether that was intended, but all other configuration examples looked realistic while in the configuration above looks like:

```
default_schema_url: http://WBwVKWvcJYnRFLOpuTSaootvh.bwCxwHzemclRM,p2bR9wN.avr4J5iwFryiF

    schemas:
      - 59663280.313260764
      - true
      - elit
      - null
      - true
```

**Comment by frederikhors** [comment]
@juliandroid https://www.ory.sh/kratos/docs/next/reference/configuration

**Comment by juliandroid** [comment]
Ah, that so sad. I've spent days reading the doc and I have no idea how and when I was redirected to 0.1 version, nor way to select one or another.

**Comment by aeneasr** [comment]
Next is the master version - so not released yet!

**Comment by juliandroid** [comment]
That makes sense :)
However the full example of the configuration still looks strange and confusing:
```
identity:
  traits:
    default_schema_url: http://Kgcg.lghebwppFC+TYRjCxC8
    schemas:
      - 63705193
      - -97849322
      - 36726392
```
The URL or the schemas names looks like randomly generated like using fakeit or other mock :)

**Comment by aeneasr** [comment]
> The URL or the schemas names looks like randomly generated, like using fakeit or other mock :)

That's exactly what's happening. They don't have proper example values yet - if you want to contribute those that would be super helpful! This particular example is generated from here: https://github.com/ory/kratos/blob/master/.schema/config.schema.json#L556
