### ISSUE TITLE
If a user only has an oidc provider as active first factor credential, an disabled unlink node should be send

### ISSUE THREAD

**Issue by simon-wirths-uninow** [ory/kratos#3485]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

If a user only has an oidc provider as active first factor credential you get absolutely no feedback why you can not unlink your social account. This is really confusing for the user.

### Describe your ideal solution

When the settings flow checks if there is more then one first factor credential for a user, it could also check if its a linked social account if there is only one. It the should create a disabled unlink node maybe with a message why unlinking is not possible at the moment.

### Workarounds or alternatives

an alternative would be to check separately with kratos if the user has an linked account and then show a disabled button without a ui node. also you could show a hint all the time that you need to set a password to unlink.

### Version

1.0.0

**Comment by alnr** [comment]
I think that would be a useful improvement.
