### ISSUE TITLE
`PostRegistration` fails without network connection

### ISSUE THREAD

**Issue by cswaney** [ory/kratos#3491]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I'm trying to run Kratos on an air-gapped system. While testing the `quickstart.yml` I discovered that the registration self-service flow appears to fail. Upon inspection, I discovered that the user is in fact added to the database and can subsequently login. However, an error occurs after `PostRegistrationPrePersistHooks`, which prevents Kratos from returning a response. According to the logs (see below), Kratos thinks that the new user already exists.

### Reproducing the bug

Turn off your network connection and follow the Kratos quickstart example: https://www.ory.sh/docs/kratos/quickstart.

### Relevant log output

```shell
kratos-kratos-1                      | time=2023-08-25T01:07:17Z level=info msg=started handling request ...
kratos-kratos-1                      | time=2023-08-25T01:07:32Z level=debug msg=Running PostRegistrationPrePersistHooks ...
kratos-kratos-1                      | time=2023-08-25T01:07:32Z level=info msg=Encountered self-service flow error ... an account with the same identifier (email, phone, username, ...) exists already stack_trace:
```

### Version

0.13.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
Airgapped systems are out of scope. Furthermore it looks like registration fails because the user already exists.
