### ISSUE TITLE
Migration failed with CockroachDB version > v21.0.0

### ISSUE THREAD

**Issue by vivianlii** [ory/kratos#3502]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It cannot drop index `session_devices.unique_session_device` when running `kratos migrate sql` cmd.

CockroachDB version: v23.1.9

Error logs:
```
Error: error executing migrations/sql/20230216142104000000_session_devices_index_drop.up.sql, sql: DROP INDEX IF EXISTS session_devices.unique_session_device;
: ERROR: target database or schema does not exist (SQLSTATE 3F000)
Usage:
  kratos migrate sql <database-url> [flags]

Flags:
  -c, --config strings   Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
  -h, --help             help for sql
  -e, --read-from-env    If set, reads the database connection string from the environment variable DSN or config file key dsn.
  -y, --yes              If set all confirmation requests are accepted without user interaction.

error executing migrations/sql/20230216142104000000_session_devices_index_drop.up.sql, sql: DROP INDEX IF EXISTS session_devices.unique_session_device;
: ERROR: target database or schema does not exist (SQLSTATE 3F000) 
```

It can run successfully if using CockroachDB version <= v21.2.17

### Reproducing the bug

docker compose file

```yaml
version: "3.9"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.9
    ports:
      - "26257:26257"
      - "8888:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data:cached
    networks:
      - default
    command: start-single-node --http-addr=localhost:8080 --insecure

  kratos-migrate:
    depends_on:
      - "cockroachdb"
    image: oryd/kratos:v0.13.0
    environment:
      LOG_LEVEL: trace
      DSN: postgres://root@cockroachdb.local:26257/local-ory-kratos?sslmode=disable
    volumes:
      - ./test/config:/home/ory:cached
    networks:
      - default
    command: migrate sql -e --yes -c /home/ory/kratos.yaml

volumes:
  go-mod-cache:
  cockroach-data:
networks:
  default:
    name: local
```

Steps:
1. run `docker-compose up -d cockroachdb`
2. create db `docker-compose exec cockroachdb cockroach sql --url postgresql://root@localhost:26257/defaultdb --insecure --execute "CREATE DATABASE \"local-ory-kratos\";" || exit 0`
3. run migrate `docker-compose up kratos-migrate`

Repeat the steps by downgrade the cockroachdb image to v21.2.17, it will migrate successfully.

### Version

v0.13.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by chris-ruecker** [comment]
I am running into the same issue, but i am using Cockroach serverless, so i cannot downgrade cockroach.

I noticed, you are using the prostgresql:// driver, i did the same. I am wondering if not using the cockroach:// driver caused the issue. 

Did you move forward after downgrading, or did you find another solution?

**Comment by PetrSilar** [comment]
I ran into the same issue. I can confirm using `cockroach://` works well for the database migration.
On the other hand `kratos serve` does not even connect to the database server with `cockroach://` while `postgres://` works without a problem.

**Comment by aeneasr** [comment]
Hello, please use `cockroach://` as the scheme in the DSN. If you use `postgres`, then the Postgres migrations will be executed, which fail on Cockroach.

https://www.ory.sh/docs/self-hosted/deployment

It is not true that `cockroach://` doesn't work with `kratos serve`, given that end to end tests as well as our production system use this prefix.

**Comment by PetrSilar** [comment]
> Hello, please use `cockroach://` as the scheme in the DSN. If you use `postgres`, then the Postgres migrations will be executed, which fail on Cockroach.
> 
> https://www.ory.sh/docs/self-hosted/deployment
> 
> It is not true that `cockroach://` doesn't work with `kratos serve`, given that end to end tests as well as our production system use this prefix.

My bad, I apologize.
I saw "could not open database connection: failed to connect to..." in the logs when `cockroach://` was used but not when `postgres://` was used and I didn't check further. It's actually timing issue with *istio* proxy sidecar.

**Comment by plokhotnyuk** [comment]
I have a migration failure when starting Ory Kratos v1.1.0 with Cockroach DB v23.1.9 (the same version as in the description of this issue), `cockroach://` as the scheme, and the following SQL for creation of database with user:
```sql
CREATE DATABASE kratos;
CREATE USER kratos;
GRANT ALL ON DATABASE kratos to kratos;
```

Bellow is an error message:
```txt
Error: error executing migrations/sql/20191100000010000002_errors.cockroach.up.sql, sql: UPDATE "selfservice_errors" SET "seen_at" = "_seen_at_tmp";: ERROR: column "_seen_at_tmp" does not exist (SQLSTATE 42703)
Usage:
  kratos migrate sql <database-url> [flags]

Flags:
  -c, --config strings   Path to one or more .json, .yaml, .yml, .toml config files. Values are loaded in the order provided, meaning that the last config file overwrites values from the previous config file.
  -h, --help             help for sql
  -e, --read-from-env    If set, reads the database connection string from the environment variable DSN or config file key dsn.
  -y, --yes              If set all confirmation requests are accepted without user interaction.

error executing migrations/sql/20191100000010000002_errors.cockroach.up.sql, sql: UPDATE "selfservice_errors" SET "seen_at" = "_seen_at_tmp";: ERROR: column "_seen_at_tmp" does not exist (SQLSTATE 42703)
```

Have I made something wrong?

Thanks in advance!

I will try to find the latest version of Cockroach DB that will complete migrations successfully...
