### ISSUE TITLE
docs: clarify required variables for starting Kratos

### ISSUE THREAD

**Issue by tomascharad** [ory/kratos#352]
**Describe the bug**

When I pull the image from Docker Hub and try to run it, it asks me to include the file

**Reproducing the bug**

_Server logs_

_Server configuration_

**Expected behavior**

It should run by itself, as stated in docs: https://www.ory.sh/kratos/docs/reference/configuration.
"If file $HOME/.kratos.yaml exists, it will be used as a configuration file which supports all configuration settings listed below."

By saying 'If file exists' it shouldn't be required.

**Environment**

- Version: 16-04-2020 latest version
- Environment: Docker

**Additional context**

I'm running the instance on heroku, do you know how could I make it run without making any modifications to the original image?

**Comment by aeneasr** [comment]
Could you please provide the server logs? I am asking because it is possible to run Kratos without a configuration file, but you still need to provide the required configuration values.

> I'm running the instance on heroku, do you know how could I make it run without making any modifications to the original image?

Heroku will probably not be sufficient as it does not have (afaik) the ability to expose a port only on an internal / privileged network or alternatively with a security system in front, which is required for ORY Kratos' Admin API Port.

**Comment by tomascharad** [comment]
Ok with heroku, I''ll try another service, If i run this on my local computer I get this.

![image](https://user-images.githubusercontent.com/1534092/79570778-0ff76300-8088-11ea-9980-ba23b78679dd.png)

**Comment by aeneasr** [comment]
Perfect! I'll be closing this then, yes?

**Comment by tomascharad** [comment]
Hi @aeneasr,

I think that at least you should update the docs, so people understand that tweaking the .kratos.yaml is a must, or at least setting up the ENV variables, which is not very clear on the docs and how to do so.

But for me everything is ok. Thanks.

**Comment by aeneasr** [comment]
Yup, makes sense!

**Comment by tomascharad** [comment]
If it helps

```bash

COURIER_SMTP_CONNECTION_URI
smtps://foo:bar@my-mailserver:1234/
 
DATABASE_URL
postgres://xxx:yyy@zzz:ttt/uuu
 
HASHERS_ARGON2_MEMORY
11883317
 
IDENTITY_TRAITS_DEFAULT_SCHEMA_URL
http://WBwVKWvcJYnRFLOpuTSaootvh.bwCxwHzemclRM,p2bR9wN.avr4J5iwFryiF
 
SELFSERVICE_LOGOUT_REDIRECT_TO
http://TPNXSkIbeASVeSLyyRTbVjdkX.ygfeQk8llwnWZ+NeenrZJJHgd8BAoqaQ5iHO9BW-DeqlXBuYKVlL0ijQpJw9Q
 
HASHERS_ARGON2_ITERATIONS
21236220
 
HASHERS_ARGON2_PARALLELISM
71551855
 
HASHERS_ARGON2_SALT_LENGTH
80719037
 
HASHERS_ARGON2_KEY_LENGTH
86477135
 
URLS_PROFILE_UI
http://BMvdJD.oumrvPl+.YTtiPL6I21HYzlRsoTW-Dd1-lDUCJltAHcth.+eggbpCfQvWY.YSS3i
 
URLS_MFA_UI
http://jJAIvAwZyxLFzQjBYtcGhLGuzwudpru.dbF.OeGVZf-fC
 
URLS_LOGIN_UI
http://bC.dsmw,wLBWDeODw.jzOSI
 
URLS_REGISTRATION_UI
http://aFuZJoeUxZWbuTpHLFZvK.gxlPs3in99K,qmGgreVGQFtdAJbjtOmf4,oaXujXoOfC9
 
URLS_ERROR_UI
http://XyOnfsMVwIYMBlWKnkCPLOEjjM.czcUWzDof8Yf3EfshOx2zlNKWInKZLdpwX6P+UoqMabq6j7wR2Wpgx+zXrxhS34dr
 
URLS_VERIFY_UI
https://AFOEiEYuMWbJuHEggEbQ.pfQWlSMyPl,,pcK80YpSmfTu4+8fJfb9nsteihlmuak
 
URLS_DEFAULT_RETURN_TO
http://zkQAiAiiIYb.ccihU+5ATPZJD2Pw8g,BV1p3ttrEDUdvY1.smb0rA
 
DSN
postgres://dondccvxgrctty:857be4b67deea80af2c89e2592c1090bf370648e6c6685361cd5d28cdfc05efa@ec2-54-197-34-207.compute-1.amazonaws.com:5432/d4csiqpevk8dq8
 
URLS_SELF_PUBLIC
https://soaSpPGphWtHdGE.jnisR2qXIxFM6sRpbYF6B9pd1FBsbPIWBKPsXHYbqlRhdmG0xq.pO0IJ4m
 
URLS_SELF_ADMIN
http://AW.pbumgzDhx3hSJ+clKU7Oe,amEjmmbm1Ru2yMg0k6kV7cdSKDcPsn1QYXOVUB1071goU
 
URLS_WHITELISTED_RETURN_TO_DOMAINS
http://CTLQXiigUbkVwraZAOiDopaD.lzwMQNslH,m2aPn
 
```
