### ISSUE TITLE
Session data in webhooks payload

### ISSUE THREAD

**Issue by stcherenkov** [ory/kratos#3548]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to send users security notifications on successful login containing useful information – basically, IP address, location and user agent. The session object is not included in the webhook payload, but there are Cloudflare headers.

### Describe your ideal solution

Would be great  to have session data passed to the after-login webhook (and probably some other webhooks to, like login, registration and settings changes), so we would rely on internal implementation, rather than external headers.

### Workarounds or alternatives

Cloudflare headers.

### Version

Network

### Additional Context

Slack thread: https://ory-community.slack.com/archives/C05PHQCFL1F/p1695824213274279

**Comment by aeneasr** [comment]
I believe thisbisbdone
