### ISSUE TITLE
list identities API `page_token` paramter has incorrect default

### ISSUE THREAD

**Issue by Benehiko** [ory/kratos#3593]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The `page_token` parameter has an API definition that it is of type number and has a default value of 1. 
https://github.com/ory/x/blob/master/pagination/migrationpagination/header.go#L54-L57

This breaks SDKs that do not specify the parameter since the default value is used which returns a 500 response from Kratos.

### Reproducing the bug

Use the SDK to list identities.
SDKs that do not omit values that aren't specified will error with response code 500. It seems in this case PHP is affected.

### Version

latest

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

Ory Network

**Comment by aeneasr** [comment]
This is solved by token pagination

**Comment by taisph** [comment]
Using the PHP SDK the page_token query parameter is added automatically causing Kratos 1.1.0 to return error 500. Works without the parameter.

Possibly related?

cURL example with URL as generated by PHP SDK:
```shell
curl -s 'http://localhost:4434/admin/identities?per_page=250&page_size=250&page_token=1&credentials_identifier=me%40example.com'
```

Result:
```json
{"error":{"code":500,"status":"Internal Server Error","message":"unable to fetch records: ERROR: error in argument for $2: could not parse \"1\" as type uuid: could not parse \"1\" as type uuid: uuid: incorrect UUID length: 1 (SQLSTATE 22P02)"}}
```
