### ISSUE TITLE
Unable to unlink OIDC credential even if a second one is available

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#3604]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When trying to unlink an OIDC credential of an identity with multiple, you get this error:

> "Cannot unlink OpenID Connect connection because it is the last remaining first factor credential."

### Reproducing the bug

1. create an identity with two or more OIDC credentials (but no other credential type)
2. try to unlinke one of them
3. see the incorrect error

### Version

master

**Comment by zepatrik** [comment]
Actually, tried to reproduce it again and it worked as expected.

**Comment by oleorhagen** [comment]
Actually, @zepatrik . I am trying to do this.

But I am not able to figure out how you unlink your account. Is it possible to do through `Kratos`?
