### ISSUE TITLE
Allow usage of breached passwords on users own risk.

### ISSUE THREAD

**Issue by torepettersen** [ory/kratos#361]
**Is your feature request related to a problem? Please describe.**

I want to use Kratos on a side project where security is not a high priority. The password validation is quite strong, so I am afraid I will lose lazy users that are not capable of coming up with secure passwords.

**Describe the solution you'd like**

I would like to give the users a choice to use a password that has been part of a data breach on their own risks. This could be achieved by adding a query parameter to the registration endpoint. E.g. `allowBreachedPassword`.

Maybe also save the information in the database to see which users are using an insecure password.

**Describe alternatives you've considered**

Doing some deeper research to check if my concerns are valid.

**Comment by aeneasr** [comment]
> I would like to give the users a choice to use a password that has been part of a data breach on their own risks. 

No, that is very bad practice. This will not be implemented, sorry!

**Comment by torepettersen** [comment]
I totally agree with it being bad practice, but it is sadly still more common to not do any password validation like this. Actually, I have never seen any website that has done this kind of validation before.

I looked through some of the issues and passwordless login https://github.com/ory/kratos/issues/286 seems like a better alternative for users that can't come up with secure passwords.

So no reason to keep this issue open then.

**Comment by aeneasr** [comment]
> I totally agree with it being bad practice, but it is sadly still more common to not do any password validation like this. Actually, I have never seen any website that has done this kind of validation before.

The point of ORY Kratos is to have the best security practice. This policy is actually encouraged by NIST and others, including Microsoft and several security researchers!

You can offer login with a social provider (e.g. Google) which usually increases conversion rates.
