### ISSUE TITLE
12 Dropped Errors in 'x' Dependency

### ISSUE THREAD

**Issue by alrs** [ory/kratos#3614]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

There is a block of 12 dropped `err` variables in the `github.com/ory/x/decoderx` dependency.

This affects the following parts of `kratos`:

`identity`
`selfservice/strategy/password`
`selfservice/strategy/code`
`selfservice/strategy/totp`
`selfservice/strategy/lookup`
`selfservice/strategy/webauthn`
`selfservice/strategy/oidc`
`selfservice/strategy/link`
`selfservice/strategy/profile`
`selfservice/flow/login`
`selfservice/flow`
`session`
`ui/container`

There is a PR to fix this issue in the `x` repo: https://github.com/ory/x/pull/741

### Reproducing the bug

.

### Version

.

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by jonas-jonas** [comment]
Thanks for fixing this.

Closed via https://github.com/ory/x/pull/741
