### ISSUE TITLE
Kratos `GET /self-service/registration/api`  returns a Json object which does not meet the spec - an obligatory field `state` field is missing.

### ISSUE THREAD

**Issue by kamilkloch** [ory/kratos#3647]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Kratos `GET /self-service/registration/api`  returns a Json object which does not meet the spec - an obligatory field `state` field is missing.

Spec: https://www.ory.sh/docs/reference/api#tag/frontend/operation/createNativeRegistrationFlow

### Reproducing the bug

`curl http://localhost:4433/self-service/registration/api`

### Version

1.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by kamilkloch** [comment]
@jonas-jonas Thank you for checking.

I am running kratos in the docker container as follows:
```yaml
kratos:
    container_name: kratos
    image: oryd/kratos:v1.0.0
    environment:
      DSN: "postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"
      ....
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      ...
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
```

`state` is missing in the response:

```
$ curl http://ls15:4433/self-service/registration/api

{
  "id": "3f38da45-d64b-46da-83ab-4893f2cb2785",
  "type": "api",
  "expires_at": "2023-12-01T22:10:25.358840052Z",
  "issued_at": "2023-12-01T22:00:25.358840052Z",
  "request_url": "http://ls15:4433/self-service/registration/api",
  "ui": {
    "action": "https://ls15.<...>/self-service/registration?flow=3f38da45-d64b-46da-83ab-4893f2cb2785",
    "method": "POST",
    "nodes": [
      {
        "type": "input",
        "group": "default",
        "attributes": {
          "name": "csrf_token",
          "type": "hidden",
          "value": "",
          "required": true,
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {}
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "traits.email",
          "type": "email",
          "required": true,
          "autocomplete": "email",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1070002,
            "text": "E-Mail",
            "type": "info"
          }
        }
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "password",
          "type": "password",
          "required": true,
          "autocomplete": "new-password",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1070001,
            "text": "Password",
            "type": "info"
          }
        }
      },
      {
        "type": "input",
        "group": "password",
        "attributes": {
          "name": "method",
          "type": "submit",
          "value": "password",
          "disabled": false,
          "node_type": "input"
        },
        "messages": [],
        "meta": {
          "label": {
            "id": 1040001,
            "text": "Sign up",
            "type": "info",
            "context": {}
          }
        }
      }
    ]
  }
}
```

**Comment by kamilkloch** [comment]
@jonas-jonas I cannot find a way to re-open, should I create a new ticket? Please let me know hot to reproduce your env. Thank you.

**Comment by jonas-jonas** [comment]
I see. I tested this against the Ory Network, which is already running an up-to-date version. Seems like this might be a bug in Kratos v1.0.0. Could you try latest master?

**Comment by kamilkloch** [comment]
Not sure how to run in it easliy without the Docker images. Could you perhaps cut the new release into Docker Hub?

**Comment by TimVosch** [comment]
@jonas-jonas Same issue here with v1 and latest tags from docker hub. I built the image myself from this repository and the issue was solved. Built using:

`docker build -f .docker/Dockerfile-build -t oryd/kratos:latest .`

Seems like the docker images are "outdated" or the client-go is "too new".
