### ISSUE TITLE
Docker: additionalProperties "use_continue_with_transitions" not allowed

### ISSUE THREAD

**Issue by abdulhadiayaz** [ory/kratos#3648]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I have been using ORY Kratos successfully for a couple of weeks, but today, after pulling the latest changes from the origin and attempting to run ORY Kratos on Docker, I encountered an issue preventing successful execution. The error identified in the logs is as follows:

`The configuration contains values or keys which are invalid: feature_flags: map[cacheable_sessions:false use_continue_with_transitions:true] additionalProperties "use_continue_with_transitions" not allowed`

To resolve this issue, I had to remove the following configuration block from `contrib/quickstart/kratos/email-password/kratos.yml`:
```
 feature_flags:
   use_continue_with_transitions: true
```
from `contrib/quickstart/kratos/email-password/kratos.yml`

This modification allowed me to overcome the problem and successfully run ORY Kratos on Docker.

Best regards,

### Reproducing the bug

1- Pull latest code
2- Run docker compose

Kratos crashes and keeps on restarting forever.

### Relevant log output

```shell
`The configuration contains values or keys which are invalid: feature_flags: map[cacheable_sessions:false use_continue_with_transitions:true] additionalProperties "use_continue_with_transitions" not allowed`
```

### Relevant configuration

```yml
feature_flags:
  use_continue_with_transitions: true
```

### Version

master branch

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

**Comment by jonas-jonas** [comment]
Please checkout the v1.0 tag: 

```sh
$ git checkout v1.0.0
```
