### ISSUE TITLE
Tokenize fail for valid session

### ISSUE THREAD

**Issue by tetra12** [ory/kratos#3685]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I tried to tokenize my kratos session following the [doc](https://www.ory.sh/docs/identities/session-to-jwt-cors). I did exactly what is written and tried both URL and base64 for `jwks_url`. I also tried default and custom claims as specified in your docs.

Getting http 400 `bad request` for my call. See details below

### Reproducing the bug

1. Config kratos tokenizer:
```yaml
session:
  whoami:
    tokenizer:
      templates:
        jwt_tmpl_1:
          jwks_url: http://192.168.1.93:4444/.well-known/jwks.json
          # jwks_url: "base64://eyJrZXl..."
          # claims_mapper_url: "base64://..."
          ttl: 1m # 1 minute (defaults to 10 minutes)
```
```sh 
> http -v 192.168.1.93:4433/sessions/whoami 'Cookie:ory_kratos_session="MTcwND..."' tokenize_as==jwt_tmpl_1               
GET /sessions/whoami?tokenize_as=jwt_tmpl_1 HTTP/1.1
Accept: */*                                                                           
Accept-Encoding: gzip, deflate, br
Connection: keep-alive        
Cookie: ory_kratos_session="MTcwND..."
Host: 192.168.1.93:4433
User-Agent: HTTPie/2.6.0                                                                                      
                                                                                      
HTTP/1.1 400 Bad Request       
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Length: 158
Content-Type: application/json
Date: Mon, 08 Jan 2024 12:38:46 GMT
Vary: Origin, Cookie                                                                                                                                                         

{
    "error": {
        "code": 400,
        "message": "The request was malformed or contained invalid parameters",
        "reason": "Unable to sign JSON Web Token.",
        "status": "Bad Request"
    }
}
```

### Relevant log output
Running the same req without tokenization returns 200:
```sh
HTTP/1.1 200 OK                                                                       
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Length: 1460          
Content-Type: application/json; charset=utf-8
Date: Mon, 08 Jan 2024 12:49:51 GMT
Vary: Origin, Cookie           
X-Kratos-Authenticated-Identity-Id: aed89977-dea1-4e30-a2df-63635fc46d64
                                           
{                                                                                     
    "active": true,
    "authenticated_at": "2024-01-08T12:36:54.2236Z",
    "authentication_methods": [
        {                            
            "aal": "aal1",
            "completed_at": "2024-01-08T12:36:54.223596657Z",
            "method": "password"                                                      
        }                        
    ],       
    "authenticator_assurance_level": "aal1",                
...
```

### Version

1.0.0 - latest master

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

### Additional Context

I built my own docker image as of Dec 30 2023

**Comment by ykhedar** [comment]
I had a similar issue and it turned out it had something to do with the JWKS key. So i generated a new signing key using the oathkeeper cli as shown here: https://www.ory.sh/docs/oathkeeper/cli/oathkeeper-credentials-generate and then base64 encoded and directly copied to the config file. This worked for me.
