### ISSUE TITLE
Outdated OTEL libraries prevent import

### ISSUE THREAD

**Issue by nico151999** [ory/kratos#3734]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The open telemetry libraries have changed their folder structure over time and consequently the packages one needs to import. People using the Kratos Golang client library might not only want to mock the HTTP calls to Kratos in their tests but have an actual Kratos instance to perform requests against. The outdated dependencies keep one from importing Kratos in such projects.

### Reproducing the bug

Start a new Golang module and import current versions of open telemetry. Then, import Kratos, too. You will get an error due to the different folder structure of the packages in the different OTEL module versions.

### Version

v1.0.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other

**Comment by nico151999** [comment]
Note: seems like the dependencies will be updated in v1.1.0. As soon as v1.1.0 is released this issue can most likely be closed.

**Comment by alnr** [comment]
I believe this is fixed. Reopen if not.
