### ISSUE TITLE
Kratos container fails to start with quickstart example

### ISSUE THREAD

**Issue by Szymongib** [ory/kratos#379]
**Describe the bug**

Kratos container fails to start when running `quickstart.yaml` using `docker-compose` with the following message:
```
time="2020-05-04T08:30:02Z" level=fatal msg="The configuration is invalid and could not be loaded." config_key[1]=urls validation_error[1]="validation failed"
```

After some investigation, I have found that the image used in the compose file (`oryd/kratos:latest-sqlite`) is 2 months old. 

Updating the image tag to version `6684fbfc78b3` (the latest I have found on DockerHub) solves the issue.

**Reproducing the bug**

1. Run `docker-compose -f quickstart.yml -f quickstart-oathkeeper.yml up`
2. See logs of `kratos` container

**Expected behavior**

The example working out of the box :)

**Environment**

**N/A**

**Comment by aeneasr** [comment]
If you use the quickstart, check out the tag as documented here: https://www.ory.sh/kratos/docs/quickstart#clone-ory-kratos-and-run-it-in-docker

**Comment by Szymongib** [comment]
Right, I have missed the checkout line as I was not building the images. Thanks!
