### ISSUE TITLE
Using highest_available AAL does not work with SMS based 2FA

### ISSUE THREAD

**Issue by MichaelMarner** [ory/kratos#3801]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Kratos does not enforce `aal2` for flows configured for `highest_available` AAL when using SMS based 2FA.

When using other 2FA methods, Kratos will require AAL2 if 2FA is configured on the identity. For example, setting `whoami` to highest available:

```
  whoami:
    required_aal: highest_available
```

An identity that has TOTP based 2FA configured will not be able to access `whoami` without an AAL2 session. A call to whoami will redirect the client to a new aal2 login flow, eg:

```json
{
    "error": {
        "id": "session_aal2_required",
        "code": 403,
        "status": "Forbidden",
        "reason": "An active session was found but it does not fulfill the requested Authenticator Assurance Level. Please verify yourself with a second factor to resolve this issue.",
        "details": {
            "redirect_browser_to": "http://127.0.0.1:4433/self-service/login/browser?aal=aal2"
        },
        "message": "Session does not fulfill the requested Authenticator Assurance Level"
    }
}
```

However, this enforcement of AAL2 does not happen when using SMS based 2FA. whoami responds with a 200 when a session is `aal1`, even though the identity has a verified phone number and Kratos is configured to use SMS for 2FA.

### Reproducing the bug

1. Configure identity schema with a phone number to be used for 2FA

```
       "phone": {
          "title": "Mobile Number",
          "type": "string",
          "format": "tel",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "sms"
            }
          }
```

2. Configure Kratos for SMS based 2FA (relevant sections of Kratos.yml shown)

```yml
session:
  whoami:
    required_aal: highest_available

methods:
    code:
      enabled: true
      mfa_enabled: true

courier:
  (omitted, but configured to send SMS)
```

3. Log in through Kratos.
4. In a settings flow, add the user's phone number
5. Complete the verification process
6. Log out
7. Log in with email/password
8. Call whoami

I would expect that, given the user has a valid 2FA method on their account, that the call to whoami would fail, as the `highest_available` AAL _should be_ AAL2. However, Kratos works as if the user only has AAL1.

Other flows like settings behave in the same way. It is possible to change a password, generate recovery codes, etc. all at AAL1, which defeats the purpose of configuring SMS based 2FA. This also does not match how Kratos works with other 2FA methods.

### Version

1.1.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

**Comment by jonas-jonas** [comment]
Yes, that is a known limitation of the current implementation. We didn't consider SMS a full MFA method (due to the nature of SMS, and other factors), so the current implementation is more of a workaround to achieve an AAL2 session, rather than a drop-in replacement/full alternative for the other MFA methods. 

However, I agree that this leaves room for improvement here, and contributions are welcome.

**Comment by aeneasr** [comment]
We are actively working on improving htis. No timelines on the open source release though.

**Comment by MichaelMarner** [comment]
Legend! Did this make it into the 1.3 release?

**Comment by aeneasr** [comment]
Yes!
