### ISSUE TITLE
Jsonnet template `ctx` shape for http notification body breaking changes since 1.1

### ISSUE THREAD

**Issue by WoodyWoodsta** [ory/kratos#3815]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

N/A

### Describe the bug

Upgrading to 1.1 broke my jsonnet template for sending a notification via the http delivery strategy. Before 1.1, and as per the documentation [here](https://www.ory.sh/docs/kratos/self-hosted/email-http#request-configuration), the shape of `ctx` passed into the template contains at least keys `TemplateType` and `TemplateData.Identity`.

However, in 1.1, we now get those keys in a different casing, `template_type` and `template_data.identity`.

I couldn't find any mention of this in the 1.1 changelog.

Either the documentation needs to be updated, or this is a regression which needs to be fixed.

### Reproducing the bug

Upgrade to 1.1

### Version

1.1

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Kubernetes with Helm

**Comment by zepatrik** [comment]
The commit in question: https://github.com/ory/kratos/commit/84149c4b420ea89f0a16a579c017a8e7e1670204
It looks like this was changed without the necessary precautions by @aeneasr, there should really have been a breaking change note and ideally the "old" keys for some transition period.
As the commit was already part of the v1.1.0 release, there is probably no point in back-porting the old keys.

Regardless, we're very sorry of the inconvenience this has caused, this one has just slipped through.

**Comment by WoodyWoodsta** [comment]
No problem at all - easy fix, just came as a surprise and had to do a bit of rooting around to understand the issue :)
