### ISSUE TITLE
Hydra sdk version

### ISSUE THREAD

**Issue by nsklikas** [ory/kratos#3904]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The hydra sdk version defined in go.mod (https://github.com/ory/kratos/blob/master/go.mod#L76) points to a commit (https://github.com/ory/hydra-client-go/commit/1c7b57df3bb0) that is not under the master branch. This was introduced by https://github.com/ory/kratos/pull/3729.

This commit seems to include a lot of changes, like disallowing extra parameters in the hydra response, that are not part of the master branch. I assume that the change was not intentional, so I would suggest to change it to install `v2.2.0` of the hydra sdk.

I can open a PR to fix it, if you want.

### Version

v1.1.0

**Comment by shipperizer** [comment]
@hperl is there any plan in addressing this?

would you accept contributions to fix the problem?

**Comment by shipperizer** [comment]
this has been solved in #4017
