### ISSUE TITLE
Cannot use a refresh login flow to invoke a prompt=consent OIDC refresh

### ISSUE THREAD

**Issue by aran** [ory/kratos#3956]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

If sending `{"upstream_parameters": {"prompt": "consent"}}` in a login flow with refresh=true, `"prompt":"login"` is nevertheless in the generated link.

This appears to be because of the `IsForced` condition:

https://github.com/ory/kratos/blob/bac030b3d5a4d145fb616d59d1603bb2c5f2a429/selfservice/flow/login/flow.go#L235 
https://github.com/ory/kratos/blob/bac030b3d5a4d145fb616d59d1603bb2c5f2a429/selfservice/strategy/oidc/provider_generic_oidc.go#L90

### Reproducing the bug

1. Create a login flow with refresh: true
2. Submit the login flow with Google OIDC provider, and json encoding of `{"upstream_parameters": {"prompt": "consent"}}`
3. Expect to enter a consent OIDC flow, actual is a login OIDC flow.

### Version

1.20

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
This is expected behavior. You should not be able to make decisions on whether Google should show the login form or not as a user. Only Kratos can make that decision.
