### ISSUE TITLE
"The recovery token is invalid or has already been used" but it's not.

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#3971]
I'm having an issue with Kratos self hosted.

When I start a new recovery flow with email, I get the email and the link like:

```
https://custom_domain.com/self-service/recovery?flow=b12ff5cd-09a3-852c-8e27-ca5123489444&token=AtlocRrLsHIr8ZYMRIsFj8QmduKp
```

If for example I send this link on a chat or there is a mail system (maybe an ANTI-SPAM extension) that "navigates" this link the token is signed in the DB as "used" but it's not!

And when a user clicks that link it gets:

```
The recovery token is invalid or has already been used.
```

Is there a way to disable the "flag as used" option in Kratos?

This is tragic!

### Version

1.2.0

**Comment by frederikhors** [comment]
No one? This is very tricky to fix by ourselves.

**Comment by jonas-jonas** [comment]
This is the reason, we introduced the code strategy. Is that an option for you?

**Comment by frederikhors** [comment]
Thank you.
