### ISSUE TITLE
docs: Legacy one step registration configuration key is incorrect in Changelog

### ISSUE THREAD

**Issue by MichaelMarner** [ory/kratos#3972]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Going through the changelog to upgrade to Kratos 1.2.0. Kratos 1.2.0 introduced the two step registration process by default. According to the documentation,:

> To disable, set selfservice.flows.registration.enable_legacy_flow to true.

However this seems to be incorrect - Kratos won't start with this key set, and there are validation errors when editing config.yml.

Looks like the correct key is: `selfservice.flows.registration.enable_legacy_one_step`

### Reproducing the bug

Add `selfservice.flows.registration.enable_legacy_flow: true` to the Kratos config file.

### Relevant log output

```shell
kratos-1                      | The configuration contains values or keys which are invalid:
[OMITTED]
kratos-1                      |                                 ^-- additionalProperties "enable_legacy_flow" not allowed
```

### Version

1.2.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

### Additional Context

The change was introduced here:

https://github.com/ory/kratos/commit/3621411dc4386d841bc6766a5ab8d03e65812073#diff-bf0a09e20de9d62786fc7a927a89888f4648e1ba775473499d307d9678cca3d4

The commit message does not match the code change.

Let me know if you would like the changelog fixed or the code fixed to match the changelog.

**Comment by alnr** [comment]
fixed in https://github.com/ory/kratos/pull/3976
