### ISSUE TITLE
Add support for Salesforce which uses the ISO 8601 date format for updated_at timestamp in user claims

### ISSUE THREAD

**Issue by IchordeDionysos** [ory/kratos#3984]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Context and scope

Not all identity providers follow the OIDC standard (like [Auth0](https://github.com/ory/kratos/blob/be8a15b4bbecb85c5a6790ca83ae53563d7e0064/selfservice/strategy/oidc/provider_auth0.go#L129), [Salesforce](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_using_userinfo_endpoint.htm&type=5), …).

A [workaround](https://github.com/ory/kratos/blob/be8a15b4bbecb85c5a6790ca83ae53563d7e0064/selfservice/strategy/oidc/provider_auth0.go#L129) has been added for the pre-configured Auth0 identity provider. For generic providers, it's not possible to have an ISO 8601 date (e.g. `2013-12-02T18:46:42Z`)

### Goals and non-goals

Goals:
- Support Unix and ISO 8601 in the `updated_at` field of the OIDC user info
- Add support for generic providers

Non-goals:
- Don't add support for pre-configured providers that don't need this workaround
- Don't add support for other fields

### The design

When fetching the OIDC claims for a generic provider,
check which type the `updated_at` in the user info object has:

If it's a string and an ISO date, convert it to a Unix timestamp in the user info object.
If it's not a string or iSO date, leave the `updated_at` field untouched.

### Code and pseudo-code

```go
func tranformUpdatedAtISODateWorkaround(body []byte) ([]byte, error) {
	// Force updatedAt to be an int if given as a string in the response.
	if updatedAtField := gjson.GetBytes(body, "updated_at"); updatedAtField.Exists() && updatedAtField.Type == gjson.String {
		t, err := time.Parse(time.RFC3339, updatedAtField.String())
		if err != nil {
			return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("bad time format in updated_at"))
		}
		body, err = sjson.SetBytes(body, "updated_at", t.Unix())
		if err != nil {
			return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("%s", err))
		}
	}
	return body, nil
}
```
Code was taken from existing Auth0 workaround.

### Alternatives considered

There was some discussion (by @alnr) around whether to convert the date using in the Jsonnet snippet, using the [`toUnixTimestamp` function](https://github.com/jsonnet-libs/xtd/blob/63d430b69a95741061c2f7fc9d84b1a778511d9c/date.libsonnet#L102).
The drawback of this solution might be that it does not properly handle leap seconds.

**Comment by aeneasr** [comment]
Thank you for the suggestion. I agree that this is a problem and at the same time it's disappointing that many upstream providers have this issue.

In my view, a fix should be provider-specific. Also, I think that the transformation should be done using a custom JSON marshaller/unmarshaller as we don't want to be dependent on the field being called `updated_at`.

There's also some libraries for that: https://github.com/joeshaw/iso8601

**Comment by IchordeDionysos** [comment]
> In my view, a fix should be provider-specific.

The issue is with the fix being applied only to specific providers.
If you need to integrate a custom provider not yet available in Kratos, you can't use that provider until out-of-the-box support is added.

**Comment by IchordeDionysos** [comment]
### Potential alternative:

Have an optional `user_info_mapper_url` that points to a Jsonnet file or other similar mapper that maps the necessary fields used by Kratos of the user info response to the user claims.

This is more complex to integrate, though supporting more providers and different formats would be more abstract.

#### Benefits

- Supports all possible object schemas (e.g. `updatedAt` instead of `updated_at`)
- Supports parsing ISO8601 / RFC3339 timestamps (with [Extended Jsonnet standard library](https://github.com/jsonnet-libs/xtd/blob/63d430b69a95741061c2f7fc9d84b1a778511d9c/date.libsonnet#L147))

#### Downsides

- Does not support leap seconds (note @alnr: the current Auth0 workaround also does not respect leap seconds, see [here](https://pkg.go.dev/time#:~:text=with%20no%20leap%20seconds))
- Limited parsing possibilities (only available Jsonnet or other functions supported)
- Requires complex mapping for each provider that deviates from the standard

#### Next steps

@aeneasr @alnr or others, do we have some idea how much other implementations deviate from the standard?
Is it required to be able to use `updatedAt` instead of `updated_at`? 
Or is the date format the only deviation from the standard?

**Comment by aeneasr** [comment]
> > In my view, a fix should be provider-specific.
> 
> The issue is with the fix being applied only to specific providers. If you need to integrate a custom provider not yet available in Kratos, you can't use that provider until out-of-the-box support is added.

Yes, that is the case in my view. The OIDC generic provider should only work with spec compliant providers. For anything that needs custom code we need dedicated code in my view.

**Comment by IchordeDionysos** [comment]
In itself, I don't think something would speak against that approach if two conditions are true:

1. You would be happy to add support for non-compliant SSO providers (e.g. Salesforce)

2. It's possible to set up multiple pre-configured providers of the same type.

e.g. Salesforce itself heavily relies on tenant based authentication, there is not a single Issuer URL that is used for all Salesforce installations.

So you should be able to somehow set up two independent Salesforce SSO connections.

-

The first is more an ongoing commitment to add support for those providers as needed (or at least accept PR for those).
The second, I believe, is right now not possible with Ory Kratos and/or Network?
So would need some adjustments on how you can configure those pre-configured providers.
(Maybe I'm wrong and multiple (e.g. Auth0 providers are possible via the API but not via the UI?)

**Comment by jonas-jonas** [comment]
2. Is possible, it's just not possible in the Ory Console (on the backlog to be fixed, because this is also problematic for other situations/providers). As of now, you can set different IDs for each provider in the configuration via the CLI.

**Comment by IchordeDionysos** [comment]
2. Ahh yes thanks ☺️ I've see @vinckr comment in Slack:
https://ory-community.slack.com/archives/C02MR4DEEGH/p1719391550931369?thread_ts=1719326079.593729&cid=C02MR4DEEGH

**Comment by IchordeDionysos** [comment]
@aeneasr @jonas-jonas I've opened a PR which fixes the invalid schema for Salesforce :)
