### ISSUE TITLE
Why does recovery with code returns `redirect_browser_to` instead of a redirect response?

### ISSUE THREAD

**Issue by frederikhors** [ory/kratos#3988]
Why does the recovery method with code returns:

```
{
    "error": {
        "id": "browser_location_change_required",
        "code": 422,
        "status": "Unprocessable Entity",
        "reason": "In order to complete this flow please redirect the browser to: https://example.com/account/settings?flow=8f8190f1-...",
        "message": "browser location change required"
    },
    "redirect_browser_to": "https://example.com/account/settings?flow=8f8190f1-..."
}
```

instead of returning a redirect response to that URL?

### Version

1.2.0

**Comment by alnr** [comment]
This should happen only in API flows, where there is no native redirect mechanism. Returning 302 here might cause implementations to follow that redirect rather than open a browser and send the user there.

**Comment by rakhmanov** [comment]
Following setting in kratos.yaml changes this behavior, and stops the redirect:

    feature_flags:
      use_continue_with_transitions: true
    
I've encountered it in the UI flows, not sure about native flows.
