### ISSUE TITLE
Verify email address before registration

### ISSUE THREAD

**Issue by doneHappyPlay** [ory/kratos#4096]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

no

### Describe your ideal solution

When users register, I hope to first ask them to fill in their email and accurately fill in the email verification code before completing the registration.

### Workarounds or alternatives

Add a before configuration to the registered flow, which supports email verification

### Version

v1.2.0

**Comment by aeneasr** [comment]
This is unfortunately not possible. Email verification can only happen after we have a user record on file (after registration). To do it before registration, you can customize Ory Kratos‘ logic on the before hook with a web hook, for example.
