### ISSUE TITLE
Missing "x-total-count" header for listIdentities endpoint

### ISSUE THREAD

**Issue by thephilippbusch** [ory/kratos#4128]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

When calling the /admin/identities endpoint to list identities, the "X-Total-Count" header cannot be found in the response (in contrast to i.e. the /admin/sessions endpoint). This confuses me a bit, as the _Link_ header is present. So I don't really see a reason, why the listIdentities endpoint should omit that header. 

Is there a reason why the _identites_ endpoint does not include an X-Total-Count header (since its also not mentioned on the [pagination site](https://www.ory.sh/docs/ecosystem/api-design) in the docs)?

(PS: I'm not really experienced in Go, but it seems like the header could be added without much hassle when comparing the implementation of the listIdentities handler to the aforementioned _sessions_ endpoint handler. I could maybe take a look at that but again, haven't done much with Go yet)

### Reproducing the bug

1. Run `docker run oryd/kratos:v1.3.0`
2. Create some identities.
3. Fetch from _identities_ endpoint and print headers, i.e. via:
```bash
curl -X GET -I http://localhost:4434/admin/identities
```
4. A similar result like the following should be printed:
```bash
HTTP/1.1 200 OK
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Type: application/json; charset=utf-8
Link: </admin/identities?page_size=250&page_token=some-page-token>; rel="first"
Date: Fri, 27 Sep 2024 13:24:18 GMT
Content-Length: 952
```
5. The _X-Total-Count_ header is missing.

In contrast, the _sessions_ endpoint returns the following:
```bash
curl -X GET -I http://localhost:4434/admin/sessions
HTTP/1.1 200 OK
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Type: application/json; charset=utf-8
Link: </admin/sessions?page_size=250&page_token=some-page-token>; rel="first"
X-Total-Count: 3
Date: Fri, 27 Sep 2024 13:27:07 GMT
Content-Length: 1122
```

### Version

1.3.0

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
We are no longer exposing this header due to performance reasons, so this is expected.
