### ISSUE TITLE
Since 2 step Registration - I receive error status 400 for registrationFlow even with correct data provided in response

### ISSUE THREAD

**Issue by FilipObrCeit** [ory/kratos#4178]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

Hello, we are encountering new issue and couldnt find suitable sollution or explanation so was hoping to get some hint here. Since we implemented 2 step registration process we started to receive error after updating Registration flow with traits. From this request we receive correct data in response but status says 400. We double checked everything today and couldnt find a problem. We are using native sollution (not web) and problem was not present before we updated to 2 step registration.

### Reproducing the bug

1.) Initialize registration flow, render nodes
2.) Fill up email and optionally also First name and/or Last name
3.) Update registration flow with provided info
4.) Now I got second step nodes rendered correctly and can proceed with a process but request returns incorrectly status 400

Example of URL used:
https://100.100.200.120/self-service/registration?flow=a3561461-3349-41cc-a291-8288dcc0bd87

### Version

1.2.0

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Docker Compose

### Additional Context

Status 400 is same for correcttly or incorrectly filled data

**Comment by alnr** [comment]
Known issue, probably wontfix.

**Comment by aeneasr** [comment]
See https://github.com/ory/kratos/issues/4052
