### ISSUE TITLE
Failed to gracefully shutdown public httpd

### ISSUE THREAD

**Issue by One041** [ory/kratos#425]
**Describe the bug**

Im getting "Failed to gracefully shutdown public httpd" when trying to run kratos.

**Reproducing the bug**

1. Download https://github.com/ory/kratos/releases/download/v0.3.0-alpha.1/kratos_0.3.0-alpha.1-sqlite_windows_64bit.zip
2. Copy configuration file from https://www.ory.sh/kratos/docs/reference/configuration
3. Change `dsn` to memory or sqlite option
4. Run Kratos

_Server logs_

```
C:\Users\Admin\Desktop\kratos-sqlite>kratos -c C:\Users\Admin\Desktop\kratos-sqlite\config.yml serve
time="2020-05-19T13:41:11+03:00" level=info msg="Config file loaded successfully." path="C:\\Users\\Admin\\Desktop\\kratos-sqlite\\config.yml"
time="2020-05-19T13:41:11+03:00" level=info msg="Courier worker started."
time="2020-05-19T13:41:11+03:00" level=info msg="Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa"
time="2020-05-19T13:41:11+03:00" level=info msg="Starting the admin httpd on: amet:4434"
time="2020-05-19T13:41:11+03:00" level=info msg="Starting the public httpd on: minim esse officia:4433"
time="2020-05-19T13:41:11+03:00" level=fatal msg="Failed to gracefully shutdown public httpd"
C:\Users\Admin\Desktop\kratos-sqlite>
C:\Users\Admin\Desktop\kratos-sqlite>kratos version
Version:                        v0.3.0-alpha.1
Build Commit:   43b693a449bf7cd219eb6901acf36725ace1c41c
Build Timestamp:        2020-05-15T13:22:46Z
```

**Environment**

- Version: v0.3.0
- Environment: Windows 10 x64

**Additional context**

When Kratos is running it creates empty `mem.db` but then crashes. When using sqlite data source name I set path to my `db.sqlite` file but error is the same. Any idea what I did wrong?

Btw, I found one little typo in config docs. I got error message below when copied config from website.
```
C:\Users\Admin\Desktop\kratos-sqlite>kratos -c C:\Users\Admin\Desktop\kratos-sqlite\config.yml serve
time="2020-05-19T13:53:53+03:00" level=info msg="Config file loaded successfully." path="C:\\Users\\Admin\\Desktop\\kratos-sqlite\\config.yml"
time="2020-05-19T13:53:53+03:00" level=error msg="The provided configuration is invalid and could not be loaded. Check the output below to understand why." config_file="C:\\Users\\Admin\\Desktop\\kratos-sqlite\\config.yml"

urls.whitelisted_return_to_urls: https://app.my-app.com/dashboard
                                 ^-- expected array, but got string

time="2020-05-19T13:53:53+03:00" level=fatal msg="The services failed to start because the configuration is invalid. Check the output above for more details."
C:\Users\Admin\Desktop\kratos-sqlite>
```
I guess new line is required there https://nimb.ws/vd2r7a

**Comment by aeneasr** [comment]
Is there anything running on that port already maybe?

> Btw, I found one little typo in config docs. I got error message below when copied config from website.

Could you link me to the page, or create a PR for it? :)

**Comment by One041** [comment]
> Is there anything running on that port already maybe?

I think no. I tried to change default ports and error is the same.
```
C:\Users\Admin\Desktop\kratos-sqlite>kratos -c C:\Users\Admin\Desktop\kratos-sqlite\config.yml serve
time="2020-05-19T14:10:17+03:00" level=info msg="Config file loaded successfully." path="C:\\Users\\Admin\\Desktop\\kratos-sqlite\\config.yml"
time="2020-05-19T14:10:17+03:00" level=info msg="Courier worker started."
time="2020-05-19T14:10:17+03:00" level=info msg="Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa"
time="2020-05-19T14:10:17+03:00" level=info msg="Starting the admin httpd on: amet:44349"
time="2020-05-19T14:10:17+03:00" level=info msg="Starting the public httpd on: minim esse officia:44339"
time="2020-05-19T14:10:17+03:00" level=fatal msg="Failed to gracefully shutdown public httpd"
```
> Could you link me to the page, or create a PR for it? :)

https://www.ory.sh/kratos/docs/reference/configuration

**Comment by aeneasr** [comment]
> I think no. I tried to change default ports and error is the same.

Hm very strange, is there maybe a firewall or antivirus that somehow kills this? It's very weird that there is no error shown, typically indicating something like SIGKILL or SIGINT (implying that the process was halted or killed by the operating system).

I do have access to a Windows machine and will try to check it out soon. As a workaround you should be good to go with Docker if you have Docker for Desktop installed.

> https://www.ory.sh/kratos/docs/reference/configuration

For me this looks correct:

<img width="1335" alt="Bildschirmfoto 2020-05-19 um 13 12 51" src="https://user-images.githubusercontent.com/3372410/82319795-7e567a80-99d2-11ea-9ee1-bf73a3bc771a.png">

**Comment by One041** [comment]
> Hm very strange, is there maybe a firewall or antivirus that somehow kills this?

Windows defender only by default. But I did not add any rules.

Can you give me advice please how to use external (from my host) configuration file with docker?

> For me this looks correct:

Different for me https://nimb.ws/ByjdSx

**Comment by aeneasr** [comment]
> Can you give me advice please how to use external (from my host) configuration file with docker?

All the examples, including the quickstart, use Docker. You will find your answer there, including awesome diagrams and instructions!

> Different for me https://nimb.ws/ByjdSx
https://github.com/ory/kratos/blob/master/docs/docs/reference/configuration.md

Ah, that's our ServiceWorker cache. Try a hard reload with Ctrl+R!

**Comment by One041** [comment]
I created screenshot in private window (with clear cache). Maybe your ServiceWorker cache have some duration for cached data.

**Comment by aeneasr** [comment]
Ok that's definitely strange. I'll have to investigate the ServiceWorker. We've had issues with it before unfortunately...

**Comment by aeneasr** [comment]
Nope, you're right! It was cached on my end, now I also see the wrong instruction :)

**Comment by One041** [comment]
Thank you for advice. I will investigate examples :)

**Comment by One041** [comment]
Maybe problem in configuration file. I tried to run quickstart example in docker and it works. But when I changed configuration to same as I used from docs it crashed with error as in my first message.

**Comment by One041** [comment]
Reason was really stupid =_=". Don't copypaste configuration as I did it.
https://nimb.ws/7g1rFW

**Comment by aeneasr** [comment]
Glad you were able to resolve it!
