### ISSUE TITLE
Courier messages polling the database

### ISSUE THREAD

**Issue by jonaslimads** [ory/kratos#466]
Hello,
great software you're doing here!

I've enabled Postgres logging and seen a new query in second:

```sql
SELECT courier_messages.body, courier_messages.created_at, courier_messages.id, courier_messages.recipient, courier_messages.status, courier_messages.subject, courier_messages.type, courier_messages.updated_at FROM courier_messages AS courier_messages WHERE status != $1 ORDER BY created_at ASC LIMIT 10
```
which happens because of the for in:
https://github.com/ory/kratos/blob/8050e33a2a4593307fa32feba6c448b850aed3fc/courier/courier.go#L126

While this works, it can lead to some problems in case the database gets a heavy load.
One solution is making it "reactive" via goroutine or something like that. 
I can give it a try coding a solution for this, at least to learn your code :)

Another question: is it possible to disable SMTP connection altogether?

Thank you!

**Comment by aeneasr** [comment]
Thank you! We'll probably make this configurable in the future :) PRs welcomed

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️

**Comment by frederikhors** [comment]
@aeneasr I think we should reopen this because the database is flooded with calls all the time for this problem!
