### ISSUE TITLE
Introduce prevent extension in Identity JSON schema

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#47]
The `prevent` extension would:

- always prevent the user from writing to this field in a selfservice mannger (registration, profile update, ...)
- prevent the user from reading in a selfservice manner (e.g. ``) the field if a config option is set

e.g.

```json
{
 "hive": {
    "protected": {
       "readable": true // just an example
     }
  }
}
```

This field could still be modified/read when accessing the identity API through the admin port.

Alternatively, the identity model would get a `privileged` field that acts similar to `traits` and that is only writable through the admin port. It would be difficult to decide about the readability here. Other companies allow reads but no writes here.

**Comment by aeneasr** [comment]
If there is a `privileged` schema, it should be possible to link field to credentials there as well. Assuming a username that could only be chosen and edited by an admin, for example.

**Comment by kszafran** [comment]
"view" sound like a synonym of "read". How about "know"?

Another approach could be to have just a few different field types, and avoid permission combinations that might not be useful. For example: `hidden` (-), `readonly` (rv), `writable` (rvw), `writeonly` (vw).

**Comment by viters** [comment]
@kszafran 

That's a nice idea. It simplifies API and addresses missing combinations issue. I will think it through and update my proposal.

**Comment by kszafran** [comment]
Let's say I wanted to store user roles (or some kind of permission list) in identity traits. Are there any workarounds available (e.g. failing the "after settings" hook if the user tries to change their roles)? Or am I going the wrong way about it and such information should never be stored in Kratos?

**Comment by viters** [comment]
@kszafran 

I believe that's currently impossible, because every trait can be modified by user (it has to be valid according to schema). 

Kratos is meant for identities - meaning who somebody is - not what is he able to do. Although for simple use cases I would vote for storing anything in Kratos, even roles. If I have a simple app with user / admin roles, keeping everything about users in Kratos, without spawning another service, imo is fine. The `prevent` extension suggested by @aeneasr (and the elaboration in my proposal) would allow administrator to store arbitrary data on user's profile - effectively increasing the possible use cases of traits.

Although it will probably take time to implement that feature, it's also not a top priority I suppose. I will try to help. Until that I suggest you look at ORY Keto or just run your own micro service to manage roles in coordination with Kratos.

**Comment by aeneasr** [comment]
I think this issue here is not going to be implemented as is. Instead, we should just add like a "metadata" field to the identity which can only be modified via the admin API. Adding this to the JSON Schema simply makes things too complicated IMO.

**Comment by kszafran** [comment]
That would also work. The only question then would be -- should those metadata fields be visible to self-service users? I could imagine scenarios where you'd want to show the values as readonly, and other scenarios where you'd want to hide them completely.

**Comment by aeneasr** [comment]
I can imagine that we have two types of metadata available:

```
metadata:
  # Visible to users and at /session/whoami
  public: 
  # Only visible if you call admin endpoint /identity/<id>
  admin: 
```

Contributions welcomed :)

**Comment by rubybb** [comment]
Is it possible to have like ``identity.jsonnet`` to control this kind of thing?

**Comment by aeneasr** [comment]
In this case I think it would be better developer experience if we govern this via the identity schema :)

**Comment by nrutherford** [comment]
What about making use of "readOnly" and "writeOnly" annotations from JSON schema? https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.4

**Comment by aeneasr** [comment]
Thank you for the idea! Those have specific reserved use cases. I think for our purposes we should either write an extension, or follow https://github.com/ory/kratos/issues/47#issuecomment-975377301 :)

**Comment by nrutherford** [comment]
> Thank you for the idea! Those have specific reserved use cases. I think for our purposes we should either write an extension, or follow https://github.com/ory/kratos/issues/47#issuecomment-975377301 :)

With the metadata fields, do you imagine those as being stored together as JSON in a new DB column? Would they also be defined in identity schema? So in summary a copy of traits without the extensions and less business logic?

**Comment by aeneasr** [comment]
I imagine them being two columns in the database `metadata.public` and `metadata.private` as `json` types. I think it would be cool to validate them with the Identity Schema as well, but it does not have to be.

**Comment by frederikhors** [comment]
Is there a way to do this in 0.9.0?
