### ISSUE TITLE
Adding identity id in /whoami endpoint response header (for authorized user)

### ISSUE THREAD

**Issue by bandirsen** [ory/kratos#502]
**Is your feature request related to a problem? Please describe.**
For authorized user, current '/whoami' endpoint response only return identity information as json payload, while most reverse proxy server can only forward response header from authorization server to backend application

**Describe the solution you'd like**
I wish '/whoami' endpoint also put identity id in response header, for example in 'X-Forwarded-User' header, which later forwarded by reverse proxy to backend application

This will simplify the authorization process by reverse proxy, no need to marshal/unmarshal json payload from /whoami endpoint just to get identity id

**Comment by aeneasr** [comment]
Since there is no standard for this this would mean that we would have to return the header in multiple ways and formats. Is there any common standard here? `X-Forwarded-User` does not look correct to me, I've seen something like `X-User-ID` although this isn't standardized.

**Comment by bandirsen** [comment]
I agree _X-Forwarded-User_ doesn't look correct, especially for client who accessing Kratos REST API directly, my suggestion is _X-Kratos-User_ since it could help for branding too.

I think any header name would work, since we customize it on reverse proxy server setting, there is no standard header name for it, but in nginx or traefik documentation they always use _X-Forwarded-xxxx_ as example for any forwarded headers.

**Comment by koenmtb1** [comment]
Just came across this issue, I've been working on this. See #530

**Comment by aeneasr** [comment]
#530 was merged
