### ISSUE TITLE
Social sign in with Twitter

### ISSUE THREAD

**Issue by romcok** [ory/kratos#517]
**Is your feature request related to a problem? Please describe.**

Hi,
we want to use the sign in with Twitter, but I don't know how to configure it.

This is written in the documentation:
`The oidc method uses OpenID Connect, or OAuth2 where OpenID Connect is not supported, to authenticate identities using a third-party identity provider, such as Google, Microsoft, GitHub - or any other OAuth2 / OpenID Connect provider..`

Twitter is the OAuth2 provider, so I hope it will work somehow 🙏

**Comment by aeneasr** [comment]
Twitter is not OAuth2 but the older OAuth1, so we will need a dedicated strategy to deal with Twitter! By searching on Google it appears that there's at least one library able to deal with Twitter's OAuth (1.0) protocol: https://github.com/kkdai/twitter

**Comment by romcok** [comment]
Oh, now I see. They have OAuth2 only for application-only authentication. 
https://developer.twitter.com/en/docs/basics/authentication/oauth-2-0

Twitter is quite a big player and a lot of people come to us from there, it would be good to have it as an option.

**Comment by marcinkoziej** [comment]
Hello @aeneasr !
What is the hour estimate to add this functionality to Kratos?
Could we sponsor such work to be done by You or someone form Ory team?

**Comment by aeneasr** [comment]
Someone from out team will reach out to you in the next days!

**Comment by lanphan** [comment]
https://github.com/dghubble/oauth1 is a better lib to use, imho.

**Comment by mfzl** [comment]
> Twitter is not OAuth2 but the older OAuth1, so we will need a dedicated strategy to deal with Twitter! By searching on Google it appears that there's at least one library able to deal with Twitter's OAuth (1.0) protocol: https://github.com/kkdai/twitter

Are you suggesting another strategy along with `oidc` and `password`. What would it be called for example `oauth1` or `twitter`?

**Comment by aeneasr** [comment]
No, this can be dealt with in the normal oidc strategy. You just need to use a different library to complete it, and not our generic OIDC provider!

**Comment by mfzl** [comment]
@aeneasr Is this being developed? If not I'd like to take this up

**Comment by aeneasr** [comment]
Noone is working on it afaik :) Please do pick it up! :)

**Comment by vinckr** [comment]
And let me know if I can support you in any way with this :-).

**Comment by 8thblock** [comment]
> Twitter is not OAuth2 but the older OAuth1, so we will need a dedicated strategy to deal with Twitter! By searching on Google it appears that there's at least one library able to deal with Twitter's OAuth (1.0) protocol: https://github.com/kkdai/twitter

They are OAuth2 now. Just letting you know ...

https://developer.twitter.com/en/docs/authentication/oauth-2-0

**Comment by aeneasr** [comment]
Awesome!! If anyone is up for contributing this I would appreciate it a lot!
