### ISSUE TITLE
New account recovery feature can't use recovery token

### ISSUE THREAD

**Issue by avamonitoring** [ory/kratos#525]
**Describe the bug**

The `persister_recovery.go` file contains a bug in the [UseRecoveryToken](https://github.com/ory/kratos/blob/8bf9a1ac4162c677a455c2f02de658bd5d146905/persistence/sql/persister_recovery.go#L83) function. The for loop is written in such a way that even if the recovery token is found in the database, the loop continues. If there are multiple session secrets configured, a no-rows-found exception will be thrown, and the outcome of the loop is that the `err` variable will contain an error, which will make the function return the error rather than the token.

So, for example, **if you have two session keys, and the first was used to hash the token**, then the first iteration in the loop will produce a match, but instead of breaking the loop, it continues with the next session secret. Then, a now rows found error will be thrown at the second iteration, and then the loop stops. So, the outcome of the loop is that the `err `variable will have an error, and therefore the following if-statement becomes true and the error is returned from the function:

```
if err != nil {
    return err
}
```

Same problem if the second session secret is the one that was used to hash the token. Then, the first iteration in the loop would produce an error, and the second iteration a match. But still, the `err `variable would contain an error so the if-statement above would make the function return the error instead of the token.

**Reproducing the bug**

Follow the intended recovery flow.

_Server configuration_

Relevant section:

```yaml
secrets:
  session:
  - session-key-123-456
  - session-key-234-567
```
-->

**Expected behavior**

Instead of continuing the for-loop when a matching token has been found, **the `err `variable should be cleared and the loop exited with a break statement**.  This fixed the issue for me, at least. 

**Environment**

- Version: current master branch

**Additional context**

**Comment by aeneasr** [comment]
Nice catch, would you be open to PR a fix for this?

**Comment by avamonitoring** [comment]
Yes. But I feel the best solution would be to construct a SQL statement that make use of the IN(...) construct instead of iterating and query once per session secret. So, the query would be something like `WHERE token IN(?, ?) AND NOT used.` However, I'm not sure how that would work with the SQL framework used. Is it possible to use an array as input to bind the variables inside the IN clause?

If the above is not feasible, I can submit a PR to fix the issue by just fixing the for loop. What's the timeframe for the next release? Just so I know when it is needed.

**Comment by aeneasr** [comment]
We'd like to avoid queries like that because it's typically down to the database regarding e.g. indices, performance and so on. Also not sure if all dialects support this!

It's probably better to just fix the for loop :)

**Comment by avamonitoring** [comment]
@aeneasr I actually found 2 more bugs in that function:

1. The below if-statement doesn't work:

```
if !errors.Is(err, sqlcon.ErrNoRows) {
  return err
}
```

It can't recognize the `sql: no rows in result set` error, so needs to be fixed as well.

2. The update statement updates entire table instead of a single row and needs a WHERE caluse

I'll fix these two issues as well and will submit a PR shortly.

**Comment by avamonitoring** [comment]
@aeneasr Submitted a PR, but tests are failing:

```
--- FAIL: TestSettingsStrategy/suite=unlink (0.11s)

        --- PASS: TestSettingsStrategy/suite=unlink/case=should_not_be_able_to_unlink_the_last_remaining_connection (0.02s)

        --- PASS: TestSettingsStrategy/suite=unlink/case=should_not_be_able_to_unlink_an_non-existing_connection (0.02s)

        --- PASS: TestSettingsStrategy/suite=unlink/case=should_not_be_able_to_unlink_a_connection_not_yet_linked (0.02s)

        --- FAIL: TestSettingsStrategy/suite=unlink/case=should_unlink_a_connection (0.05s)
```

Doesn't seem to be related to my changes though...
