### ISSUE TITLE
Support deploying HTTPS and auto-certs with certbot

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#529]
**Is your feature request related to a problem? Please describe.**

It's currently not possible to configure HTTPS.

**Describe the solution you'd like**

HTTPS should be configurable and on per default.

**Describe alternatives you've considered**

https://github.com/caddyserver/certmagic

**Additional context**

**Comment by harsimranmaan** [comment]
Do you think it would be a good idea to leave TLS termination be handled outside of the application? The reason I am thinking about this that when we deploy anything at scale, we deploy multiple replicas behind an LB or a proxy. For end to end encryption on Kratos , a solution could be using a service mesh to support encryption not only for the client connections but also for intra-service communication including access to the DB. certbots are not ideal for horizontally scalable applications unless we want to add shared state(for key and cert) across the cluster. Thoughts?

**Comment by aeneasr** [comment]
Yes, TLS Termination should be the modus operandi for 99% of use cases

**Comment by aeneasr** [comment]
It is now possible to deploy SSL in Ory Kratos. For certbot and others, please use e.g. caddy or other services that have this as their main feature :)
