### ISSUE TITLE
Require re-authentication when modifying sensitive traits via the Admin API

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#537]
**Is your feature request related to a problem? Please describe.**

When an admin changes e.g. the primary email address of a user, the session of the admin should be a privileged one, similar to how we have solved this for self-service settings management.

**Comment by harsimranmaan** [comment]
How long does the privilege last and how many actions can admin take at once when using escalated privilege?

**Comment by aeneasr** [comment]
This doesn’t make sense - the Admin API has no concept of an „admin user“.
