### ISSUE TITLE
Running docker-compose following the quickstart I get ERROR: Version in "./quickstart.yml" is unsupported.

### ISSUE THREAD

**Issue by nessita** [ory/kratos#587]
Following the quickstart for Kratos (https://www.ory.sh/kratos/docs/quickstart, v0.4), when running:

ubuntu@ory:~/kratos$ docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate

I get the following error:

ERROR: Version in "./quickstart.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

1. Create a VM with Ubuntu 18.04
2. Install docker-compose with `sudo apt install docker-compose`
3. Follow the quickstart

ubuntu@ory:~/kratos$ apt show docker-compose
Package: docker-compose
Version: 1.17.1-2

**Comment by aeneasr** [comment]
Please use a more recent version of Docker / Docker Compose - the sources from apt are usually quite old.

**Comment by nessita** [comment]
Thank you for your quick response. Do you have the list of recommended/supported versions for docker and docker-compose?

**Comment by nessita** [comment]
In case this happens to someone else, a valid workaround for Ubuntu 18.04 is as follows:

(purge old installed versions)
sudo apt purge docker-compose

Download/link to a newer docker-compose with:

$ `sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`
$ `sudo chmod +x /usr/local/bin/docker-compose`
# ensure the version is correct
$ `docker-compose --version`
docker-compose version 1.26.2, build eefe0d31
