### ISSUE TITLE
Integration of Kratos and Keto?

### ISSUE THREAD

**Issue by batistein** [ory/kratos#591]
What are the options at the moment to integrate Keto in Kratos? 
In the docs there is no information about this topic.

**Comment by aeneasr** [comment]
Can you be more specific, please?

**Comment by batistein** [comment]
We want to use Kratos for our platform which manages a Kubernetes cluster for our customers. We need to translate the access given in the platform to roles in Kubernetes and want to use Keto for that.
Apart from the fact, that I would very much appreciate some documentation on how to use Kratos and Keto together, we would like to know if the two services can use the same database and if the traits you can define for users in Kratos can somehow translate to what Keto needs.

**Comment by aeneasr** [comment]
There are many "integration" scenarios possible. You could use ORY Keto to protect ORY Kratos' APIs for example, or you want to use ORY Kratos as the identity management and use ORY Keto for permissions in your platform. It depends on what you want to solve, which is why I asked about specificity.

**Comment by batistein** [comment]
Kratos is generally our Single Point of Truth and should be used as identity management. Roles will be assigned in Keto to the identities/users stored in Kratos. For example, a user belongs to an org. and should only do things in a namespace in k8s. Or a user should be able to create an org. where he gets admin rights and can add and manage other users of this org/group.

The other case is that we want to authorize the admin API. Meaning our backend gets a M2M (machine-to-machine) access to do tasks this user / API access should only get the rights he needs for the task. Since the microservices work on the zero-trust principle, authentication and authorization is mandatory.

**Comment by aeneasr** [comment]
In that case you check the session for the logged in "user ID" and then check the permission server if the permission was granted. This can be solved with oathkeeper or in your programming language (middleware) itself. I'm not sure what type of integration would you expect beyond that?

**Comment by aeneasr** [comment]
Closing due to lack of response
