### ISSUE TITLE
initializeSelfServiceBrowserLoginFlow: Request Header Fields Too Large

### ISSUE THREAD

**Issue by ellioseven** [ory/kratos#599]
**Describe the bug**

I am trying to initialise the a login flow in my React application. Redirecting the user works:

```
window.location.href = `${ config.kratos.browser }/self-service/browser/flows/${ type }`
```

However, if I try to use `initializeSelfServiceBrowserLoginFlow` I get the following:

`431: Request Header Fields Too Large`

![image](https://user-images.githubusercontent.com/5354445/88524693-f906cc00-cff9-11ea-8dda-359e5a549a05.png)

I'm using oathkeeper in my example.

**Reproducing the bug**

```
git clone https://github.com/ellioseven/kratos-ss-ui-react.git -b bugfix/api-login-flow
cd kratos-ss-ui-react
docker-compose up -d
browse http://127.0.0.1:4455/auth/login
```

_Server logs_

NA

**Expected behavior**

I should be redirected back to the login page with a valid request ID in the URL.

**Environment**

- `@oryd/kratos-client`: ^0.4.6-alpha.1
- `kratos`: Docker: `oryd/kratos:latest-sqlite`
- `oathkeeper`: Docker: `oryd/oathkeeper:v0.38`

**Comment by aeneasr** [comment]
From a quick glance it looks to me as if the problem is with the UI, possibly something that sends too many headers back to Oathkeeper?

I think you generally don't need oathkeeper in this scenario, because the React UI runs completely in the user's browser.

Also make sure to `docker pull oryd/kratos:latest-sqlite` to get the most recent version, or use a dedicated tag.

**Comment by ellioseven** [comment]
I switched from Oathkeeper to NGINX as a reverse proxy, however I still see the same issue. I pulled the latest just a couple of days ago, however I will settle with `kratos:v0.4.6-sqlite`.

In my React app I am doing the following:

```
useEffect(() => {
    kratos.initializeSelfServiceBrowserLoginFlow(true)
      .catch(error => console.log(error))
  }, [])
```

I am assuming this is how it would work, I can't find any examples with React code.

I would of thought under the hood it would perform a redirect to that URL with a request header but it seems like it's a fetch. Maybe that's the problem?

**Comment by aeneasr** [comment]
So what you need to do is forward the user to the init endpoint (a `<a>` link would also work):

```
window.location.href = `${ config.kratos.browser }/self-service/browser/flows/${ type }`
```

which in the end will redirect you to `http://your-login/endpoint/auth/login?request=...` and then use the ORY Kratos SDK to fetch the login request info like so (pseudocode):

```
request = ... // the value of ?request=<..>
kratos.initializeSelfServiceBrowserLoginFlow(request).then(({body}) => body.methods.password ....)
```

**Comment by ellioseven** [comment]
That's what I am doing currently, however I was hoping `initializeSelfServiceBrowserVerificationFlow` was a possible short cut for that. That's the impression I got from the documentaiton here:

> This endpoint initializes a browser-based user login flow. Once initialized, the browser will be redirected to `selfservice.flows.login.ui_url` with the request ID set as a query parameter. If a valid user session exists already, the browser will be redirected to `urls.default_redirect_url`.  > This endpoint is NOT INTENDED for API clients and only works with browsers (Chrome, Firefox, ...).  More information can be found at [ORY Kratos User Login and User Registration Documentation](https://www.ory.sh/docs/next/kratos/self-service/flows/user-login-user-registration).

**Comment by aeneasr** [comment]
How would a clarification of that look like?

**Comment by ellioseven** [comment]
I think what is there is quite clear, I just didn't make the connection with the following reference in the docs: 

> The initialization request (http://127.0.0.1:4455/.ory/kratos/public/self-service/browser/flows/(login|registration)) cannot be made via AJAX or API requests. You must open that URL in the user's browser using e.g. window.open location.href or plain and simple old < a href=...>.

Thank you for help @aeneasr
