### ISSUE TITLE
Ability to set Docker ory UID/GID

### ISSUE THREAD

**Issue by michael-robbins** [ory/kratos#618]
**Is your feature request related to a problem? Please describe.**

Ability to customised the UID/GID of the 'ory', currently this isn't explicitly set in the Dockerfile(s) and rather tricky to bind mount config/DB/etc and provide permissions from within the container.

**Describe the solution you'd like**

It would be great to be able to set a couple of environment variables similar to PUID/PGID to be able to customise these at runtime before starting the 'kratos server' command.

**Describe alternatives you've considered**

Another less customisable way would be to hardcode the UID/GID inside the container so that we can use those IDs outside the container on the Host OS to provide permissions correctly.

**Comment by aeneasr** [comment]
Is there any documented best practice around this?

**Comment by michael-robbins** [comment]
So I've used these in all the linuxserver.io images:
https://docs.linuxserver.io/general/understanding-puid-and-pgid
https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/10-adduser

There's the use of overriding entrypoint with a script that will read in the PUID/PGID env vars and update the local users IDs appropriately (groupmod/usermod), with a default if not specified.

This seems to provide the most flexibility.

This does mean the current `ENTRYPOINT ["kratos"]` would need to be an `/entrypoint.sh` or similar, with it passing anything in like `CMD ["serve"]` through to the 'underlying' entrypoint `kratos`

**Comment by aeneasr** [comment]
Given that we need to run chmod I assume that this can't be done without entrypoint, right?

**Comment by aeneasr** [comment]
Looking at this again, this will be difficult to pull of in scratch containers - while it might still work in alpine-based images. However, due to a lack of public interest in this issue I will be closing this to clean up the backlog. But feel free to comment or reopen if this issue persists.
