### ISSUE TITLE
Require recaptcha on suspicious login and signup

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#65]
Right now, sign up and login can be done over and over again. We should protect these endpoints with some type of challenge (e.g. recaptcha) on consecutive requests.

**Comment by aeneasr** [comment]
Not sure how this works exactly, but for recaptcha we could probably provide the HTML as part of the login request payload?

**Comment by akonyushevskiy** [comment]
Hi, Any progress here?

**Comment by aeneasr** [comment]
Contributions welcomed.

**Comment by aeneasr** [comment]
#138
