### ISSUE TITLE
Separate out typescript typings so that they don't require on nodejs bindings

### ISSUE THREAD

**Issue by aaahrens** [ory/kratos#651]
**Is your feature request related to a problem? Please describe.**

Right now the typed models package imports from api package, rather than being generated into their own typings package. This makes it impossible type anything client side which doesn't have nodejs bindings. 

edit: even models/raw-interface directory still import. 

**Describe the solution you'd like**
export the raw interface typings stripped from the api/api package, and in the nodejs client packaged extend them to include the nodejs bindings. This way when rehydrating client side it can be typed. 

Alternatively, publish a typings browser package. 

**Describe alternatives you've considered**

Already doing his, just creating typings in the local package that are copy pasta.

**Additional context**

this is going to be really necessary when using any sort of spa-rendering application.

**Comment by aeneasr** [comment]
Could you please provide a GitHub repository with the issue illustrated? I’ve been working on SPA and RN examples without issues.

**Comment by aaahrens** [comment]
Yeah sure! I'll post it once I get it working up to standards. It's an angular project so the the TS bindings are a little more strict than CRA's IIRC. Just a tl;dr though it has to do with FileRequest being typed for a Buffer and a fs.Buffer, which are node bindings. 

On the offhand, for Rn are you doing auth through an authenticated browser session and just polling the whoami request?

**Comment by aeneasr** [comment]
For SPA I'm using whoami

**Comment by aaahrens** [comment]
I made a fairly functional angular-kratos prototype here: https://github.com/aaahrens/kratos_angular

So the original issue was a bug with my version of typescript, updating to angular 10 solved it. I'm going to be closing this issue.

However, registration and login works only once. I am currently unable to login or register after the first time because kratos is not reading the corrected expected csrf value from the database. The one currently being sent is the one in the database (verified through the rest api and the database itself). The csrf token that kratos is expecting exists nowhere in database, nor is it in the two cookies that are set. I would really appreciate it if you would take a look.  

I believe this is a bug with using http-proxy-middleware (which is the defacto standard) or maybe some internal stuff. I don't use the request pipe method since the library has been depreciated since Feburary.
