### ISSUE TITLE
Password reset emails sent twice by each of the two kratos pods in my cluster

### ISSUE THREAD

**Issue by alsuren** [ory/kratos#652]
**Describe the bug**

Password reset emails are sent twice if I have two kratos pods in my cluster.

**Reproducing the bug**

* Go to https://beta.future.nhs.uk/auth/recovery and type in an email address that you control
* Receive two emails with identical bodies.

_Server logs_

logs from my cluster:
```
$ stern kratos -n kratos -c kratos
...
kratos-597b499965-pqd9n kratos time=2020-08-13T10:52:15Z level=info msg=started handling request method=POST name=public#/.ory/kratos/public/ remote=127.0.0.1 request=/self-service/browser/flows/recovery/link?request=33e4c070-20d5-43fa-a566-ad59a143db68 request_id=3aa1024edfd605e7eb5a1b880f6f6304
kratos-597b499965-pqd9n kratos time=2020-08-13T10:52:15Z level=info msg=Preparing account recovery token. address=Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". audience=audit service_name=ORY Kratos service_version= via=email
kratos-597b499965-pqd9n kratos time=2020-08-13T10:52:15Z level=info msg=Sending out stub recovery email because address is not linked to any account. audience=audit email_address=Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". service_name=ORY Kratos service_version= via=email
kratos-597b499965-pqd9n kratos time=2020-08-13T10:52:15Z level=info msg=completed handling request method=POST name=public#/.ory/kratos/public/ remote=127.0.0.1 request=/self-service/browser/flows/recovery/link?request=33e4c070-20d5-43fa-a566-ad59a143db68 request_id=3aa1024edfd605e7eb5a1b880f6f6304 status=302 text_status=Found took=100.785916ms
kratos-597b499965-g9w78 kratos time=2020-08-13T10:52:15Z level=info msg=started handling request method=GET name=admin#http://kratos:4434/ remote=127.0.0.1:38412 request=/self-service/browser/flows/requests/recovery?request=33e4c070-20d5-43fa-a566-ad59a143db68
kratos-597b499965-g9w78 kratos time=2020-08-13T10:52:15Z level=info msg=completed handling request method=GET name=admin#http://kratos:4434/ remote=127.0.0.1:38412 request=/self-service/browser/flows/requests/recovery?request=33e4c070-20d5-43fa-a566-ad59a143db68 status=200 text_status=OK took=3.812622ms
kratos-597b499965-pqd9n kratos time=2020-08-13T10:52:16Z level=debug msg=Courier sent out message. audience=application message_id=df74fdd0-639c-4a5d-b4d8-f49b6566c328 message_subject=Account access attempted
kratos-597b499965-pqd9n kratos  message_type=1 service_name=kratos service_version=
kratos-597b499965-g9w78 kratos time=2020-08-13T10:52:16Z level=debug msg=Courier sent out message. audience=application message_id=df74fdd0-639c-4a5d-b4d8-f49b6566c328 message_subject=Account access attempted
kratos-597b499965-g9w78 kratos  message_type=1 service_name=kratos service_version=
```
These seem to suggest that the http POST request is only being handled once, but there are two emails being sent out.

_Server configuration_

The interesting thing about our setup is that we have 2 replicas of the kratos deployment talking to the same postgresql database: https://github.com/FutureNHS/futurenhs-platform/blob/fd68011/infrastructure/kubernetes/kratos/base/kratos.yaml#L50
We are also using sendgrid's smtp transport for our outgoing email (free tier). I can try to reproduce this with mailslurper if you want.
There may be a concise way to reproduce this by setting replica counts in docker-compose. I haven't tried that yet.

**Expected behavior**

Receive a single password reset email.

**Environment**

- Version: I build my image from master from a few days ago (git describe says: v0.4.6-alpha.1-98-gc13b1838) merged with my uri-reference-for-ui_url branch (ga42cd2bd) before it was rebased and merged.
- Environment: Docker + Kubernetes + Sendgrid + linkerd

**Additional context**

Does courier need to have some kind of reserve(with ttl) -> send -> ack thing going on for its email queue to reduce the probability of this happening?

**Comment by aeneasr** [comment]
Potentially https://github.com/ory/kratos/issues/402#issuecomment-658675897
