### ISSUE TITLE
Self-service GDPR identity export

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#658]
**Is your feature request related to a problem? Please describe.**

GDPR requires developers to provide users with an option to export all of their data.

**Describe the solution you'd like**

Identities should be able to export all of their traits and similar using a self-service flow.

**Comment by NickUfer** [comment]
@aeneasr is this open for contribution?

**Comment by aeneasr** [comment]
Absolutely! First step would be an API proposal, preferably in OpenAPI format!

**Comment by NickUfer** [comment]
I'm currently looking into how other selfservice flows are implemented and I stumpled upon the logout flow. The actual implemented endpoints differ from the ones in the openapi schema.

https://github.com/ory/kratos/blob/master/selfservice/flow/logout/handler.go#L22-L26

This is the only documented logout endpoint:

https://github.com/ory/kratos/blob/master/.schema/openapi.json#L1825-L1849

I think this is not intended right?

**Comment by aeneasr** [comment]
Yeah that looks strange!

**Comment by alantbarlow** [comment]
I don't have much experience actually using Kratos and am still studying how it works so I can implement it, so excuse me if I am being naive. But would this work better if there was an export flow for self-service. Ideally the export flow would email the user their identity info and also include a webhook to add additional user data to the email before it is sent.

**Comment by kmherrmann** [comment]
That sounds right to me, @alantbarlow!

One thought: The email should be completely customizable so that a flow implementation can e.g. compile a zip file with additional data and include a download link in the email.

**Comment by alantbarlow** [comment]
It might be possible to have the data be compiled into PDF format and sent directly in the email. I don't know how feasible this is though.

**Comment by mitar** [comment]
E-mails are not encrypted, so please do not send private data over e-mails.

**Comment by alantbarlow** [comment]
@mitar I didn't think about that, but you are right. The email should just let the user know that the information they requested can be found at the url provided in the email. That page would provide a download link could additionally require the user to be logged in to access.
