### ISSUE TITLE
Design of the client cli

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#663]
**Is your feature request related to a problem? Please describe.**

We want to add a client CLI with management capabilities similar to [Hydra](https://www.ory.sh/hydra/docs/cli/hydra/). This issue summarizes all the features it should provide for now.

Feel free to comment on any feature. The points denoted with a question mark are not going to be included if nobody wants them.

**Describe the solution you'd like**

Output formats (flag `--output -o`):
- Table view (default)
- JSON pretty
- JSON
- ID only (nice for piping, similar to `docker ps -q`)
- ? file

Configuration of remote URL:
- env var
- flag
- ? config file in working dir
- ? globally defined context like with kubectl

Here is the list of proposed commands, output format is just exemplary:
- [ ] check status
    ```
    $ kratos remote status
    Property | Status
    ---------|-------
    alive    | true
    ready    | true
    ```
- [ ] check version
    ```
    $ kratos remote version
    v1.0.0
    ```
- [ ] list identities (filtering will be added when it is implemented in kratos). **Should we allow listing all without pagination? What information would you like to see in the table output?**
    ```
    $ kratos identities list --page 1 --per-page 100
    ID   | Identifier
    -----|------------
    ID_1 | foo@bar.com
    ```
- [ ] create identity (reading from `STD_IN` should be enough as one can pipe a file via cat)
    ```
    $ cat identity_peter.json | kratos identities create
    ID_PETER
    ```
- [ ] get a single identity (ID should be provided via `STD_IN` or argument). **What information would you like to see in the table output?**
    ```
    $ kratos identities get <id>
    {...}   # dump of the identity json
- [ ] update a single identity (reading from `STD_IN` should be enough as one can pipe a file via cat)
    ```
    $ cat identity_peter_updated.json | kratos identities update
    ID_PETER
    ```
- [ ] delete a single identity (ID should be provide via `STD_IN` or argument; skip question with `--force -f`). **What information would you like to see in the table output?**
    ```
    $ kratos identities delete <id>
    Do you really want to delete the identity with the identifier foo@bar.com? [yes/no]: y
    <id>
**Additional context**

The CLI will be a wrapper for the go SDK.

**Comment by aeneasr** [comment]
What about `-q` which returns only the ID? Think docker :)

It would also be cool if I could do:

```
kratos identities delete $(kratos identities find --filter-param="asdf" -q)
```

For now, we could simply walk through all the pages locally and filter out the correct elements. Will not scale, but gets the point across.

> Output formats (flag --output -o):

Most CLIs I know will use `-o` as the output file location.

Also, what would the values look like? (e.g. `json`)

> Configuration of remote URL:

Good idea! This is usually `--api` or `--endpoint` or something like that.

> Should we allow listing all without pagination? 

Could be a good idea!

> What information would you like to see?

Would be nice if you could define what you want to see. `kubectl` allows you to query specific fields IIRC

> `kratos identities create`

Will there be `kratos identities import`? If so, how do they differentiate?

> `kratos identities update`

The problem with "update" is that you don't know if it's a PATCH (patching things) or a PUT (replacing whole object) operation.

**Comment by zepatrik** [comment]
> What about -q which returns only the ID? Think docker :)
> 
> It would also be cool if I could do:
> ```
> kratos identities delete $(kratos identities find --filter-param="asdf" -q)
> ```

This is what I meant with

>> - ID only (nice for piping, similar to docker ps -q)

and

>> ID should be provided via `STD_IN` **or** argument

---

> Most CLIs I know will use -o as the output file location.

E.g. kubectl uses `-o` https://kubernetes.io/docs/reference/kubectl/overview/#formatting-output which can also be an output file.

---
>> Configuration of remote URL:
>
> Good idea! This is usually --api or --endpoint or something like that.

I think there should be multiple ways to configure it, that's why I came up with a view viable ones. Setting an env var is more convenient as one does not have to specify the url with every call when doing multiple operations.

---

> Will there be `kratos identities import`? If so, how do they differentiate?

Import could also include credentials I guess? Not in plain text of course, but hashes of credentials. Therefore users can be migrated from an existing system. But as user migration is not yet fully defined we stick with the existing create endpoint for now.

---

> The problem with "update" is that you don't know if it's a PATCH (patching things) or a PUT (replacing whole object) operation.

Right, maybe allow both? The REST API just allows PUT currently but we can PATCH by first getting the identity and then patching locally. Should we rephrase the command to `kratos identities put` and `kratos identities patch`?

**Comment by zepatrik** [comment]
For writing tables, I suggest we go with `text/tabwriter`. The docker cli uses it as well and it is a standard package.

**Comment by aeneasr** [comment]
> This is what I meant with
>
>ID only (nice for piping, similar to docker ps -q)
and
>
>ID should be provided via STD_IN or argument

👍 

> E.g. kubectl uses -o https://kubernetes.io/docs/reference/kubectl/overview/#formatting-output which can also be an output file.

Perfect, so let's just do what they do and copy the spec

> Import could also include credentials I guess? Not in plain text of course, but hashes of credentials. Therefore users can be migrated from an existing system. But as user migration is not yet fully defined we stick with the existing create endpoint for now.

Yes, that is the idea. Even if it's not yet implemented we need to be aware of the implications. Will import and create be combined? Or do you first create a user and then import the credential? What do you think?

> Right, maybe allow both? The REST API just allows PUT currently but we can PATCH by first getting the identity and then patching locally. Should we rephrase the command to kratos identities put and kratos identities patch?

I think that's a good idea, renaming them to put/patch!

> I think there should be multiple ways to configure it, that's why I came up with a view viable ones. Setting an env var is more convenient as one does not have to specify the url with every call when doing multiple operations.

Right, absolutely. I meant that we need to define the naming for that :)

**Comment by zepatrik** [comment]
> Yes, that is the idea. Even if it's not yet implemented we need to be aware of the implications. Will import and create be combined? Or do you first create a user and then import the credential? What do you think?

Right, I suggest we have just one command. I see no benefit in separating them. If there is no credential the identity is just in reset-only state. What do you think then? I think we should make it `kratos identities import` then.
