### ISSUE TITLE
Implement React Native sample application consuming API

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#667]
A React Native sample application (https://github.com/ory/kratos-selfservice-ui-react-native).

- [ ] Publish tutorial on the website and link it in the docs
- [ ] Log in with password
- [ ] Sign up with password
- [ ] Update settings
- [ ] Re-request verification mail
- [ ] Logout
- [ ] Request account recovery
  - [ ] Document that this needs a browser always because it's a link

**Comment by sachaarbonel** [comment]
Hi @aeneasr, can you open a similar issue to track a Flutter implementation? I'd like to implement it when I've time, next week-end or so

**Comment by aeneasr** [comment]
That's great! If you want, you can post your progress here, no need to create another issue :)

**Comment by aeneasr** [comment]
Hell yeah!
