### ISSUE TITLE
Endpoint whoami returns valid session after user logout

### ISSUE THREAD

**Issue by tnm0113** [ory/kratos#686]
**Describe the bug**

After user logout, I use POSTMAN to take GET request to /sessions/whoami with cookie copied from browser, and it returns valid session

**Reproducing the bug**

1. Login 
2. Copy session id from cookie in browser, paste to Postman
3. Logout
4. Request to whoami using Postman

**Expected behavior**

whoami should return invalid session

**Environment**

- Version: latest code on master

**Comment by aeneasr** [comment]
Thank you for the report! This has been resolved in #624 already, so I'll be closing this :)
