### ISSUE TITLE
Do not create system errors on duplicate credentials when linking oidc providers

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#694]
**Describe the bug**

Currently, linking a oidc profile with an account where the oidc profile has already been linked to another account will result in a system error.

**Reproducing the bug**

1. Sign up a new identity using e.g. GitHub (idA)
2. Sign up another identity using e.g. password (idB) and go to settings page
3. Link the already used GitHub profile from idA to idB

![image](https://user-images.githubusercontent.com/3372410/92475843-b7676480-f1e6-11ea-9ce3-44820d29fb9e.png)

**Expected behavior**

This should not result in a system error but instead in a validation error.

**Environment**

- Version: all

**Additional context**

**Comment by lmcl90** [comment]
It tried to create a duplicated identifier, not a credential.
