### ISSUE TITLE
Validate identity schema on load

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#701]
**Is your feature request related to a problem? Please describe.**

It would be nice to not only validate the config but also the identity schema to catch errors early on.

**Describe the solution you'd like**

Validate the identity schema against either the JSON schema meta schema, or define our own meta schema.

**Additional context**

Whether our meta schema would add any benefit is to be determined. It could validate our extensions though.

**Comment by zepatrik** [comment]
Validating the identity schema against the jsonschema meta schema would be enough for the moment, but if you are very motivated go ahead and validate our extension as well
It's schema is located here: https://github.com/ory/kratos/blob/master/schema/.schema/extension/identity.schema.json
The initial config validation is done here: https://github.com/ory/kratos/blob/master/x/config.go

**Comment by nanikjava** [comment]
> Validating the identity schema against the jsonschema meta schema would be enough for the moment, but if you are very motivated go ahead and validate our extension as well
> It's schema is located here: https://github.com/ory/kratos/blob/master/schema/.schema/extension/identity.schema.json
> The initial config validation is done here: https://github.com/ory/kratos/blob/master/x/config.go

@zepatrik the link to `config.go` does not exist anymore is this file `github.com/ory/kratos/driver/config/config.go` you referring to ?

**Comment by zepatrik** [comment]
Sorry for not using permalinks back then :see_no_evil: 
Actually, @Benehiko started to work on this already this week :wink:
