### ISSUE TITLE
Support OAuth2 and OpenID Connect in API-based flows

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#707]
**Is your feature request related to a problem? Please describe.**

It's currently not possible to use Google to sign in through ORY Kratos' Admin APIs which would be necessary in mobile environment (e.g. React Native).

**Describe the solution you'd like**

This should be implemented. Keep in mind that Facebook does not allow login through a browser, but instead requires us to use their SDK.

**Comment by splaunov** [comment]
Can we just add auth code and access/refresh token as parameters to the submit method of the oidc flow?
Would it be the right solution?
On mobile platforms it's not hard to get auth code or access token directly from OAuth provider with numerous plugins available. Only the last step is missing: we need to exchange OAuth code/token for Kratos session token.

**Comment by aeneasr** [comment]
The access token would not be a good option because that would open a very specific vulnerability of OAuth2 (as it does not prove authentication but authorization). There is a good resource on that [here](https://oauth.net/articles/authentication/).

The most secure and interoperable option would be an OpenID Connect ID Token. Here, the proposed submit flow could work! I am not sure if all social sign in providers support that but for those that do, this could be an option. For those that do not (like facebook) we probably have to implement some custom stuff anyways!

**Comment by splaunov** [comment]
Yes, I've just misused the terminology. It definitely should be an ID Token.
And auth code should also work fine. If one prefers to exchange it for ID token server-side. Right?

I would try to implement this if the concept seems right to you.

**Comment by splaunov** [comment]
My first step would be to separate 'browser' and 'api' tests in `selfservice/strategy/oidc/strategy_test.go`

**Comment by aeneasr** [comment]
That's a good first step :)

**Comment by splaunov** [comment]
Remove flow type check in Strategy.PopulateLoginMethod

**Comment by aeneasr** [comment]
👍

**Comment by splaunov** [comment]
This is what I've done so far as an experiment:
- Deleted throwing of `ErrAPIFlowNotSupported` in `oidc.Strategy.validateFlow()`.
- Deleted API flow blocking in `oidc.Strategy.PopulateLoginMethod()`.
- Changes in `oidc.Strategy.Login()`:
    - Added validation check if `id_token` parameter present for API flow.
    - Added id token claims extraction.
    - Added search of identity in db by `claims.Subject`.
    - Added code to create and persist new identity if db search failed with `ErrNoRows`.
      Duplicated this code from `oidc.Strategy.processRegistration()`.

My tests from an iOS device with Apple, Google, and Microsoft providers have run with no issues.

**Comment by splaunov** [comment]
@aeneasr what could be the next step? Should I submit a pull request with the modifications above?

**Comment by aeneasr** [comment]
Yes! That sounds good! The plan looks solid IMO

**Comment by nicolaric** [comment]
awesome work! I'm looking forward to test that! 🤩

**Comment by gustavovalverde** [comment]
I'll be waiting for this to test it!

**Comment by mfzl** [comment]
Is this still being developed. 

I maybe missing some context here but I wasn't sure where the development is happening since comments suggest there is work being done.

**Comment by splaunov** [comment]
> Is this still being developed.
> 
> I maybe missing some context here but I wasn't sure where the development is happening since comments suggest there is work being done.

Hi! It's currently developed in the linked PR.
