### ISSUE TITLE
Building From Source fails

### ISSUE THREAD

**Issue by leadiato** [ory/kratos#711]
**Describe the bug**
Building Kratos from source fails when following [Kratos Building from source](https://www.ory.sh/kratos/docs/install/#building-from-source)

**Reproducing the bug**
1. run `go get -d -u github.com/ory/kratos`
2. `cd $(go env GOPATH)/src/github.com/ory/kratos`
3. GO111MODULE=on make install

**Output:**
make: *** No rule to make target '.bin/packr2', needed by 'install'.  Stop.

**Expected behavior**

`$(go env GOPATH)/bin/kratos help` runs successfully and returns proper version number

**Environment**

- Environment: Mac OS 10.14.6
- Make: GNU Make 4.3
- Go: go1.15.2 darwin/amd64

**Comment by aeneasr** [comment]
https://www.ory.sh/kratos/docs/install#building-from-source

**Comment by aeneasr** [comment]
Sorry, looks like you're following the guide!

**Comment by leadiato** [comment]
To fix the issue I had to manually create 2 folders (`.bin/packr2` & `.bin/pack`) prior to start the build.

**Comment by aeneasr** [comment]
Would you be open to contribute that change to the Makefile? :)

**Comment by chris-rock** [comment]
The `make tools` mentioned in the docs is also not working.

**Comment by aeneasr** [comment]
Could you please provide more details? What make version, what is "not working" (error message please), where in the docs - and so on! :) I can only help if sufficient details are provided, otherwise it's a guessing game.

**Comment by chris-rock** [comment]
No problemo. There is a reference to `make tool` in https://github.com/ory/kratos/blob/master/README.md#install-tools It seems that there is no `tools` task in the latest Makefile. With the changes in #750 I got the binary compiled.

**Comment by aeneasr** [comment]
Ok so `make tools` no longer exists - these things now compile automatically (e.g. "golangci-lint" or "goreturns"). Another problem was that we no longer use packr2 so it's not listed as a dependency and thus shouldn't be required!
