### ISSUE TITLE
Write CLI helper for recommending Argon2 parameters

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#723]
**Is your feature request related to a problem? Please describe.**

See https://github.com/bburman/Twelve21.PasswordStorage

**Additional context**

#722 
#647

**Comment by zepatrik** [comment]
After reading https://www.twelve21.io/how-to-choose-the-right-parameters-for-argon2/ I think we could also add a "auto" mode where you configure the argon2 execution time and then kratos determines the right parameters on start. Setting the values manually should still be possible though.
The auto mode would basically find the highest amount of memory while requiring at least X (4?) iterations within the given execution time. What do you think?

**Comment by aeneasr** [comment]
I thought about that also, but one problem with that is that the process would take quite a while to start in order to compute the correct parameters. Maybe we simply enforce Argon2 configuration  and if it is not set we show an error that explains what needs to be done?

**Comment by zepatrik** [comment]
I mean if you use the auto mode you should expect it to boot longer. But then the hardware doesn't change, so it would actually be better to determine it once and done.
My thought was that people might miss the cli helper...
What about printing the argon2 execution time on start? It would allow to check if the parameters are set correctly and we can have a hint there to use the cli to tune the parameters.
