### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by dfector** [ory/kratos#769]
The documentation seems pretty clear that the only databases supported are PostgreSQL and MySQL.

Is it possible to use Microsoft SQL Server as the identity store?

We'd consider using Postgre, but our entire platform is running on MSSQL. 

The system looks awesome though.

**Comment by aeneasr** [comment]
Thank you for the question! Unfortunately, we do not plan to support closed source databases as they are too much effort to test and develop against.

**Comment by aeneasr** [comment]
I'll be closing this but if you have more questions around this feel free to ask!

**Comment by dfector** [comment]
Thanks for the quick response.

So, to be clear, is the use of MSSQL impossible? ...or just not supported?

Does Kratos use an ORM layer or direct access through the DB drivers?

Thanks again!

**Comment by aeneasr** [comment]
It's not supported - not sure if it would be possible. We don't use insane queries or migrations but obviously every SQL dialect works a bit different. We use https://github.com/gobuffalo/pop/ as a DBAL which doesn't support MSSQL either, as far as I have seen (we partially maintain the project). OSS SQL databases are easy and cheap to spin up in today's cloud environment so before venturing into forks or other work, I'd recommend using a managed SQL option first. Kratos doesn't need a lot of beef, so you'll probably be fine with a smaller installation that has maybe a failover replica.
