### ISSUE TITLE
Webhook notification based system

### ISSUE THREAD

**Issue by merlindorin** [ory/kratos#776]
**Is your feature request related to a problem? Please describe.**

Currently, smtp is implemented so we can send an email for an account registration... but how can I handle "sms" notification, "slack" notification or whatever?

**Describe the solution you'd like**

Have the opportunity to be ory implementation free through a webhook. e.g.

```
+-------------------+    +---------+    +--------------+    +-------------+
| user registration +--->| webhook +--->| email-sender +--->| smtp server |
+-------------------+    +---------+    +--------------+    +-------------+
```

**Describe alternatives you've considered**

SMTP custom implementation for sending sms? #kidding

**Additional context**

- comment on smtp PR: https://github.com/ory/kratos/pull/146#issuecomment-712123612

**Comment by merlindorin** [comment]
After reading the source... lot of fun/works in this feature request xD.

@aeneasr Do we have a work in progress for sms? There is some opinionated works around this feature and, if I have time, I don't want to move in the bad direction (interface for courrier, separate models from smtp specific func like EmailRecipient, move templating in a SMTPCourier implementation, strategy->link->send update, etc.)

**Comment by aeneasr** [comment]
> @aeneasr Do we have a work in progress for sms? There is some opinionated works around this feature and, if I have time, I don't want to move in the bad direction (interface for courrier, separate models from smtp specific func like EmailRecipient, move templating in a SMTPCourier implementation, strategy->link->send update, etc.)

We don't right now, unfortunately :)

**Comment by aeneasr** [comment]
Yeah, I think they are about more or less the same thing.

**Comment by eshepelyuk** [comment]
Sorry for multipost, 
I'm just trying to check a roadmap and some issues are in 0.7 and some are not.
So tryin ot figure out if those issues are really planned for 0.7
