### ISSUE TITLE
Typescript ErrorContainer type is incorrect

### ISSUE THREAD

**Issue by snikch** [ory/kratos#782]
**Describe the bug**

The current typescript type for `ErrorContainer` in `api.d.ts` doesn't correctly represent the payload.

**Reproducing the bug**

Look at the typescript bindings to see the `ErrorContainer` type.

```ts
/**
 *
 * @export
 * @interface ErrorContainer
 */
export interface ErrorContainer {
    /**
     * Errors in the container
     * @type {object}
     * @memberof ErrorContainer
     */
    errors: object;
    /**
     *
     * @type {string}
     * @memberof ErrorContainer
     */
    id: string;
}
```

Generate an error and look at the payload.

```json
{
  "id": "d513f09a-11df-4fb7-a258-71acafc780f0",
  "errors": [{
    "code": 403,
    "reason": "A request failed due to a missing or invalid csrf_token value.",
    "status": "Forbidden",
    "message": "The requested action was forbidden"
  }]
}
```

As you can see, the `error` key is an array not an object.

The correct type would be:

```ts
export interface ErrorContainer {
    /**
     * Errors in the container
     * @type {error}
     * @memberof ErrorContainer
     */
    errors: Error[];
    /**
     *
     * @type {string}
     * @memberof ErrorContainer
     */
    id: string;
}

export interface Error {
    /**
     *
     * @type {number}
     * @memberof Error
     */
    code: number;
    /**
     *
     * @type {string}
     * @memberof Error
     */
    reason: string;
    /**
     *
     * @type {string}
     * @memberof Error
     */
    status: string;
    /**
     *
     * @type {string}
     * @memberof Error
     */
    message: string;
}
```

**Environment**

Both server and client package are `0.5.0-alpha.1`

**Comment by aeneasr** [comment]
Does this refer to the self-service error endpoint?

**Comment by snikch** [comment]
Correct, yes.

**Comment by aeneasr** [comment]
I looked into this a bit, the problem right now is that the error could also have a different layout, which is why this is currently polymorph. One problem are for example system errors that do not have a proper JSON object representation. So this needs to be fixed in both the server as well as the swagger spec, but it's a bit more work :)

**Comment by snikch** [comment]
Ok, that makes sense. I've just created my own type as needed for the moment and cast it to it 👌

**Comment by aeneasr** [comment]
Resolved on master!
