### ISSUE TITLE
Add TLS configuration

### ISSUE THREAD

**Issue by dmayle** [ory/kratos#791]
**Is your feature request related to a problem? Please describe.**
I've been working my way through the docs and a sample deployment based off of quickstart, thinking that it was possible to deploy Kratos without using a reverse proxy like oathkeeper.  After combing through docs and source code looking for how to configure TLS, I stumbled across issue #529 which makes it clear that you don't support deploying kratos to production without placing it behind a reverse proxy.

**Describe the solution you'd like**
Please just make it clear in the documentation that a reverse proxy is required for production usage due to the lack of TLS support.

**Describe alternatives you've considered**
Don't think there are any.

**Additional context**
None needed

**Comment by aeneasr** [comment]
Sounds like you had a frustrating exprience, sorry about that. Would you be open to contribute this to the documentation?

**Comment by milochristiansen** [comment]
I spent far too Fing long trying to figure out how TLS is supposed to be configured, because a user management system supports TLS right? Right? Wrong.

Useful documentation for a production deployment is nonexistent.

**Comment by seremenko-wish** [comment]
Even with reverse proxy, it needs TLS support to set up end-to-end traffic encryption.

**Comment by aeneasr** [comment]
Porting the TLS capabilities of e.g. Ory Oathkeeper [is pretty straight forward](https://github.com/ory/oathkeeper/blob/64429016f7f549f2f5a3ff94c8c43da95cf47e8a/cmd/server/server.go#L144) if anyone's up for the challenge :)
