### ISSUE TITLE
Implement PASETO as a more secure alternative to JOSE (JWT & co)

### ISSUE THREAD

**Issue by sycured** [ory/kratos#808]
Hi, PASETO exists for a long time now and Okta implemented it as a more secure alternative to JOSE.

- https://paragonie.com/blog/2018/03/paseto-platform-agnostic-security-tokens-is-secure-alternative-jose-standards-jwt-etc
- https://developer.okta.com/blog/2019/10/17/a-thorough-introduction-to-paseto
- Library in Go: https://github.com/o1egl/paseto (listed on official website: https://paseto.io/)

Regards

**Comment by aeneasr** [comment]
Thank you for the idea! However, this project does not use JOSE and does not intend to use it. So I'll be closing this. One area where we *could* add support for PASETO would be in ORY Oathkeeper as an alternative to the JWT ID Token.
