### ISSUE TITLE
Generated PHP swagger client unable to fully use api

### ISSUE THREAD

**Issue by NickUfer** [ory/kratos#817]
**Describe the bug**

Kratos cannot be used in PHP with the generated swagger client of https://openapi-generator.tech because the time precision is too high. PHP can only parse timestamps with microsecond precision but timestamps returned from the api have nanosecond precision.

The generator generates:

```php
} elseif ($class === '\DateTime') {
    // Some API's return an invalid, empty string as a
    // date-time property. DateTime::__construct() will return
    // the current time for empty input which is probably not
    // what is meant. The invalid empty string is probably to
    // be interpreted as a missing field/value. Let's handle
    // this graceful.
    if (!empty($data)) {
        return new \DateTime($data);
    } else {
        return null;
    }
}
```

When I then try to call `/sessions/whoami` with the client I get:

```
PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (2020-11-11T15:17:58.868722633Z) at position 0 (2): The timezone could not be found in the database in Standard input code:1
Stack trace:
#0 Standard input code(1): DateTime->__construct()
[...]
```

**Reproducing the bug**

Make a call to for example `/sessions/whoami` to get any timestamp. In this example I use `expires_at`:

```bash
▶ curl 'http://127.0.0.1:4433/sessions/whoami' \ 
  -H 'Cookie: csrf_token=...; ory_kratos_session=...; ory_kratos_continuity=...' | jq
{
  "id": "fc3cf993-3e71-4080-8dc0-0afaa6f80486",
  "active": true,
  "expires_at": "2020-11-11T15:17:58.868722633Z",
  "authenticated_at": "2020-11-10T15:17:58.868722633Z",
  "issued_at": "2020-11-10T15:17:58.868743993Z",
  "identity": {
    "id": "f9be5d04-fc70-4d78-9215-8835f6a7d5f5",
    "schema_id": "default",
    "schema_url": "http://127.0.0.1:4433/schemas/default",
    "traits": {
      "username": "TestAccount",
      "email": "testaccount@test.invalid"
    },
    "verifiable_addresses": [
      {
        "id": "a2fb8c29-cedc-4f65-b162-bc44304da331",
        "value": "testaccount@test.invalid",
        "verified": false,
        "via": "email",
        "status": "pending",
        "verified_at": null
      }
    ],
    "recovery_addresses": [
      {
        "id": "b6759c1a-7054-4a94-9a9e-4e5ab60e155d",
        "value": "testaccount@test.invalid",
        "via": "email"
      }
    ]
  }
}
```

Run with the timestamp: 
```bash
▶ echo "<?php echo (new DateTime('2020-11-11T15:17:58.868722633Z'))->getTimestamp();" | php
PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (2020-11-11T15:17:58.868722633Z) at position 0 (2): The timezone could not be found in the database in Standard input code:1
Stack trace:
#0 Standard input code(1): DateTime->__construct()
```

If you remove the nanosecond precision from the timestamp:
 ```bash
▶ echo "<?php echo (new DateTime('2020-11-11T15:17:58.868722Z'))->getTimestamp();" | php
1605107878%
```

**Expected behavior**

PHP / the generated php client should be able to parse dates of kratos's api.

**Environment**

- Version: v0.5.3-alpha.1
- Environment: Ubuntu, Docker
- Database: SQLite

**Comment by NickUfer** [comment]
Maybe it's safe to truncate all timestamps not even to microseconds but to seconds? In my opinion we don't need such high precision here at all.

**Comment by zepatrik** [comment]
Sounds reasonable, we should use the highest precision that is supported by all systems. Milliseconds should be available everywhere and is good enough. What do you think?
Regardless, this should also be solved in the generator in my opinion. We will not be the only ones with this problem.
The RFC does not define any precision https://tools.ietf.org/html/rfc3339#section-5.6 and as such a compatible parser should automatically truncate any digits it can not store itself IMO.

**Comment by NickUfer** [comment]
I think I will create an issue at the generator. I just ran in the same problem with the API of an E-Ink Device and Google's storage API.

**Comment by aeneasr** [comment]
Yeah this looks like an upstream issue to me. The format we use is standard JSON and should be supported in all languages, or if not, should be properly handled by the library/generator implementing the functionality.

**Comment by NickUfer** [comment]
Fix was merged in generator: https://github.com/OpenAPITools/openapi-generator/pull/7943

**Comment by aeneasr** [comment]
We probably still need to wait for a release from them right?

**Comment by NickUfer** [comment]
Oh, yes right. I will it close again when a new release is out.

**Comment by NickUfer** [comment]
Version 5.0.0 with the fix is now released. However, the cli still uses 4.3.1 but it is possible to switch to 5.0.0 with `openapi-generator-cli version-manager set 5.0.0`.

**Comment by aeneasr** [comment]
Nice, I will be upgrading the pipeline in the next days!

**Comment by aeneasr** [comment]
I checked, unfortunately 5.0.0 is not yet available through NPM

**Comment by aeneasr** [comment]
Actually it is, I am just blind and did not read the changelog ;)
