### ISSUE TITLE
API documentation for kratos nodejs client

### ISSUE THREAD

**Issue by CSRaghunandan** [ory/kratos#818]
I don't see the API documentation for kratos nodejs client anywhere in this codebase or in npm website for kratos client.

Where is the codebase for kratos nodejs client hosted at? If there are any documentation for the same, can you please point me to them.

Thank you

**Comment by xlanor** [comment]
I was also looking for this awhile back, but ultimately when you execute an `npm install --save` the codebase will appear in your `node_modules` folder.

When using the node client I was able to integrate using the codebase from `node_modules`

**Comment by CSRaghunandan** [comment]
> I was also looking for this awhile back, but ultimately when you execute an `npm install --save` the codebase will appear in your `node_modules` folder.
> 
> When using the node client I was able to integrate using the codebase from `node_modules`

Correct, but there is no API documentation for the same. I would need to go through the source code to understand the usage of kratos client.

**Comment by vinckr** [comment]
Hey, we don't have enough documentation for the SDKs. 
I have [an issue for this](https://github.com/ory/docs/issues/309) and will start making some progress there. 
If you can help me in any way filling in the blanks here, it would be much appreciated!
You can also always contact me in Slack or via email.

**Comment by CSRaghunandan** [comment]
> Hey, we don't have enough documentation for the SDKs.
> I have [an issue for this](https://github.com/ory/docs/issues/309) and will start making some progress there.
> If you can help me in any way filling in the blanks here, it would be much appreciated!
> You can also always contact me in Slack or via email.

Hi @vinckr 
I would be willing to help in my free time. Can you please share your email so that I contact you.

Thanks

**Comment by vinckr** [comment]
Thats great to hear @CSRaghunandan, my email is vincent@ory.sh and you can always contact me directly in [our slack](https://www.ory.sh/chat)!

**Comment by Mimameid** [comment]
What is the status and what are the future plans here?

I found this: https://www.npmjs.com/package/@ory/kratos-client.
There is no public repository for it though. Not sure if it is official.

**Comment by vinckr** [comment]
Hey @Mimameid,
that is the official Javascript/Typescript SDK for Ory Kratos!
You can find the source in our [SDK repository](https://github.com/ory/sdk/), more specifically here:
https://github.com/ory/sdk/tree/master/clients/kratos/typescript . 

Alas, there has been some progress on the documentation front, but any help is appreciated!

Future plan would be to have some basic documentation for Ory Kratos SDKs, like there is for e.g. [Ory Hydra](https://www.ory.sh/hydra/docs/sdk/js).

**Comment by Mimameid** [comment]
Hey @vinckr,

Thank you. I would like to lend a hand, but honestly I don't understand the tool yet. 

Reading through old and new doc (also api docs) versions and playing around with it to get a grasp. I know that it is a powerful and in its core a complicated tool, but honestly the docs are not accessible to me.

I read and worked with several of related tools, some more and some less sophisticated. Getting started with Kratos just feels obstructed. An example is the term "Client-Side Browser Client" or "Server-Side Browser Client". I have yet to understand what the terms mean. My experience seems not to suffice, nor a google search can help. I'm getting off topic now...
