### ISSUE TITLE
More meta information about the managed identity

### ISSUE THREAD

**Issue by dadrus** [ory/kratos#820]
**Is your feature request related to a problem? Please describe.**

Feature Fequest:

When the user accesses its profile, it should see 
* which authentication methods are configured, 
* when was the last password change
* ...

**Describe the solution you'd like**

All, the browser based self-service flows, API based flows as well as the implementation of the admin API to retrieve the information about the identity (`GET /identities/{id}`) should not only return the traits, but also the aforesaid additional information

**Additional context**

![image](https://user-images.githubusercontent.com/10072595/98856190-8234f800-245d-11eb-88c5-2d0993ae2cb5.png)

**Comment by aeneasr** [comment]
Good ideas!
