### ISSUE TITLE
Quickstart is failing to mount volume kratos.yml when SELinux is enabled using Podman

### ISSUE THREAD

**Issue by debrutal** [ory/kratos#831]
**Is your feature request related to a problem? Please describe.**

Trying out the quickstart tutorial from [kratos site](https://www.ory.sh/kratos/docs/quickstart) fails if the system enforces SELinux.
Containers `kratos-migrate` and `kratos` do share the same volume. Since SELinux is blocking the access, the running container fails to access `contrib/quickstart/kratos/email-password/kratos.yml`

This probably will also cause issues on docker with SELinux

**Describe the solution you'd like**
Configure SELinux to the target volume mount.
Attach the (lowercase) `:z` to `target: /etc/config/kratos` within the quickstart.yml the mentioned containers.  

**Describe alternatives you've considered**

Disabling SELinux locally.

**Additional context**
I do not know the security implications of the change, nor do i have an opinion changing a label on the filesystem. Since it is a quickstart i would ignore the implications just to have it runnable on non-docker systems.

```bash
$sestatus                             
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```

On my research about the solution on SELinux i was using [this](https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/) approach

**Comment by aeneasr** [comment]
Would `:z` cause issues with non-SELinux installations or would it simply be ignored?

**Comment by debrutal** [comment]
I will have a look!

**Comment by debrutal** [comment]
Apparently non SELinux hosts are not capable to interpret this correct. Adding my suggestion will lead into the same error.
(docker, ubuntu, docker-compose) So this is likely to be no option.

Error message:
`time=2020-11-17T21:30:10Z level=fatal msg=Unable to open config file. Make sure it exists and the process has sufficient permissions to read it func=github.com/ory/x/viperx.InitializeConfig file=/go/pkg/mod/github.com/ory/x@v0.0.153/viperx/viper.go:157 audience=application error=map[message:open /etc/config/kratos/kratos.yml: no such file or directory trace:stack trace could not be recovered from error type *os.PathError] path=/etc/config/kratos/kratos.yml service_name=kratos service_version=
`

**Comment by debrutal** [comment]
My Knowledge in this area only scratches the surface...
Any ideas how to solve this without having a compose file fore each possible configuration? Hints are appreciated :)

**Comment by aeneasr** [comment]
Could you check please if this works: https://github.com/ory/kratos/pull/889 ? Thanks!

**Comment by debrutal** [comment]
I like the solution. Unfortunately podman-compose is not able to merge correctly: [podman-compose:#256](https://github.com/containers/podman-compose/issues/256)

**Comment by debrutal** [comment]
so i think the status is correct. Thank you, i didn't came up with the idea of the merging capability.

**Comment by aeneasr** [comment]
Awesome, I hop the upstream podman issue can be resolved also :)
