### ISSUE TITLE
Add randomized constant time to every login request

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#832]
**Describe the bug**

Currently, login requests will fail faster if the user does not exist as the hash does not have to be computed. This can leave to timing attacks where an attacker can guess if a user exists or not, which defeats account enumeration defenses.

**Expected behavior**

Every login request should take a similar amount of time regardless of whether the user exists or not. The time should be configurable.

**Environment**

- Version: v0.5

**Additional context**

If anyone wants to tackle this let me know and I will give the right pointers!

**Comment by divbhasin** [comment]
@aeneasr new contributor here 👋  I can try and have a crack at this. Can you please give me the pointers?

**Comment by aeneasr** [comment]
Sorry  @divbhasin I missed this - are you still up for the challenge?

**Comment by soniabhishek** [comment]
@aeneasr I am up for this. Let me know the pointers.

**Comment by aeneasr** [comment]
Yes, the code should be around here https://github.com/ory/kratos/blob/master/selfservice/strategy/password/login.go#L140 as that is the error handling for "user not found".

We should add some delay here. I think it should be randomized. If the credentials are found we still add a randomized delay. The deviation and base value should be configurable. What would be really cool is if this value would be set automatically by benchmarking how long it takes for valid passwords to be hashed. But for now it can also just be configured. For example:

```
base: 100ms
deviation: 50ms // meaning a std deviation between 50ms and 150ms
```

or 

```
min: 100ms
max: 200ms
```

**Comment by zepatrik** [comment]
That benchmarking will be added with #803 
I will add the values to the config, then they can be used later on in the randomization.
We can then also collect stats for password hashing and see if the times deviate too much from the desired values so we can warn people.

**Comment by tdwyer** [comment]
Perhaps, a solution could be to add code something like this, so that even if the user does not exist it will still do the hashing and checking
```
if ! user_password:
    user_password = "lkasdkjfhsadkfhsadkjafshk"
```
and then do the check

**Comment by mattbonnell** [comment]
Think we can close this one now

**Comment by aeneasr** [comment]
#1088

**Comment by dmitrii-sisutech** [comment]
It seems that problem appeared again - if login with correct email address it takes ~400ms to login, if use wrong email address it takes ~50ms.
Kratos helm chart 0.37.1 (app version 1.0.0), default hasher (I assume it's bcrypt) and default configuration (I assume cost is 12).
