### ISSUE TITLE
Email templating docs link broken

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#835]
**Describe the bug**

The link pointing to https://www.ory.sh/kratos/docs/self-service/concepts/email-sms#templates is broken on https://www.ory.sh/kratos/docs/self-service/flows/verify-email-account-activation/#verification-link-via-email
It should point to https://www.ory.sh/kratos/docs/concepts/email-sms#templates

**Comment by vinckr** [comment]
You mean the link in https://www.ory.sh/kratos/docs/self-service/flows/verify-email-account-activation/#verification-link-method ? "Customizing E-Mail Templates"

I built the docs locally (npm start) and the link points to the correct location. npm build also works. 

(../../concepts/email-sms#templates) seems to be ok also, going two levels up you are in /docs and then into /concepts. 

There is the same problem with the Self-Service link right at the top of the page and all other links (except the on to REST API).
It works fine locally but not deployed. 

Is there something happening to the links that i am not aware of?

**Comment by vinckr** [comment]
Its working now? 
Except
https://www.ory.sh/kratos/docs/self-service/self-service#initialization-and-redirect-to-ui
should go to 
https://www.ory.sh/kratos/docs/self-service#initialization-and-redirect-to-ui

**Comment by vinckr** [comment]
Seems all links on that page are working again @zepatrik ?

**Comment by zepatrik** [comment]
Yes. looks so. Can you also fix the links in the versioned docs though? I saw that at least `v0.5` is still broken.

**Comment by vinckr** [comment]
at v0.5 all the links are working for me. 
/next is also working and in 0.4 its is only some github stuff missing.
Maybe there was some change in the docusaurus that solved it?

**Comment by aeneasr** [comment]
Can this be closed then?

**Comment by vinckr** [comment]
I just checked again and now all the links are broken again. 
I could swear that it worked for me before, no idea... 
I see if I can fix it.

**Comment by aeneasr** [comment]
Yeah strange, the links seem to be correct.

**Comment by zepatrik** [comment]
It is still broken, and never worked for me.

**Comment by zepatrik** [comment]
But yes, it looks good in the source...

**Comment by vinckr** [comment]
I checked everything that I can think of, and when I build locally it is working fine. 

Maybe some arcane docusaurus magic?
