### ISSUE TITLE
Diagram image has malformed text

### ISSUE THREAD

**Issue by doenn** [ory/kratos#902]
On MS Edge, the Quickstart diagram has malformed text.

1. Navigate to https://www.ory.sh/kratos/docs/quickstart/
2. View the diagram under Network Architecture in MS Edge.
**Expected behavior**

The image has no overlapping text.

**Actual behavior**
The image text overlaps. Maybe this occurred since my MS Edge was zoomed, though I zoomed out as well.

**Environment**
MS Edge, Windows 10

**Additional context**

If this is a static image, it is probably reproducible across any browser.
![NetDiagram](https://user-images.githubusercontent.com/3093577/102068423-68733180-3dca-11eb-91a2-70a7526faff9.JPG)

**Comment by aeneasr** [comment]
Thank you for the report, unfortunately this looks like an issue in https://github.com/mermaid-js/mermaid/issues that can not be solved here.
