### ISSUE TITLE
Swagger specification for security is wrong

### ISSUE THREAD

**Issue by dmayle** [ory/kratos#938]
**Describe the bug**
The swagger specification for security is incomplete.  It only shows one of the three supported authentication mechanisms.

**Reproducing the bug**
https://github.com/ory/kratos/blob/master/session/manager_http.go#L98 Shows the code that checks security

**Expected behavior**
The swagger spec is correct

**Comment by aeneasr** [comment]
Unfortunately this is an upstream/cantfix issue: https://github.com/ory/kratos/pull/939#discussion_r548850163
