### ISSUE TITLE
Support wildcard in whitelisted_return_urls

### ISSUE THREAD

**Issue by Zippersk** [ory/kratos#943]
**Is your feature request related to a problem? Please describe.**

We are using multiple subdomains in our system (user1.mydomain.tld, user2.mydomain.tld, ...) with wildcard https certificate. When a user is not logged in, he is redirected to auth.mydomain.tld. I want to return him to the original url after login (for example user1.mydomain.tld).

**Describe the solution you'd like**

Two solutions would fix our issue:
1. We could use glob or regex match here: 
https://github.com/ory/kratos/blob/ef1e3f77238d090112808e988b890ab7e8b58074/x/http_secure_redirect.go#L90

2. or specify only domain in `whitelisted_return_urls` and allow all its subdomain by default.

**Comment by Zippersk** [comment]
I can make PR if we agree on solution :)

**Comment by zepatrik** [comment]
Sounds good to me, but we should consider the config format to be backwards compatible if possible. Just interpreting the allow list as regex might be a problem in some cases. https://github.com/ory/kratos/blob/eb0399c2788c39a53c9f53233184fb420453bec2/.schema/config.schema.json#L372-L388 is where we define it currently. In oathkeeper we require people to specify the match strategy (`glob`, `regexp`) explicitly and we have to do that here as well. As I don't see a nice backwards compatible format right now, we should restructure that entirely, maybe to something like
```json
        "allowed_return_uris": {
          "title": "List of allowed Return To URLs",
          "description": "List of URLs that are allowed to be redirected to. A redirection request is made by appending `?return_to=...` to Login, Registration, and other self-service flows.",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "pattern": {
                "type": "string",
                "format": "uri-reference"
              },
              "matching_strategy": {
                "enum": ["glob", "regex"]
              },
              "required": ["pattern", "matching_strategy"],
              "additional_properties": false
          },
          "examples": [
            [
              {
                "pattern": "https://app.my-app.com/dashboard",
                "matching_strategy": "glob"
              }
            ]
          ],
          "uniqueItems": true
        },
```
With this breaking change we should also remove the vocab whitelist btw.

**Comment by Zippersk** [comment]
I am able to implement only some simple feature (e.g. support *.example.com). And that should be backwards compatible. 

But I can not implement refactoring/breaking change as you described above. 
But I agree with your proposal with one note. In oathkeeper, we define matching_strategy globally. I think, that we should:
1.  define matching strategy globally here also 
or 
2. define matching strategy in oathkeeper for every entry.

**Comment by aeneasr** [comment]
Wildcard redirect URLs are usually considered bad practice because the allow developers to be lazy and whitelist every domain on the planet, leaving a TON of room for abuse and open redirect vulnerabilities. An open redirect could, for example, point to a malicious phishing UI which looks exactly the same to the one from the legit app, and just says "credentials invalid please try again".

I understand your use case with dynamic redirect URLs but there is some weighing between ease of configuration and security here.

**Comment by zepatrik** [comment]
But ease of configuration and possibility to have dynamic URLs is not the same. Currently it would not be possible to redirect to e.g. `github.com/{org}/{repo}` right? One would have to dynamically add all repos to the config when they are created.

**Comment by aeneasr** [comment]
It is, see https://github.com/ory/kratos/blob/ef1e3f77238d090112808e988b890ab7e8b58074/x/http_secure_redirect.go#L88

OP is asking for wildcards in domain names!

**Comment by zepatrik** [comment]
oh right, was thinking too much of oathkeeper rules there

**Comment by davidthor** [comment]
> It is, see
> 
> https://github.com/ory/kratos/blob/ef1e3f77238d090112808e988b890ab7e8b58074/x/http_secure_redirect.go#L88
> 
> OP is asking for wildcards in domain names!

It looks like the only _practical_ limitation (practical is of course subjective) I can see from the current implementation is support for multiple subdomains. This was my issue coming from https://github.com/ory/kratos/discussions/993. 

I'm struggling to think of an answer at the moment, but is there a leaner modification that could be made to the current logic that might allow the host to be interpreted as a base url of sorts?

**Comment by aeneasr** [comment]
The problem with wildcard domains is that not all domains are equal. `foo.github.io` is not equal to `bar.github.io` - they are owned by different people.

**Comment by zepatrik** [comment]
Or take https://publicsuffix.org/ as an example. This list is used e.g. by let's encrypt to check whether you are allowed to create a certificate for a subdomain. None of the suffixes mentioned there should be allowed as `*.public.suffix`

**Comment by NickUfer** [comment]
As already said, subdomains or zones can be delegated to other people. You could sell third level domains to other people. For example you could sell `foo.example.com` if you have control over `example.com`. Some registries only sold third level domains in the past, for example Registro.br, the ones responsible for .br domains: https://en.wikipedia.org/wiki/.br#Second-level_domains

Verisign, the ones responsible for .name domains, did that too: https://en.wikipedia.org/wiki/.name#Structure

These companies have already dropped this policy, but they show that it is possible.

**Comment by davidthor** [comment]
I understand the risks of allowing subdomains for _public_ or shared zones, but since that's not the case for most private, enterprise usage it feels like there should be a way for me to acknowledge that anyone able to generate a DNS record for `*.zone.mydomain.tld` is a "good actor". Assuming I DO own the domain and all those with access to it are considered good actors, is there ever any reason I wouldn't want to blankety allow them to be whitelisted?

**Comment by ramsy1980** [comment]
Any updates on this? In my specific situation my CI/CD is generating review URLs with a random subdomain for the team to review their changes on. Being able to add *.domain.tld is the only way to make this work for me.

**Comment by aeneasr** [comment]
Not really but yeah maybe we can support add wildcards for domains?

**Comment by aeneasr** [comment]
But disallow things like `*` (so all domains)

**Comment by ramsy1980** [comment]
Being able to add *.domain.tld would solve the issue for my specific use case. You could consider adding an acception for public domain names like github.io if required.

**Comment by aeneasr** [comment]
That makes sense - is there such a list available somewhere (preferably online and kept up to date)?

**Comment by ramsy1980** [comment]
I would leave it to GitHub and GitLab for now and add when necessary because that's the only use case I can think of and disallow wildcards of root domains all together.

**Comment by zepatrik** [comment]
See above mentioned public suffix list https://github.com/ory/kratos/issues/943#issuecomment-762102942

**Comment by ErwinSteffens** [comment]
+1

Also needed for whitelisting preview urls like `*.my-app-1234.pages.dev` generated by Cloudflare Pages for example.

**Comment by chlasch** [comment]
+1

Also wondering if there is a security reason relative whitelists are not allowed either? 

for instance
```yaml
  whitelisted_return_urls:
    - /some-path
    - /some-path/some-resource
```

**Comment by aeneasr** [comment]
If anyone wants to pick this up, we'd appreciate contributions! The public suffix list is, IMO, a good idea!

**Comment by abador** [comment]
@aeneasr I'll take it
