### ISSUE TITLE
High memory usage when idle

### ISSUE THREAD

**Issue by tvarsis** [ory/kratos#945]
**Describe the bug**

I cloned the latest getting started project from the documentation and followed the step to set it up. When I then checked docker stats, I can see that it idles at a very high RAM usage around 380 MB. This is on the level that you would see from the Java EE projects such as Keycloak etc. It is also a bit strange to me that it has constant CPU usage (even if it is low) which indicates that it does some kind of polling instead of listening to events.

![image](https://user-images.githubusercontent.com/10090010/103241650-2e6e6780-4954-11eb-95f3-5c62bb23cdc8.png)

**Reproducing the bug**

git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.5.5-alpha.1

docker pull oryd/kratos:latest-sqlite
docker pull oryd/kratos-selfservice-ui-node:latest
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate

Created a new user, verified email and logged in to the SecureApp demo.
Run "docker stats"

I also tested to close down all related websites, with no major impact on the results.

**Expected behavior**

I would expect a lean Go application to idle at maybe 20 MB or similar of RAM usage, and I have gotten the impression that being lightweight is a high priority by this project.

**Environment**

OpenSUSE Tumbleweed
docker 19.03.12
docker-compose version 1.26.2, build unknown
docker-py version: 4.2.2
CPython version: 3.8.6
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

**Comment by aeneasr** [comment]
This has been asked and answered several times before and is well documented: https://www.ory.sh/kratos/docs/debug/performance-out-of-memory-password-hashing-argon2

**Comment by tvarsis** [comment]
@aeneasr Thanks for you reply! I searched for issues and the forum and could not find anything about it, hence the bug report.

The link to the blog post is dead, so could not read up on it, but I understand that the memory consumption could be tweaked by the CLI, which is good. However, it does not describe the constant CPU usage, even though nothing is using kratos. Do you have any information about that as well?

**Comment by aeneasr** [comment]
Ah yes thank you for the hint that the blog post link is broken. /cc @zepatrik could you fix that?

The blog post is: https://www.ory.sh/choose-recommended-argon2-parameters-password-hashing/

Regarding the CPU usage, I will try and reproduce that. Generally, there are no background tasks except for the mail queue watcher which require CPU cycles. My guess is that that's the culprit as there isn't anything else.

Regarding memory - Golang reserves memory as needed and keeps it around for some time. If it really isn't used anymore it will be freed up after a while by the GC. This takes usually around 5-15 minutes. If you keep the container idle for that amount of time it the usage goes back to a couple of megs.

Regarding CPU you could also use CPU profiling: set env var PROFILING=cpu and restart the container and watch logs for the CPU profile file. You have to stop the container gracefully to close the profile file. Could be a bit tricky inside docker but you can give it a shot!

**Comment by aeneasr** [comment]
This will become much easier to handle once https://github.com/ory/kratos/issues/955 is merged - tracking there.
