### ISSUE TITLE
CSRF token is empty when initialize Login Flow for API clients

### ISSUE THREAD

**Issue by tnm0113** [ory/kratos#948]
**Describe the bug**

I have followed Quick start guide but i cant get CSRF token when initialize Login Flow for API clients 

**Reproducing the bug**

git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.5.5-alpha.1

docker pull oryd/kratos:latest-sqlite
docker pull oryd/kratos-selfservice-ui-node:latest
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate

Use POSTMAN request GET to URL: http://127.0.0.1:4433/self-service/login/api, CSRF token is empty on field value

_Server logs_
kratos_1                      | time=2020-12-30T08:17:06Z level=info msg=completed handling request func=github.com/ory/x/reqlog.(*Middleware).ServeHTTP file=/go/pkg/mod/github.com/ory/x@v0.0.165/reqlog/middleware.go:139 method=GET name=public#http://127.0.0.1:4433/ remote=10.55.123.69:44578 request=/self-service/login/api status=200 text_status=OK took=91.256µs

_Server configuration_

Default configuration

**Expected behavior**

Get CSRF Token value

**Environment**

- Version: latest version
- Environment: Ubuntu 20.04, Docker version 20.10.1

**Comment by tnm0113** [comment]
I found that Login with API flows doesnt need CSRF Token for verifying like Browser flows. I want to build a service between our clients and Kratos, so our clients dont need to know stuff about Kratos, just send our service username, password and the service will request init API flows, complete flow, get token and send back to client.
Does it have any risks ?

**Comment by zepatrik** [comment]
So basically a reverse proxy? Can't you use the browser flow then?

**Comment by tnm0113** [comment]
No, our clients are API clients

**Comment by aeneasr** [comment]
There is no CSRF for API clients because they are API clients and not browsers. If you use browsers, use the browser APIs. CSRF is a browser attack vector only. So this is expected behaviour.

**Comment by gotascii** [comment]
Sorry to bump this super old thread, but I too am seeing an empty `csrf_token`, which makes sense given the reasons discussed above. The problem is that when I POST to the action_url I am getting a `security_csrf_violation`. I am following the docs [here](https://www.ory.sh/docs/kratos/self-service#api-flows) with a very basic setup in which I am making requests directly to my oryapis project URL. I'm probably missing something obvious, any suggestions would be appreciated thanks!

**Comment by aeneasr** [comment]
Hi @gotascii, can you please open a discussion with details? Best would be a reproducible code base
