### ISSUE TITLE
Delete self-service flows after completion

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#952]
**Is your feature request related to a problem? Please describe.**

Currently, old flows are not purged from the database. This accumulates stale records in the database and bears potential privacy and security risks.

**Describe the solution you'd like**

Flows should be removed when stale, preferably as a background task.

**Comment by anonrig** [comment]
hey @aeneasr, I've been using Kratos on production for a while now, and this issue is getting out of hand (both in terms of storage and query execution speed). is this issue a priority? I would like to know more since it became a game-changer for us.

**Comment by harnash** [comment]
There are other tables that needs this (i.e. `sessions`). So probably one task that will purge all expired records (in batches!) would be needed.

**Comment by aeneasr** [comment]
I was also thinking of cleaning up successful flows on completion. Expiry still needs batch deletion though

**Comment by abador** [comment]
@aeneasr  I started working on it. I'll ping you to take a look at our branch before porting those changes to your repo

**Comment by aeneasr** [comment]
Nice!

**Comment by abador** [comment]
@aeneasr I've been looking into removing finished flows, but it doesn't look as easy to do as I hoped (or I misread something). There seem to be a few edge cases when a flow can be reused or is needed at some point later in the code. I think I'll try to tackle this in a seperate pr/issue

**Comment by aeneasr** [comment]
It can also be a background worker that checks for expired flows and cleans them up, we probably need that anyways for flows that expire and are never completed

**Comment by abador** [comment]
@aeneasr what do you think about https://github.com/Wikia/kratos/pull/56 ? Is this what you were thinking of? I might be able to port those changes to your repo this week.

**Comment by aeneasr** [comment]
Yes, sweet! I only have a few suggestions of things we can probably omit (e.g. i dont think we need the flag because anyone that runs into this issue will have at least 2 or 3 pods of kratos runing) :)

**Comment by frederikhors** [comment]
Is there a way to avoid a new executable to launch and have something like `--watch courier` within the main executable?
