### ISSUE TITLE
Admin Api /recovery/link giving 404

### ISSUE THREAD

**Issue by Benehiko** [ory/kratos#954]
**Describe the bug**

When attempting to do a `POST` request to `/recovery/link` - I get a 404 from the Kratos server.
Currently I am on version v0.5.5-alpha.1 in docker.

**Reproducing the bug**

1. Run docker-compose up --build --force-recreate --remove-orphans
2. Make an API request with curl
    curl -X POST http://127.0.0.1:4434/recovery/link \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json'
    
3. Request responds with `404 page not found`

Kratos server logs:

    kratos_1          | time=2021-01-03T17:59:30Z level=info msg=started handling request method=POST name=admin#http://kratos:4434/ remote=172.18.0.1:47534 request=/recovery/link

    kratos_1          | time=2021-01-03T17:59:30Z level=info msg=completed handling request method=POST name=admin#http://kratos:4434/ remote=172.18.0.1:47534 request=/recovery/link status=404 text_status=Not Found took=272.286µs

`docker-compose.yml`

    kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.5.5-alpha.1
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres@172.17.0.1:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      serve -c "/etc/config/kratos.dev.yaml" --dev
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config
    networks:
      - intranet

`kratos.dev.yaml`
**please note I override the dsn with an environment variable pointing it to postgres**

    dsn: sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    serve:
      public:
        base_url: http://127.0.0.1:4455/.auth/
        port: 4433
      admin:
        base_url: http://kratos:4434/
        port: 4434
    identity:
      default_schema_url: file:///etc/config/identity.schema.traits.dev.json
      schemas:
        - id: lite
          url: file://etc/config/identity.schema.traits.lite.dev.json

    selfservice:
      default_browser_return_url: http://127.0.0.1:8080
      
      methods:
        profile:
          enabled: true
        link:
          enabled: false
        password:
          enabled: true
      
      whitelisted_return_urls:
        - http://127.0.0.1:4455
        - http://127.0.0.1:8080
      
      flows:
        error:
          ui_url: http://127.0.0.1:8080/error
        
        settings:
          ui_url: http://127.0.0.1:8080/auth/profile
          privileged_session_max_age: 15m
          after:
            default_browser_return_url: http://127.0.0.1:8080/auth/profile
            password:
              default_browser_return_url: http://127.0.0.1:8080/auth/profile
        login:
          ui_url: http://127.0.0.1:8080/auth/login
          lifespan: 24h
        
        registration:
          ui_url: http://127.0.0.1:8080/auth/register
          lifespan: 24h
          after:
            oidc:
              hooks:
                - hook: session
            password:
              hooks:
                - hook: session
        
        verification:
          enabled: true
          ui_url: http://127.0.0.1:8080/verify
          lifespan: 72h
        
        recovery:
          enabled: true
          ui_url: http://127.0.0.1:8080/recovery
        
        logout:
          after:
            default_browser_return_url: http://127.0.0.1:8080

    courier:
      smtp:
        connection_uri: smtps://example@example.com@smtp.eu.mailgun.org:465?skip_ssl_verify=true
        from_address: no-reply@example.com
    log:
      level: debug

    secrets:
      default:
        - "some-secret"
      cookie:
        - "some-secret"

    hashers:
      argon2:
        parallelism: 1
        memory: 131072
        iterations: 2
        salt_length: 16
        key_length: 16

    session:
      lifespan: 24h
      cookie:
        persistent: true
        same_site: Strict

    version: v0.5.5-alpha.1

**Expected behavior**

Expect to get a response described in the documentation [here](https://www.ory.sh/kratos/docs/reference/api#create-a-recovery-link)

**Environment**

- Version: v0.5.5-alpha.1 (docker image)
- Environment: Ubuntu 18.04 OS

**Additional context**

All the other endpoints work, such as the self-service login, registration flow.

**Comment by aeneasr** [comment]
Thank you for the report - maybe we forgot to mount it. For the sake of completeness, could you please share your kratos config?

**Comment by Benehiko** [comment]
@aeneasr I have updated the post with the kratos config file

**Comment by aeneasr** [comment]
You have disabled the recovery method in your config, which is why the endpoint is not mounted!

**Comment by Benehiko** [comment]
:man_facepalming: sorry about that, missed this config. Tested and it's working now :+1:

**Comment by aeneasr** [comment]
No problem - we could probably provide a better error message than 404 in this case.

**Comment by lmcl90** [comment]
A strategy object will be provided only when the strategy is enabled. See [code](https://github.com/ory/kratos/blob/master/driver/registry_default_recovery.go#L27). So the endpoint for link recovery will not be mounted when the strategy(the corresponding config path is `selfservice.methods.link.enabled`) is disabled.

Password, oidc and profile strategies also have the same problem.

**Comment by aeneasr** [comment]
see #1025
