### ISSUE TITLE
Mitigate expired login and registration requests

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#96]
**Describe the bug**

When a login or registration request expires, the request will show an error indicating that the user should try again. However, Hive fails to generate a new request on the fly, rendering any retry pointless (as retrying will still result in an expired request).

**Reproducing the bug**

<img width="1444" alt="Bildschirmfoto 2019-10-24 um 13 46 20" src="https://user-images.githubusercontent.com/3372410/67482810-afe9ac00-f664-11e9-9dbe-6d76c6f889a7.png">

1. Attempt to login
2. Wait for request to expire
3. Fill out form and press send

**Environment**

* Version: master

**Comment by zepatrik** [comment]
send expiration date with login request data
