### ISSUE TITLE
Does not work with mariadb (10.4.17) as database

### ISSUE THREAD

**Issue by DanielFuchs98** [ory/kratos#964]
**Describe the bug**

When using mariadb as database system, kratos-migrate throw an error:
```
kratos-migrate_1  | An error occurred while connecting to SQL: error executing github.com/ory/kratos:/persistence/sql/migrations/sql/20200317160354_create_profile_request_forms.mysql.up.sql, sql: CREATE TABLE `selfservice_profile_management_request_methods` (
kratos-migrate_1  | `id` char(36) NOT NULL,
kratos-migrate_1  | PRIMARY KEY(`id`),
kratos-migrate_1  | `method` VARCHAR (32) NOT NULL,
kratos-migrate_1  | `selfservice_profile_management_request_id` char(36) NOT NULL,
kratos-migrate_1  | `config` JSON NOT NULL,
kratos-migrate_1  | `created_at` DATETIME NOT NULL,
kratos-migrate_1  | `updated_at` DATETIME NOT NULL
kratos-migrate_1  | ) ENGINE=InnoDB;
kratos-migrate_1  | ALTER TABLE `selfservice_profile_management_requests` ADD COLUMN `active_method` VARCHAR (32);
kratos-migrate_1  | INSERT INTO selfservice_profile_management_request_methods (id, method, selfservice_profile_management_request_id, config) SELECT id, 'traits', id, form FROM selfservice_profile_management_requests;
kratos-migrate_1  | ALTER TABLE `selfservice_profile_management_requests` DROP COLUMN `form`;: Error 1364: Field 'created_at' doesn't have a default value
```

The error-message is `Error 1364: Field 'created_at' doesn't have a default value` while altering the table `selfservice_profile_management_requests`

**Reproducing the bug**

change the database-image in the file `quickstart-mysql.yml` to `mariadb:10.4.17` and run the command `docker-compose -f quickstart.yml -f quickstart-mysql.yml up --build --force-recreate` as provided in the [docs](https://www.ory.sh/kratos/docs/quickstart/#clone-ory-kratos-and-run-it-in-docker)

**Expected behavior**

It should make no difference whether I use MariaDB or Mysql

**Environment**

- kratos: oryd/kratos:v0.5.5-alpha.1 (latest)
- mariadb: mariadb:10.4.17
- docker: 20.10.0 (wsl2 on windows 10)

The error also apear on debian 10.5 with docker and mariadb galera cluster.

**Comment by aeneasr** [comment]
https://github.com/ory/kratos/issues/770
