### ISSUE TITLE
Password policies: make api.pwnedpasswords.com configurable

### ISSUE THREAD

**Issue by radekg** [ory/kratos#969]
**Is your feature request related to a problem? Please describe.**

No related to a problem.

**Describe the solution you'd like**

I would like to use a custom server / database for password breach verification. For that, I would like to have a configuration option to specify my own DNS name instead of api.pwnedpasswords.com. 

**Describe alternatives you've considered**

Egress proxy type of solution but in certain environments this might be difficult to configure.

**Comment by aeneasr** [comment]
The check only works with the haveibeenpwnd API with their special k-anonymity thing. Do you want to host the database yourself?

**Comment by radekg** [comment]
Yes, I host the database myself. I have an API conforming the haveibeenpwned API and I would like to have an option to use my own API instead of the public hosted one. I can prepare a PR. I would leave the default to be the official one, as is now, and allow an override.

**Comment by aeneasr** [comment]
Ok sounds good!

**Comment by hanselke** [comment]
hi, are you guys hosting api.pwnedpasswords.com. yourself? is it simply a mirror of https://haveibeenpwned.com/ or do you guys have other sources of information?



i’m still in development, but i’ve run into hardcoded but randomly (by smashing my keyboard like aefcjio@89dhqniw891) generated test passwords being rejected for new registrations twice the past 2 months. passwords worked when i first generated it

**Comment by xlanor** [comment]
> hi, are you guys hosting api.pwnedpasswords.com. yourself? is it simply a mirror of https://haveibeenpwned.com/ or do you guys have other sources of information?
> 
> i’m still in development, but i’ve run into hardcoded but randomly (by smashing my keyboard like aefcjio@89dhqniw891) generated test passwords being rejected for new registrations twice the past 2 months. passwords worked when i first generated it

The pwndpasswords.com api is offered by haveibeenpwned.

**Comment by zepatrik** [comment]
Reopen if I am wrong, but this seems to be implemented already by #1009: https://github.com/ory/kratos/blob/29aab569908ad19d596e7570d0d34708f753622f/driver/config/config.go#L1010-L1011

**Comment by radekg** [comment]
@xlanor you can also host one yourself: https://github.com/radekg/hibp
