### ISSUE TITLE
Password policies: make settings configurable

### ISSUE THREAD

**Issue by radekg** [ory/kratos#970]
**Is your feature request related to a problem? Please describe.**

Not related to an issue.

**Describe the solution you'd like**

Currently, minimum password length, minIdentifierPasswordDist and maxIdentifierPasswordSubstrThreshold are currently hard coded. I would like to have configuration options to configure these settings using Kratos configuration. Additionally, have an option to maybe specify minimum number of character in certain classes, similar to Keycloak: lowercase, uppercase, special characters.

**Describe alternatives you've considered**

A hook but I see no option to define custom hooks, for example HTTP based hooks.

**Additional context**

For services deployed in private networks where the password rules might be distributed from an external source.

**Comment by aeneasr** [comment]
Password complexity is an anti-pattern, please read: https://www.ory.sh/kratos/docs/concepts/security#passwords

The chosen values are best-practice values. Why do you want to change them?

**Comment by wangchucheng** [comment]
Vote for configurable password policies. 

For intense, kratos now use HIBP api to check the leaking possibilities. Some users may feel umcomfortable when seeing "password has been found in xxxx". They do not know how it works so they may even regard this safer approach as risky. Most apps are not like Google or Apple, most apps lack this "credibility".

Therefore, in some cases, it may be a good choice to allow users to customize password policies.

**Comment by aeneasr** [comment]
That’s not how security works. Users will learn eventually how this works. It protects them. Disabling it does not.

**Comment by aeneasr** [comment]
You can always adjust the error message in your UI also

**Comment by radekg** [comment]
Hey, so I've been actually thinking a bit more about my original request. I've mixed up two things there.

1. make the min length, `minIdentifierPasswordDist` and `maxIdentifierPasswordSubstrThreshold` configurable
2. allow specifying character classes

Re 1. I'm fine with the defaults. I mean, it would be nice for some use cases to require longer passwords. For example registering API clients.

Re 2. I understand the best practices around passwords and I totally agree on "users should be educated on passwords". Unfortunately, the real world is what it is and businesses have to deal with decision makers who have their own views on what the systems should support. I fear that the lack of being able to explicitly specify what character classes to use may disqualify Kratos in the eyes of some of those decision makers who simply do not get it and refuse authority.

Now, when we consider the minimum password requirement + HIBP integration, it actually does not matter which character groups and at what counts are in use. I know, you know, the guy next to knows that. So, I wonder if there is a middle ground here. If there was a way to implement a pre-validation hook, without the ability to skip already implemented validation, that would allow people to implement a feature like that.

This potentially prevents people from doing other silly stuff like putting some kind of reverse proxies in front just to implement such requirement and potentially screwing up in other ways by actually decreasing security with those layers in between.

**Comment by aeneasr** [comment]
Yeah, that's a fair point. I think the password distance things should be configurable as they can be too strict or too lose.

Regarding password "complexity" or character classes - one thing we had planned was to actually *not* send the password in hooks! Because we feel that the password does not belong anywhere else. Think about an accidental log statement on error which drops, for example, the request payload (this actually happened at Facebook!) or similar problems.

Another possibility would be to use JSON Schema for this? It has all the stuff in there with min/max/regex/format/...

**Comment by ethanchangbd** [comment]
Regarding this, where can I get the password policy structure or requirements.

**Comment by zepatrik** [comment]
This is the current password validator implementation: https://github.com/ory/kratos/blob/4b9da3c9d98d40f7b71a56c51543fc115974630d/selfservice/strategy/password/validator.go

**Comment by radekg** [comment]
Hey @aeneasr, 

> Another possibility would be to use JSON Schema for this? It has all the stuff in there with ...

That sounds like a reasonable idea. This should be pretty easy to add. I guess the schema (or the link to the schema, rather) could be configurable via new `selfservice.methods.password.config....` property. What would be really neat is to also have an API endpoint to fetch that schema so it could be used to drive a user interface. Similar to what Keycloak offers. If the direction is okay for you, I can pick it up.

**Comment by aeneasr** [comment]
Thinking about this again - JSON Schema is really something to verify JSON, not really for singular fields - the following configs would be for example non-sensical:

```
type: object
```

```
type: array
```

```
type: string
format: email
```

Only this really makes sense:

```
type: string
pattern: ...
```

So not sure...

**Comment by g13013** [comment]
@aeneasr Kratos should allow to disable password policies all together or tweak the settings for whatever fits the application provider ! even though Kratos wants to enforce best practice regarding security, we cannot ask implementers  to force there existing users into bizarre workflows to import their credentials, we had hard times implementing fairly complex workflows to import existing accounts without the user noticing the change but we are stuck because legacy passwords are not accepted when the users type their weak **existing** passwords, we don't want to ask the users to change their password when they try to login as they normally do.

**Comment by g13013** [comment]
any updates on this ?

**Comment by IgorGov** [comment]
> developer can choose w

+1

**Comment by Sytten** [comment]
This should probably not be closed. Even if in a "better" world the password should have complexity, regulations and user expectations must also be taken into account. This means having settings to specify the number of uppercase, number and symbols.

**Comment by bcordobaq** [comment]
Are you considering extending the password settings to support additional checks like @Sytten commented and/or adding other mechanisms like password history? I'm aware that you indicated those cases like anti-patterns, but some customers still require them as a check...

**Comment by radekg** [comment]
The problem with how things are right now is the following:

- One can either use the HIBP check or disable it.
- In air-gapped environments, it may be e difficult to get an egress policy towards HIBP API. Hence my original pull request from a couple of years ago added a customizable HIBP API endpoint.
- HIBP check can be disabled. However, when disabled, nothing prevents a user from submitting a weak password.
  - Because it is impossible to send the password via webhook, there's zero protection from submitting a weak password.

@aeneasr I get your point re not sending passwords via webhooks. There may be a middle ground. How about jsonnet or some wasm/yaegi voodoo plugins that could run in the main process responsible for the original password validation?
