### ISSUE TITLE
Go get fails when building from source

### ISSUE THREAD

**Issue by zkrzyzanowski** [ory/kratos#979]
**Describe the bug**

Build from source based on doc instructions https://www.ory.sh/kratos/docs/install/#building-from-source fails with error

```
go get: github.com/ory/cli@v0.0.28-0.20200903094455-e203529bf12b updating to
	github.com/ory/cli@v0.0.37 requires
	github.com/ory/kratos@v0.5.5-alpha.1.0.20201219142622-e589c07bb081 requires
	github.com/ory/kratos-client-go@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Reproducing the bug**

1. `go get -d -u github.com/ory/kratos`

**Expected behavior**
Package installed to `$GOPATH/src/github.com/ory/kratos`

**Environment**

- MacOs Sierra 10.15.6
- Go 1.15

**Comment by aeneasr** [comment]
Do not use "-u" with go modules.
