### ISSUE TITLE
Allow password hashing parameter and algorithm updates

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#984]
It might happen that hasher parameters have to be updated or the algorithm will change. Hashes can then be recomputed *after* a successful login and updated in the store. It is important to compute them lazily after the request is handled.

**Comment by aeneasr** [comment]
Marked as stale in error.

**Comment by sebastianvoss** [comment]
@aeneasr @zepatrik 
If I'm not mistaken this is not implemented yet. Should it be re-opened?
