### ISSUE TITLE
Access identity schema information (e.g. usernames) within the jsonnet mapper

### ISSUE THREAD

**Issue by christian-roggia** [ory/kratos#987]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I would like to be able to fetch any arbitrary data from the identity schema within the jsonnet mapper.

A common use-case is to be able to generate a username during the OIDC flow and if the username is already taken then append or prepend a random string to make it unique.

**Comment by aeneasr** [comment]
Something along the lines of:

- verifiableEmailAddressKnown
- recoveryEmailAddressKnown
- loginMethodPasswordIdentifierKnown

**Comment by christian-roggia** [comment]
https://github.com/ory/kratos/discussions/983
